import {ID,featureActive} from '../core.js';
import {ADEPT_KEY} from './adept-data.js';
import {markReactiveStress} from './stress-payment.js';
const WRAPPED=Symbol.for(`${ID}.adeptRoll`),DIALOG=Symbol.for(`${ID}.adeptDialog`),PAY=`${ID}.adeptPay`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function adeptItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===ADEPT_KEY;})??null:null;}
export function adeptCost(config,id){return config?.costs?.find(cost=>cost.extKey===id)?.key??null;}
export function setAdeptCost(dialog,id,cost){const config=dialog?.config,actor=dialog?.actor,experience=actor?.system?.experiences?.[id];if(!adeptItem(actor)||!experience||!config?.experiences?.includes(id)||!['hope','stress'].includes(cost))return false;const entry=config.costs?.find(value=>value.extKey===id);if(!entry)return false;entry.key=cost;entry.value=1;entry.total=1;dialog.render();return true;}
export function adeptStressIds(config){return(config?.experiences??[]).filter(id=>adeptCost(config,id)==='stress');}
export function adeptBonuses(options){const actor=options?.data?.parent,item=adeptItem(actor);if(!item)return[];return(options.experiences??[]).flatMap(id=>adeptCost(options,id)==='stress'&&actor.system.experiences?.[id]?[{label:`Adept — ${actor.system.experiences[id].name}`,value:Number(actor.system.experiences[id].value)||0}]:[]);}
export async function payAdept(request,{user},pay=markReactiveStress){if(!game.user.isActiveGM||!user?.active||!Number.isSafeInteger(request.count)||request.count<1)return false;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER')||!adeptItem(actor))return false;return pay(actor.uuid,current=>Boolean(adeptItem(current)),request.count);}
export function installAdeptRoll(D20Roll,pay){if(!D20Roll||D20Roll[WRAPPED])return;const bonus=D20Roll.prototype.applyBaseBonus,evaluate=D20Roll.buildEvaluate;D20Roll.prototype.applyBaseBonus=function(...args){const result=bonus.apply(this,args);result.push(...adeptBonuses(this.options));return result;};D20Roll.buildEvaluate=async function(roll,config,...args){const ids=adeptStressIds(config);if(ids.length&&!config[ID]?.adeptPaid){const actor=config.data?.parent,paid=await pay({actorUuid:actor?.uuid,count:ids.length});if(!paid)throw Error('Adept could not mark the selected Stress.');config[ID]={...config[ID],adeptPaid:true};for(const cost of config.costs??[])if(ids.includes(cost.extKey))cost.enabled=false;}return evaluate.call(this,roll,config,...args);};Object.defineProperty(D20Roll,WRAPPED,{value:true});}
export function installAdeptDialog(Dialog){if(!Dialog||Dialog[DIALOG])return;Dialog.DEFAULT_OPTIONS.actions.dhpAdeptCost=function(_event,button){setAdeptCost(this,button.dataset.key,button.dataset.cost);};Object.defineProperty(Dialog,DIALOG,{value:true});}
export function registerAdept(){const D20=CONFIG.Dice.daggerheart.D20Roll,Dialog=game.system.api.applications.dialogs.d20RollDialog;CONFIG.queries[PAY]=payAdept;installAdeptRoll(D20,async request=>{const gm=game.users.activeGM;if(!gm)throw Error('Adept needs an active GM.');return gm.isSelf?payAdept(request,{user:game.user}):gm.query(PAY,request,{timeout:20000});});installAdeptDialog(Dialog);Hooks.on('renderApplicationV2',(app,html)=>{if(!(app instanceof Dialog)||!adeptItem(app.actor))return;html.querySelectorAll('.dhp-adept-cost').forEach(node=>node.remove());for(const id of app.config.experiences??[]){const experience=app.actor.system.experiences?.[id],index=app.config.costs?.findIndex(cost=>cost.extKey===id),entry=index>=0?html.querySelector(`#action-costs-${index}`)?.closest('li'):null;if(!experience||!entry)continue;const cost=adeptCost(app.config,id)??'hope',row=html.ownerDocument.createElement('div');row.className='dhp-adept-cost';row.innerHTML=`<span>Adept</span><button type="button" data-action="dhpAdeptCost" data-key="${esc(id)}" data-cost="hope" class="${cost==='hope'?'selected':''}">1 Hope</button><button type="button" data-action="dhpAdeptCost" data-key="${esc(id)}" data-cost="stress" class="${cost==='stress'?'selected':''}">1 Stress ×2</button>`;entry.append(row);}});}
