import {premadeDocuments,configurePremadePack} from '../premade-setup-context.js';
import {ID} from '../core.js';
import {modernDamageEffects} from '../effect-compat.js';
export const ADRENALINE_KEY='nightwalker-adrenaline',ADRENALINE_EFFECT='HMx9uZ54mvMiH95x';
export function adrenalineData(folder){const data={
 name:'Adrenaline',type:'feature',img:'icons/magic/unholy/hand-marked-pink.webp',
 system:{description:"<p>While you're Vulnerable, add your level to your damage rolls.</p>",resource:null,actions:{},attribution:{source:'Daggerheart SRD',page:null,artist:''},gmNotes:'The level bonus is automatically selected on damage rolls while you are Vulnerable.',granter:null,featureForm:'passive'},
 effects:[{name:'Adrenaline',img:'icons/magic/unholy/hand-marked-pink.webp',transfer:true,_id:ADRENALINE_EFFECT,type:'base',system:{changes:[{key:'system.bonuses.damage.bonus',type:'add',value:'@system.levelData.level.current',priority:null,phase:'initial'}],duration:{description:''},rangeDependence:null,stacking:null,targetDispositions:[],conditionals:[]},disabled:true,duration:{value:null,units:'seconds',expiry:null,expired:false},description:"<p>While you're Vulnerable, add your level to your damage rolls.</p>",tint:'#ffffff',statuses:[],sort:0,flags:{},start:null,showIcon:1,folder:null}]
};modernDamageEffects(data);data.folder=folder;data.flags={[ID]:{premade:{key:ADRENALINE_KEY,version:'1.0.0',category:'subclass-features',aliases:[],sourceUuids:['Compendium.daggerheart.subclasses.Item.uByM34yQlw38yf1V']}}};return data;}
export async function ensureAdrenaline(){const pack=game.packs.get(`${ID}.subclass-features`);if(!pack)throw new Error('The Subclass Features compendium is missing.');const existing=(await premadeDocuments(pack)).find(i=>i.getFlag(ID,'premade')?.key===ADRENALINE_KEY);if(existing?.getFlag(ID,'premade')?.version==='1.0.0')return existing;const folder=pack.folders.find(f=>!f.folder&&f.name==='Nightwalker');if(!folder)throw new Error('The Nightwalker compendium folder is missing.');const locked=pack.locked;try{if(locked)await configurePremadePack(pack,{locked:false});const item=existing?await existing.update(adrenalineData(folder.id)):await Item.create(adrenalineData(folder.id),{pack:pack.collection});if(!item)throw new Error('Adrenaline creation was cancelled.');return item;}finally{if(locked)await configurePremadePack(pack,{locked:true});}}
