import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {ownerFor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {ARCANE_CHARGE_KEY,ARCANE_CHARGE_ACTION,ARCANE_CHARGE_EFFECT,ARCANE_CHARGE_BONUS} from './arcane-charge-data.js';
const QUERY=`${ID}.arcaneCharge`,PROMPT=`${ID}.arcaneChargePrompt`,WRAPPED=Symbol.for(`${ID}.arcaneCharge`),pending=new Map();
export function arcaneChargeItem(actor){return actor?.type==='character'?actor.items?.find(i=>{const f=i.flags?.[ID];return featureActive(i)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===ARCANE_CHARGE_KEY;})??null:null;}
export function chargedEffect(actor){const item=arcaneChargeItem(actor);return item?actor.effects?.find(e=>!e.disabled&&!e.isSuppressed&&(e.flags?.[ID]?.arcaneCharged||e.origin===item.effects?.get?.(ARCANE_CHARGE_EFFECT)?.uuid))??null:null;}
export function magicalDamage(value){const types=value?.options?.damageTypes??value?.damageTypes??value?.type??[];return [...types].includes('magical');}
export function tookMagicDamage(packet,updates){return Boolean(magicalDamage(packet?.main)&&(updates??[]).some(u=>['hitPoints','stress'].includes(u.key)&&!u.clear&&!u.itemId&&Number(u.value)>0));}
function chargeData(item){const source=item.effects?.get?.(ARCANE_CHARGE_EFFECT)??item.effects?.find?.(e=>(e.id??e._id)===ARCANE_CHARGE_EFFECT),data=source?.toObject?source.toObject():structuredClone(source);if(!data)throw Error('Arcane Charge effect is missing. Reapply Medkit.');delete data._id;delete data.id;data.disabled=false;data.transfer=false;data.origin=source.uuid??`${item.uuid}.ActiveEffect.${ARCANE_CHARGE_EFFECT}`;data.system={...data.system,duration:{...data.system?.duration,type:'longRest',description:'Until your next long rest.'}};data.flags={...data.flags,[ID]:{...data.flags?.[ID],arcaneCharged:true}};return data;}
async function createCharge(actor){const item=arcaneChargeItem(actor);if(!item||chargedEffect(actor))return false;const created=await actor.createEmbeddedDocuments('ActiveEffect',[chargeData(item)]);if(created?.length!==1)throw Error('Could not apply Arcane Charge.');return true;}
export async function becomeCharged(actor){return actor?withHopeLock(actor.uuid,()=>createCharge(actor)):false;}
export async function spendHopeToCharge(request,{user}){if(!game.user.isActiveGM||!user?.active)return false;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER'))return false;return withHopeLock(actor.uuid,async()=>{if(!arcaneChargeItem(actor)||chargedEffect(actor))return false;const hope=Number(actor.system.resources?.hope?.value);if(hope<2)throw Error('Arcane Charge requires 2 Hope.');const paid=await actor.update({'system.resources.hope.value':hope-2});if(!paid||Number(actor.system.resources.hope.value)!==hope-2)throw Error('Could not spend Arcane Charge Hope.');try{return await createCharge(actor);}catch(error){await actor.update({'system.resources.hope.value':hope});throw error;}});}
export function arcaneAttackModes(action,config){if(action?.type!=='attack'||!chargedEffect(action.actor)||(config?.targets??[]).every(t=>!t.hitResult?.success)||!magicalDamage(action.damage?.main))return[];const modes=['damage'];if(action.save?.trait)modes.push('reaction');return modes;}
export async function promptArcaneChoice(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!chargedEffect(actor))return null;const buttons=[];if(data.modes?.includes('damage'))buttons.push({action:'damage',label:'+10 Damage',callback:()=> 'damage'});if(data.modes?.includes('reaction'))buttons.push({action:'reaction',label:'+3 Reaction Difficulty',callback:()=> 'reaction'});buttons.push({action:'decline',label:'Decline',default:true,callback:()=>null});return timedDialog(`Arcane Charge — ${actor.name}`,'<p>Clear your Charge to enhance this successful magic-damage attack?</p>',buttons);}
export async function resolveArcaneChoice(request,{user},ask=promptArcaneChoice){if(!game.user.isActiveGM||!user?.active||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000))return null;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER')||!chargedEffect(actor))return null;const modes=(request.modes??[]).filter(m=>['damage','reaction'].includes(m)),key=actor.uuid;if(!modes.length||pending.has(key))return null;const operation=(async()=>{const owner=ownerFor(actor,[...game.users],game.user),choice=owner.isSelf?await ask({actorUuid:actor.uuid,modes},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,modes},{timeout:decisionBudget(65000)});if(!modes.includes(choice)||request.deadline<decisionNow())return null;return withHopeLock(actor.uuid,async()=>{const effect=chargedEffect(actor);if(!effect)return null;await effect.delete();return choice;});})();pending.set(key,operation);try{return await operation;}finally{pending.delete(key);}}
export function selectArcaneBonus(roll,config){const message=game.messages.get(config.source?.message),effect=roll.options.bonusEffects?.[ARCANE_CHARGE_BONUS]??config.bonusEffects?.[ARCANE_CHARGE_BONUS];if(effect)effect.selected=Boolean(!config.hasHealing&&message?.flags?.[ID]?.arcaneCharge?.mode==='damage');return effect?.selected??false;}
export function installArcaneTarget(Target,offer){const native=Target.execute;Target.execute=async function(config,...args){const result=await native.call(this,config,...args),modes=arcaneAttackModes(this,config);if(!modes.length)return result;const mode=await offer({actorUuid:this.actor.uuid,modes,deadline:decisionNow()+decisionBudget(120000)});if(mode){config[ID]={...config[ID],arcaneCharge:{mode}};await config.message?.setFlag(ID,'arcaneCharge',{mode});}return result;};}
export function installArcaneSave(Save){const native=Save.execute;Save.execute=async function(config,...args){if(config[ID]?.arcaneCharge?.mode!=='reaction')return native.call(this,config,...args);const base=Number(this.save?.difficulty??this.actor?.baseSaveDifficulty);if(!Number.isFinite(base))return native.call(this,config,...args);const action=new Proxy(this,{get:(target,key,receiver)=>key==='save'?{...target.save,difficulty:base+3}:Reflect.get(target,key,receiver)});return native.call(action,config,...args);};}
export function installArcaneDamage(Damage){const native=Damage.createRollInstance;Damage.createRollInstance=function(config){const roll=native.call(this,config);selectArcaneBonus(roll,config);return roll;};}
export function installArcaneIncoming(Actor,charge){const native=Actor.prototype.takeDamage;Actor.prototype.takeDamage=async function(packet,...args){const result=await native.call(this,packet,...args);if(tookMagicDamage(packet,result)&&arcaneChargeItem(this)&&!chargedEffect(this))await charge({actorUuid:this.uuid});return result;};}
export function registerArcaneCharge(){CONFIG.queries[QUERY]=async(request,{user})=>{if(request.op==='hope')return spendHopeToCharge(request,{user});if(request.op==='damage'){if(!game.user.isActiveGM||!user?.active)return false;return becomeCharged(await fromUuid(request.actorUuid));}return resolveArcaneChoice(request,{user});};CONFIG.queries[PROMPT]=promptArcaneChoice;const dispatch=async request=>{const gm=game.users.activeGM;if(!gm)throw Error('Arcane Charge needs an active GM.');return gm.isSelf?CONFIG.queries[QUERY](request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});};installArcaneTarget(game.system.api.fields.ActionFields.TargetField,request=>dispatch({...request,op:'choice'}));installArcaneSave(game.system.api.fields.ActionFields.SaveField);installArcaneDamage(CONFIG.Dice.daggerheart.DamageRoll);installArcaneIncoming(CONFIG.Actor.documentClass,request=>dispatch({...request,op:'damage'}));Hooks.on('daggerheart.preUseAction',action=>{if(action.id!==ARCANE_CHARGE_ACTION||arcaneChargeItem(action.actor)?.uuid!==action.item?.uuid)return;void dispatch({op:'hope',actorUuid:action.actor.uuid}).catch(e=>ui.notifications.error(e.message));return false;});Hooks.on('renderChatMessageHTML',(message,html)=>{const mode=message.flags?.[ID]?.arcaneCharge?.mode;if(!message.isContentVisible||!mode||html.querySelector('.dhp-arcane-charge'))return;const p=html.ownerDocument.createElement('p');p.className='dhp-arcane-charge';p.textContent=`Arcane Charge: ${mode==='damage'?'+10 damage':'+3 Difficulty to the caused reaction roll'}.`;html.querySelector('.message-content')?.append(p);});Object.defineProperty(CONFIG.Dice.daggerheart.DamageRoll,WRAPPED,{value:true});}
