import {isHopePaymentCancellation,hopefulArmor,hopeCapacity,chooseHopePayment,spendHope,registerHopePaymentQueries,registerHopePaymentPlans} from './hope-payment.js';
import {ID} from '../core.js';
const WRAPPED=Symbol.for(`${ID}.armorHopeful`),ledgers=new WeakMap(),plans=new WeakMap();
const genuineCost=row=>row?.key==='hope'&&Number(row.value)<0&&!row.itemId&&!row.target&&(Object.hasOwn(row,'itemId')||row.enabled===true);
export function recoversArmor(action,config){
  const healing=action?.type==='healing'||action?.hasHealing||config?.hasHealing;
  if(!healing)return false;
  return Object.entries(action?.damage?.resources??{}).some(([key,row])=>(row.applyTo??key)==='armor')||config?.resourceFormulas?.some(row=>row.applyTo==='armor')||false;
}
function rollRecoversArmor(config){const actor=config.data?.parent,source=config.source;if(recoversArmor(null,config))return true;if(!source?.action)return false;const item=actor?.items?.get?.(source.item)??actor?.items?.find?.(i=>i.id===source.item),action=item?.actionsList?.find?.(a=>a.id===source.action)??item?.system?.actions?.[source.action]??actor?.system?.actions?.[source.action];return recoversArmor(action,config);}
export function installHopefulCosts(Cost,ResourceMap,Action){
  if(Cost&&!Object.hasOwn(Cost,WRAPPED)){const hasCost=Cost.hasCost,calcCosts=Cost.calcCosts,execute=Cost.execute;
    // Keep native resource values and displayed Hope counts real. Armor extends
    // payment eligibility only; it is not additional Hope in resource dialogs.
    Cost.hasCost=function(costs,...args){const actor=this.actor?.system?.partner??this.actor;if(recoversArmor(this)){const count=Cost.getRealCosts.call(this,costs).filter(c=>c.key==='hope'&&!c.itemId).reduce((sum,c)=>sum+Number(c.total??c.value),0);return Number.isFinite(count)&&count<=Number(actor?.system?.resources?.hope?.value??0)&&hasCost.call(this,costs,...args);}if(!hopefulArmor(actor)||costs?.some(c=>c.key==='hope'&&c.itemId))return hasCost.call(this,costs,...args);const real=Cost.getRealCosts.call(this,costs),count=real.filter(c=>c.key==='hope'&&!c.itemId).reduce((sum,c)=>sum+Number(c.total??c.value),0);return Number.isFinite(count)&&count<=hopeCapacity(actor)&&hasCost.call(this,real.filter(c=>c.key!=='hope'),...args);};
    Cost.calcCosts=function(costs,...args){const rows=calcCosts.call(this,costs,...args),actor=this.actor?.system?.partner??this.actor;if(!recoversArmor(this)&&hopefulArmor(actor)&&!costs?.some(c=>c.key==='hope'&&c.itemId))for(const row of rows)if(row.key==='hope'&&!row.itemId&&row.scalable)row.maxStep=Math.floor((hopeCapacity(actor)-row.value)/row.step);return rows;};
    Cost.execute=async function(config,successCost=false,...args){if(recoversArmor(this,config))return execute.call(this,config,successCost,...args);const actor=this.actor?.system?.partner??this.actor,count=Cost.getRealCosts(config.costs??[]).filter(c=>c.key==='hope'&&!c.itemId&&((!successCost&&(!c.consumeOnSuccess||config.roll?.success))||(successCost&&c.consumeOnSuccess))).reduce((sum,c)=>sum+Number(c.total??c.value),0);if(count>0&&hopefulArmor(actor)&&config.resourceUpdates&&!plans.has(config.resourceUpdates)){installHopefulCosts(null,config.resourceUpdates.constructor,null);const choice=await chooseHopePayment(actor,count,config.title??this.name);if(choice===null)return false;plans.set(config.resourceUpdates,{actor,choice,label:config.title??this.name,source:hopefulArmor(actor)?.uuid});}return execute.call(this,config,successCost,...args);};Object.defineProperty(Cost,WRAPPED,{value:true});}
  if(ResourceMap&&!Object.hasOwn(ResourceMap,WRAPPED)){const add=ResourceMap.prototype.addResources,update=ResourceMap.prototype.updateResources;
    ResourceMap.prototype.addResources=function(rows,...args){const plan=plans.get(this);if(!plan)return add.call(this,rows,...args);let ledger=ledgers.get(this);if(!ledger){ledger={...plan,count:0,paid:false};ledgers.set(this,ledger);}const remaining=(rows??[]).filter(row=>{if(!genuineCost(row))return true;ledger.count-=Number(row.value);return false;});return add.call(this,remaining,...args);};
    ResourceMap.prototype.updateResources=async function(...args){const ledger=ledgers.get(this);if(ledger?.count&&!ledger.paid){ledger.operation??=(async()=>{try{if(hopefulArmor(ledger.actor)?.uuid!==ledger.source)throw Error('Hopeful armor changed before payment.');const count=ledger.count,armor=Math.min(ledger.choice,count);const receipt=await spendHope(ledger.actor,count,{locked:false,choice:armor,label:ledger.label});if(!receipt)throw Error('Hopeful could not pay this ability cost.');ledger.paid=true;}catch(error){if(isHopePaymentCancellation(error))return false;throw error;}})();await ledger.operation;}return update.apply(this,args);};Object.defineProperty(ResourceMap,WRAPPED,{value:true});
  }
  if(Action&&!Object.hasOwn(Action,WRAPPED)){const workflow=Action.prototype.executeWorkflow;Action.prototype.executeWorkflow=async function(config,...args){const actor=this.actor?.system?.partner??this.actor,costs=Cost.getRealCosts(config.costs??[]).filter(c=>c.key==='hope'&&!c.itemId),count=costs.reduce((sum,c)=>sum+Number(c.total??c.value),0);
    installHopefulCosts(null,config.resourceUpdates?.constructor,null);
    // Rolled actions choose after their native dialog, including any Experience costs.
    if(!recoversArmor(this,config)&&!this.hasRoll&&count>0&&hopefulArmor(actor)&&!plans.has(config.resourceUpdates)){const choice=await chooseHopePayment(actor,count,config.title??this.name);if(choice===null)return false;plans.set(config.resourceUpdates,{actor,choice,label:config.title??this.name,source:hopefulArmor(actor)?.uuid});}
    return workflow.call(this,config,...args);
  };Object.defineProperty(Action,WRAPPED,{value:true});}
}
export function installHopefulRoll(Roll,Cost){if(!Roll||Object.hasOwn(Roll,WRAPPED))return;const configure=Roll.buildConfigure;Roll.buildConfigure=async function(config,...args){const roll=await configure.call(this,config,...args);if(!roll?.constructFormula||roll._evaluated||config.source?.message||!config.resourceUpdates||plans.has(config.resourceUpdates))return roll;const actor=config.data?.parent?.system?.partner??config.data?.parent,count=Cost.getRealCosts(config.costs??[]).filter(c=>c.key==='hope'&&!c.itemId).reduce((sum,c)=>sum+Number(c.total??c.value),0);if(rollRecoversArmor(config)||!hopefulArmor(actor)||count<1)return roll;installHopefulCosts(null,config.resourceUpdates.constructor,null);const choice=await chooseHopePayment(actor,count,config.title??'Roll');if(choice===null)return null;plans.set(config.resourceUpdates,{actor,choice,label:config.title??'Roll',source:hopefulArmor(actor)?.uuid});return roll;};Object.defineProperty(Roll,WRAPPED,{value:true});}
export function registerArmorHopeful(){registerHopePaymentQueries();registerHopePaymentPlans();const api=game.system.api,Cost=api.fields.ActionFields.CostField;installHopefulCosts(Cost,null,api.data.actions.actionsTypes.base);for(const Roll of [CONFIG.Dice.daggerheart.D20Roll,CONFIG.Dice.daggerheart.DualityRoll])installHopefulRoll(Roll,Cost);Hooks.on('daggerheart.preUseAction',action=>{if(hopefulArmor(action.actor)===action.item&&action.item.system.armorFeatures.some(f=>f.value==='hopeful'&&f.actionIds?.includes(action.id))){ui.notifications.info('Hopeful automatically offers Armor instead of Hope when you use an ability.');return false;}});}
