import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {helpRecipients,validHelpRecipient} from '../help-ally.js';
import {ownerFor,closeDistance,unavailableActor} from './aura-rules.js';
import {sourceToken} from './hallowed-aura.js';
import {markReactiveStress} from './stress-payment.js';
import {withHopeLock} from './hope-lock.js';
import {overwhelmHits} from './overwhelm.js';
import {CANNONBALL_KEY,CANNONBALL_PREPARE,CANNONBALL_AGILITY,CANNONBALL_STRENGTH,cannonballTemporaryData} from './cannonball-data.js';
const ACTIVATE=`${ID}.cannonballActivate`,PROMPT=`${ID}.cannonballPrompt`,SECONDARY=`${ID}.cannonballSecondary`,ACTION_WRAP=Symbol.for(`${ID}.cannonballAction`),DAMAGE_WRAP=Symbol.for(`${ID}.cannonballDamage`),REFRESH_WRAP=Symbol.for(`${ID}.cannonballRefresh`),seen=new Map();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const actionIds=new Set([CANNONBALL_AGILITY,CANNONBALL_STRENGTH]);
export function cannonballItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===CANNONBALL_KEY;})??null:null;}
export const cannonballTemporary=item=>item?.flags?.[ID]?.cannonballTemporary??null;
const temporaryItems=actor=>[...(actor?.items??[])].filter(item=>cannonballTemporary(item));
const canStress=actor=>Number(actor?.system?.resources?.stress?.value)<Number(actor?.system?.resources?.stress?.max);
const ranges=()=>game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement;
const closeLimit=()=>closeDistance(canvas.scene,ranges(),CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id);
const veryCloseLimit=()=>{const rules=ranges(),local=canvas.scene.flags?.daggerheart?.rangeMeasurement;return Number(rules.enabled&&local?.setting===CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id?local.veryClose:rules.veryClose);};
export async function promptCannonball(actor){if(!actor?.isOwner||!cannonballItem(actor)||!canStress(actor))throw Error('Cannonball needs an available Stress slot.');const allies=helpRecipients(actor).filter(ally=>!temporaryItems(ally).length).sort((a,b)=>a.name.localeCompare(b.name));if(!allies.length)throw Error('No active-party ally is available to throw you.');const choice=await timedDialog(`Cannonball — ${actor.name}`,`<p>Choose an ally to receive the temporary Cannonball attack. You will mark <strong>1 Stress</strong>.</p><label>Thrower<select name="thrower">${allies.map(ally=>`<option value="${esc(ally.uuid)}">${esc(ally.name)}</option>`).join('')}</select></label>`,[{action:'prepare',label:'Mark Stress & Prepare',callback:(_e,b)=>b.form.elements.thrower.value},{action:'cancel',label:'Cancel',default:true,callback:()=>null}]);if(!choice)return false;const gm=game.users.activeGM;if(!gm)throw Error('Cannonball needs an active GM.');const request={id:foundry.utils.randomID(),beastUuid:actor.uuid,throwerUuid:choice};return gm.isSelf?activateCannonball(request,{user:game.user}):gm.query(ACTIVATE,request,{timeout:decisionBudget(65000)});}
export async function activateCannonball(request,{user}){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string')return false;const beast=await fromUuid(request.beastUuid),thrower=await fromUuid(request.throwerUuid),item=cannonballItem(beast);if(!item||!beast.testUserPermission(user,'OWNER')||!canStress(beast)||!validHelpRecipient(beast,thrower)||temporaryItems(thrower).length)return false;const created=await thrower.createEmbeddedDocuments('Item',[cannonballTemporaryData(beast,item)]);if(created?.length!==1)throw Error('Could not create the temporary Cannonball attack.');let paid=false;try{paid=await markReactiveStress(beast.uuid,current=>Boolean(cannonballItem(current)&&validHelpRecipient(current,thrower)&&!temporaryItems(thrower).filter(entry=>entry.id!==created[0].id).length));if(!paid)return false;}finally{if(!paid)await created[0].delete();}await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:beast}),content:`<p><strong>Cannonball:</strong> ${esc(beast.name)} marks 1 Stress. ${esc(thrower.name)} can make one Cannonball attack using Agility or Strength.</p>`});return created[0].uuid;}
export function validCannonballTarget(action,config){const temp=cannonballTemporary(action?.item);if(!temp||!actionIds.has(action.id))return null;const targets=config?.targets??[...(game.user.targets??[])].map(token=>({id:token.id,actorId:token.actor?.uuid}));if(targets.length!==1)return null;const target=canvas.tokens.get(targets[0].id),origin=sourceToken(action.actor),distance=origin&&target&&origin.distanceTo(target);return target?.actor?.type==='adversary'&&target.actor.uuid===targets[0].actorId&&Number.isFinite(distance)&&distance<=closeLimit()?target:null;}
export function cannonballHits(message){return overwhelmHits(message);}
export function markCannonballDamage(config){const actor=config.data?.parent??foundry.utils.fromUuidSync?.(config.source?.actor),item=actor?.items?.get?.(config.source?.item),temp=cannonballTemporary(item);if(config.hasHealing||!config.damage?.main||!temp||!actionIds.has(config.source?.action))return false;config.damage.main.options[ID]={...config.damage.main.options[ID],cannonball:{throwerUuid:actor.uuid,itemUuid:item.uuid,beastUuid:temp.beastUuid,messageUuid:config.source?.message}};if(typeof config.damage.toObject==='function')config.damage=new config.damage.constructor({...config.damage.toObject(),main:config.damage.main.toJSON(),resources:Object.fromEntries(Object.entries(config.damage.resources??{}).map(([key,value])=>[key,value.toJSON()]))});return true;}
export function secondaryCandidates(primary){const origin=sourceToken(primary),limit=veryCloseLimit(),found=new Map();if(!origin||!Number.isFinite(limit))return[];for(const token of canvas.tokens.placeables){const actor=token.actor,distance=origin.distanceTo(token);if(actor?.type!=='adversary'||actor.uuid===primary.uuid||unavailableActor(actor)||!Number.isFinite(distance)||distance>limit)continue;if(!found.has(actor.uuid)||found.get(actor.uuid).distance>distance)found.set(actor.uuid,{actorUuid:actor.uuid,name:actor.name,distance});}return[...found.values()].sort((a,b)=>a.distance-b.distance||a.name.localeCompare(b.name));}
export async function promptSecondary(data,{user}){const beast=await fromUuid(data.beastUuid);if(!user?.active||!beast?.testUserPermission(game.user,'OWNER')||Number(beast.system.resources?.hope?.value)<1||!data.candidates?.length)return null;return timedDialog(`Cannonball — Additional Target`,`<p>Spend <strong>1 Hope</strong> to deal <strong>${data.damage} physical damage</strong> to one additional adversary within Very Close of ${esc(data.primaryName)}?</p>${data.candidates.map((candidate,index)=>`<label style="display:block;margin:.4rem 0"><input type="radio" name="target" value="${esc(candidate.actorUuid)}" ${index===0?'checked':''}> ${esc(candidate.name)}</label>`).join('')}`,[{action:'spend',label:'Spend 1 Hope',callback:(_e,b)=>b.form.elements.target.value},{action:'decline',label:'Decline',default:true,callback:()=>null}]);}
export async function resolveSecondary(request,{user},ask=promptSecondary){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||request.deadline<decisionNow())return false;for(const[id,expiry]of seen)if(expiry<decisionNow())seen.delete(id);if(seen.has(request.id))return false;const beast=await fromUuid(request.beastUuid),thrower=await fromUuid(request.throwerUuid),primary=await fromUuid(request.primaryUuid),item=await fromUuid(request.itemUuid);if(!beast||!thrower||!primary||cannonballTemporary(item)?.beastUuid!==beast.uuid||(!beast.testUserPermission(user,'OWNER')&&!thrower.testUserPermission(user,'OWNER')))return false;seen.set(request.id,decisionNow()+decisionBudget(300000));try{let candidates=secondaryCandidates(primary);const damage=Math.ceil(Number(request.damage)/2);if(!candidates.length||damage<1)return false;const owner=ownerFor(beast,[...game.users],game.user),data={beastUuid:beast.uuid,primaryName:primary.name,damage,candidates},selected=owner.isSelf?await ask(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});if(!selected)return false;return withHopeLock(beast.uuid,async()=>{candidates=secondaryCandidates(primary);if(!candidates.some(candidate=>candidate.actorUuid===selected))return false;const hope=Number(beast.system.resources?.hope?.value);if(hope<1)return false;const paid=await beast.update({'system.resources.hope.value':hope-1});if(!paid||Number(beast.system.resources.hope.value)!==hope-1)throw Error('Could not spend Cannonball Hope.');const target=await fromUuid(selected);await target.takeDamage({main:{total:damage,options:{damageTypes:['physical'],[ID]:{cannonballSecondary:true}}},resources:{}},false);await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:beast}),content:`<p><strong>Cannonball:</strong> ${esc(beast.name)} spends 1 Hope; ${esc(target.name)} takes ${damage} physical damage.</p>`});return true;});}finally{if(item?.parent)await item.delete();}}
export async function clearCannonballs(){if(!game.user.isActiveGM)return 0;let count=0;for(const actor of game.actors??[]){const ids=temporaryItems(actor).map(item=>item.id);if(ids.length){await actor.deleteEmbeddedDocuments('Item',ids);count+=ids.length;}}return count;}
export function installCannonballRefresh(actions,clear=clearCannonballs){const native=actions?.refreshActors;if(typeof native!=='function'||native[REFRESH_WRAP])return;const wrapped=async function(...args){const scene=game.user.isGM&&this.refreshSelections?.scene?.selected,result=await native.apply(this,args);if(scene)await clear();return result;};Object.defineProperty(wrapped,REFRESH_WRAP,{value:true});actions.refreshActors=wrapped;}
export function installCannonball(Action,Damage,Actor,offer){if(Action&&!Action[ACTION_WRAP]){const native=Action.prototype.use;Action.prototype.use=async function(...args){const temp=cannonballTemporary(this.item);if(!temp||!actionIds.has(this.id))return native.apply(this,args);const config=await native.apply(this,args);if(!config)return config;const hits=cannonballHits(config.message);if(this.item?.parent){if(hits.length)await this.item.update({[`flags.${ID}.cannonballTemporary.consumed`]:true});else await this.item.delete();}return config;};Object.defineProperty(Action,ACTION_WRAP,{value:true});}if(Damage&&!Damage[DAMAGE_WRAP]){const evaluate=Damage.buildEvaluate;Damage.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);markCannonballDamage(config);return result;};Object.defineProperty(Damage,DAMAGE_WRAP,{value:true});const take=Actor.prototype.takeDamage;Actor.prototype.takeDamage=async function(packet,...args){const source=packet?.main?.options?.[ID]?.cannonball,effective=source&&!packet.main.options[ID]?.cannonballSecondary?this.calculateDamage(Number(packet.main.total),packet.main.options?.damageTypes??[]):0,result=await take.call(this,packet,...args);if(source&&effective>0)await offer({...source,primaryUuid:this.uuid,damage:effective});return result;};}}
export function registerCannonball(){CONFIG.queries[ACTIVATE]=activateCannonball;CONFIG.queries[SECONDARY]=resolveSecondary;CONFIG.queries[PROMPT]=promptSecondary;installCannonball(game.system.api.data.actions.actionsTypes.base,CONFIG.Dice.daggerheart.DamageRoll,CONFIG.Actor.documentClass,request=>{const gm=game.users.activeGM;if(!gm)throw Error('Cannonball needs an active GM.');const data={...request,id:foundry.utils.randomID(),deadline:decisionNow()+decisionBudget(120000)};return gm.isSelf?resolveSecondary(data,{user:game.user}):gm.query(SECONDARY,data,{timeout:decisionBudget(125000)});});Hooks.on('daggerheart.preUseAction',(action,config)=>{if(action.id===CANNONBALL_PREPARE&&cannonballItem(action.actor)?.uuid===action.item?.uuid){void promptCannonball(action.actor).catch(error=>ui.notifications.error(error.message));return false;}if(cannonballTemporary(action.item)&&actionIds.has(action.id)&&!validCannonballTarget(action,config)){ui.notifications.warn('Target exactly one adversary within Close range for Cannonball.');return false;}});const install=()=>{installCannonballRefresh(CONFIG.ui.daggerheartMenu?.DEFAULT_OPTIONS?.actions);installCannonballRefresh(ui.daggerheartMenu?.options?.actions);};install();Hooks.on('renderDaggerheartMenu',app=>installCannonballRefresh(app.options.actions));}
