import {premadeDocuments,configurePremadePack} from '../premade-setup-context.js';
import { ID } from '../core.js';

export const CANNONBALL_KEY='beastform-cannonball',CANNONBALL_PREPARE='dhpCannonPrep001',CANNONBALL_AGILITY='dhpCannonAgi0001',CANNONBALL_STRENGTH='dhpCannonStr0001';
const img='icons/skills/movement/ball-spinning-blue.webp';
const attack=(id,name,trait)=>({type:'attack',_id:id,systemPath:'actions',description:`Throw the Beastform character using ${name}.`,chatDisplay:true,actionType:'action',cost:[],uses:{value:null,max:'',recovery:null,consumeOnSuccess:false},damage:{main:{resultBased:false,value:{custom:{enabled:false,formula:''},multiplier:'prof',dice:'d12',bonus:2,flatMultiplier:1},applyTo:'hitPoints',type:['physical'],base:false,valueAlt:null,includeBase:false,direct:false,fullRestore:false,itemId:null},resources:{}},target:{type:'any',amount:1},effects:[],roll:{type:'attack',trait,difficulty:null,bonus:null,advState:'neutral',diceRolling:{multiplier:'prof',flatMultiplier:1,dice:'d6',compare:null,treshold:null},useDefault:false},save:{trait:null,difficulty:10,damageMod:'none'},name:`Cannonball — ${name}`,img,range:'close',baseAction:false,originItem:{type:'itemCollection'},triggers:[],areas:[]});
export function cannonballTemporaryData(beast,item){return{name:`Cannonball — Throw ${beast.name}`,type:'feature',img,system:{description:`<p>Throw or launch <strong>${beast.name}</strong> at one adversary within Close range. Choose Agility or Strength. On a success, deal <strong>d12+2</strong> physical damage using your Proficiency.</p>`,resource:null,actions:{[CANNONBALL_AGILITY]:attack(CANNONBALL_AGILITY,'Agility','agility'),[CANNONBALL_STRENGTH]:attack(CANNONBALL_STRENGTH,'Strength','strength')},attribution:{source:'Daggerheart SRD',page:null,artist:''},gmNotes:'Temporary Cannonball attack. Use once; it is removed after damage resolves, after a miss, or on scene refresh.',granter:null,featureForm:'passive',actorResources:[]},effects:[],flags:{[ID]:{cannonballTemporary:{beastUuid:beast.uuid,sourceItemUuid:item.uuid}}}};}
export function cannonballData(folder){return{name:'Cannonball',type:'feature',img,folder,system:{description:'<p><strong>Mark a Stress</strong> to allow an ally to throw or launch you at an adversary. To do so, the ally makes an attack roll using Agility or Strength (their choice) against a target within Close range. On a success, the adversary takes <strong>d12+2</strong> physical damage using the thrower\'s Proficiency. You can <strong>spend a Hope</strong> to target an additional adversary within Very Close range of the first. The second target takes half the damage dealt to the first target.</p>',resource:null,actions:{[CANNONBALL_PREPARE]:{type:'effect',_id:CANNONBALL_PREPARE,systemPath:'actions',description:'Choose an allied thrower and mark 1 Stress to place a temporary Cannonball attack on their sheet.',chatDisplay:false,actionType:'action',cost:[],uses:{value:null,max:'',recovery:null,consumeOnSuccess:false},effects:[],target:{type:'friendly',amount:1},name:'Prepare Cannonball',img,range:'',baseAction:false,originItem:{type:'itemCollection'},triggers:[],areas:[]}},attribution:{source:'Daggerheart SRD',page:null,artist:''},gmNotes:'Prepare Cannonball chooses an active-party ally, marks the Beastform character’s Stress, and gives the ally a temporary one-use Agility or Strength attack. Native targeting, Proficiency damage, and damage application are preserved. After primary damage, the Beastform character may spend 1 Hope to deal half that effective damage to one additional adversary within Very Close of the first.',granter:null,featureForm:'passive',actorResources:[]},effects:[],flags:{[ID]:{premade:{key:CANNONBALL_KEY,version:'1.0.0',category:'beastform-features',aliases:[],sourceUuids:['Compendium.daggerheart.beastforms.Item.jp5KpPRBFBOIs46Q']}}}};}
export async function ensureCannonball(){const pack=game.packs.get(`${ID}.beastform-features`);if(!pack)throw Error('The Beastform Features compendium is missing.');const existing=(await premadeDocuments(pack)).find(item=>item.getFlag(ID,'premade')?.key===CANNONBALL_KEY);if(existing?.getFlag(ID,'premade')?.version==='1.0.0')return existing;const folder=pack.folders.find(f=>!f.folder&&f.name==='Beastform Features');if(!folder)throw Error('The Beastform Features compendium folder is missing.');const locked=pack.locked;try{if(locked)await configurePremadePack(pack,{locked:false});const data=cannonballData(folder.id),item=existing?await existing.update(data,{diff:false,recursive:false}):await Item.create(data,{pack:pack.collection});if(!item)throw Error('Cannonball creation was cancelled.');return item;}finally{if(locked)await configurePremadePack(pack,{locked:true});}}
