import {ID} from '../core.js';
import {rainOfBladesBonus,rainOfBladesPacket} from './rain-of-blades.js';
const WRAP=Symbol.for(`${ID}.chokehold`),ENTRY=Symbol('Chokehold apply damage'),options={flavor:'Chokehold',formulaKey:'chokeholdFormula',recordKey:'chokehold',appliedKey:'chokeholdApplied'},extra='2d6[Chokehold]';
export const chokeholdBonus=main=>rainOfBladesBonus(main,options);
export const chokeholdPacket=(packet,actor)=>rainOfBladesPacket(packet,actor,options);
export function chokeholdTarget(actor){return Boolean(actor?.statuses?.has('vulnerable')&&[...(actor.effects??[])].some(e=>e.flags?.[ID]?.chokehold===true&&!e.disabled&&!e.isSuppressed&&e.active!==false&&!e.duration?.expired&&(e.statuses?.has?.('vulnerable')||e.statuses?.includes?.('vulnerable'))));}
export function chokeholdAttack(config){const message=config.message??game.messages?.get(config.source?.message),actor=config.data?.parent??foundry.utils.fromUuidSync?.(config.source?.actor),item=actor?.items?.get?.(config.source?.item),id=config.source?.action;
 const action=message?.system?.action??(id&&item?.system?.attack?.id===id?item.system.attack:null)??item?.system?.actions?.get?.(id)??item?.system?.actions?.[id]??(id&&(actor?.system?.attack?.id??actor?.system?.attack?._id)===id?actor.system.attack:null);return action?.type==='attack'?{message,action}:null;}
export function prepareChokehold(config){
 const context=chokeholdAttack(config),targets=(context?.message?.system?.targeting?.usingSelect?context.message.system._getCurrentTargets?.():null)??config.targets??context?.message?.system?.targets??[],seen=new Set(),eligible=[];
 if(!config.hasHealing&&config.messageType!=='healing'&&config.damageFormula?.applyTo==='hitPoints'&&context)for(const target of targets){const actor=foundry.utils.fromUuidSync?.(target.actorId);if(!actor?.uuid||!chokeholdTarget(actor)||seen.has(actor.uuid))continue;seen.add(actor.uuid);eligible.push({actorId:actor.uuid,name:target.name??actor.name});}
 if(!eligible.length)return false;
 if(!config.damageFormula.extraFormula?.includes(extra))config.damageFormula.extraFormula=[config.damageFormula.extraFormula,extra].filter(Boolean).join(' + ');
 config[ID]={...config[ID],chokehold:{targets:eligible}};return true;
}
export function tagChokehold(config,nativeScaling=false,targets=null){const main=config.damage?.main,record=config[ID]?.chokehold??main?.options?.[ID]?.chokehold;if(config.hasHealing||!main||!record)return false;const recipientModifiers={};if(nativeScaling){const save=CONFIG.DH.ACTIONS.damageOnSave[config.onSave];if(save)for(const target of targets??config.targets??[])if(save.onSuccess?target.saveResult?.success===true:!target.saveResult?.success)recipientModifiers[target.actorId]=save.mod??1;}main.options??={};main.options[ID]={...main.options[ID],chokehold:{targets:record.targets,bonus:chokeholdBonus(main),referenceTotal:main.total,nativeScaling,recipientModifiers}};
 const damage=config.damage;if(typeof damage.toObject==='function')config.damage=new damage.constructor({...damage.toObject(),main:main.toJSON(),resources:Object.fromEntries(Object.entries(damage.resources??{}).map(([key,value])=>[key,value.toJSON()]))});return true;}
export function installChokehold(Damage,Field,Actor){
 if(!Object.hasOwn(Damage,WRAP)){const create=Damage.createRollInstance,construct=Damage.prototype.constructFormula,evaluate=Damage.buildEvaluate,post=Damage.buildPost;
  Damage.createRollInstance=function(config,...args){prepareChokehold(config);return create.call(this,config,...args);};
  Damage.prototype.constructFormula=function(part,config,isDamage,...args){const result=construct.call(this,part,config,isDamage,...args);if(isDamage&&result?.roll&&config[ID]?.chokehold){const roll=result.roll;roll.options??={};roll.options[ID]={...roll.options[ID],chokeholdFormula:{criticalFlat:Boolean(config.isCritical&&config.dialog?.configure!==false),multiplier:this.getTotalBonus('system.rules.attack.damage.hpDamageMultiplier')||1}};}return result;};
  Damage.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);tagChokehold(config);return result;};
  Damage.buildPost=async function(roll,config,...args){tagChokehold(config);return post.call(this,roll,config,...args);};Object.defineProperty(Damage,WRAP,{value:true});
 }
 if(!Object.hasOwn(Field,WRAP)){const native=Field.applyDamage;Field.applyDamage=async function(config,...args){tagChokehold(config,true,args[0]);return native.call(this,config,...args);};Object.defineProperty(Field,WRAP,{value:true});}
 if(!Object.hasOwn(Actor,WRAP)){const native=Actor.prototype.takeDamage;Actor.prototype.takeDamage=async function(packet,...args){return native.call(this,chokeholdPacket(packet,this),...args);};Object.defineProperty(Actor,WRAP,{value:true});}
}
export function installChokeholdWorkflow(Action){if(Object.hasOwn(Action,WRAP))return;let prototype=Action.prototype,descriptor;while(prototype&&!descriptor){descriptor=Object.getOwnPropertyDescriptor(prototype,'workflow');prototype=Object.getPrototypeOf(prototype);}if(!descriptor?.get)throw Error('Chokehold requires the native workflow getter.');Object.defineProperty(Action.prototype,'workflow',{...descriptor,get(){const workflow=descriptor.get.call(this),entry=workflow.get('applyDamage');if(entry&&!entry[ENTRY])workflow.set('applyDamage',{...entry,[ENTRY]:true,execute(config,...args){tagChokehold(config,true,args[0]);return entry.execute(config,...args);}});return workflow;}});Object.defineProperty(Action,WRAP,{value:true});}
export function chokeholdLines(message){if(!message.isContentVisible)return null;const main=message.system?.damage?.main,record=main?.options?.[ID]?.chokehold,bonus=typeof main?.toJSON==='function'?chokeholdBonus(main):record?.bonus;return record&&bonus?`Chokehold: held Vulnerable targets take an extra 2d6 (${bonus}); other targets take ${Math.max(0,main.total-bonus)} damage before defenses.`:null;}
export function registerChokehold(){installChokehold(CONFIG.Dice.daggerheart.DamageRoll,game.system.api.fields.ActionFields.DamageField,CONFIG.Actor.documentClass);installChokeholdWorkflow(game.system.api.data.actions.actionsTypes.base);Hooks.on('renderChatMessageHTML',(message,html)=>{const line=chokeholdLines(message);if(!line||html.querySelector('.dhp-chokehold'))return;const note=html.ownerDocument.createElement('p');note.className='dhp-chokehold';note.textContent=line;html.querySelector('.message-content')?.append(note);});}
