import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {timedDialog} from '../dialog.js';
import {ID,featureActive} from '../core.js';
import {ownerFor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {DAMAGE_SINK_KEY,DAMAGE_SINK_ACTION} from './damage-sink-data.js';
const QUERY=`${ID}.damageSink`,PROMPT=`${ID}.damageSinkPrompt`,WRAPPED=Symbol.for(`${ID}.damageSink`),receipts=new Map();
const actionFor=item=>item?.system.actions?.get?.(DAMAGE_SINK_ACTION)??item?.system.actions?.[DAMAGE_SINK_ACTION];
const esc=s=>foundry.utils.escapeHTML(String(s??''));
export function damageSinkItem(actor){if(actor?.type!=='character'||!(Number(actor.system.resources?.favor?.value)>0))return null;return actor.items?.find(item=>{const f=item.flags?.[ID],action=actionFor(item);return featureActive(item)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===DAMAGE_SINK_KEY&&Number(action?.uses?.value??0)<1;})??null;}
export function incomingDamage(args={}){const key='total'in args?'root':args.main?'main':args.damage?'damage':null,raw=key==='root'?args:args[key];const total=typeof raw==='number'?raw:Number(raw?.total),types=Array.from(raw?.options?.damageTypes??raw?.damageTypes??[]);return key&&Number.isFinite(total)&&total>0?{key,raw,total,types,halved:Math.ceil(total/2)}:null;}
const cloneDamage=(raw,total,types)=>{const data=raw?.toJSON?.()??(typeof raw==='number'?{}:{...raw});return{...data,total,options:{...(data.options??raw?.options??{}),damageTypes:[...types]}};};
export function reducedDamageArguments(args,damage){const reduced=cloneDamage(damage.raw,damage.halved,damage.types);if(damage.key==='root')return{...args,...reduced};return{...args,[damage.key]:reduced};}
export async function promptDamageSink(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!damageSinkItem(actor))return false;return Boolean(await timedDialog(`Damage Sink — ${actor.name}`,`<p><strong>${esc(actor.name)}</strong> is taking <strong>${data.total} damage</strong>.</p><p>Spend <strong>1 Favor</strong> and your once-per-rest use to reduce it to <strong>${Math.ceil(data.total/2)}</strong> before thresholds and Armor?</p>`,[{action:'use',label:'Spend Favor',callback:()=>true},{action:'decline',label:'Decline',default:true,callback:()=>false}]));}
export async function resolveDamageSink(request,{user},ask=promptDamageSink){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||!Number.isFinite(request.total)||request.total<=0||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000))return false;for(const[id,r]of receipts)if(r.expires<decisionNow())receipts.delete(id);const key=`${user.id}:${request.id}`;if(receipts.has(key))return receipts.get(key).promise;const promise=(async()=>{let actor=await fromUuid(request.actorUuid),item=damageSinkItem(actor);if(!item||(!user.isGM&&!actor.testUserPermission(user,'OWNER')))return false;const owner=ownerFor(actor,[...game.users],game.user),accepted=owner.isSelf?await ask({actorUuid:actor.uuid,total:request.total},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,total:request.total},{timeout:decisionBudget(65000)});if(!accepted||request.deadline<decisionNow())return false;return withHopeLock(actor.uuid,async()=>{actor=await fromUuid(request.actorUuid);item=damageSinkItem(actor);if(!item)return false;const favor=Number(actor.system.resources.favor.value),usePath=`system.actions.${DAMAGE_SINK_ACTION}.uses.value`,used=await item.update({[usePath]:1});if(!used||Number(actionFor(item)?.uses.value)!==1)throw Error('Could not spend the Damage Sink use.');try{const paid=await actor.update({'system.resources.favor.value':favor-1});if(!paid||Number(actor.system.resources.favor.value)!==favor-1)throw Error('Could not spend Damage Sink Favor.');return true;}catch(error){await item.update({[usePath]:0});throw error;}});})();receipts.set(key,{promise,expires:decisionNow()+decisionBudget(300000)});return promise;}
async function offerDamageSink(actor,damage){const gm=game.users.activeGM;if(!gm)throw Error('Damage Sink needs an active GM.');const request={id:foundry.utils.randomID(),actorUuid:actor.uuid,total:damage.total,deadline:decisionNow()+decisionBudget(120000)};return gm.isSelf?resolveDamageSink(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});}
export function installDamageSink(ActorClass,offer=offerDamageSink){if(ActorClass[WRAPPED])return;const native=ActorClass.prototype.takeDamage;if(typeof native!=='function')throw Error('Unsupported Daggerheart damage API.');ActorClass.prototype.takeDamage=async function(args={},isDirect=false){const damage=incomingDamage(args);if(!damage||!damageSinkItem(this)||!(this.calculateDamage(damage.total,damage.types)>0))return native.call(this,args,isDirect);let accepted;try{accepted=await offer(this,damage);}catch(error){ui.notifications.error(`Damage Sink stopped damage application: ${error.message}`);throw error;}if(!accepted)return native.call(this,args,isDirect);try{return await native.call(this,reducedDamageArguments(args,damage),isDirect);}catch(error){ui.notifications.error('Damage application failed after Damage Sink was paid. Check this actor’s damage, Favor, and use before retrying.');throw error;}};Object.defineProperty(ActorClass,WRAPPED,{value:true});}
export function registerDamageSink(){CONFIG.queries[QUERY]=resolveDamageSink;CONFIG.queries[PROMPT]=promptDamageSink;installDamageSink(CONFIG.Actor.documentClass);Hooks.on('daggerheart.preUseAction',action=>{const f=action.item?.flags?.[ID];if(action.id===DAMAGE_SINK_ACTION&&(f?.applied?.key??f?.premade?.key)===DAMAGE_SINK_KEY){ui.notifications.info('Damage Sink is offered automatically when incoming damage is applied.');return false;}});}
