import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {timedDialog} from '../dialog.js';
import {ID,featureActive} from '../core.js';
import {ownerFor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {HP_REACTIONS_HANDLED} from './hp-reactions.js';
import {DARK_AEGIS_KEY,DARK_AEGIS_ACTION} from './dark-aegis-data.js';
const QUERY=`${ID}.darkAegis`,PROMPT=`${ID}.darkAegisPrompt`,HANDLED=`${ID}.darkAegisHandled`,receipts=new Map(),handling=new WeakSet();
const actionFor=item=>item?.system.actions?.get?.(DARK_AEGIS_ACTION)??item?.system.actions?.[DARK_AEGIS_ACTION];
export function darkAegisItem(actor){if(actor?.type!=='character'||!(Number(actor.system.resources?.favor?.value)>0))return null;return actor.items?.find(item=>{const f=item.flags?.[ID],action=actionFor(item);return featureActive(item)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===DARK_AEGIS_KEY&&Number(action?.uses?.value??0)<1&&action?.uses?.recovery==='longRest';})??null;}
export async function promptDarkAegis(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!darkAegisItem(actor))return false;return Boolean(await timedDialog(`Dark Aegis — ${actor.name}`,`<p><strong>${actor.name}</strong> would mark <strong>${data.count} HP</strong>.</p><p>Spend <strong>1 Favor</strong> and your once-per-long-rest use to mark no HP from this damage?</p>`,[{action:'use',label:'Spend Favor',callback:()=>true},{action:'decline',label:'Decline',default:true,callback:()=>false}]));}
export async function resolveDarkAegis(request,{user},ask=promptDarkAegis){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||!Number.isSafeInteger(request.count)||request.count<1||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000))return false;for(const[id,r]of receipts)if(r.expires<decisionNow())receipts.delete(id);const key=`${user.id}:${request.id}`;if(receipts.has(key))return receipts.get(key).promise;const promise=(async()=>{let actor=await fromUuid(request.actorUuid),item=darkAegisItem(actor);if(!item||(!user.isGM&&!actor.testUserPermission(user,'OWNER')))return false;const owner=ownerFor(actor,[...game.users],game.user),accepted=owner.isSelf?await ask({actorUuid:actor.uuid,count:request.count},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,count:request.count},{timeout:decisionBudget(65000)});if(!accepted||request.deadline<decisionNow())return false;return withHopeLock(actor.uuid,async()=>{actor=await fromUuid(request.actorUuid);item=darkAegisItem(actor);if(!item)return false;const favor=Number(actor.system.resources.favor.value),path=`system.actions.${DARK_AEGIS_ACTION}.uses.value`,used=await item.update({[path]:1});if(!used||Number(actionFor(item)?.uses.value)!==1)throw Error('Could not spend the Dark Aegis use.');try{const paid=await actor.update({'system.resources.favor.value':favor-1},{[HANDLED]:true,[HP_REACTIONS_HANDLED]:true});if(!paid||Number(actor.system.resources.favor.value)!==favor-1)throw Error('Could not spend Dark Aegis Favor.');return true;}catch(error){await item.update({[path]:0});throw error;}});})();receipts.set(key,{promise,expires:decisionNow()+decisionBudget(300000)});return promise;}
async function offerDarkAegis(actor,count){const gm=game.users.activeGM;if(!gm)throw Error('Dark Aegis needs an active GM.');const request={id:foundry.utils.randomID(),actorUuid:actor.uuid,count,deadline:decisionNow()+decisionBudget(120000)};return gm.isSelf?resolveDarkAegis(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});}
export function installDarkAegis(ActorClass,offer=offerDarkAegis){const modify=ActorClass.prototype.modifyResource,pre=ActorClass.prototype._preUpdate;ActorClass.prototype.modifyResource=async function(resources){const hp=resources?.filter(r=>r.key==='hitPoints'&&!r.itemId&&!r.clear&&r.damageTypes!=null&&Number.isSafeInteger(r.value)&&r.value>0)??[],count=hp.reduce((n,r)=>n+r.value,0);if(count>0&&darkAegisItem(this)&&await offer(this,count))for(const entry of hp)entry.value=0;handling.add(this);try{return await modify.call(this,resources);}finally{handling.delete(this);}};ActorClass.prototype._preUpdate=async function(changed,options={},user){const path='system.resources.hitPoints.value',proposed=changed[path]??foundry.utils.getProperty(changed,path),current=Number(this.system?.resources?.hitPoints?.value),delta=Number(proposed)-current;if(!handling.has(this)&&!options[HP_REACTIONS_HANDLED]&&!options[HANDLED]&&Number.isSafeInteger(delta)&&delta>0&&darkAegisItem(this)&&await offer(this,delta)){if(Object.hasOwn(changed,path))changed[path]=current;else foundry.utils.setProperty(changed,path,current);options[HANDLED]=true;}return pre.call(this,changed,options,user);};}
export function registerDarkAegis(){CONFIG.queries[QUERY]=resolveDarkAegis;CONFIG.queries[PROMPT]=promptDarkAegis;installDarkAegis(CONFIG.Actor.documentClass);Hooks.on('daggerheart.preUseAction',action=>{const f=action.item?.flags?.[ID];if(action.id===DARK_AEGIS_ACTION&&(f?.applied?.key??f?.premade?.key)===DARK_AEGIS_KEY){ui.notifications.info('Dark Aegis is offered automatically when you would mark HP from damage.');return false;}});}
