import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {withHopeLock} from './hope-lock.js';
import {resolvedAttackTargets} from '../attack-outcome.js';
import {syncBeastformAttackAction} from '../beastform-roll-damage.js';
import {DEADLY_FOCUS_KEY,DEADLY_FOCUS_ACTION,DEADLY_FOCUS_EFFECT} from './deadly-focus-data.js';
const QUERY=ID+'.expireDeadlyFocus',WRAP=Symbol.for(QUERY),contexts=new Map();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function deadlyFocusItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const f=item.flags?.[ID],s=item.system;return item.type==='domainCard'&&featureActive(item)&&!f?.disabled&&(!s.inVault||s.vaultActive)&&!s.isDomainTouchedSuppressed&&(f?.applied?.key??f?.premade?.key)===DEADLY_FOCUS_KEY;})??null:null;}
export function deadlyFocusDefeated(actor){const hp=actor?.system?.resources?.hitPoints;return !actor||actor.statuses?.has('dead')||actor.statuses?.has('defeated')||Number(hp?.max)>0&&Number(hp.value)>=Number(hp.max)||Boolean(game.combat?.combatants?.some(c=>c.actor?.uuid===actor.uuid&&c.defeated));}
export function deadlyFocusEffects(actor){return [...(actor?.effects??[])].filter(effect=>{const f=effect.flags?.[ID]?.deadlyFocus;return f?.casterUuid===actor.uuid&&typeof f.targetUuid==='string'&&effect.origin===f.itemUuid+'.ActiveEffect.'+DEADLY_FOCUS_EFFECT;});}
export function deadlyFocusTargets(actor){const seen=new Set();return (canvas.ready?canvas.tokens?.placeables??[]:[]).filter(token=>{const target=token.actor;if(!['character','adversary'].includes(target?.type)||target.uuid===actor.uuid||!token.visible||deadlyFocusDefeated(target)||seen.has(target.uuid))return false;seen.add(target.uuid);return true;});}
export async function chooseDeadlyFocus(actor){const targets=deadlyFocusTargets(actor),selected=[...(game.user.targets??[])].filter(t=>targets.some(candidate=>candidate.id===t.id));if(selected.length===1)return selected[0];if(!targets.length){ui.notifications.info('Deadly Focus needs a living creature on the scene.');return null;}const uuid=await timedDialog('Deadly Focus',`<div class="form-group"><label>Focus target</label><select name="deadlyFocusTarget">${targets.map(t=>`<option value="${esc(t.document.uuid)}">${esc(t.name)}</option>`).join('')}</select></div>`,[{action:'focus',label:'Focus',callback:(_e,_b,dialog)=>dialog.element.querySelector('[name="deadlyFocusTarget"]')?.value},{action:'cancel',label:'Cancel',default:true,callback:()=>null}]);return targets.find(t=>t.document.uuid===uuid)??null;}
export function deadlyFocusSwitched(message,targetUuid){const d=message?.system;return d?.action?.type==='attack'&&d.hasRoll!==false&&d.roll?._evaluated!==false&&Number.isFinite(d.roll?.total)&&resolvedAttackTargets(message).some(t=>typeof t.actorId==='string'&&t.actorId!==targetUuid);}
export async function expireDeadlyFocus(request,{user}){if(!game.user.isActiveGM||!user?.active||!Array.isArray(request.effectIds))return false;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER'))return false;return withHopeLock('deadly-focus:'+actor.uuid,async()=>{const message=request.reason==='attack'?await fromUuid(request.messageUuid):null;if(request.reason==='attack'&&message?.system?.action?.actor?.uuid!==actor.uuid)return false;if(!['attack','defeat'].includes(request.reason))return false;const ids=[];for(const effect of deadlyFocusEffects(actor)){if(!request.effectIds.includes(effect.id))continue;const f=effect.flags[ID].deadlyFocus;if(request.reason==='attack'?deadlyFocusSwitched(message,f.targetUuid):deadlyFocusDefeated(await fromUuid(f.targetUuid)))ids.push(effect.id);}if(!ids.length)return false;await actor.deleteEmbeddedDocuments('ActiveEffect',ids);if(message)await syncBeastformAttackAction(message,actor);return true;});}
function allActors(){const actors=new Map([...game.actors].map(a=>[a.uuid,a]));for(const scene of game.scenes??[])for(const token of scene.tokens??[])if(token.actor)actors.set(token.actor.uuid,token.actor);return [...actors.values()];}
export async function sweepDeadlyFocus(targetUuid=null){if(!game.user.isActiveGM)return;for(const actor of allActors()){const effects=deadlyFocusEffects(actor).filter(e=>!targetUuid||e.flags[ID].deadlyFocus.targetUuid===targetUuid);if(effects.length)await expireDeadlyFocus({actorUuid:actor.uuid,effectIds:effects.map(e=>e.id),reason:'defeat'},{user:game.user});}}
export function installDeadlyFocus(Action,Field,RollField,send,choose=chooseDeadlyFocus){
 if(!Object.hasOwn(Field,WRAP)){
  const apply=Field.applyEffect,execute=Field.execute;
  Field.applyEffect=async function(effect,actor){const item=effect.parent,context=contexts.get(item?.uuid);if(!context?.record||actor.uuid!==context.casterUuid||effect.id!==DEADLY_FOCUS_EFFECT)return apply.call(this,effect,actor);if(deadlyFocusEffects(actor).some(e=>e.flags[ID].deadlyFocus.generation===context.record.generation))return;const previous=deadlyFocusEffects(actor).map(e=>e.id),view=Object.create(effect),data=effect.toObject();data.flags={...data.flags,[ID]:{...data.flags?.[ID],deadlyFocus:context.record}};Object.defineProperty(view,'toObject',{value:()=>data});const write=(async()=>{await apply.call(this,view,actor);if(!deadlyFocusEffects(actor).some(e=>e.flags[ID].deadlyFocus.generation===context.record.generation))throw Error('Deadly Focus effect was not created.');if(previous.length)await actor.deleteEmbeddedDocuments('ActiveEffect',previous);})();context.writes.push(Promise.resolve(write));return write;};
  Field.execute=async function(config,...args){const item=deadlyFocusItem(this.actor),message=config.message??game.messages.get(config.parent?._id??config.parent?.id),record=message?.flags?.[ID]?.deadlyFocusActivation;
   if(this.id!==DEADLY_FOCUS_ACTION||item?.uuid!==this.item?.uuid||contexts.has(item.uuid)||!record)return execute.call(this,config,...args);
   if(record.itemUuid!==item.uuid||record.casterUuid!==this.actor.uuid||deadlyFocusDefeated(await fromUuid(record.targetUuid)))return false;
   const context={...record,record,writes:[]};contexts.set(item.uuid,context);try{const result=await execute.call(this,config,...args);await Promise.all(context.writes);return result;}finally{contexts.delete(item.uuid);}
  };Object.defineProperty(Field,WRAP,{value:true});
 }
 if(!Object.hasOwn(Action,WRAP)){
  const native=Action.prototype.use;let proto=Action.prototype,descriptor;while(proto&&!descriptor){descriptor=Object.getOwnPropertyDescriptor(proto,'workflow');proto=Object.getPrototypeOf(proto);}
  if(!descriptor?.get)throw Error('Deadly Focus requires native action workflows.');
  Object.defineProperty(Action.prototype,'workflow',{...descriptor,get(){const parts=descriptor.get.call(this);if(deadlyFocusItem(this.actor)?.uuid===this.item?.uuid&&this.id===DEADLY_FOCUS_ACTION){const entry=parts.get('effects');if(entry&&!entry[WRAP])parts.set('effects',{...entry,[WRAP]:true,execute:(config,...args)=>Field.execute.call(this,config,...args)});}if(this.type==='attack'&&deadlyFocusEffects(this.actor).length){const entry=parts.get('roll');if(entry&&!entry[WRAP])parts.set('roll',{...entry,[WRAP]:true,execute:(config,...args)=>RollField.execute.call(this,config,...args)});}return parts;}});
  Action.prototype.use=async function(...args){const item=deadlyFocusItem(this.actor);if(item?.uuid!==this.item?.uuid||this.id!==DEADLY_FOCUS_ACTION)return native.apply(this,args);if(!this.actor.testUserPermission(game.user,'OWNER')||contexts.has(item.uuid))return false;
   const context={casterUuid:this.actor.uuid,writes:[]};contexts.set(item.uuid,context);try{const target=await choose(this.actor);if(!target||!game.user.active||deadlyFocusItem(this.actor)?.uuid!==item.uuid||!deadlyFocusTargets(this.actor).some(t=>t.document.uuid===target.document.uuid&&t.actor.uuid===target.actor.uuid))return false;
    context.record={casterUuid:this.actor.uuid,itemUuid:item.uuid,targetUuid:target.actor.uuid,tokenUuid:target.document.uuid,generation:foundry.utils.randomID()};const result=await native.apply(this,args);await Promise.all(context.writes);if(result&&deadlyFocusDefeated(target.actor))await send({actorUuid:this.actor.uuid,effectIds:deadlyFocusEffects(this.actor).filter(e=>e.flags[ID].deadlyFocus.generation===context.record.generation).map(e=>e.id),reason:'defeat'});return result;
   }finally{contexts.delete(item.uuid);}
  };Object.defineProperty(Action,WRAP,{value:true});
 }
 if(!Object.hasOwn(RollField,WRAP)){const native=RollField.execute;RollField.execute=async function(config,...args){const actor=this.actor,effects=this.type==='attack'?deadlyFocusEffects(actor):[];const result=await native.call(this,config,...args);if(result!==false&&effects.length&&config.message){try{await syncBeastformAttackAction(config.message,actor);if(effects.some(e=>deadlyFocusSwitched(config.message,e.flags[ID].deadlyFocus.targetUuid)))await send({actorUuid:actor.uuid,messageUuid:config.message.uuid,effectIds:effects.map(e=>e.id),reason:'attack'});}catch(error){ui.notifications.error('Deadly Focus could not expire; check the Proficiency bonus before rolling damage: '+error.message);throw error;}}return result;};Object.defineProperty(RollField,WRAP,{value:true});}
}
export function registerDeadlyFocus(){CONFIG.queries[QUERY]=expireDeadlyFocus;const Fields=game.system.api.fields.ActionFields,send=request=>{const gm=game.users.activeGM;if(!gm)throw Error('Deadly Focus needs an active GM.');return gm.isSelf?expireDeadlyFocus(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(65000)});};installDeadlyFocus(game.system.api.data.actions.actionsTypes.base,Fields.EffectsField,Fields.RollField,send);
 Hooks.on('preCreateChatMessage',message=>{const source=message.system?.source,actor=source?.actor&&foundry.utils.fromUuidSync(source.actor),item=actor?.items?.get(source.item),context=contexts.get(item?.uuid);if(source?.action===DEADLY_FOCUS_ACTION&&context?.record&&context.casterUuid===actor.uuid)message.updateSource({['flags.'+ID+'.deadlyFocusActivation']:context.record});});
 for(const hook of ['updateActor','deleteActor','createActiveEffect','updateActiveEffect','deleteActiveEffect','updateCombatant'])Hooks.on(hook,doc=>{const actor=hook.includes('ActiveEffect')?doc.parent:hook==='updateCombatant'?doc.actor:doc;if(!['character','adversary'].includes(actor?.type))return;void sweepDeadlyFocus(actor.uuid).catch(error=>ui.notifications.error('Deadly Focus expiry needs manual review: '+error.message));});
}
