import {ID,featureActive} from '../core.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {timedDialog} from '../dialog.js';
import {ownerFor,unavailableActor} from './aura-rules.js';
import {sourceToken} from './hallowed-aura.js';
import {meleeLimit} from './kick.js';
import {overwhelmHits} from './overwhelm.js';
import {animateInitialDamage} from './combo-strike.js';
import {animateLuckbenderReroll} from './luckbender.js';
import {selectableDamageDice,rerollDamageDice} from './damage-reroll.js';
import {DEADLY_RAPTOR_KEY,DEADLY_RAPTOR_ACTION,DEADLY_RAPTOR_EFFECT} from './deadly-raptor-data.js';
const QUERY=`${ID}.deadlyRaptor`,PROMPT=`${QUERY}Prompt`,ACTION_WRAP=Symbol.for(`${ID}.deadlyRaptorAction`),DAMAGE_WRAP=Symbol.for(`${ID}.deadlyRaptorDamage`),requests=new Map();
export function deadlyRaptorItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===DEADLY_RAPTOR_KEY;})??null:null;}
export function deadlyRaptorPrimes(actor){return[...(actor?.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&effect.flags?.[ID]?.deadlyRaptorPrime?.targetActorUuid);}
export function deadlyRaptorDice(roll,proficiency){return selectableDamageDice(roll).filter(die=>Number.isFinite(Number(die.value))&&Number(die.value)<Number(proficiency));}
export async function primeDeadlyRaptor(action,targets=[...(game.user.targets??[])]){const actor=action?.actor,item=deadlyRaptorItem(actor);if(action?.id!==DEADLY_RAPTOR_ACTION||item?.uuid!==action.item?.uuid)return null;if(targets.length!==1){ui.notifications.warn('Select exactly one target for Deadly Raptor.');return false;}const target=[...targets][0],origin=sourceToken(actor),distance=origin&&target&&origin.distanceTo(target);if(!target?.actor||target.actor.uuid===actor.uuid||unavailableActor(target.actor)||!Number.isFinite(distance)||distance>meleeLimit(canvas.scene)){ui.notifications.warn('Deadly Raptor requires one living target within Melee range.');return false;}const template=item.effects?.get?.(DEADLY_RAPTOR_EFFECT);if(!template)throw Error('Deadly Raptor prime effect is missing.');const existing=deadlyRaptorPrimes(actor);if(existing.length)await actor.deleteEmbeddedDocuments('ActiveEffect',existing.map(effect=>effect.id));const data=template.toObject?template.toObject():structuredClone(template);delete data._id;data.flags={...data.flags,[ID]:{...data.flags?.[ID],deadlyRaptorPrime:{targetActorUuid:target.actor.uuid,targetTokenUuid:target.document?.uuid}}};const[effect]=await actor.createEmbeddedDocuments('ActiveEffect',[data]);if(!effect)throw Error('Could not prime Deadly Raptor.');ui.notifications.info(`Deadly Raptor primed against ${target.name}.`);return effect;}
export async function promptDeadlyRaptor(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.active||!actor?.testUserPermission(game.user,'OWNER')||!deadlyRaptorItem(actor)||!data.dice?.length)return false;return Boolean(await timedDialog(`Deadly Raptor — ${actor.name}`,`<p><strong>${data.dice.length}</strong> damage ${data.dice.length===1?'die is':'dice are'} below Proficiency ${Number(data.proficiency)}.</p><p>Reroll all of them?</p>`,[{action:'reroll',label:'Reroll All',callback:()=>true},{action:'decline',label:'Keep Damage',default:true,callback:()=>false}]));}
export async function resolveDeadlyRaptor(request,{user},ask=promptDeadlyRaptor){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000)||!Array.isArray(request.dice)||!request.dice.length)return false;for(const[id,expiry]of requests)if(expiry<decisionNow())requests.delete(id);if(requests.has(request.id))return false;const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,item=deadlyRaptorItem(actor),flag=message?.flags?.[ID]?.deadlyRaptor;if(!item||!flag||!actor.testUserPermission(user,'OWNER')||Number(flag.proficiency)!==Number(request.proficiency)||request.dice.some(die=>!/^[0-9]+:[0-9]+$/.test(die.id)||Number(die.value)>=Number(request.proficiency)))return false;requests.set(request.id,decisionNow()+decisionBudget(300000));const owner=ownerFor(actor,[...game.users],game.user);return owner.isSelf?ask({actorUuid:actor.uuid,dice:request.dice,proficiency:request.proficiency},{user:game.user}):owner.query(PROMPT,{actorUuid:actor.uuid,dice:request.dice,proficiency:request.proficiency},{timeout:decisionBudget(65000)});}
export async function offerDeadlyRaptor(config,dependencies={}){const message=game.messages.get(config.source?.message),actor=message?.system?.action?.actor,flag=message?.flags?.[ID]?.deadlyRaptor,roll=config.damage?.main,proficiency=Number(flag?.proficiency),dice=deadlyRaptorDice(roll,proficiency);if(config.hasHealing||!message||!deadlyRaptorItem(actor)||!flag||!Number.isFinite(proficiency)||!dice.length||roll.options?.[ID]?.deadlyRaptor)return false;await(dependencies.initial??animateInitialDamage)(config,message);const decide=dependencies.decide??(async request=>{const gm=game.users.activeGM;if(!gm)throw Error('Deadly Raptor needs an active GM.');return gm.isSelf?resolveDeadlyRaptor(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});});const accepted=await decide({id:foundry.utils.randomID(),messageUuid:message.uuid,proficiency,dice,deadline:decisionNow()+decisionBudget(120000)});if(!accepted)return false;const current=deadlyRaptorDice(roll,proficiency);if(!current.length)return false;const fresh=await rerollDamageDice(roll,current.map(die=>die.id));roll.options[ID]={...roll.options[ID],deadlyRaptor:true};await(dependencies.animate??animateLuckbenderReroll)(roll,config,message);if(game.dice3d)for(const result of fresh)result.hidden=true;return true;}
export function installDeadlyRaptor(Action,Damage,offer=offerDeadlyRaptor){if(Action&&!Action[ACTION_WRAP]){const use=Action.prototype.use;Action.prototype.use=async function(...args){const primes=this.type==='attack'?deadlyRaptorPrimes(this.actor):[],config=await use.apply(this,args);if(!config||!primes.length)return config;const hitTargets=new Set(overwhelmHits(config.message).map(hit=>hit.actorId)),prime=primes.find(effect=>hitTargets.has(effect.flags[ID].deadlyRaptorPrime.targetActorUuid));if(prime)await config.message.setFlag(ID,'deadlyRaptor',{targetActorUuid:prime.flags[ID].deadlyRaptorPrime.targetActorUuid,proficiency:Number(this.actor.system.proficiency)});const ids=primes.map(effect=>effect.id).filter(id=>this.actor.effects?.get?.(id));if(ids.length)await this.actor.deleteEmbeddedDocuments('ActiveEffect',ids);return config;};Object.defineProperty(Action,ACTION_WRAP,{value:true});}if(Damage&&!Damage[DAMAGE_WRAP]){const evaluate=Damage.buildEvaluate;Damage.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);if(!config.hasHealing&&config.damage?.main)try{await offer(config);}catch(error){console.error(`${ID} | Deadly Raptor failed`,error);ui.notifications.error('Deadly Raptor failed; the normal damage roll was preserved.');}return result;};Object.defineProperty(Damage,DAMAGE_WRAP,{value:true});}}
export function registerDeadlyRaptor(){CONFIG.queries[QUERY]=resolveDeadlyRaptor;CONFIG.queries[PROMPT]=promptDeadlyRaptor;installDeadlyRaptor(game.system.api.data.actions.actionsTypes.base,CONFIG.Dice.daggerheart.DamageRoll);Hooks.on('daggerheart.preUseAction',action=>{if(action.id!==DEADLY_RAPTOR_ACTION||deadlyRaptorItem(action.actor)?.uuid!==action.item?.uuid)return;void primeDeadlyRaptor(action).catch(error=>{console.error(`${ID} | Deadly Raptor prime failed`,error);ui.notifications.error(`Deadly Raptor failed: ${error.message}`);});return false;});}
