import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {attackTargetOutcome,resolvedAttackTargets} from '../attack-outcome.js';
import {sourceToken} from './hallowed-aura.js';
import {closeDistance,ownerFor,unavailableActor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {decisionBudget} from '../settings.js';
import {GRIP_KEY,GRIP_CAST,GRIP_VINES} from './death-grip-data.js';

const QUERY=ID+'.deathGrip',PROMPT=QUERY+'Prompt',WRAP=Symbol.for(QUERY),APPLY=Symbol.for(QUERY+'Apply');
const casting=new WeakMap(),waves=new WeakMap(),authorized=new WeakSet();
const HIDE=Symbol.for(QUERY+'Hide');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function gripItem(actor){return actor?.type==='character'?actor.items?.find(i=>{const f=i.flags?.[ID];return i.type==='domainCard'&&featureActive(i)&&!f?.disabled&&(!i.system.inVault||i.system.vaultActive)&&!i.system.isDomainTouchedSuppressed&&(f?.applied?.key??f?.premade?.key)===GRIP_KEY;})??null:null;}
export function gripAction(action,id){return Boolean(gripItem(action?.actor)?.uuid===action?.item?.uuid&&action?.id===id&&action.actionType!=='reaction');}
function vinesIdentity(action){const f=action?.item?.flags?.[ID];return action?.id===GRIP_VINES&&action.item?.type==='domainCard'&&(f?.applied?.key??f?.premade?.key)===GRIP_KEY;}
export function hideGripAction(item){const f=item?.flags?.[ID];if(item?.type!=='domainCard'||(f?.applied?.key??f?.premade?.key)!==GRIP_KEY)return;const action=item.system.actions?.get?.(GRIP_VINES)??item.system.actions?.[GRIP_VINES];if(action)action.isGrouped=true;}
export function installGripVisibility(Item,SelectionDialog){
 if(!Object.hasOwn(Item,HIDE)){const prepare=Item.prototype.prepareData;Item.prototype.prepareData=function(...args){const result=prepare.apply(this,args);hideGripAction(this);return result;};Object.defineProperty(Item,HIDE,{value:true});}
 // The native selection popup reads actionsList directly and ignores isGrouped.
 // Filter its display context, never actionsList: saved chat cards use that list
 // to recover the follow-up action for native reaction/damage buttons.
 if(SelectionDialog&&!Object.hasOwn(SelectionDialog,HIDE)){const prepare=SelectionDialog.prototype._prepareContext;SelectionDialog.prototype._prepareContext=async function(...args){const context=await prepare.apply(this,args),item=this.item??context.item,f=item?.flags?.[ID];if(item?.type!=='domainCard'||(f?.applied?.key??f?.premade?.key)!==GRIP_KEY)return context;return {...context,actions:context.actions.filter(a=>a.id!==GRIP_VINES)};};Object.defineProperty(SelectionDialog,HIDE,{value:true});}
}
function castMessage(message){const d=message?.system;return gripAction(d?.action,GRIP_CAST)&&d.action.type==='attack'&&d.hasRoll!==false&&d.roll?._evaluated!==false&&d.roll?.options?.actionType!=='reaction'&&Number.isFinite(d.roll?.total)?message:null;}
const alive=token=>token?.visible&&!token.document?.hidden&&!unavailableActor(token.actor)&&!(Number(token.actor.system.resources?.hitPoints?.max)>0&&Number(token.actor.system.resources.hitPoints.value)>=Number(token.actor.system.resources.hitPoints.max));
const point=token=>({x:Number(token.center?.x),y:Number(token.center?.y)});
const position=token=>JSON.stringify([token.document.uuid,token.actor.uuid,token.x,token.y,token.w,token.h,token.document.elevation]);
function range(){const rules=game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement;return Number(canvas.scene.rangeSettings?.close??closeDistance(canvas.scene,rules,CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id));}
function within(origin,target){const d=origin.distanceTo(target),limit=range();return Number.isFinite(d)&&d>=0&&Number.isFinite(limit)&&limit>=0&&d<=limit;}
// A zero-width line intersects the rectangular token footprint, not just its center.
// No invented spell width: the confirmation dialog supports table adjudication.
export function gripIntersects(a,b,token){const x=Number(token.x),y=Number(token.y),w=Number(token.w),h=Number(token.h);if(![a.x,a.y,b.x,b.y,x,y,w,h].every(Number.isFinite)||w<=0||h<=0||a.x===b.x&&a.y===b.y)return false;let lo=0,hi=1;for(const [start,delta,min,max] of [[a.x,b.x-a.x,x,x+w],[a.y,b.y-a.y,y,y+h]]){if(delta===0){if(start<min||start>max)return false;continue;}const u=(min-start)/delta,v=(max-start)/delta;lo=Math.max(lo,Math.min(u,v));hi=Math.min(hi,Math.max(u,v));if(lo>hi)return false;}return hi>0&&lo<1;}
function candidates(origin,target){const seen=new Set([origin.actor.uuid,target.actor.uuid]),a=point(origin),b=point(target);return canvas.tokens.placeables.filter(t=>{if(t.actor?.type!=='adversary'||seen.has(t.actor.uuid)||!alive(t)||!within(origin,t))return false;seen.add(t.actor.uuid);return true;}).map(t=>({id:t.id,actorId:t.actor.uuid,tokenUuid:t.document.uuid,name:t.name??t.actor.name,img:t.actor.img,difficulty:t.actor.system.difficulty??null,evasion:null,selected:gripIntersects(a,b,t)}));}
export function gripState(message){if(!castMessage(message)||!canvas.ready||message.speaker?.scene!==canvas.scene?.id)return null;const targets=resolvedAttackTargets(message),record=message.flags?.[ID]?.deathGripCast;if(targets.length!==1||!record||attackTargetOutcome(message.system.roll,targets[0])!=='success')return null;const origin=canvas.tokens.placeables.find(t=>t.document.uuid===record.originUuid&&t.actor?.uuid===message.system.action.actor.uuid),target=canvas.tokens.get(targets[0].id);if(!origin||!target||target.actor?.uuid!==targets[0].actorId||!alive(origin)||!alive(target)||!within(origin,target)||position(origin)!==record.originPosition||position(target)!==record.targetPosition)return null;return {actor:message.system.action.actor,item:message.system.action.item,origin,target,candidates:candidates(origin,target)};}
export function gripSelection(selection,choices){return Array.isArray(selection)&&new Set(selection).size===selection.length&&selection.every(id=>choices.some(t=>t.tokenUuid===id));}
export function gripPreview(origin,target){if(!globalThis.PIXI?.Graphics||!canvas.stage?.addChild)return ()=>{};const a=point(origin),b=point(target),graphic=new PIXI.Graphics();graphic.eventMode='none';graphic.interactive=false;graphic.lineStyle(4,0x55ddff,0.9).moveTo(a.x,a.y).lineTo(b.x,b.y);canvas.stage.addChild(graphic);return ()=>{if(!graphic.destroyed)graphic.destroy();};}
export async function promptGrip(data,{user}){if(!user?.active||!user.isGM)return null;const message=await fromUuid(data.messageUuid),state=gripState(message);if(!state||!state.actor.testUserPermission(game.user,'OWNER')||!gripSelection(data.candidates?.map(t=>t.tokenUuid),state.candidates))return null;
 const cleanup=gripPreview(state.origin,state.target);try{return await timedDialog('Death Grip — Intervening Adversaries',`<p>Confirm adversaries between you and <strong>${esc(state.target.name)}</strong>. Tokens intersecting the blue line are preselected; adjust for your table’s interpretation of “between.”</p><p>Selected adversaries make a <strong>Reaction Roll (13)</strong>. Failures take <strong>3d6+2 physical damage</strong>. The original target is excluded.</p>`+data.candidates.map(t=>`<label style="display:block;margin:0.5rem 0"><input type="checkbox" name="deathGripTarget" value="${esc(t.tokenUuid)}" data-dhp-token="${esc(t.tokenUuid)}" ${t.selected?'checked':''}> ${esc(t.name)}</label>`).join(''),[{action:'confirm',label:'Confirm Targets',callback:(_e,_b,d)=>[...d.element.querySelectorAll('[name="deathGripTarget"]:checked')].map(t=>t.value)},{action:'cancel',label:'Cancel Follow-Up',default:true,callback:()=>null}]);}finally{cleanup();}}
export async function launchGrip(action,targets,message){if(waves.has(action))throw Error('Death Grip follow-up is already running.');waves.set(action,{targets,messageUuid:message.uuid});try{const config=action.prepareConfig({shiftKey:false},{dialog:{configure:false}});if(!config)return null;config.effects=await game.system.api.data.actions.actionsTypes.base.getActionRelevantEffects(action.getRollData(),action.actor);if(await action.executeWorkflow(config)===false)return null;await config.resourceUpdates.updateResources();if(action.chatDisplay&&!config.skips.createMessage&&!config.actionChatMessageHandled)await action.toChat(null,config);return config;}finally{waves.delete(action);}}
export async function resolveGrip(request,{user},ask=promptGrip,launch=launchGrip){if(!game.user.isActiveGM||!user?.active||typeof request?.messageUuid!=='string')return false;const message=castMessage(await fromUuid(request.messageUuid));if(!message||!message.system.action.actor.testUserPermission(user,'OWNER'))return false;return withHopeLock('death-grip:'+message.uuid,async()=>{
 if(!user.active||!castMessage(message)||!message.system.action.actor.testUserPermission(user,'OWNER')||message.flags?.[ID]?.deathGrip?.offered)return false;
 if(!message.flags?.[ID]?.deathGrip?.ready&& !await message.setFlag(ID,'deathGrip',{ready:true,offered:false}))throw Error('Could not save Death Grip readiness.');
 let state=gripState(message);if(!state)return false;
 if(!await message.setFlag(ID,'deathGrip',{ready:true,offered:true,started:false}))throw Error('Could not reserve Death Grip confirmation.');
 if(game.dice3d)await game.dice3d.waitFor3DAnimationByMessageID(message.id);
 if(!state.candidates.length){await message.setFlag(ID,'deathGrip',{ready:true,offered:true,completed:true,targets:[]});return {completed:true,targets:[]};}
 const owner=ownerFor(state.actor,[...game.users],game.user),data={messageUuid:message.uuid,candidates:state.candidates},selected=owner.isSelf?await ask(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});
 state=gripState(message);if(!owner.active||!user.active||!state||!gripSelection(selected,data.candidates)||!gripSelection(selected,state.candidates)){ui.notifications.warn('Death Grip cast preserved; follow-up canceled or targets changed. Resolve intervening adversaries manually if needed.');return false;}
 const targets=state.candidates.filter(t=>selected.includes(t.tokenUuid)).map(({selected,...t})=>({...t,hitResult:{success:true},saveResult:null}));
 if(!targets.length){await message.setFlag(ID,'deathGrip',{ready:true,offered:true,completed:true,targets:[]});return {completed:true,targets:[]};}
 const action=state.item.system.actions?.get?.(GRIP_VINES)??state.item.system.actions?.[GRIP_VINES];if(typeof action?.executeWorkflow!=='function')throw Error('Death Grip follow-up action is missing; re-Medkit the card.');
 if(!await message.setFlag(ID,'deathGrip',{ready:true,offered:true,started:true,targets}))throw Error('Could not save Death Grip recipients.');
 try{const result=await launch(action,targets,message);if(!result)throw Error('The native reaction/damage workflow was canceled.');const messageUuid=result.message?.uuid??null;await message.setFlag(ID,'deathGrip',{ready:true,offered:true,started:true,completed:true,messageUuid,targets});return {completed:true,messageUuid,targets};}
 catch(error){ui.notifications.error('Death Grip stopped: '+error.message+' Original cast preserved; check the follow-up card before resolving manually.');throw error;}
 });}
function waveMessage(config){return config.message??game.messages.get(config.source?.message)??game.messages.get(config.parent?._id??config.parent?.id)??config.parent;}
export function gripFailedTargets(action,config,targets){const message=waveMessage(config),record=message?.flags?.[ID]?.deathGripWave;if(!record||record.itemUuid!==action.item?.uuid||record.actorUuid!==action.actor?.uuid)return [];const saves=message.system?.targetSaves??{},approved=new Map(record.targets.map(t=>[t.id,t]));return (targets??config.targets??[]).filter(t=>{const a=approved.get(t.id),save=saves[t.id];return a?.actorId===t.actorId&&(!t.tokenUuid||a.tokenUuid===t.tokenUuid)&&save&&!save.isCritical&&Number.isFinite(save.value)&&save.value<13;}).map(t=>({...t,hitResult:{success:true},saveResult:{success:false}}));}
export function installGrip(Action,Damage,send,chooseOrigin=sourceToken){
 if(!Object.hasOwn(Damage,APPLY)){const apply=Damage.applyDamage;Damage.applyDamage=async function(config,targets=null,...args){if(!vinesIdentity(this))return apply.call(this,config,targets,...args);const failures=gripFailedTargets(this,config,targets);if(!failures.length)return;return apply.call(this,config,failures,...args);};Object.defineProperty(Damage,APPLY,{value:true});}
 if(Object.hasOwn(Action,WRAP))return;
 let proto=Action.prototype,descriptor;while(proto&&!descriptor){descriptor=Object.getOwnPropertyDescriptor(proto,'workflow');proto=Object.getPrototypeOf(proto);}if(!descriptor?.get)throw Error('Death Grip requires native action workflows.');
 Object.defineProperty(Action.prototype,'workflow',{...descriptor,get(){const parts=descriptor.get.call(this);if(vinesIdentity(this)){const part=parts.get('applyDamage');if(part&&!part[APPLY])parts.set('applyDamage',{...part,[APPLY]:true,execute:(...args)=>Damage.applyDamage.call(this,...args)});}return parts;}});
 const prepare=Action.prototype.prepareConfig;Action.prototype.prepareConfig=function(event,options,...args){const config=prepare.call(this,event,options,...args),wave=waves.get(this);if(config&&wave){config.targets=structuredClone(wave.targets);config.hasRoll=false;config.hasSave=true;config.isCritical=false;authorized.add(config);}return config;};
 const workflow=Action.prototype.executeWorkflow;Action.prototype.executeWorkflow=async function(config,...args){
  if(gripAction(this,GRIP_CAST)){if(casting.has(this))return false;const origin=chooseOrigin(this.actor),target=config.targets?.length===1?canvas.tokens.get(config.targets[0].id):null;if(!origin||!target||target.actor?.uuid!==config.targets[0].actorId||!alive(origin)||!alive(target)||!within(origin,target)){ui.notifications.warn('Death Grip needs one visible living target within Close and an unambiguous caster token.');return false;}const record={originUuid:origin.document.uuid,originPosition:position(origin),targetPosition:position(target)};casting.set(this,record);try{return await workflow.call(this,config,...args);}finally{casting.delete(this);}}
  if(!authorized.has(config))return workflow.call(this,config,...args);
  const parts=this.workflow,target=parts.get('target');if(!target)throw Error('Death Grip native target workflow is missing.');const wrapped={...target,execute:async(...a)=>{const result=await target.execute(...a);if(a[0]===config)for(const t of config.targets)t.hitResult={success:true};return result;}};parts.set('target',wrapped);try{return await workflow.call(this,config,...args);}finally{if(parts.get('target')===wrapped)parts.set('target',target);authorized.delete(config);}
 };
 const use=Action.prototype.use;Action.prototype.use=async function(...args){if(vinesIdentity(this)&&!waves.has(this)){ui.notifications.info('Use Hit All Adversaries Between; its reaction/damage follow-up opens after a successful cast.');return false;}const result=await use.apply(this,args);if(gripAction(this,GRIP_CAST)&&result?.message)try{await send({messageUuid:result.message.uuid});}catch(error){console.error(ID+' | Death Grip',error);ui.notifications.error('Death Grip cast preserved; intervening targets need manual review: '+error.message);}return result;};Object.defineProperty(Action,WRAP,{value:true});
}
export function tagGripMessage(message){const source=message.system?.source,actor=source?.actor&&foundry.utils.fromUuidSync(source.actor),item=actor?.items?.get(source.item),action=item?.system.actions?.get?.(source.action)??item?.system.actions?.[source.action],cast=casting.get(action),wave=waves.get(action);if(cast&&gripAction(action,GRIP_CAST))message.updateSource({['flags.'+ID+'.deathGripCast']:cast});if(wave&&gripAction(action,GRIP_VINES))message.updateSource({['flags.'+ID+'.deathGripWave']:{castMessageUuid:wave.messageUuid,itemUuid:item.uuid,actorUuid:actor.uuid,targets:wave.targets.map(t=>({id:t.id,actorId:t.actorId,tokenUuid:t.tokenUuid}))}});}
export function registerDeathGrip(){installGripVisibility(CONFIG.Item.documentClass,game.system.api.applications.dialogs.ActionSelectionDialog);for(const item of game.items??[])hideGripAction(item);for(const actor of game.actors??[])for(const item of actor.items)hideGripAction(item);for(const scene of game.scenes??[])for(const token of scene.tokens??[])for(const item of token.actor?.items??[])hideGripAction(item);CONFIG.queries[QUERY]=resolveGrip;CONFIG.queries[PROMPT]=promptGrip;const send=request=>{const gm=game.users.activeGM;if(!gm)throw Error('Death Grip needs an active GM.');return gm.isSelf?resolveGrip(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(600000)});};installGrip(game.system.api.data.actions.actionsTypes.base,game.system.api.fields.ActionFields.DamageField,send);Hooks.on('preCreateChatMessage',tagGripMessage);Hooks.on('updateChatMessage',message=>{const state=message.flags?.[ID]?.deathGrip;if(!game.user.isActiveGM||!state?.ready||state.offered||!castMessage(message))return;void resolveGrip({messageUuid:message.uuid},{user:game.user}).catch(error=>ui.notifications.error('Death Grip follow-up needs manual review: '+error.message));});}
