import {decisionBudget} from '../settings.js';
import {timedDialog} from '../dialog.js';
import {ID,featureActive} from '../core.js';
import {withHopeLock} from './hope-lock.js';
import {patronFaces} from './patrons-pact.js';
import {DEATHLESS_KEY,DEATHLESS_ACTION} from './deathless-embrace-data.js';
const QUERY=`${ID}.deathlessEmbrace`,pending=new Set();
const actionFor=item=>item?.system.actions?.get?.(DEATHLESS_ACTION)??item?.system.actions?.[DEATHLESS_ACTION];
export function deathlessItem(actor){return actor?.items?.find(item=>{const f=item.flags?.[ID];return featureActive(item)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===DEATHLESS_KEY;})??null;}
export function successfulPatronDice(roll){return (roll?.dice??[]).flatMap(die=>die?.results??[]).filter(result=>result?.active!==false&&!result?.discarded&&Number(result?.result)>=4).length;}
export function deathlessAvailable(actor){const item=deathlessItem(actor),action=actionFor(item),favor=Number(actor?.system?.resources?.favor?.value),hp=Number(actor?.system?.resources?.hitPoints?.value);return item&&action&&Number(action.uses?.value??0)<1&&Number.isInteger(favor)&&favor>0&&Number.isFinite(hp)&&hp>0?{item,action,favor,hp}:null;}
export async function promptDeathless(actor){const valid=deathlessAvailable(actor);if(!valid)return null;return timedDialog(`Deathless Embrace — ${actor.name}`,`<p>Spend Favor and roll the same number of <strong>d${patronFaces(actor)} Patron Dice</strong>. Clear 1 HP for each result of 4 or higher.</p><label>Favor<select name="deathlessFavor" style="width:100%">${Array.from({length:valid.favor},(_,i)=>`<option value="${i+1}">${i+1} Favor — ${i+1}d${patronFaces(actor)}</option>`).join('')}</select></label>`,[{action:'roll',label:'Spend Favor & Roll',callback:(_e,b)=>Number(b.form.elements.deathlessFavor.value)},{action:'cancel',label:'Cancel',default:true,callback:()=>null}]);}
export async function resolveDeathless(request,{user},rollDice=async formula=>new foundry.dice.Roll(formula).evaluate()){if(!game.user.isActiveGM||!user?.active||!Number.isInteger(request.count))return false;return withHopeLock(request.actorUuid,async()=>{const actor=await fromUuid(request.actorUuid),valid=deathlessAvailable(actor);if(!valid||!actor.testUserPermission(user,'OWNER')||request.count<1||request.count>valid.favor)return false;const faces=patronFaces(actor),usePath=`system.actions.${DEATHLESS_ACTION}.uses.value`,favorPath='system.resources.favor.value',hpPath='system.resources.hitPoints.value',beforeFavor=valid.favor,beforeHp=valid.hp;let paid=false,healed=false;try{const used=await valid.item.update({[usePath]:1});if(!used||Number(actionFor(valid.item)?.uses.value)!==1)throw Error('Could not spend the Deathless Embrace use.');const payment=await actor.update({[favorPath]:beforeFavor-request.count});if(!payment||Number(actor.system.resources.favor.value)!==beforeFavor-request.count)throw Error('Could not spend Favor.');paid=true;const roll=await rollDice(`${request.count}d${faces}`),successes=successfulPatronDice(roll),cleared=Math.min(beforeHp,successes),nextHp=beforeHp-cleared;if(cleared){const update=await actor.update({[hpPath]:nextHp});if(!update||Number(actor.system.resources.hitPoints.value)!==nextHp)throw Error('Could not clear Hit Points.');healed=true;}const message=await roll.toMessage({speaker:ChatMessage.getSpeaker({actor}),flags:{[ID]:{unshakeableRoll:true}},flavor:`<strong>Deathless Embrace</strong><p>Spent ${request.count} Favor. ${successes} Patron ${successes===1?'Die':'Dice'} rolled 4 or higher; cleared ${cleared} HP.</p>`});if(message&&game.dice3d)await game.dice3d.waitFor3DAnimationByMessageID(message.id);return {successes,cleared,faces};}catch(error){if(!healed){if(paid)await actor.update({[favorPath]:beforeFavor});await valid.item.update({[usePath]:0});}throw error;}});}
export function registerDeathlessEmbrace(){CONFIG.queries[QUERY]=resolveDeathless;Hooks.on('daggerheart.preUseAction',action=>{if(action.id!==DEATHLESS_ACTION||deathlessItem(action.actor)?.uuid!==action.item?.uuid)return;if(pending.has(action.actor.uuid))return false;const gm=game.users.activeGM;if(!gm){ui.notifications.error('Deathless Embrace needs an active GM.');return false;}pending.add(action.actor.uuid);void (async()=>{try{const count=await promptDeathless(action.actor);if(!count)return;const result=gm.isSelf?await resolveDeathless({actorUuid:action.actor.uuid,count},{user:game.user}):await gm.query(QUERY,{actorUuid:action.actor.uuid,count},{timeout:decisionBudget(125000)});if(!result)ui.notifications.warn('Deathless Embrace is no longer available.');}catch(error){ui.notifications.error(error.message);}finally{pending.delete(action.actor.uuid);}})();return false;});}
