import { decisionBudget } from '../settings.js';
import { decisionNow } from '../decision-clock.js';
import { ID,featureActive } from '../core.js';
import { DEFENSIVE_KEY,DEFENSIVE_EFFECT } from './defensive-data.js';
import { sourceToken } from './hallowed-aura.js';
import { meleeLimit } from './kick.js';
import { ownerFor } from './aura-rules.js';
import { timedDialog } from '../dialog.js';
import { markReactiveStress } from './stress-payment.js';
const QUERY=`${ID}.defensive`,PROMPT=`${ID}.defensivePrompt`,seen=new Map();
export function defensiveActive(actor){const item=actor?.items?.find(i=>{const f=i.flags?.[ID];return featureActive(i)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===DEFENSIVE_KEY;});const origin=item?.effects.get(DEFENSIVE_EFFECT)?.uuid;return Boolean(origin&&actor.effects.some(e=>e.origin===origin&&!e.disabled&&!e.isSuppressed));}
export function defensiveTargets(config){if(config[ID]?.defensivePaid)return [];const actor=config.data?.parent??(config.source?.actor?foundry.utils.fromUuidSync(config.source.actor):null);if(!actor)return [];const source=config.source;const item=actor.items?.get?.(source?.item),action=source?.action&&(actor.system?.attack?.id??actor.system?.attack?._id)===source.action?actor.system.attack:item?.system.actions?.get?.(source?.action)??item?.system.actionsList?.find(a=>a.id===source?.action);if(action?.type!=='attack')return [];const origin=sourceToken(actor);if(!origin)return [];const limit=meleeLimit(canvas.scene);return (config.targets??[]).filter(t=>{const token=canvas.tokens.get(t.id);if(!token||token.actor?.uuid!==t.actorId||!defensiveActive(token.actor))return false;const distance=origin.distanceTo(token);return Number.isFinite(distance)&&Number.isFinite(limit)&&distance<=limit;});}
const canPay=actor=>Number(actor.system.resources?.stress?.value)<Number(actor.system.resources?.stress?.max);
export async function promptDefensive(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!canPay(actor))return false;return Boolean(await timedDialog(`Defensive — ${actor.name}`,'<p>Your target’s Defensive stance imposes disadvantage at Melee range. Mark 1 Stress to negate that disadvantage for this attack?</p>',[{action:'use',label:'Mark 1 Stress',callback:()=>true},{action:'decline',label:'Keep Disadvantage',default:true,callback:()=>false}]));}
export async function resolveDefensive(request,{user},ask=promptDefensive,pay=markReactiveStress){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000))return false;const actor=await fromUuid(request.source?.actor);if(!actor?.testUserPermission(user,'OWNER')||!canPay(actor))return false;const config={source:request.source,targets:request.targets,data:{parent:actor}};if(!defensiveTargets(config).length)return false;for(const[id,expiry]of seen)if(expiry<decisionNow())seen.delete(id);if(seen.has(request.id))return false;seen.set(request.id,decisionNow()+decisionBudget(300000));const owner=ownerFor(actor,[...game.users],game.user),data={actorUuid:actor.uuid};const accepted=owner.isSelf?await ask(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});return Boolean(accepted&&decisionNow()<=request.deadline&&await pay(actor.uuid,()=>defensiveTargets(config).length>0));}
export function installDefensive(Roll,offer){const native=Roll.buildConfigure;Roll.buildConfigure=async function(config,...args){const actor=config.data?.parent;if(actor&&canPay(actor)&&defensiveTargets(config).length){const paid=await offer({source:config.source,targets:config.targets,id:foundry.utils.randomID(),deadline:decisionNow()+decisionBudget(120000)});if(paid)config[ID]={...config[ID],defensivePaid:true};}return native.call(this,config,...args);};}
export function registerDefensive(){CONFIG.queries[QUERY]=resolveDefensive;CONFIG.queries[PROMPT]=promptDefensive;installDefensive(CONFIG.Dice.daggerheart.D20Roll,request=>{const gm=game.users.activeGM;if(!gm)throw new Error('Defensive needs an active GM.');return gm.isSelf?resolveDefensive(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(65000)});});}
