import {ID,featureActive} from '../core.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {timedDialog} from '../dialog.js';
import {ownerFor,unavailableActor} from './aura-rules.js';
import {sourceToken} from './hallowed-aura.js';
import {meleeLimit} from './kick.js';
import {markReactiveStress} from './stress-payment.js';
import {DEVASTATING_STRIKES_KEY,DEVASTATING_STRIKES_ACTION} from './devastating-strikes-data.js';
const QUERY=`${ID}.devastatingStrikes`,PROMPT=`${QUERY}Prompt`,DAMAGE_WRAP=Symbol.for(`${ID}.devastatingStrikesDamage`),ACTOR_WRAP=Symbol.for(`${ID}.devastatingStrikesActor`),requests=new Map();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function devastatingStrikesItem(actor,requireStress=false){const stress=actor?.system?.resources?.stress;if(actor?.type!=='character'||requireStress&&!(Number(stress?.value)<Number(stress?.max)))return null;return actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===DEVASTATING_STRIKES_KEY;})??null;}
export function devastatingSevere(updates){return updates?.find(update=>update.key==='hitPoints'&&!update.clear&&!update.itemId&&update.damageTypes!=null&&Number(update.value)>=3);}
export function devastatingMelee(actor,target){const origin=sourceToken(actor),recipient=sourceToken(target),distance=origin&&recipient&&origin.distanceTo(recipient),limit=meleeLimit(canvas.scene);return Boolean(origin&&recipient&&Number.isFinite(distance)&&Number.isFinite(limit)&&distance<=limit);}
export async function promptDevastatingStrikes(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.active||!actor?.testUserPermission(user,'OWNER')||!devastatingStrikesItem(actor,true))return false;return Boolean(await timedDialog(`Devastating Strikes — ${actor.name}`,`<p>You dealt Severe damage to <strong>${esc(data.targetName)}</strong> within Melee.</p><p>Mark <strong>1 Stress</strong> to make them mark <strong>1 additional HP</strong>?</p>`,[{action:'use',label:'Mark 1 Stress',callback:()=>true},{action:'decline',label:'Decline',default:true,callback:()=>false}]));}
export async function resolveDevastatingStrikes(request,{user},ask=promptDevastatingStrikes,pay=markReactiveStress){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000)||!Number.isFinite(request.severity)||request.severity<3)return false;for(const[id,expiry]of requests)if(expiry<decisionNow())requests.delete(id);if(requests.has(request.id))return false;const actor=await fromUuid(request.actorUuid),target=await fromUuid(request.targetUuid),item=devastatingStrikesItem(actor,true),hp=target?.system?.resources?.hitPoints;if(!actor?.testUserPermission(user,'OWNER')||!item||!['character','adversary'].includes(target?.type)||unavailableActor(target)||!hp||Number(hp.value)>=Number(hp.max)||!devastatingMelee(actor,target))return false;requests.set(request.id,decisionNow()+decisionBudget(300000));const owner=ownerFor(actor,[...game.users],game.user),accepted=owner.isSelf?await ask({actorUuid:actor.uuid,targetName:target.name},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,targetName:target.name},{timeout:decisionBudget(65000)});if(!accepted||decisionNow()>request.deadline||unavailableActor(target)||Number(hp.value)>=Number(hp.max)||!devastatingMelee(actor,target)||!await pay(actor.uuid,current=>Boolean(devastatingStrikesItem(current,true))))return false;if(unavailableActor(target)||Number(hp.value)>=Number(hp.max)||!devastatingMelee(actor,target))return false;await target.modifyResource([{key:'hitPoints',value:1}]);await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Devastating Strikes:</strong> ${esc(actor.name)} marks 1 Stress; ${esc(target.name)} marks 1 additional HP.</p>`});return true;}
export function markDevastatingDamage(config){const message=game.messages.get(config.source?.message),actor=message?.system?.action?.actor??config.data?.parent;if(config.hasHealing||!config.damage?.main||!devastatingStrikesItem(actor,true))return false;config.damage.main.options[ID]={...config.damage.main.options[ID],devastatingStrikesSource:actor.uuid};if(typeof config.damage.toObject==='function')config.damage=new config.damage.constructor({...config.damage.toObject(),main:config.damage.main.toJSON(),resources:Object.fromEntries(Object.entries(config.damage.resources??{}).map(([key,value])=>[key,value.toJSON()]))});return true;}
export function installDevastatingStrikes(Damage,Actor,offer){if(!Damage[DAMAGE_WRAP]){const evaluate=Damage.buildEvaluate;Damage.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);markDevastatingDamage(config);return result;};Object.defineProperty(Damage,DAMAGE_WRAP,{value:true});}if(!Actor[ACTOR_WRAP]){const take=Actor.prototype.takeDamage;Actor.prototype.takeDamage=async function(packet,...args){const source=packet?.main?.options?.[ID]?.devastatingStrikesSource,result=await take.call(this,packet,...args),severe=devastatingSevere(result);if(source&&source!==this.uuid&&severe&&await offer(source,this,severe.value))severe.value=Number(severe.value)+1;return result;};Object.defineProperty(Actor,ACTOR_WRAP,{value:true});}}
export function registerDevastatingStrikes(){CONFIG.queries[QUERY]=resolveDevastatingStrikes;CONFIG.queries[PROMPT]=promptDevastatingStrikes;installDevastatingStrikes(CONFIG.Dice.daggerheart.DamageRoll,CONFIG.Actor.documentClass,async(actorUuid,target,severity)=>{const gm=game.users.activeGM;if(!gm)throw Error('Devastating Strikes needs an active GM.');const request={id:foundry.utils.randomID(),actorUuid,targetUuid:target.uuid,severity,deadline:decisionNow()+decisionBudget(120000)};return gm.isSelf?resolveDevastatingStrikes(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});});Hooks.on('daggerheart.preUseAction',action=>{const flags=action.item?.flags?.[ID];if(action.id!==DEVASTATING_STRIKES_ACTION||(flags?.applied?.key??flags?.premade?.key)!==DEVASTATING_STRIKES_KEY)return;ui.notifications.info('Devastating Strikes is offered automatically after finalized Severe damage within Melee.');return false;});}
