import {ID,featureActive,normalize} from '../core.js';
import {DEVOUT_KEY} from './devout-data.js';
const SPARING_SOURCE='Compendium.daggerheart.subclasses.Item.GfOSgVJW8bS1OjNq',PRAYER_SOURCE='Compendium.daggerheart.classes.Item.Xd7RYhfTxIj9aWI2',PRIOR='devoutSparingMax',WRAPPED=Symbol.for(`${ID}.devoutPrayer`),pending=new Map();
export function devoutItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===DEVOUT_KEY;})??null:null;}
export function sparingItem(actor){return actor?.items?.find(item=>item.type==='feature'&&featureActive(item)&&(item._stats?.compendiumSource===SPARING_SOURCE||normalize(item.name)==='sparing touch'))??null;}
export function devoutPrayerItem(item,actor){if(!devoutItem(actor))return item;const replaced=Roll.replaceFormulaData(String(item.system.resource.max),actor.getRollData?.()??{}),count=Number(replaced);if(!Number.isFinite(count))return item;const resource={...item.system.resource,max:String(count+1)},system=Object.create(item.system);Object.defineProperty(system,'resource',{value:resource,enumerable:true});return new Proxy(item,{get(target,key,receiver){return key==='system'?system:Reflect.get(target,key,receiver);}});}
export function keepDevoutPrayer(values,actor){if(!devoutItem(actor)||!Array.isArray(values)||values.length<2)return values;const lowest=Math.min(...values.map(d=>Number(d.value))),index=values.findIndex(d=>Number(d.value)===lowest);return values.filter((_d,i)=>i!==index);}
export function prayerResource(item){const flags=item?.flags?.[ID];return item?.type==='feature'&&((flags?.applied?.key??flags?.premade?.key)==='seraph-prayer-dice'||item._stats?.compendiumSource===PRAYER_SOURCE||normalize(item.name)==='prayer dice');}
export function installDevoutPrayerDialog(Dialog){const actions=Dialog?.DEFAULT_OPTIONS?.actions,reroll=actions?.rerollDice;if(!reroll||reroll[WRAPPED])return;const wrapped=async function(...args){if(!prayerResource(this.item)||!devoutItem(this.actor))return reroll.apply(this,args);const item=this.item,close=this.close;this.item=devoutPrayerItem(item,this.actor);this.close=async(...closeArgs)=>{this.rollValues=keepDevoutPrayer(this.rollValues,this.actor);return close.apply(this,closeArgs);};try{return await reroll.apply(this,args);}finally{this.item=item;this.close=close;}};Object.defineProperty(wrapped,WRAPPED,{value:true});actions.rerollDice=wrapped;}
export function sparingUpdates(item,enabled){const resource=item?.system?.resource;if(resource?.progression!=='decreasing'||resource.recovery!=='longRest')return{};const prior=item.flags?.[ID]?.[PRIOR],changes={};if(enabled&&prior===undefined){const oldMax=Number(resource.max);if(!Number.isFinite(oldMax))return{};changes[`flags.${ID}.${PRIOR}`]=String(resource.max);changes['system.resource.max']=String(oldMax+1);changes['system.resource.value']=Math.min(oldMax+1,Number(resource.value)+1);}else if(!enabled&&prior!==undefined){const oldMax=Number(prior);changes['system.resource.max']=String(prior);changes['system.resource.value']=Math.min(oldMax,Number(resource.value));changes[`flags.${ID}.-=${PRIOR}`]=null;}return changes;}
export async function syncDevout(actor){if(!game.user.isActiveGM||actor?.type!=='character')return;const operation=(pending.get(actor.uuid)??Promise.resolve()).catch(()=>{}).then(async()=>{const item=sparingItem(actor);if(!item)return;const changes=sparingUpdates(item,Boolean(devoutItem(actor)));if(Object.keys(changes).length)await item.update(changes);});pending.set(actor.uuid,operation);try{await operation;}finally{if(pending.get(actor.uuid)===operation)pending.delete(actor.uuid);}}
export function registerDevout(){installDevoutPrayerDialog(game.system.api.applications.dialogs.ResourceDiceDialog);const sync=actor=>{void syncDevout(actor).catch(error=>console.error(`${ID} | Devout`,error));},scan=()=>{const actors=new Map([...game.actors].map(actor=>[actor.uuid,actor]));for(const token of canvas.tokens?.placeables??[])if(token.actor)actors.set(token.actor.uuid,token.actor);for(const actor of actors.values())sync(actor);};for(const hook of ['createItem','updateItem','deleteItem'])Hooks.on(hook,item=>sync(item.actor));Hooks.on('updateActor',sync);Hooks.on('updateToken',token=>sync(token.actor));Hooks.on('canvasReady',scan);scan();}
