import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {ownerFor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {consumeResolutionTicket} from '../resolution-manager.js';
import {DIMINISH_KEY,DIMINISH_ACTION} from './diminish-my-foes-data.js';
import {attackTargetOutcome} from '../attack-outcome.js';
const QUERY=`${ID}.diminishMyFoes`,PROMPT=`${QUERY}Prompt`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function diminishItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===DIMINISH_KEY;})??null:null;}
export function diminishTargets(actor,roll,config={}){if(!diminishItem(actor)||roll?.options?.actionType!=='action'||!(roll.withHope||roll.isCritical)||Number(actor.system.resources?.favor?.value)<1)return[];const targets=config.targets??roll.options?.targets??[];return targets.filter(target=>target.actorId&&attackTargetOutcome(roll,target)==='success').map(target=>({targetUuid:target.actorId,targetName:foundry.utils.fromUuidSync?.(target.actorId)?.name??'Target',difficulty:target.difficulty,evasion:target.evasion}));}
export async function validateDiminish(request,user){if(!user?.active||request.deadline<=decisionNow()||request.actionType!=='action'||!request.withHope||!Number.isFinite(request.total))return null;const actor=await fromUuid(request.sourceUuid),target=await fromUuid(request.targetUuid),item=diminishItem(actor),threshold=request.difficulty||request.evasion,converted=request.convertedSuccess===true;if(!item||item.uuid!==request.candidate?.itemUuid||!actor.testUserPermission(user,'OWNER')||Number(actor.system.resources?.favor?.value)<1||!target?.system?.resources?.stress||!converted&&!request.critical&&(threshold==null||request.total<threshold))return null;return{actor,target,item,owner:ownerFor(actor,[...game.users],game.user)};}
export function diminishAmountButtons(max){return Array.from({length:Math.max(0,Math.floor(Number(max)||0))},(_,index)=>{const amount=index+1;return{action:`spend-${amount}`,label:`Spend ${amount} Favor`,callback:()=>amount};});}
export async function promptDiminish(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.active||!actor?.testUserPermission(game.user,'OWNER')||!diminishItem(actor))return null;const max=Math.max(0,Math.floor(Number(actor.system.resources?.favor?.value)||0));if(!max)return null;return timedDialog(`Diminish My Foes — ${actor.name}`,`<p>How much Favor do you want to spend to force <strong>${esc(data.targetName)}</strong> to mark the same amount of Stress?</p>`,[...diminishAmountButtons(max),{action:'decline',label:'Decline',default:true,callback:()=>null}]);}
export function diminishResourceUpdate(target,amount){const stress=target.system.resources.stress,hp=target.system.resources.hitPoints,before=Number(stress.value),max=Number(stress.max),updates={'system.resources.stress.value':Math.min(max,before+amount)};if(before+amount>max&&hp)updates['system.resources.hitPoints.value']=Math.min(Number(hp.max),Number(hp.value)+1);return updates;}
export async function resolveDiminish(request,{user},ask=promptDiminish,authorize=consumeResolutionTicket){if(!game.user.isActiveGM||!Number.isFinite(request.deadline)||request.deadline>decisionNow()+decisionBudget(125000))return false;const valid=await validateDiminish(request,user);if(!valid||!authorize(request.resolutionToken,'diminish',valid.item.uuid,user))return false;const owner=valid.owner,data={actorUuid:valid.actor.uuid,targetName:valid.target.name},amount=owner.isSelf?await ask(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});if(!Number.isSafeInteger(amount)||amount<1)return false;return withHopeLock(valid.actor.uuid,async()=>{const item=diminishItem(valid.actor),favor=Number(valid.actor.system.resources?.favor?.value);if(item?.uuid!==valid.item.uuid||amount>favor)return false;const stressBefore=Number(valid.target.system.resources.stress.value),hpBefore=Number(valid.target.system.resources.hitPoints?.value),paid=await valid.actor.update({'system.resources.favor.value':favor-amount});if(!paid||Number(valid.actor.system.resources.favor.value)!==favor-amount)throw Error('Could not spend Diminish My Foes Favor.');try{const updated=await valid.target.update(diminishResourceUpdate(valid.target,amount));if(!updated)throw Error(`Could not mark ${valid.target.name}'s Stress.`);}catch(error){await valid.actor.update({'system.resources.favor.value':favor});throw error;}const stressMarked=Number(valid.target.system.resources.stress.value)-stressBefore,hpMarked=Number.isFinite(hpBefore)?Number(valid.target.system.resources.hitPoints.value)-hpBefore:0;await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:valid.actor}),content:`<p><strong>Diminish My Foes</strong>: ${esc(valid.actor.name)} spends ${amount} Favor; ${esc(valid.target.name)} marks ${stressMarked} Stress${hpMarked?` and ${hpMarked} HP from Stress overflow`:''}.</p>`});return{amount,stressMarked,hpMarked,targetUuid:valid.target.uuid};});}
export function registerDiminishMyFoes(){CONFIG.queries[QUERY]=resolveDiminish;CONFIG.queries[PROMPT]=promptDiminish;Hooks.on('daggerheart.preUseAction',action=>{if(action.id===DIMINISH_ACTION&&diminishItem(action.actor)?.uuid===action.item?.uuid){ui.notifications.info('Diminish My Foes is offered automatically after a successful action roll with Hope against a target.');return false;}});}
