import {ID,featureActive} from '../core.js';
import {ELEMENTALIST_KEY,ELEMENTALIST_ROLL_EFFECT,ELEMENTALIST_DAMAGE_EFFECT} from './elementalist-data.js';
const QUERY=`${ID}.expireElementalist`,WRAPPED=Symbol.for(`${ID}.elementalist`);
export function elementalistItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===ELEMENTALIST_KEY;})??null:null;}
export function elementalistEffects(actor,mode){const item=elementalistItem(actor),id=mode==='roll'?ELEMENTALIST_ROLL_EFFECT:ELEMENTALIST_DAMAGE_EFFECT,origin=item?.effects?.get?.(id)?.uuid??item?.effects?.find?.(effect=>(effect.id??effect._id)===id)?.uuid;if(!origin)return[];return [...(actor.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&(effect.origin===origin||effect.origin?.endsWith(`.ActiveEffect.${id}`)));}
export async function expireElementalist(request,{user}){if(!game.user.isActiveGM||!user?.active)return false;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER'))return false;const allowed=new Set(request.effectIds??[]),effects=['roll','damage'].flatMap(mode=>elementalistEffects(actor,mode)).filter(effect=>allowed.has(effect.id));if(!effects.length)return false;await actor.deleteEmbeddedDocuments('ActiveEffect',effects.map(effect=>effect.id));return true;}
export function installElementalistRoll(Duality,expire){if(Duality[WRAPPED])return;const evaluate=Duality.buildEvaluate;Duality.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);if(config.actionType!=='action')return result;const actor=config.data?.parent??roll.data?.parent,rollEffects=elementalistEffects(actor,'roll');if(rollEffects.length)await expire({actorUuid:actor.uuid,effectIds:rollEffects.map(effect=>effect.id)});return result;};Object.defineProperty(Duality,WRAPPED,{value:true});}
export function installElementalistDamage(Damage,expire){const mark=Symbol.for(`${ID}.elementalistDamage`);if(Damage[mark])return;const evaluate=Damage.buildEvaluate;Damage.buildEvaluate=async function(roll,config,...args){const actor=game.messages?.get?.(config.source?.message)?.system?.action?.actor??config.data?.parent,effects=!config.hasHealing?elementalistEffects(actor,'damage'):[];const result=await evaluate.call(this,roll,config,...args);if(effects.length)await expire({actorUuid:actor.uuid,effectIds:effects.map(effect=>effect.id)});return result;};Object.defineProperty(Damage,mark,{value:true});}
export function registerElementalist(){CONFIG.queries[QUERY]=expireElementalist;const dispatch=request=>{const gm=game.users.activeGM;if(!gm)throw new Error('Elementalist expiry needs an active GM.');return gm.isSelf?expireElementalist(request,{user:game.user}):gm.query(QUERY,request,{timeout:15000});};installElementalistRoll(CONFIG.Dice.daggerheart.DualityRoll,dispatch);installElementalistDamage(CONFIG.Dice.daggerheart.DamageRoll,dispatch);}
