import {premadeDocuments,configurePremadePack} from '../premade-setup-context.js';
import {ID} from '../core.js';
export const ELEMENTALIST_KEY='elemental-origin-elementalist',ELEMENTALIST_ROLL_ACTION='rxuFLfHP1FILDpds',ELEMENTALIST_DAMAGE_ACTION='S7HvFD3qIR3ifJRL',ELEMENTALIST_ROLL_EFFECT='EY87mY6ULfIt3XC8',ELEMENTALIST_DAMAGE_EFFECT='WwibpgaO6Kkks7aZ';
export function elementalistData(folder){const data={
 name:'Elementalist',type:'feature',img:'icons/magic/symbols/elements-air-earth-fire-water.webp',
 system:{description:'<p>Choose one of the following elements at character creation: air, earth, fire, lightning, or water. You can shape this element into harmless effects. Additionally, you can spend a Hope and describe how your control over this element helps an action roll you’re about to make, then either gain a +2 bonus to the roll or a +3 bonus to the roll’s damage.</p>',resource:null,actions:{
  [ELEMENTALIST_ROLL_ACTION]:{_id:ELEMENTALIST_ROLL_ACTION,type:'effect',systemPath:'actions',name:'Bonus to Roll',actionType:'action',cost:[{scalable:false,key:'hope',value:1,step:null,itemId:null,consumeOnSuccess:false}],uses:{value:null,max:null,recovery:null,consumeOnSuccess:false},effects:[{_id:ELEMENTALIST_ROLL_EFFECT,onSave:false}],target:{type:'self',amount:null},range:'self',chatDisplay:true},
  [ELEMENTALIST_DAMAGE_ACTION]:{_id:ELEMENTALIST_DAMAGE_ACTION,type:'effect',systemPath:'actions',name:'Bonus to Damage',actionType:'action',cost:[{scalable:false,key:'hope',value:1,step:null,itemId:null,consumeOnSuccess:false}],uses:{value:null,max:null,recovery:null,consumeOnSuccess:false},effects:[{_id:ELEMENTALIST_DAMAGE_EFFECT,onSave:false}],target:{type:'self',amount:null},range:'self',chatDisplay:true}
 },attribution:{source:'Daggerheart SRD',page:null,artist:''},gmNotes:'The temporary bonus expires automatically after the next action roll (and its damage, when applicable).',granter:null,featureForm:'passive'},
 effects:[
  {_id:ELEMENTALIST_ROLL_EFFECT,name:'Elementalist: Bonus to Roll',img:'icons/magic/symbols/elements-air-earth-fire-water.webp',type:'base',transfer:true,disabled:true,system:{changes:[{key:'system.bonuses.roll.bonus',type:'add',value:'2',priority:null,phase:'initial'}],duration:{description:'Until the next action roll is resolved.'},rangeDependence:null,stacking:null,targetDispositions:[]},duration:{value:null,units:'seconds',expiry:null,expired:false},description:'<p>Gain a +2 bonus to your next action roll.</p>',statuses:[],flags:{[ID]:{elementalistMode:'roll'}}},
  {_id:ELEMENTALIST_DAMAGE_EFFECT,name:'Elementalist: Bonus to Damage',img:'icons/magic/symbols/elements-air-earth-fire-water.webp',type:'base',transfer:true,disabled:true,system:{changes:[{key:'system.bonuses.damage.bonus',type:'add',value:'3',priority:null,phase:'initial'}],duration:{description:'Until the next action roll and its damage are resolved.'},rangeDependence:null,stacking:null,targetDispositions:[]},duration:{value:null,units:'seconds',expiry:null,expired:false},description:'<p>Gain a +3 bonus to the damage of your next action roll.</p>',statuses:[],flags:{[ID]:{elementalistMode:'damage'}}}
 ]
};data.folder=folder;data.flags={[ID]:{premade:{key:ELEMENTALIST_KEY,version:'1.0.0',category:'subclass-features',aliases:[],sourceUuids:['Compendium.daggerheart.subclasses.Item.dPcqKN5NeDkjB1HW']}}};return data;}
export async function ensureElementalist(){const pack=game.packs.get(`${ID}.subclass-features`);if(!pack)throw new Error('The Subclass Features compendium is missing.');const existing=(await premadeDocuments(pack)).find(i=>i.getFlag(ID,'premade')?.key===ELEMENTALIST_KEY);if(existing?.getFlag(ID,'premade')?.version==='1.0.0')return existing;const folder=pack.folders.find(f=>!f.folder&&f.name==='Elemental Origin');if(!folder)throw new Error('The Elemental Origin compendium folder is missing.');const locked=pack.locked;try{if(locked)await configurePremadePack(pack,{locked:false});const item=existing?await existing.update(elementalistData(folder.id)):await Item.create(elementalistData(folder.id),{pack:pack.collection});if(!item)throw new Error('Elementalist creation was cancelled.');return item;}finally{if(locked)await configurePremadePack(pack,{locked:true});}}
