import {isHopePaymentCancellation,hopeCapacity,spendHope,refundHope} from './hope-payment.js';
import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {consumeResolutionTicket} from '../resolution-manager.js';
import {helpRecipients,validHelpRecipient,readyHelp,claimedHelp} from '../help-ally.js';
import {withHopeLock} from './hope-lock.js';
import {ENCHANTED_AID_KEY,ENCHANTED_HELP_ACTION,ENCHANTED_SWAP_ACTION,enchantedAidData} from './enchanted-aid-data.js';
const OFFER=`${ID}.enchantedAid`,requests=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function enchantedAidItem(actor){return actor?.type==='character'?actor.items?.find(i=>{const f=i.flags?.[ID];return featureActive(i)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===ENCHANTED_AID_KEY;})??null:null;}
const actionFor=(item,id)=>item?.system.actions?.get?.(id)??item?.system.actions?.[id];
export function swapAvailable(item){const action=actionFor(item,ENCHANTED_SWAP_ACTION);return Boolean(action&&Number(action.uses.value??0)<Number(action.uses.max||1));}
export function spellcastRoll(actor,actionType,trait){return Boolean(actor?.type==='character'&&actionType==='action'&&trait&&trait===actor.system?.spellcastModifierTrait?.key);}
export async function resolveEnchantedAid(request,{user},rollDie=async()=>new Roll('1d8').evaluate()){
 if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||request.id.length>64)throw Error('Invalid Enchanted Aid request.');
 const helper=await fromUuid(request.helperUuid),ally=await fromUuid(request.allyUuid),item=enchantedAidItem(helper);
 if(!item||!helper.testUserPermission(user,'OWNER')||!validHelpRecipient(helper,ally))throw Error('Enchanted Aid is no longer available.');
 for(const [receipt,value]of requests)if(value.expires<decisionNow())requests.delete(receipt);const key=`${user.id}:${request.id}`;if(requests.has(key))return requests.get(key).promise;
 const promise=withHopeLock(helper.uuid,()=>withHopeLock(ally.uuid,async()=>{try{let hopePayment;
  const current=enchantedAidItem(helper),hope=hopeCapacity(helper);if(!current||hope<1)throw Error('You need 1 Hope to use Enchanted Aid.');
  if(!validHelpRecipient(helper,ally)||readyHelp(ally).some(row=>row.helperUuid===helper.uuid))throw Error('This ally already has your help ready.');
  const paid=(hopePayment=await spendHope(helper,1));if(!paid||!hopePayment)throw Error('Could not spend Hope.');
  let roll,created;try{roll=await rollDie();if(!Number.isInteger(roll.total)||roll.total<1||roll.total>8)throw Error('Invalid Enchanted Aid d8 result.');created=await ally.createEmbeddedDocuments('ActiveEffect',[{name:`Enchanted Aid — ${helper.name} (${roll.total})`,img:current.img,origin:current.uuid,disabled:false,description:`${esc(helper.name)} provides a d8 advantage die for the upcoming Spellcast Roll.`,flags:{[ID]:{helpAlly:{helperUuid:helper.uuid,helperName:helper.name,value:roll.total,enchantedAid:{itemUuid:current.uuid}}}},system:{changes:[],duration:{type:''}}}]);if(created?.length!==1)throw Error('Could not prepare Enchanted Aid.');}catch(error){await refundHope(helper,hopePayment);throw error;}
  try{await roll.toMessage({speaker:ChatMessage.getSpeaker({actor:helper}),flags:{[ID]:{unshakeableRoll:true}},flavor:`<strong>Enchanted Aid — ${esc(helper.name)} → ${esc(ally.name)}</strong><p>Spent 1 Hope. A <strong>${roll.total}</strong> on the d8 helps the upcoming Spellcast Roll.</p>`});}catch(error){console.error(`${ID} | Enchanted Aid chat card`,error);}
  return {value:roll.total,effectId:created[0].id};
 }catch(error){if(isHopePaymentCancellation(error))return false;throw error;}}));requests.set(key,{promise,expires:decisionNow()+decisionBudget(600000)});return promise;
}
async function dispatch(data){const gm=game.users.activeGM;if(!gm)throw Error('Enchanted Aid needs an active GM.');return gm.isSelf?resolveEnchantedAid(data,{user:game.user}):gm.query(OFFER,data,{timeout:decisionBudget(75000)});}
export async function promptEnchantedAid(helper){const item=enchantedAidItem(helper);if(!helper?.isOwner||!item)return;if(hopeCapacity(helper)<1)throw Error('You need 1 Hope to use Enchanted Aid.');const allies=helpRecipients(helper).sort((a,b)=>a.name.localeCompare(b.name));if(!allies.length)throw Error('There are no other characters in the active Party to help.');const targeted=[...(game.user.targets??[])].map(t=>t.actor).filter(Boolean);let allyUuid;if(targeted.length===1){if(!validHelpRecipient(helper,targeted[0]))throw Error('Target another member of the active Party.');allyUuid=targeted[0].uuid;}else allyUuid=await timedDialog(`Enchanted Aid — ${helper.name}`,`<p>Spend <strong>1 Hope</strong> and roll a <strong>d8 advantage die</strong> for an ally’s upcoming Spellcast Roll.</p><label>Ally<select name="ally">${allies.map(a=>`<option value="${esc(a.uuid)}">${esc(a.name)}</option>`).join('')}</select></label>`,[{action:'help',label:'Spend 1 Hope & Roll d8',callback:(_e,b)=>b.form.elements.ally.value},{action:'cancel',label:'Cancel',default:true,callback:()=>null}]);if(allyUuid)await dispatch({id:foundry.utils.randomID(),helperUuid:helper.uuid,allyUuid});}
export async function validateEnchantedSwap(request,user){if(!user?.active||request.deadline<=decisionNow()||request.hope===request.fear)return null;const source=await fromUuid(request.sourceUuid),item=await fromUuid(request.candidate?.itemUuid),helper=item?.actor,receipt=claimedHelp(user,request.claimId,source?.uuid);if(!source?.testUserPermission(user,'OWNER')||!receipt.some(row=>row.enchantedAid?.itemUuid===item?.uuid)||enchantedAidItem(helper)?.uuid!==item?.uuid||!swapAvailable(item)||!spellcastRoll(source,request.actionType,request.trait))return null;return {source,helper,item};}
export async function resolveEnchantedSwap(request,{user},authorize=consumeResolutionTicket){if(!game.user.isActiveGM||request.deadline>decisionNow()+decisionBudget(125000))return false;const valid=await validateEnchantedSwap(request,user);if(!valid||!authorize(request.resolutionToken,'enchanted-aid',valid.item.uuid,user))return false;return withHopeLock(valid.item.uuid,async()=>{const fresh=enchantedAidItem(valid.helper);if(fresh?.uuid!==valid.item.uuid||!swapAvailable(fresh))return false;const action=actionFor(fresh,ENCHANTED_SWAP_ACTION),path=`system.actions.${ENCHANTED_SWAP_ACTION}.uses.value`,next=Number(action.uses.value??0)+1,updated=await fresh.update({[path]:next});if(!updated)return false;return {itemUuid:fresh.uuid,bearerName:valid.helper.name};});}
export function swapEnchantedDice(roll){const hope=roll.dHope,fear=roll.dFear,before=hope.results.map(r=>({...r}));hope.results=fear.results.map(r=>({...r}));fear.results=before;for(const die of [hope,fear])if(die.options)delete die.options.sfx;roll._total=roll._evaluateTotal();}
export function registerEnchantedAid(){CONFIG.queries[OFFER]=resolveEnchantedAid;CONFIG.queries[`${ID}.enchantedAidSwap`]=resolveEnchantedSwap;Hooks.on('daggerheart.preUseAction',action=>{const item=enchantedAidItem(action.actor);if(item?.uuid!==action.item?.uuid)return;if(action.id===ENCHANTED_HELP_ACTION){void promptEnchantedAid(action.actor).catch(e=>ui.notifications.error(e.message));return false;}if(action.id===ENCHANTED_SWAP_ACTION){ui.notifications.info('Swap Dice Results is offered after an ally makes a Spellcast Roll with your Enchanted Aid.');return false;}});Hooks.on('renderChatMessageHTML',(message,html)=>{const used=message.rolls?.find(r=>r.options?.[ID]?.enchantedAid)?.options[ID].enchantedAid;if(!message.isContentVisible||!used||html.querySelector('.dhp-enchanted-aid'))return;const p=html.ownerDocument.createElement('p');p.className='dhp-enchanted-aid';p.textContent=`Enchanted Aid: ${used.bearerName} swapped the Hope and Fear Die results.`;html.querySelector('.message-content')?.append(p);});}
