import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {ID,featureActive} from '../core.js';
import {adaptabilityOutcome} from './adaptability.js';
import {ETHEREAL_KEY} from './ethereal-visage-data.js';
import {consumeResolutionTicket} from '../resolution-manager.js';
const QUERY=`${ID}.etherealVisage`;let fearQueue=Promise.resolve();
export const etherealFear=()=>Number(ui.resources?.currentFear??game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.Resources.Fear));
export function etherealItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===ETHEREAL_KEY;})??null:null;}
export function etherealAdvantage(config){const actor=config.data?.parent??(config.source?.actor?foundry.utils.fromUuidSync(config.source.actor):null);return Boolean(config.roll?.trait==='presence'&&actor?.statuses?.has('fly')&&etherealItem(actor));}
export async function validateEthereal(request,user){if(!user?.active||request.deadline<=decisionNow()||request.actionType!=='action'||request.trait!=='presence'||!request.withHope||!Number.isFinite(request.total)||etherealFear()<=0)return null;const actor=await fromUuid(request.sourceUuid),item=etherealItem(actor);if(!item||item.uuid!==request.candidate?.itemUuid||!actor.testUserPermission(user,'OWNER'))return null;const outcome=adaptabilityOutcome(request.total,request.critical,request.difficulty,request.targets);return outcome==='failure'?null:{actor,item,outcome};}
export async function resolveEthereal(request,{user},authorize){if(!game.user.isActiveGM||!Number.isFinite(request.deadline)||request.deadline>decisionNow()+decisionBudget(125000))return false;const valid=await validateEthereal(request,user);if(!valid||!authorize(request.resolutionToken,'ethereal',valid.item.uuid,user))return false;return{itemUuid:valid.item.uuid,actorUuid:valid.actor.uuid,bearerName:valid.actor.name};}
export async function settleEthereal(data,{user}){if(!game.user.isActiveGM||!user?.active||etherealFear()<=0)return false;const actor=await fromUuid(data.actorUuid);if(!actor?.testUserPermission(user,'OWNER')||etherealItem(actor)?.uuid!==data.itemUuid)return false;const remove=async()=>{const current=etherealFear();if(current<=0)return false;await ui.resources.updateFear(current-1);return true;},result=fearQueue.then(remove,remove);fearQueue=result.catch(()=>{});return result;}
export function installEtherealResources(Duality,settle=async data=>{const gm=game.users.activeGM;if(!gm)throw new Error('Ethereal Visage needs an active GM.');return gm.isSelf?settleEthereal(data,{user:game.user}):gm.query(QUERY,{op:'settle',...data},{timeout:decisionBudget(65000)});}){const native=Duality.addDualityResourceUpdates;Duality.addDualityResourceUpdates=async function(config){const choice=config[ID]?.etherealChoice,withHope=config.roll?.result?.duality===1||config.roll?.isCritical;if(!choice||config.actionType!=='action'||!withHope)return native.call(this,config);const actor=await fromUuid(config.source.actor);if(etherealItem(actor)?.uuid!==choice.itemUuid)return native.call(this,config);const original=config.resourceUpdates,proxy=new Proxy(original,{get(target,key){if(key==='addResources')return updates=>target.addResources(updates.filter(update=>!(update.key==='hope'&&update.value===1)));const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;}});config.resourceUpdates=proxy;try{const result=await native.call(this,config);if(!await settle(choice))throw new Error('Ethereal Visage could not remove Fear.');return result;}finally{config.resourceUpdates=original;}};}
export function registerEtherealVisage(){CONFIG.queries[QUERY]=async(request,context)=>request.op==='settle'?settleEthereal(request,context):resolveEthereal(request,context,consumeResolutionTicket);installEtherealResources(CONFIG.Dice.daggerheart.DualityRoll);Hooks.on('renderChatMessageHTML',(message,html)=>{const used=message.rolls?.find(roll=>roll.options?.[ID]?.etherealVisage)?.options[ID].etherealVisage;if(!message.isContentVisible||!used||html.querySelector('.dhp-ethereal-visage'))return;const note=html.ownerDocument.createElement('p');note.className='dhp-ethereal-visage';note.textContent='Ethereal Visage: removed 1 Fear instead of gaining Hope.';html.querySelector('.message-content')?.append(note);});}
