import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {ownerFor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {animateInitialDamage} from './combo-strike.js';
import {animateLuckbenderReroll} from './luckbender.js';
import {selectableDamageDice,rerollDamageDice} from './damage-reroll.js';
import {FEARSOME_KEY,FEARSOME_ACTION} from './fearsome-attack-data.js';
const QUERY=`${ID}.fearsomeAttack`,PROMPT=`${QUERY}Prompt`,WRAPPED=Symbol.for(`${ID}.fearsomeAttack`),requests=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function fearsomeItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===FEARSOME_KEY;})??null:null;}
export function fearsomeDice(roll){return selectableDamageDice(roll);}
export async function fearsomeActor(config){const message=config.source?.message?game.messages.get(config.source.message):null;let actor=message?.system?.action?.actor??config.data?.parent;if(!actor&&config.source?.actor)actor=await fromUuid(config.source.actor);return{actor,message};}
export async function promptFearsome(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.active||!actor?.testUserPermission(game.user,'OWNER')||!fearsomeItem(actor)||Number(actor.system.resources?.favor?.value)<1)return null;return timedDialog(`Fearsome Attack — ${actor.name}`,`<p>Damage: <strong>${Number(data.total)}</strong>. Spend <strong>1 Favor</strong> to reroll any selected dice.</p>${data.dice.map(die=>`<label style="display:inline-block;margin:0.4rem"><input type="checkbox" name="fearsomeDie" value="${esc(die.id)}"> d${Number(die.faces)}: <strong>${Number(die.value)}</strong>${die.discarded?' <em>(discarded)</em>':''}</label>`).join('')}`,[{action:'use',label:'Spend 1 Favor & Reroll',callback:(_e,_b,dialog)=>[...dialog.element.querySelectorAll('[name="fearsomeDie"]:checked')].map(input=>input.value)},{action:'decline',label:'Keep Damage',default:true,callback:()=>null}]);}
export async function resolveFearsome(request,{user}){if(!game.user.isActiveGM||!user?.active||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000)||!Array.isArray(request.dice)||!request.dice.length)return false;for(const[id,expiry]of requests)if(expiry<decisionNow())requests.delete(id);if(requests.has(request.id))return false;const actor=await fromUuid(request.actorUuid),item=fearsomeItem(actor);if(!item||item.uuid!==request.itemUuid||Number(actor.system.resources?.favor?.value)<1||!actor.testUserPermission(user,'OWNER')||request.dice.some(die=>!/^[0-9]+:[0-9]+$/.test(die.id)||!Number.isInteger(die.faces)||!Number.isFinite(die.value)))return false;requests.set(request.id,decisionNow()+decisionBudget(300000));const owner=ownerFor(actor,[...game.users],game.user),data={actorUuid:actor.uuid,total:request.total,dice:request.dice},selected=owner.isSelf?await promptFearsome(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});if(!Array.isArray(selected)||!selected.length||new Set(selected).size!==selected.length||!selected.every(id=>request.dice.some(die=>die.id===id))||decisionNow()>request.deadline)return false;return withHopeLock(actor.uuid,async()=>{const current=fearsomeItem(actor),favor=Number(actor.system.resources.favor.value);if(current?.uuid!==item.uuid||favor<1)return false;const updated=await actor.update({'system.resources.favor.value':favor-1});if(!updated||Number(actor.system.resources.favor.value)!==favor-1)throw Error('Could not spend Fearsome Attack Favor.');return selected;});}
export async function rerollFearsome(roll,selected){const fresh=await rerollDamageDice(roll,selected);roll.options[ID]={...roll.options[ID],fearsomeAttack:Number(roll.options[ID]?.fearsomeAttack??0)+1};return fresh;}
export function installFearsomeAttack(Damage,offer){if(Damage[WRAPPED])return;const native=Damage.buildEvaluate;Damage.buildEvaluate=async function(roll,config,...args){const result=await native.call(this,roll,config,...args);if(!config.hasHealing&&config.damage?.main)await offer(config);return result;};Object.defineProperty(Damage,WRAPPED,{value:true});}
export async function offerFearsome(config,dependencies={}){const{actor,message}=await fearsomeActor(config),initial=dependencies.initial??animateInitialDamage,reroll=dependencies.reroll??rerollFearsome,animate=dependencies.animate??animateLuckbenderReroll,decide=dependencies.decide??(async request=>{const gm=game.users.activeGM;if(!gm)throw Error('Fearsome Attack needs an active GM.');return gm.isSelf?resolveFearsome(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});});let item=fearsomeItem(actor),dice=fearsomeDice(config.damage.main);if(!item||Number(actor.system.resources?.favor?.value)<1||!dice.length)return;await initial(config,message??getDocumentClass('ChatMessage').applyMode({},config.selectedMessageMode??config.rollMode??game.settings.get('core','messageMode')));while((item=fearsomeItem(actor))&&Number(actor.system.resources?.favor?.value)>0&&(dice=fearsomeDice(config.damage.main)).length){const request={id:foundry.utils.randomID(),actorUuid:actor.uuid,itemUuid:item.uuid,total:config.damage.main.total,dice,deadline:decisionNow()+decisionBudget(120000)},selected=await decide(request);if(!selected)break;const fresh=await reroll(config.damage.main,selected);await animate(config.damage.main,config,message);if(game.dice3d)for(const result of fresh)result.hidden=true;}}
export function registerFearsomeAttack(){CONFIG.queries[QUERY]=resolveFearsome;CONFIG.queries[PROMPT]=promptFearsome;installFearsomeAttack(CONFIG.Dice.daggerheart.DamageRoll,offerFearsome);Hooks.on('daggerheart.preUseAction',action=>{if(action.id===FEARSOME_ACTION&&fearsomeItem(action.actor)?.uuid===action.item?.uuid){ui.notifications.info('Fearsome Attack is offered automatically after rolling damage.');return false;}});}
