import { decisionBudget } from '../settings.js';
import { decisionNow } from '../decision-clock.js';
import { ID,featureActive } from '../core.js';
import { GRAPPLING_KEY,GRAPPLING_EFFECT,GRABBED } from './grappling-data.js';
import { overwhelmHits } from './overwhelm.js';
import { quickPayments } from './quick-stance.js';
import { sourceToken } from './hallowed-aura.js';
import { meleeLimit } from './kick.js';
import { ownerFor } from './aura-rules.js';
import { timedDialog } from '../dialog.js';
import { markReactiveStress } from './stress-payment.js';
import { withHopeLock } from './hope-lock.js';
import { syncFocus } from './stance-fighter.js';
const QUERY=`${ID}.grappling`,PROMPT=`${ID}.grapplingPrompt`,pending=new Set();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function grapplingItem(actor){const item=actor?.items?.find(i=>{const f=i.flags?.[ID];return featureActive(i)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===GRAPPLING_KEY;});const origin=item?.effects.get(GRAPPLING_EFFECT)?.uuid;return origin&&actor.effects.some(e=>e.origin===origin&&!e.disabled&&!e.isSuppressed)?item:null;}
export function grapplingHits(message){const actor=message?.system?.action?.actor,origin=actor&&sourceToken(actor);if(!origin)return [];return overwhelmHits(message).filter(hit=>{const token=canvas.tokens.get(hit.id),distance=token&&origin.distanceTo(token);return token?.actor?.uuid===hit.actorId&&Number.isFinite(distance)&&distance<=meleeLimit(canvas.scene);});}
export async function promptGrappling(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!grapplingItem(actor))return null;return timedDialog(`Grappling — ${actor.name}`,`<p>Use Grappling on <strong>${esc(data.targetName)}</strong>?</p><select name="grappleMode" style="width:100%"><option value="restrain">Temporarily Restrain</option><option value="throw">Throw up to Close (manual)</option></select>`,[...quickPayments(actor).map(payment=>({action:payment,label:payment==='focus'?'Spend 1 Focus':'Mark 1 Stress',callback:(_e,_b,d)=>({payment,mode:d.element.querySelector('[name="grappleMode"]').value})})),{action:'decline',label:'Decline',default:true,callback:()=>null}]);}
export async function resolveGrappling(request,{user},ask=promptGrappling){if(!game.user.isActiveGM||!user?.active||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000))return false;const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,key=`${request.messageUuid}:${request.targetId}`;if(!actor?.testUserPermission(user,'OWNER')||!grapplingItem(actor)||!quickPayments(actor).length||pending.has(key)||message.flags?.[ID]?.grappling?.[request.targetId])return false;const hit=grapplingHits(message).find(h=>h.id===request.targetId);if(!hit)return false;const target=await fromUuid(hit.actorId);if(!target)return false;pending.add(key);try{
 await message.update({[`flags.${ID}.grappling.${request.targetId}`]:'offered'});const owner=ownerFor(actor,[...game.users],game.user),data={actorUuid:actor.uuid,targetName:target.name};const choice=owner.isSelf?await ask(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});if(!choice||!['restrain','throw'].includes(choice.mode)||!quickPayments(actor).includes(choice.payment)||decisionNow()>request.deadline)return false;
 return await withHopeLock(actor.uuid,async()=>{const item=grapplingItem(actor);if(!item||!grapplingHits(message).some(h=>h.id===hit.id)||!quickPayments(actor).includes(choice.payment))return false;
 if(choice.payment==='stress'){if(!await markReactiveStress(actor.uuid,a=>Boolean(grapplingItem(a))))return false;}else{const next=Number(actor.system.resources.focus.value)-1;const updated=await actor.update({'system.resources.focus.value':next});if(!updated||Number(actor.system.resources.focus.value)!==next)throw new Error('Could not spend Grappling Focus.');await syncFocus(actor);}
 if(choice.mode==='restrain')await game.system.api.fields.ActionFields.EffectsField.applyEffect(item.effects.get(GRABBED),target);
 await message.update({[`flags.${ID}.grappling.${request.targetId}`]:choice});await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Grappling</strong>: ${esc(actor.name)} ${choice.payment==='focus'?'spends 1 Focus':'marks 1 Stress'}. ${choice.mode==='restrain'?`${esc(target.name)} is temporarily Restrained.`:`Throw ${esc(target.name)} up to Close range; move the token manually.`}</p>`});return true;});
 }finally{pending.delete(key);}}
export function registerGrappling(){CONFIG.queries[QUERY]=resolveGrappling;CONFIG.queries[PROMPT]=promptGrappling;const Action=game.system.api.data.actions.actionsTypes.base,native=Action.prototype.use;Action.prototype.use=async function(...args){const config=await native.apply(this,args);if(config&&grapplingItem(this.actor))for(const hit of grapplingHits(config.message)){if(!quickPayments(this.actor).length)break;const gm=game.users.activeGM;if(!gm)throw new Error('Grappling needs an active GM.');const request={messageUuid:config.message.uuid,targetId:hit.id,deadline:decisionNow()+decisionBudget(120000)};if(gm.isSelf)await resolveGrappling(request,{user:game.user});else await gm.query(QUERY,request,{timeout:decisionBudget(125000)});}return config;};}
