import { decisionBudget } from '../settings.js';
import { decisionNow } from '../decision-clock.js';
import { ID, featureActive } from '../core.js';
import { HOBBLING_STRIKE_KEY, HOBBLING_STRIKE_ACTION, HOBBLING_STRIKE_EFFECT } from './hobbling-strike-data.js';
import { overwhelmHits } from './overwhelm.js';
import { sourceToken } from './hallowed-aura.js';
import { meleeLimit } from './kick.js';
import { markReactiveStress } from './stress-payment.js';
import { ownerFor } from './aura-rules.js';
import { timedDialog } from '../dialog.js';

const QUERY=`${ID}.hobblingStrike`,PROMPT=`${ID}.hobblingStrikePrompt`,pending=new Set();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function hobblingStrikeItem(actor,requireStress=false){const stress=actor?.system?.resources?.stress;if(actor?.type!=='character'||(requireStress&&!(Number(stress?.value)<Number(stress?.max))))return null;return actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===HOBBLING_STRIKE_KEY;})??null;}
export function hobblingStrikeHits(message){const actor=message?.system?.action?.actor,origin=actor&&sourceToken(actor);if(!origin)return[];return overwhelmHits(message).filter(hit=>{const token=canvas.tokens.get(hit.id),distance=token&&origin.distanceTo(token);return token?.actor?.uuid===hit.actorId&&Number.isFinite(distance)&&distance<=meleeLimit(canvas.scene);});}
export async function promptHobblingStrike(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!hobblingStrikeItem(actor,true))return false;return Boolean(await timedDialog(`Hobbling Strike — ${actor.name}`,`<p>You hit <strong>${esc(data.targetName)}</strong> within Melee range.</p><p>Mark <strong>1 Stress</strong> to make them temporarily <strong>Vulnerable</strong>?</p>`,[{action:'use',label:'Mark 1 Stress',callback:()=>true},{action:'decline',label:'Decline',default:true,callback:()=>false}]));}
export async function resolveHobblingStrike(request,{user},ask=promptHobblingStrike){if(!game.user.isActiveGM||!user?.active||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000))return false;const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,key=`${request.messageUuid}:${request.targetId}`;if(!actor?.testUserPermission(user,'OWNER')||!hobblingStrikeItem(actor,true)||pending.has(key)||message.flags?.[ID]?.hobblingStrike?.[request.targetId])return false;const hit=hobblingStrikeHits(message).find(entry=>entry.id===request.targetId);if(!hit)return false;const target=await fromUuid(hit.actorId);if(!target)return false;pending.add(key);try{await message.update({[`flags.${ID}.hobblingStrike.${request.targetId}`]:'offered'});const owner=ownerFor(actor,[...game.users],game.user),accepted=owner.isSelf?await ask({actorUuid:actor.uuid,targetName:target.name},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,targetName:target.name},{timeout:decisionBudget(65000)});if(!accepted||decisionNow()>request.deadline||!hobblingStrikeHits(message).some(entry=>entry.id===request.targetId))return false;if(!await markReactiveStress(actor.uuid,current=>Boolean(hobblingStrikeItem(current,true))))throw new Error('Hobbling Strike could not mark Stress.');const currentActor=await fromUuid(actor.uuid),item=hobblingStrikeItem(currentActor),effect=item?.effects?.get?.(HOBBLING_STRIKE_EFFECT);if(!effect)throw new Error('Hobbling Strike effect is missing.');await game.system.api.fields.ActionFields.EffectsField.applyEffect(effect,target);await message.update({[`flags.${ID}.hobblingStrike.${request.targetId}`]:'applied'});await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:currentActor}),content:`<p><strong>Hobbling Strike</strong>: ${esc(currentActor.name)} marks 1 Stress; ${esc(target.name)} becomes temporarily Vulnerable.</p>`});return true;}finally{pending.delete(key);}}
export function registerHobblingStrike(){CONFIG.queries[QUERY]=resolveHobblingStrike;CONFIG.queries[PROMPT]=promptHobblingStrike;const Action=game.system.api.data.actions.actionsTypes.base,native=Action.prototype.use;Action.prototype.use=async function(...args){const config=await native.apply(this,args);if(config&&hobblingStrikeItem(this.actor,true))for(const hit of hobblingStrikeHits(config.message)){try{const gm=game.users.activeGM;if(!gm)throw new Error('Hobbling Strike needs an active GM.');const request={messageUuid:config.message.uuid,targetId:hit.id,deadline:decisionNow()+decisionBudget(120000)};if(gm.isSelf)await resolveHobblingStrike(request,{user:game.user});else await gm.query(QUERY,request,{timeout:decisionBudget(125000)});}catch(error){console.error(`${ID} | Hobbling Strike`,error);ui.notifications.error(`Hobbling Strike failed: ${error.message}`);}}return config;};Hooks.on('daggerheart.preUseAction',action=>{const flags=action.item?.flags?.[ID];if(action.id!==HOBBLING_STRIKE_ACTION||(flags?.applied?.key??flags?.premade?.key)!==HOBBLING_STRIKE_KEY)return;ui.notifications.info('Hobbling Strike is offered automatically after a successful attack within Melee range.');return false;});}
