import {ID,featureActive} from '../core.js';
import {withHopeLock} from './hope-lock.js';
import {flightCastSuccess} from './flight.js';
import {sourceToken} from './hallowed-aura.js';
import {meleeLimit} from './kick.js';
import {unavailableActor} from './aura-rules.js';
import {INVISIBILITY_KEY,INVISIBILITY_CAST,INVISIBILITY_EFFECT} from './invisibility-data.js';
const QUERY=`${ID}.invisibility`,ACTION=Symbol.for(`${QUERY}Action`),ROLL=Symbol.for(`${QUERY}Roll`),casting=new Set();
const operation=()=>foundry.utils.randomID();
export function invisibilityItem(actor,available=false){return actor?.type==='character'?actor.items?.find(item=>{const f=item.flags?.[ID];return item.type==='domainCard'&&featureActive(item)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===INVISIBILITY_KEY&&(!available||!item.system.inVault&&!item.system.isDomainTouchedSuppressed&&!unavailableActor(actor));})??null:null;}
export function invisibilityTokens(item){const n=Number(item?.system.resource?.value);return Number.isSafeInteger(n)&&n>0?n:0;}
const marker=effect=>effect.flags?.[ID]?.invisibility;
export function invisibleEffects(actor){return [...(actor?.effects??[])].filter(e=>marker(e)&&!e.disabled&&!e.isSuppressed&&e.active!==false&&!e.duration?.expired);}
export function invisibilityStates(actor){return invisibleEffects(actor).map(e=>({itemUuid:marker(e).itemUuid,holderUuid:actor.uuid,generation:marker(e).generation,effectIds:[e.id]}));}
export function invisibleTargets(config){if(config.hasHealing||!['attack'].includes(config.roll?.type)&&!config.source?.action)return false;const actor=config.data?.parent??foundry.utils.fromUuidSync?.(config.source?.actor),item=actor?.items?.get?.(config.source?.item),action=item?.system?.actions?.get?.(config.source?.action)??item?.system?.actions?.[config.source?.action]??(config.source?.action&&item?.system?.attack?.id===config.source.action?item.system.attack:null);if(config.roll?.type!=='attack'&&action?.type!=='attack')return false;return (config.targets??[...(game.user.targets??[])]).some(t=>{const token=canvas.tokens?.get(t.id),recipient=t.actor??t.document?.actor??(token?.actor?.uuid===t.actorId?token.actor:null)??foundry.utils.fromUuidSync?.(t.actorId);return invisibleEffects(recipient).some(e=>e.statuses?.has?.('invisible')||e.statuses?.includes?.('invisible'));});}
export async function invisibilityRecipient(actor,selection){if(selection.holderUuid===actor.uuid)return actor;const token=await fromUuid(selection.tokenUuid),origin=sourceToken(actor),holder=token?.actor,limit=canvas.ready?meleeLimit(canvas.scene):NaN;if(!origin||!token?.object||token.parent?.id!==canvas.scene.id||holder?.uuid!==selection.holderUuid||!['character','adversary','companion'].includes(holder.type)||unavailableActor(holder)||origin.document.disposition!==1||token.disposition!==1)return null;const distance=origin.distanceTo(token.object);return Number.isFinite(distance)&&distance>=0&&Number.isFinite(limit)&&distance<=limit?holder:null;}
function template(item){return item.effects?.get?.(INVISIBILITY_EFFECT)??item.effects?.find(e=>(e.id??e._id)===INVISIBILITY_EFFECT);}
function heldEffects(holder,item,all=false){return [...(holder?.effects??[])].filter(e=>marker(e)?.itemUuid===item.uuid&&(all||invisibleEffects(holder).includes(e)));}
async function oldHolder(item){return item.flags?.[ID]?.invisibility?.holderUuid?fromUuid(item.flags[ID].invisibility.holderUuid):null;}
export async function resolveInvisibility(request,{user}){
 if(!game.user.isActiveGM||!user?.active||!['activate','spend','zero'].includes(request?.mode)||typeof request.operationId!=='string'||!request.operationId.length||request.operationId.length>128)return false;
 const item=await fromUuid(request.itemUuid),caster=item?.actor;if(invisibilityItem(caster,request.mode==='activate')?.uuid!==item?.uuid||!item)return false;
 return withHopeLock(item.uuid,async()=>{
  const prior=item.flags?.[ID]?.invisibility??null,before=invisibilityTokens(item),holder=await oldHolder(item);
  if(!game.user.isActiveGM||!user.active||invisibilityItem(caster,request.mode==='activate')?.uuid!==item.uuid)return false;
  if(request.mode==='activate'){
   if(!caster.testUserPermission(user,'OWNER'))return false;const message=await fromUuid(request.messageUuid),source=message?.system?.source,roll=message?.system?.roll;
   if(!flightCastSuccess(message)||Number(roll?.options?.roll?.difficulty)!==10||source?.actor!==caster.uuid||source.item!==item.id||source.action!==INVISIBILITY_CAST||request.operationId!==message.uuid||prior?.castMessage===message.uuid||prior?.castOperations?.includes(message.uuid))return false;
   const recipient=await invisibilityRecipient(caster,request);if(!recipient)return false;const trait=Number(caster.getRollData().cast);if(!Number.isSafeInteger(trait))throw Error('Invisibility could not read the Spellcast trait.');const count=Math.max(0,trait),old=heldEffects(holder,item,true).map(e=>e.id),data=template(item)?.toObject?.()??structuredClone(template(item));if(!data)throw Error('Invisibility effect is missing. Reapply Medkit.');for(const key of ['_id','id','uuid','_stats'])delete data[key];data.disabled=false;data.transfer=false;data.statuses=[CONFIG.specialStatusEffects?.INVISIBLE??'invisible'];data.origin=template(item).uuid??`${item.uuid}.ActiveEffect.${INVISIBILITY_EFFECT}`;data.flags={...data.flags,[ID]:{...data.flags?.[ID],invisibility:{itemUuid:item.uuid,generation:message.uuid}}};
   const created=count?await recipient.createEmbeddedDocuments('ActiveEffect',[data]):[];if(count&&created?.length!==1)throw Error('Could not apply Invisibility.');
   try{const updated=await item.update({'system.resource.value':count,[`flags.${ID}.invisibility`]:{generation:message.uuid,castMessage:message.uuid,castOperations:[...(prior?.castOperations??[]),message.uuid].slice(-512),holderUuid:recipient.uuid,spentOperations:[]}});if(!updated||invisibilityTokens(item)!==count)throw Error('Could not set Invisibility tokens.');if(old.length)await holder.deleteEmbeddedDocuments('ActiveEffect',old);}
   catch(error){if(created.length)await recipient.deleteEmbeddedDocuments('ActiveEffect',created.map(e=>e.id));await item.update({'system.resource.value':before,[`flags.${ID}.invisibility`]:prior});throw error;}return {tokens:count};
  }
  if(request.mode==='zero'){if(!caster.testUserPermission(user,'OWNER')||before)return false;const ids=heldEffects(holder,item,true).map(e=>e.id);if(ids.length)await holder.deleteEmbeddedDocuments('ActiveEffect',ids);return true;}
  if(!holder||holder.uuid!==request.holderUuid||!holder.testUserPermission(user,'OWNER')||prior?.generation!==request.generation||!before||prior.spentOperations?.includes(request.operationId)||!Array.isArray(request.effectIds)||!heldEffects(holder,item).some(e=>request.effectIds.includes(e.id)))return false;
  const updated=await item.update({'system.resource.value':before-1,[`flags.${ID}.invisibility`]:{...prior,spentOperations:[...(prior.spentOperations??[]),request.operationId].slice(-512)}});if(!updated||invisibilityTokens(item)!==before-1)throw Error('Could not spend an Invisibility token.');
  try{if(before===1)await holder.deleteEmbeddedDocuments('ActiveEffect',heldEffects(holder,item,true).map(e=>e.id));}catch(error){await item.update({'system.resource.value':before,[`flags.${ID}.invisibility`]:prior});throw error;}return {tokens:before-1};
 });
}
async function dispatch(request){const gm=game.users.activeGM;if(!gm)throw Error('Invisibility needs an active GM.');return gm.isSelf?resolveInvisibility(request,{user:game.user}):gm.query(QUERY,request,{timeout:15000});}
const completed=result=>result?.actionType==='action'&&result.evaluate!==false&&(!result.hasRoll||Number.isFinite(result.message?.system?.roll?.total??result.roll?.total));
export function installInvisibility(Action,Actor,send=dispatch){
 if(!Object.hasOwn(Action,ACTION)){const native=Action.prototype.use;Action.prototype.use=async function(...args){const item=invisibilityItem(this.actor),cast=item?.uuid===this.item?.uuid&&this.id===INVISIBILITY_CAST,states=this.actionType==='action'&&!['damage','grouped'].includes(this.type)?invisibilityStates(this.actor):[];let selection;
  if(cast){if(!invisibilityItem(this.actor,true)||casting.has(item.uuid))return false;const targets=[...(game.user.targets??[])];if(targets.length>1){ui.notifications.warn('Invisibility: select one ally, or no targets for yourself.');return false;}selection=targets.length?{holderUuid:targets[0].actor?.uuid,tokenUuid:targets[0].document.uuid}:{holderUuid:this.actor.uuid};if(!await invisibilityRecipient(this.actor,selection)){ui.notifications.warn('Invisibility: choose yourself or an ally within Melee.');return false;}if(!game.users.activeGM)throw Error('Invisibility needs an active GM.');casting.add(item.uuid);}
  const options=args[1]??{},forward=states.length||cast?[args[0],{...options,[ID]:{...options[ID],invisibilityAction:true}},...args.slice(2)]:args;
  try{const result=await native.apply(this,forward);let replaced=false;if(cast&&completed(result)&&result.hasRoll&&flightCastSuccess(result.message)){const applied=await send({mode:'activate',itemUuid:item.uuid,...selection,messageUuid:result.message.uuid,operationId:result.message.uuid});if(!applied)throw Error('Invisibility cast completed but its effect could not be confirmed. Check the card and recipient manually.');replaced=true;}
   if(completed(result))for(const state of states)if(!replaced||state.itemUuid!==item.uuid)await send({...state,mode:'spend',operationId:result.message?.uuid??operation()});return result;
  }finally{if(cast)casting.delete(item.uuid);}};Object.defineProperty(Action,ACTION,{value:true});}
 if(!Object.hasOwn(Actor,ROLL)){const native=Actor.prototype.diceRoll;Actor.prototype.diceRoll=async function(config,...args){const states=!config[ID]?.invisibilityAction&&config.actionType==='action'&&!config.source?.message&&config.evaluate!==false&&['trait','spellcast','attack'].includes(config.roll?.type)?invisibilityStates(this):[];const result=await native.call(this,config,...args);if(completed(result)&&Number.isFinite(result?.message?.system?.roll?.total??result?.roll?.total))for(const state of states)await send({...state,mode:'spend',operationId:result.message?.uuid??operation()});return result;};Object.defineProperty(Actor,ROLL,{value:true});}
}
export function registerInvisibility(){CONFIG.queries[QUERY]=resolveInvisibility;installInvisibility(game.system.api.data.actions.actionsTypes.base,CONFIG.Actor.documentClass);Hooks.on('updateItem',(item,changes)=>{if(!game.user.isActiveGM||invisibilityItem(item.actor)?.uuid!==item.uuid||invisibilityTokens(item))return;if(!Object.hasOwn(changes,'system.resource.value')&&!Object.hasOwn(changes.system?.resource??{},'value'))return;void resolveInvisibility({mode:'zero',itemUuid:item.uuid,operationId:operation()},{user:game.user}).catch(error=>{console.error(`${ID} | Invisibility`,error);ui.notifications.error(error.message);});});}
