import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {restComplete} from '../rest-loadout.js';
import {sourceToken} from './hallowed-aura.js';
import {allied,unavailableActor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {absorbingWrites} from './armor-absorbing.js';
import {bulkyDamagePacket} from './armor-bulky.js';
import {retributionSource} from './hideous-retribution.js';
import {LIFE_WARD_KEY,LIFE_WARD_ACTION,LIFE_WARD_EFFECT} from './life-ward-data.js';
const QUERY=ID+'.lifeWard',USE=Symbol.for(QUERY+'Use'),DAMAGE=Symbol.for(QUERY+'Damage'),REST=Symbol.for(QUERY+'Rest'),REFRESH=Symbol.for(QUERY+'Refresh'),DEATH=Symbol.for(QUERY+'Death'),casts=new Set(),contexts=new WeakMap(),requests=new Map(),damaging=new WeakMap(),saving=new Set();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const record=e=>e?.flags?.[ID]?.lifeWard;
const active=e=>!e.disabled&&!e.isSuppressed&&e.active!==false&&!e.duration?.expired;
const gen=id=>typeof id==='string'&&/^[a-zA-Z0-9]{16}$/.test(id);
function actors(){const found=new Map([...game.actors??[]].map(a=>[a.uuid,a]));for(const scene of game.scenes??[])for(const token of scene.tokens??[])if(token.actor)found.set(token.actor.uuid,token.actor);return [...found.values()];}
export function lifeWardItem(actor){return actor?.type==='character'&&!unavailableActor(actor)?actor.items?.find(i=>{const f=i.flags?.[ID];return i.type==='domainCard'&&featureActive(i)&&!f?.disabled&&(!i.system.inVault||i.system.vaultActive)&&!i.system.isDomainTouchedSuppressed&&(f?.applied?.key??f?.premade?.key)===LIFE_WARD_KEY;})??null:null;}
export function lifeWardEffects(casterUuid){return actors().flatMap(a=>[...a.effects??[]].filter(e=>record(e)?.casterUuid===casterUuid&&gen(record(e).generation)));}
export function lifeWardCandidates(caster){if(!canvas.ready||!lifeWardItem(caster))return [];const origin=sourceToken(caster);if(!origin||origin.document.hidden)return [];const ranges=canvas.scene.rangeSettings??game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement,local=canvas.scene.flags?.daggerheart?.rangeMeasurement,limit=Number(canvas.scene.rangeSettings?ranges.close:ranges.enabled&&local?.setting===CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id?local.close:ranges.close);if(!Number.isFinite(limit)||limit<0)return [];return canvas.tokens.placeables.filter(t=>t.actor?.type==='character'&&t.actor.uuid!==caster.uuid&&!t.actor.statuses?.has('dead')&&!t.document.hidden&&allied(origin.document,t.document)&&Number.isFinite(t.distanceTo(origin))&&t.distanceTo(origin)>=0&&t.distanceTo(origin)<=limit);}
export async function chooseLifeWardTarget(caster){const candidates=lifeWardCandidates(caster),selected=[...game.user.targets??[]].filter(t=>candidates.some(c=>c.document.uuid===t.document?.uuid));if(selected.length===1)return selected[0].document.uuid;if(!candidates.length){ui.notifications.warn('Life Ward needs an ally within Close range.');return null;}return timedDialog('Life Ward — Choose Ally',`<label>Ally<select name="ally">${candidates.map(t=>`<option value="${esc(t.document.uuid)}">${esc(t.document.name??t.actor.name)}</option>`).join('')}</select></label>`,[{action:'choose',label:'Mark Ally',callback:(_e,_b,d)=>d.element.querySelector('[name="ally"]').value},{action:'cancel',label:'Cancel',default:true,callback:()=>null}]);}
export function lifeWardEffectData(item,targetUuid,generation){const template=item.effects?.get?.(LIFE_WARD_EFFECT)??item.effects?.find?.(e=>(e.id??e._id)===LIFE_WARD_EFFECT),data=template?.toObject?.()??(template&&structuredClone(template));if(!data)throw Error('Life Ward sigil is missing. Re-Medkit the card.');for(const k of ['_id','id','_stats','start'])delete data[k];data.disabled=false;data.transfer=false;data.origin=template.uuid??item.uuid+'.ActiveEffect.'+LIFE_WARD_EFFECT;data.flags={...data.flags,[ID]:{...data.flags?.[ID],lifeWard:{casterUuid:item.actor.uuid,itemUuid:item.uuid,targetUuid,generation,phase:'ready'}}};return data;}
export async function clearLifeWards(casterUuid,effectUuids){const allowed=new Set(effectUuids);let count=0;for(const e of lifeWardEffects(casterUuid))if(allowed.has(e.uuid)){await e.delete();count++;}return count;}
export async function saveWithLifeWard(actor){if(!game.user.isActiveGM||actor?.type!=='character'||actor.system.deathMoveViable!==true||saving.has(actor.uuid))return false;
 return withHopeLock(actor.uuid,async()=>{if(!game.user.isActiveGM||actor.system.deathMoveViable!==true)return false;const effect=[...actor.effects??[]].find(e=>active(e)&&record(e)?.targetUuid===actor.uuid&&record(e).phase==='ready'&&gen(record(e).generation));if(!effect)return false;saving.add(actor.uuid);try{const r=record(effect),marked=await effect.update({[`flags.${ID}.lifeWard.phase`]:'saving'});if(!marked||record(effect)?.phase!=='saving')throw Error('Life Ward could not reserve its sigil.');const before=Number(actor.system.resources.hitPoints.value);let error;try{await absorbingWrites(actor,()=>actor.takeHealing({resources:{hitPoints:1}}));}catch(e){error=e;}
   const healed=before-Number(actor.system.resources.hitPoints.value)===1;if(!healed){if(Number(actor.system.resources.hitPoints.value)===before)await effect.update({[`flags.${ID}.lifeWard.phase`]:'ready'});throw error??Error('Life Ward could not confirm clearing 1 HP. Check the ally and sigil manually.');}
   // Never restore a ward after committed recovery, even if cleanup/chat fails.
   await effect.update({[`flags.${ID}.lifeWard.phase`]:'spent'});if(actor.effects?.some(e=>e.uuid===effect.uuid))await effect.delete();
   try{await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Life Ward:</strong> ${esc(actor.name)} clears 1 HP instead of making a death move. The sigil is consumed.</p>`});}catch(e){console.warn(ID+' | Life Ward notification',e);}return true;
  }finally{saving.delete(actor.uuid);}});}
export async function resolveLifeWard(request,{user}){if(!game.user.isActiveGM||!user?.active||!gen(request?.id)||typeof request.actorUuid!=='string')return false;const key=user.id+':'+request.id,sig=JSON.stringify(request),old=requests.get(key);if(old)return old.sig===sig?old.promise:false;
 const promise=(async()=>{const actor=await fromUuid(request.actorUuid);if(request.op==='damage'){const packet=bulkyDamagePacket(request.packet),sourceUuid=retributionSource(packet),source=sourceUuid&&await fromUuid(sourceUuid);if(!actor||!packet||typeof request.isDirect!=='boolean'||!user.isGM&&!actor.testUserPermission(user,'OWNER')&&!source?.testUserPermission(user,'OWNER'))return null;return {result:await actor.takeDamage(packet,request.isDirect)};}if(!actor?.testUserPermission(user,'OWNER'))return false;if(request.op==='save')return saveWithLifeWard(actor);if(request.op==='clear'){if(!Array.isArray(request.effectUuids)||request.effectUuids.length>1000||!request.effectUuids.every(v=>typeof v==='string'))return false;return withHopeLock('life-ward-caster:'+actor.uuid,()=>clearLifeWards(actor.uuid,request.effectUuids));}
  if(request.op!=='cast')return false;return withHopeLock('life-ward-caster:'+actor.uuid,async()=>{const item=lifeWardItem(actor),target=lifeWardCandidates(actor).find(t=>t.document.uuid===request.tokenUuid);if(!game.user.isActiveGM||!user.active||!actor.testUserPermission(user,'OWNER')||item?.uuid!==request.itemUuid||!target||target.actor.uuid!==request.targetUuid)return false;const previous=lifeWardEffects(actor.uuid).map(e=>e.uuid),[effect]=await target.actor.createEmbeddedDocuments('ActiveEffect',[lifeWardEffectData(item,target.actor.uuid,request.id)]);if(!effect||record(effect)?.generation!==request.id)throw Error('Life Ward sigil creation was canceled or unconfirmed.');await clearLifeWards(actor.uuid,previous);return {effectUuid:effect.uuid};});})();requests.set(key,{sig,promise});if(requests.size>512)requests.delete(requests.keys().next().value);return promise;}
export function installLifeWardCast(Action,send,pick=chooseLifeWardTarget){if(Object.hasOwn(Action,USE))return;const use=Action.prototype.use,prepare=Action.prototype.prepareConfig,workflow=Action.prototype.executeWorkflow;
 Action.prototype.prepareConfig=function(...args){const config=prepare.apply(this,args);if(config&&casts.has(this.item?.uuid)&&this.id===LIFE_WARD_ACTION){config.hasEffect=false;config.hasTarget=false;config.targets=[];contexts.set(config,this);}return config;};
 Action.prototype.executeWorkflow=async function(config,...args){if(contexts.get(config)!==this)return workflow.call(this,config,...args);const changed=new Map();for(const name of ['effects','target']){const old=this.workflow.get(name);if(old){const next={...old,execute:async()=>{}};this.workflow.set(name,next);changed.set(name,{old,next});}}try{return await workflow.call(this,config,...args);}finally{for(const [name,{old,next}]of changed)if(this.workflow.get(name)===next)this.workflow.set(name,old);contexts.delete(config);}};
 Action.prototype.use=async function(...args){const item=lifeWardItem(this.actor);if(this.id!==LIFE_WARD_ACTION||item?.uuid!==this.item?.uuid)return use.apply(this,args);if(casts.has(item.uuid))return false;if(!game.users.activeGM||!this.actor.testUserPermission(game.user,'OWNER'))return false;casts.add(item.uuid);try{const tokenUuid=await pick(this.actor),target=lifeWardCandidates(this.actor).find(t=>t.document.uuid===tokenUuid);if(!target)return false;const result=await absorbingWrites(this.actor,()=>use.apply(this,args));if(!result||result.source?.action!==LIFE_WARD_ACTION)return result;try{if(!await send({op:'cast',id:foundry.utils.randomID(),actorUuid:this.actor.uuid,itemUuid:item.uuid,tokenUuid,targetUuid:target.actor.uuid}))throw Error('The paid ally/card/range is no longer valid.');}catch(error){ui.notifications.error('Life Ward casting completed, but its sigil needs manual review. Check Hope and wards before retrying: '+error.message);}return result;}finally{casts.delete(item.uuid);}};Object.defineProperty(Action,USE,{value:true});}
export function installLifeWardDamage(Actor,send){if(Object.hasOwn(Actor,DAMAGE))return;const take=Actor.prototype.takeDamage;Actor.prototype.takeDamage=async function(...args){const observed=this.type==='character'&&this.effects?.some(e=>record(e)&&active(e));if(!observed)return take.apply(this,args);const packet=bulkyDamagePacket(args[0]);if(packet&&!game.user.isActiveGM){const response=await send({op:'damage',id:foundry.utils.randomID(),actorUuid:this.uuid,packet,isDirect:Boolean(args[1])});if(!response||!Object.hasOwn(response,'result'))throw Error('Life Ward damage coordination was rejected. Review incoming damage before continuing.');return response.result;}damaging.set(this,(damaging.get(this)??0)+1);let result;try{result=await absorbingWrites(this,()=>take.apply(this,args));}finally{const n=damaging.get(this)-1;if(n)damaging.set(this,n);else damaging.delete(this);}if(game.user.isActiveGM&&!damaging.has(this))try{await saveWithLifeWard(this);}catch(error){ui.notifications.error('Life Ward recovery needs manual review: '+error.message);}return result;};Object.defineProperty(Actor,DAMAGE,{value:true});}
export function installLifeWardRest(Downtime,send){if(!Downtime||Object.hasOwn(Downtime,REST))return;const close=Downtime.prototype.close;Downtime.prototype.close=async function(...args){const actor=this.actor,ids=this.shortrest===false&&restComplete(this)?lifeWardEffects(actor.uuid).map(e=>e.uuid):[],result=await close.apply(this,args);if(ids.length)try{await send({op:'clear',id:foundry.utils.randomID(),actorUuid:actor.uuid,effectUuids:ids});}catch(error){ui.notifications.error('Life Ward long-rest expiry needs manual review: '+error.message);}return result;};Object.defineProperty(Downtime,REST,{value:true});}
export function installLifeWardRefresh(actions,send){const native=actions?.refreshActors;if(typeof native!=='function'||native[REFRESH])return;const refresh=async function(...args){const snapshots=game.user.isGM&&this.refreshSelections?.longRest?.selected?[...game.actors].filter(a=>a.type==='character'&&a.prototypeToken?.actorLink).map(a=>({op:'clear',id:foundry.utils.randomID(),actorUuid:a.uuid,effectUuids:lifeWardEffects(a.uuid).map(e=>e.uuid)})).filter(r=>r.effectUuids.length):[],result=await native.apply(this,args);for(const request of snapshots)try{await send(request);}catch(error){ui.notifications.error('Life Ward long-rest refresh needs manual review: '+error.message);}return result;};Object.defineProperty(refresh,REFRESH,{value:true});actions.refreshActors=refresh;}
export function installLifeWardDeathMove(Dialog,send){if(!Dialog||Object.hasOwn(Dialog,DEATH))return;const render=Dialog.prototype.render;Dialog.prototype.render=async function(...args){const ward=this.actor?.effects?.some(e=>active(e)&&record(e)?.phase==='ready');if(ward&&this.actor.system.deathMoveViable===true){if(await send({op:'save',id:foundry.utils.randomID(),actorUuid:this.actor.uuid}))return this;}return render.apply(this,args);};Object.defineProperty(Dialog,DEATH,{value:true});}
export function registerLifeWard(){CONFIG.queries[QUERY]=resolveLifeWard;const send=r=>{const gm=game.users.activeGM;if(!gm)throw Error('Life Ward needs an active GM.');return gm.isSelf?resolveLifeWard(r,{user:game.user}):gm.query(QUERY,r,{timeout:300000});};installLifeWardCast(game.system.api.data.actions.actionsTypes.base,send);installLifeWardDamage(CONFIG.Actor.documentClass,send);installLifeWardRest(game.system.api.applications.dialogs.Downtime,send);installLifeWardDeathMove(game.system.api.applications.dialogs.DeathMove,send);installLifeWardRefresh(CONFIG.ui.daggerheartMenu?.DEFAULT_OPTIONS?.actions,send);installLifeWardRefresh(ui.daggerheartMenu?.options?.actions,send);Hooks.on('renderDaggerheartMenu',app=>installLifeWardRefresh(app.options.actions,send));
 const save=actor=>{if(game.user.isActiveGM&&!damaging.has(actor)&&!saving.has(actor?.uuid)&&actor?.system.deathMoveViable===true)void saveWithLifeWard(actor).catch(error=>ui.notifications.error('Life Ward recovery needs manual review: '+error.message));};
 Hooks.on('updateActor',(actor,changes)=>{if(changes.system?.resources?.hitPoints||Object.hasOwn(changes,'system.resources.hitPoints.value')||Object.hasOwn(changes,'system.resources.hitPoints.max'))save(actor);});Hooks.on('createActiveEffect',effect=>{if(record(effect))save(effect.parent);});
 Hooks.on('preCreateActiveEffect',(effect,data)=>{if(effect.parent?.documentName==='Actor'&&data.flags?.[ID]?.lifeWardTemplate&&!gen(data.flags[ID].lifeWard?.generation)){ui.notifications.info('Cast Life Ward using Mark with Sigil on its card.');return false;}});
}
