import {ID,featureActive} from '../core.js';
import {decisionBudget} from '../settings.js';
import {timedDialog} from '../dialog.js';
import {ownerFor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {LUNAR_PHASES_KEY,LUNAR_ADVANCE_ACTION,LUNAR_NEW,LUNAR_WAXING,LUNAR_FULL,LUNAR_WANING} from './lunar-phases-data.js';
const APPLY=`${ID}.lunarPhasesApply`,PROMPT=`${ID}.lunarPhasesPrompt`,ADVANCE=`${ID}.lunarPhasesAdvance`,WRAPPED=Symbol.for(`${ID}.lunarPhasesRefresh`),refreshRuns=new WeakMap();
const phases={1:{name:'New Moon',effectId:LUNAR_NEW},2:{name:'Waxing Moon',effectId:LUNAR_WAXING},3:{name:'Waxing Moon',effectId:LUNAR_WAXING},4:{name:'Full Moon',effectId:LUNAR_FULL},5:{name:'Waning Moon',effectId:LUNAR_WANING},6:{name:'Waning Moon',effectId:LUNAR_WANING}};
export function lunarPhasesItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===LUNAR_PHASES_KEY;})??null:null;}
export const lunarPhase=value=>phases[Number(value)]??null;
const actionFor=item=>item?.system.actions?.get?.(LUNAR_ADVANCE_ACTION)??item?.system.actions?.[LUNAR_ADVANCE_ACTION];
export async function setLunarPhase(item,value){const phase=lunarPhase(value);if(!phase||lunarPhasesItem(item?.actor)?.uuid!==item.uuid)return false;await item.update({'system.resource.value':Number(value)});await item.updateEmbeddedDocuments('ActiveEffect',[LUNAR_NEW,LUNAR_WAXING,LUNAR_FULL,LUNAR_WANING].map(_id=>({_id,disabled:_id!==phase.effectId})));return phase;}
export async function promptLunarRoll(data,{user}){const item=await fromUuid(data.itemUuid),actor=item?.actor;if(!user?.active||!actor?.testUserPermission(user,'OWNER')||lunarPhasesItem(actor)?.uuid!==item.uuid)return false;return Boolean(await timedDialog(`Lunar Phases — ${actor.name}`,'<p>Roll the <strong>d6 Lunar Die</strong> for this session?</p>',[{action:'roll',label:'Roll d6',callback:()=>true},{action:'cancel',label:'Not Now',default:true,callback:()=>false}]));}
export async function applyLunarRoll(request,{user},rollDie=async()=>new Roll('1d6').evaluate()){if(!game.user.isActiveGM||!user?.active)return false;const item=await fromUuid(request.itemUuid),actor=item?.actor;if(!actor?.testUserPermission(user,'OWNER')||lunarPhasesItem(actor)?.uuid!==item.uuid)return false;const roll=await rollDie(),value=Number(roll.total),phase=await setLunarPhase(item,value);if(!phase)return false;const message=await roll.toMessage({speaker:ChatMessage.getSpeaker({actor}),flavor:`<strong>Lunar Phases:</strong> ${phase.name}`});if(message&&game.dice3d)await game.dice3d.waitFor3DAnimationByMessageID(message.id);return{value,name:phase.name};}
export async function promptSessionLunar(){if(!game.user.isGM)return;const jobs=[];for(const actor of game.actors){const item=lunarPhasesItem(actor);if(!item||!actor.prototypeToken.actorLink)continue;const owner=ownerFor(actor,[...game.users],game.user),data={itemUuid:item.uuid},accepted=owner.isSelf?await promptLunarRoll(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});if(!accepted)continue;const gm=game.users.activeGM;const request={itemUuid:item.uuid};jobs.push(gm.isSelf?applyLunarRoll(request,{user:owner}):gm.query(APPLY,request,{timeout:decisionBudget(65000)}));}const results=await Promise.allSettled(jobs);for(const result of results)if(result.status==='rejected'){console.error(`${ID} | Lunar Phases refresh`,result.reason);ui.notifications.error('A Lunar Phases roll could not be completed.');}}
export async function promptRefreshedLunar(item){const actor=item?.actor;if(!game.user.isActiveGM||lunarPhasesItem(actor)?.uuid!==item.uuid)return false;const owner=ownerFor(actor,[...game.users],game.user),data={itemUuid:item.uuid},accepted=owner.isSelf?await promptLunarRoll(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});if(!accepted)return false;return applyLunarRoll(data,{user:owner});}
export function lunarSessionResourceReset(item,changes){const value=changes?.system?.resource?.value??changes?.system?.['resource.value'];return lunarPhasesItem(item?.actor)?.uuid===item.uuid&&item.system?.resource?.recovery==='session'&&Number(value)===0;}
export function installLunarRefresh(actions,refresh=promptSessionLunar){const native=actions?.refreshActors;if(typeof native!=='function'||native[WRAPPED])return;const wrapped=async function(...args){const running=refreshRuns.get(this);if(running)return running.entering?native.apply(this,args):running.promise;const session=game.user.isGM&&this.refreshSelections?.session?.selected,state={entering:false,promise:null};refreshRuns.set(this,state);state.promise=Promise.resolve().then(async()=>{state.entering=true;let result;try{result=native.apply(this,args);}finally{state.entering=false;}result=await result;if(session)await refresh();return result;});try{return await state.promise;}finally{if(refreshRuns.get(this)===state)refreshRuns.delete(this);}};Object.defineProperty(wrapped,WRAPPED,{value:true});actions.refreshActors=wrapped;}
export async function advanceLunarPhase(request,{user}){if(!game.user.isActiveGM||!user?.active)return false;return withHopeLock(request.actorUuid,async()=>{const actor=await fromUuid(request.actorUuid),item=lunarPhasesItem(actor),action=actionFor(item),hope=Number(actor?.system.resources?.hope?.value),value=Number(item?.system.resource?.value);if(!actor?.testUserPermission(user,'OWNER')||!item||!Number.isInteger(value)||value<1||value>6||hope<1||Number(action?.uses.value??0)>=1)return false;await actor.update({'system.resources.hope.value':hope-1});try{await item.update({[`system.actions.${LUNAR_ADVANCE_ACTION}.uses.value`]:1});const next=value===6?1:value+1,phase=await setLunarPhase(item,next);await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Lunar Phases:</strong> ${actor.name} spends 1 Hope and advances to ${phase.name} (${next}).</p>`});return{value:next,name:phase.name};}catch(error){await actor.update({'system.resources.hope.value':hope});await item.update({[`system.actions.${LUNAR_ADVANCE_ACTION}.uses.value`]:0});throw error;}});}
export function registerLunarPhases(){CONFIG.queries[APPLY]=applyLunarRoll;CONFIG.queries[PROMPT]=promptLunarRoll;CONFIG.queries[ADVANCE]=advanceLunarPhase;Hooks.on('updateItem',(item,changes)=>{if(!game.user.isActiveGM||!lunarSessionResourceReset(item,changes))return;void promptRefreshedLunar(item).catch(error=>{console.error(`${ID} | Lunar Phases refresh`,error);ui.notifications.error(`Lunar Phases: ${error.message}`);});});Hooks.on('daggerheart.preUseAction',action=>{if(action.id!==LUNAR_ADVANCE_ACTION||lunarPhasesItem(action.actor)?.uuid!==action.item?.uuid)return;const gm=game.users.activeGM;if(!gm){ui.notifications.error('Lunar Phases needs an active GM.');return false;}const request={actorUuid:action.actor.uuid};void (gm.isSelf?advanceLunarPhase(request,{user:game.user}):gm.query(ADVANCE,request,{timeout:15000})).then(result=>{if(!result)ui.notifications.warn('Lunar Phases cannot advance right now.');}).catch(error=>ui.notifications.error(error.message));return false;});}
