import {ID,featureActive} from '../core.js';import {timedDialog} from '../dialog.js';import {markReactiveStress} from './stress-payment.js';import {animateInitialDamage} from './combo-strike.js';import {MANIPULATE_KEY} from './manipulate-magic-data.js';
const deferred=new Map();
export function manipulateItem(actor){const s=actor?.system?.resources?.stress;if(!(Number(s?.value)<Number(s?.max)))return null;return actor.items?.find(i=>{const f=i.flags?.[ID];return featureActive(i)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===MANIPULATE_KEY;})??null;}
export function magicalAction(a){const i=a?.item??a?.parent,spell=i?.type==='domainCard'&&['spell','grimoire'].includes(i.system?.type),types=a?.damage?.main?.damageTypes??a?.damage?.main?.types??a?.damage?.main?.type??[];return Boolean(spell||(i?.type==='weapon'&&a?.type==='attack'&&[...types].includes('magical')));}
function eligible(config){const actor=config.data?.parent??foundry.utils.fromUuidSync?.(config.source?.actor),item=actor?.items?.get?.(config.source?.item),action=item?.system?.actions?.get?.(config.source?.action)??item?.system?.attack;return manipulateItem(actor)&&magicalAction(action)?actor:null;}
export async function promptResult(actor,total){return Boolean(await timedDialog(`Manipulate Magic — ${actor.name}`,`<p>Action result: <strong>${Number(total)}</strong>.</p><p>Mark <strong>1 Stress</strong> to add +2?</p>`,[{action:'result',label:'Mark Stress: +2',callback:()=>true},{action:'decline',label:'Decline',default:true,callback:()=>false}]));}
export function damageDice(r){return(r?.dice??[]).flatMap((d,di)=>d.results?.flatMap((x,ri)=>x.active===false?[]:[{id:`${di}:${ri}`,faces:Number(d.faces),value:Number(x.result)}])??[]);}
export async function promptDouble(r){const dice=damageDice(r);return dice.length?timedDialog('Manipulate Magic — Double Damage Die',`<p>Mark 1 Stress and choose a die.</p>${dice.map(d=>`<label><input type="radio" name="mmDie" value="${d.id}"> d${d.faces}: ${d.value}</label>`).join(' ')}`,[{action:'use',label:'Mark Stress & Double',callback:(_e,_b,x)=>x.element.querySelector('[name="mmDie"]:checked')?.value??null},{action:'decline',label:'Decline',default:true,callback:()=>null}]):null;}
export function doubleDamageDie(r,id){const d=damageDice(r).find(x=>x.id===id);if(!d)return false;r._total=Number(r.total)+d.value;r.resetFormula?.();r.options[ID]={...r.options[ID],manipulateMagic:{mode:'damage',die:d}};return true;}
export function addResultBonus(r,c){const total=Number(r.total)+2;r._total=total;r.resetFormula?.();c.roll={...c.roll,total};for(const t of c.targets??[]){const n=t.difficulty||t.evasion;t.hit=Boolean(n!=null&&(r.isCritical||total>=n));t.hitResult={...t.hitResult,success:t.hit};}r.options[ID]={...r.options[ID],manipulateMagic:{mode:'result'}};}
export function explicitSuccess(r,c){const targets=c?.targets??[],hit=t=>t.hit===true||t.hitResult?.success===true;return Boolean(r?.isCritical||(targets.length?targets.every(hit):c?.roll?.success===true));}
const pay=a=>markReactiveStress(a.uuid,x=>Boolean(manipulateItem(x)));
export function manualEffects(actor){return [...(actor?.effects??[])].filter(e=>!e.disabled&&!e.isSuppressed&&e.flags?.[ID]?.manipulateManual);}
export function installManipulateRoll(R,ask=promptResult,spend=pay){const k=Symbol.for(`${ID}.manipulateRoll`);if(R[k])return;const n=R.buildPost;R.buildPost=async function(r,c,...a){const out=await n.call(this,r,c,...a),actor=c.actionType==='action'?eligible(c):null;if(!actor)return out;const manual=manualEffects(actor);if(manual.length){await actor.deleteEmbeddedDocuments('ActiveEffect',manual.map(e=>e.id));return out;}if(explicitSuccess(r,c)){deferred.set(actor.uuid,true);return out;}if(await ask(actor,r.total)){if(await spend(actor)){addResultBonus(r,c);if(c.message)await c.message.update({rolls:[r.toJSON()],'system.targets':c.targets});}}else deferred.set(actor.uuid,true);return out;};Object.defineProperty(R,k,{value:true});}
export function installManipulateDamage(D,ask=promptDouble,spend=pay,animate=async c=>{const message=game.messages.get(c.source?.message);if(message)await animateInitialDamage(c,message);}){const k=Symbol.for(`${ID}.manipulateDamage`);if(D[k])return;const n=D.buildEvaluate;D.buildEvaluate=async function(r,c,...a){const actor=c.hasHealing?null:eligible(c),out=await n.call(this,r,c,...a);if(!actor||!deferred.delete(actor.uuid))return out;await animate(c);const main=c.damage?.main??r,choice=await ask(main);if(choice&&await spend(actor))doubleDamageDie(main,choice);return out;};Object.defineProperty(D,k,{value:true});}
export function registerManipulateMagic(){installManipulateRoll(CONFIG.Dice.daggerheart.DualityRoll);installManipulateDamage(CONFIG.Dice.daggerheart.DamageRoll);}
