import {ID,featureActive} from '../core.js';
import {overwhelmHits} from './overwhelm.js';
import {MENACING_KEY,MENACING_ACTION,MENACING_EFFECT} from './menacing-reach-data.js';
const QUERY=`${ID}.menacingReach`,RANGES=['melee','veryClose','close','far','veryFar'];
export function menacingItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===MENACING_KEY;})??null:null;}
export function primaryWeapon(actor){return actor?.system?.primaryWeapon??actor?.items?.find?.(item=>item.type==='weapon'&&item.system?.equipped&&!item.system?.secondary)??null;}
export function extendedRange(range){const index=RANGES.indexOf(range);return index<0?null:RANGES[Math.min(index+1,RANGES.length-1)];}
export function menacingEffects(actor){const item=menacingItem(actor),origin=item?.effects?.get?.(MENACING_EFFECT)?.uuid;return item?[...(actor.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&(effect.flags?.[ID]?.menacingReach||origin&&effect.origin===origin)):[];}
export function reachForAttack(action){const effect=menacingEffects(action?.actor).find(current=>current.flags?.[ID]?.menacingReach?.weaponUuid===action.item?.uuid),data=effect?.flags?.[ID]?.menacingReach;return action?.type==='attack'&&data&&data.range===extendedRange(data.baseRange)?{effect,data}:null;}
export async function bindMenacingEffect(effect){const actor=effect?.parent,item=menacingItem(actor),weapon=primaryWeapon(actor),baseRange=weapon?.system?.attack?.range,range=extendedRange(baseRange);if(!item||!weapon||!range||range===baseRange)return false;const origins=new Set([item.uuid,item.effects?.get?.(MENACING_EFFECT)?.uuid].filter(Boolean));if(!effect.flags?.[ID]?.menacingReach&&!origins.has(effect.origin))return false;await effect.update({[`flags.${ID}.menacingReach`]:{weaponUuid:weapon.uuid,weaponName:weapon.name,baseRange,range}});const updated=await weapon.update({'system.attack.range':range});if(!updated||weapon.system.attack.range!==range)throw Error(`Could not extend ${weapon.name}'s range.`);return true;}
export async function restoreMenacingWeapon(effect){const data=effect?.flags?.[ID]?.menacingReach;if(!data?.weaponUuid||!data.baseRange||!data.range)return false;const weapon=await fromUuid(data.weaponUuid);if(weapon?.actor?.uuid!==effect.parent?.uuid||weapon.system?.attack?.range!==data.range)return false;const updated=await weapon.update({'system.attack.range':data.baseRange});if(!updated||weapon.system.attack.range!==data.baseRange)throw Error(`Could not restore ${weapon.name}'s range.`);return true;}
export async function syncMenacingWeapons(){const actors=new Map;for(const actor of game.actors??[])actors.set(actor.uuid,actor);for(const token of globalThis.canvas?.tokens?.placeables??[])if(token.actor)actors.set(token.actor.uuid,token.actor);for(const actor of actors.values())for(const effect of menacingEffects(actor)){const data=effect.flags?.[ID]?.menacingReach;if(data?.weaponUuid){const weapon=await fromUuid(data.weaponUuid);if(weapon?.actor?.uuid===actor.uuid&&weapon.system?.attack?.range===data.baseRange)await weapon.update({'system.attack.range':data.range});}else await bindMenacingEffect(effect);}}
export async function expireMenacing(request,{user}){if(!game.user.isActiveGM||!user?.active||!request.success)return false;const actor=await fromUuid(request.actorUuid),effect=menacingEffects(actor).find(current=>current.id===request.effectId),data=effect?.flags?.[ID]?.menacingReach;if(!actor?.testUserPermission(user,'OWNER')||!effect||data?.weaponUuid!==request.weaponUuid)return false;const message=request.messageUuid?await fromUuid(request.messageUuid):null;if(message&&(message.system?.action?.actor?.uuid!==actor.uuid||!overwhelmHits(message).length))return false;await restoreMenacingWeapon(effect);await actor.deleteEmbeddedDocuments('ActiveEffect',[effect.id]);if(message)await message.setFlag(ID,'menacingReach',{weaponName:data.weaponName,baseRange:data.baseRange,range:data.range,expired:true});return true;}
export function installMenacingTarget(Target,send){const native=Target.execute;Target.execute=async function(config,...args){const reach=reachForAttack(this),result=await native.call(this,config,...args);if(!reach||result===false)return result;const success=Boolean(config.roll?.isCritical||(config.targets??[]).some(target=>target.hitResult?.success)),note={weaponName:reach.data.weaponName,baseRange:reach.data.baseRange,range:reach.data.range,expired:false};if(success)await send({actorUuid:this.actor.uuid,weaponUuid:this.item.uuid,effectId:reach.effect.id,messageUuid:config.message?.uuid,success:true});else await config.message?.setFlag(ID,'menacingReach',note);return result;};}
export function registerMenacingWeaponRestore(){void syncMenacingWeapons().catch(error=>ui.notifications.error(error.message));Hooks.on('canvasReady',()=>void syncMenacingWeapons().catch(error=>ui.notifications.error(error.message)));Hooks.on('deleteActiveEffect',effect=>{if(effect.flags?.[ID]?.menacingReach&&effect.parent?.documentName==='Actor')void restoreMenacingWeapon(effect).catch(error=>ui.notifications.error(error.message));});}
export function registerMenacingReach(){CONFIG.queries[QUERY]=expireMenacing;const send=request=>{const gm=game.users.activeGM;if(!gm)throw Error('Menacing Reach needs an active GM to expire.');return gm.isSelf?expireMenacing(request,{user:game.user}):gm.query(QUERY,request,{timeout:15000});};installMenacingTarget(game.system.api.fields.ActionFields.TargetField,send);Hooks.on('daggerheart.preUseAction',action=>{if(action.id!==MENACING_ACTION||menacingItem(action.actor)?.uuid!==action.item?.uuid)return;const weapon=primaryWeapon(action.actor),range=weapon?.system?.attack?.range;if(!weapon||!extendedRange(range)||extendedRange(range)===range){ui.notifications.warn('Menacing Reach requires a primary weapon below Very Far range.');return false;}if(menacingEffects(action.actor).length){ui.notifications.warn('Menacing Reach is already active.');return false;}});Hooks.on('createActiveEffect',effect=>{if(effect.flags?.[ID]?.menacingReach||effect.origin===menacingItem(effect.parent)?.effects?.get?.(MENACING_EFFECT)?.uuid)void bindMenacingEffect(effect).catch(error=>ui.notifications.error(error.message));});Hooks.on('renderChatMessageHTML',(message,html)=>{const data=message.flags?.[ID]?.menacingReach;if(!message.isContentVisible||!data||html.querySelector('.dhp-menacing-reach'))return;const label=range=>game.i18n.localize(`DAGGERHEART.CONFIG.Range.${range}.name`),note=html.ownerDocument.createElement('p');note.className='dhp-menacing-reach';note.textContent=`Menacing Reach: ${data.weaponName} extended from ${label(data.baseRange)} to ${label(data.range)}${data.expired?'; successful attack cleared the effect':'; effect remains active'}.`;html.querySelector('.message-content')?.append(note);});}
