import {ID,featureActive} from '../core.js';
import {sourceToken} from './hallowed-aura.js';
import {closeDistance} from './aura-rules.js';
import {MOONBEAM_KEY,MOONBEAM_ACTION,MOONBEAM_EFFECT} from './moonbeam-data.js';
const ACTIVATE=`${ID}.moonbeamActivate`,WRAPPED=Symbol.for(`${ID}.moonbeamRefresh`);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rawMoonbeam=item=>{const f=item?.flags?.[ID];return (f?.applied?.key??f?.premade?.key)===MOONBEAM_KEY;};
const actionFor=item=>item?.system.actions?.get?.(MOONBEAM_ACTION)??item?.system.actions?.[MOONBEAM_ACTION];
export function moonbeamItem(actor){return actor?.type==='character'?actor.items?.find(item=>featureActive(item)&&!item.flags?.[ID]?.disabled&&rawMoonbeam(item))??null:null;}
export const moonbeamState=item=>item?.flags?.[ID]?.moonbeam??null;
function sceneActors(scene){return[...new Map((scene?.tokens??[]).filter(token=>token.actor?.uuid).map(token=>[token.actor.uuid,token.actor])).values()];}
function closeLimit(){const ranges=game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement;return closeDistance(canvas.scene,ranges,CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id);}
export function moonbeamEffectUuids(scene=canvas.scene){const uuids=new Set();for(const actor of sceneActors(scene))for(const item of actor.items??[]){if(!rawMoonbeam(item))continue;const effect=item.effects?.get?.(MOONBEAM_EFFECT)??item.effects?.find?.(entry=>(entry.id??entry._id)===MOONBEAM_EFFECT);if(effect?.uuid)uuids.add(effect.uuid);}return uuids;}
function behaviorEffects(region){const values=[];for(const behavior of region?.behaviors??[]){const effects=behavior.system?.effects;if(typeof effects?.values==='function')values.push(...effects.values());else if(Array.isArray(effects))values.push(...effects);}return values;}
export function moonbeamRegions(scene=canvas.scene,effectUuids=moonbeamEffectUuids(scene)){return[...(scene?.regions??[])].filter(region=>region.flags?.[ID]?.moonbeam||behaviorEffects(region).some(uuid=>effectUuids.has(uuid)));}
export function moonbeamLights(scene=canvas.scene){return[...(scene?.lights??[])].filter(light=>light.flags?.[ID]?.moonbeam);}
async function clearEffects(scene,origins){for(const actor of sceneActors(scene)){const ids=[...(actor.effects??[])].filter(effect=>origins.has(effect.origin)).map(effect=>effect.id);if(ids.length)await actor.deleteEmbeddedDocuments('ActiveEffect',ids);}}
export async function endMoonbeam(item,{announce=false}={}){const state=moonbeamState(item),scene=state?.sceneId?game.scenes.get?.(state.sceneId)??canvas.scene:canvas.scene;if(!item||!state||!scene)return false;await item.update({[`flags.${ID}.-=moonbeam`]:null});const region=state.regionUuid?await fromUuid(state.regionUuid):null,light=state.lightUuid?await fromUuid(state.lightUuid):null;if(region?.documentName==='Region')await region.delete();if(light?.documentName==='AmbientLight')await light.delete();const origin=item.effects?.get?.(MOONBEAM_EFFECT)?.uuid;if(origin)await clearEffects(scene,new Set([origin]));if(announce)await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:item.actor}),content:`<p><strong>Moonbeam:</strong> ${esc(item.actor.name)}’s moonlight fades.</p>`});return true;}
export async function clearMoonbeam(scene=canvas.scene){if(!game.user.isActiveGM||!scene)return 0;const origins=moonbeamEffectUuids(scene),regions=moonbeamRegions(scene,origins),lights=moonbeamLights(scene),items=[];for(const actor of sceneActors(scene))for(const item of actor.items??[])if(rawMoonbeam(item)&&moonbeamState(item)?.sceneId===scene.id)items.push(item);for(const item of items)await item.update({[`flags.${ID}.-=moonbeam`]:null});if(regions.length)await scene.deleteEmbeddedDocuments('Region',regions.map(region=>region.id));if(lights.length)await scene.deleteEmbeddedDocuments('AmbientLight',lights.map(light=>light.id));await clearEffects(scene,origins);return regions.length;}
function regionData(item,token,effectUuid){const shape=CONFIG.Canvas.layers.regions.layerClass.getTemplateShape({shapeType:CONFIG.DH.GENERAL.templateTypes.circle.id,range:closeLimit(),hasHole:false});shape.x=token.center.x;shape.y=token.center.y;return{name:`Moonbeam — ${item.actor.name}`,shapes:[shape],restriction:{enabled:false,type:'move',priority:0},behaviors:[{name:'Moonbeam',type:'applyActiveEffect',system:{effects:[effectUuid]}}],displayMeasurements:true,locked:false,ownership:{default:CONST.DOCUMENT_OWNERSHIP_LEVELS.NONE},visibility:CONST.REGION_VISIBILITY.ALWAYS,flags:{[ID]:{moonbeam:{itemUuid:item.uuid}}}};}
function lightData(item,token){return{name:`Moonbeam — ${item.actor.name}`,x:Math.round(token.center.x),y:Math.round(token.center.y),elevation:token.document.elevation??0,walls:false,vision:false,hidden:false,locked:true,config:{negative:false,priority:0,alpha:0.35,angle:360,bright:closeLimit(),dim:0,color:'#c9eaff',coloration:1,contrast:0.1,attenuation:0.35,luminosity:0.65,saturation:-0.15,shadows:0,animation:{type:'pulse',speed:2,intensity:2,reverse:false},darkness:{min:0,max:1}},flags:{[ID]:{moonbeam:{itemUuid:item.uuid}}}};}
export async function activateMoonbeam(request,{user}){if(!game.user.isActiveGM||!user?.active)return false;const actor=await fromUuid(request.actorUuid),item=moonbeamItem(actor),action=actionFor(item),token=sourceToken(actor),effect=item?.effects?.get?.(MOONBEAM_EFFECT);if(!actor?.testUserPermission(user,'OWNER')||!item||!token||!effect?.uuid||Number(action?.uses.value??0)>=1||moonbeamState(item))return false;let region,light;try{[region]=await canvas.scene.createEmbeddedDocuments('Region',[regionData(item,token,effect.uuid)]);if(!region)throw Error('Could not create the Moonbeam Region.');[light]=await canvas.scene.createEmbeddedDocuments('AmbientLight',[lightData(item,token)]);if(!light)throw Error('Could not create the Moonbeam light.');const state={sceneId:canvas.scene.id,regionUuid:region.uuid,lightUuid:light.uuid};const updated=await item.update({[`system.actions.${MOONBEAM_ACTION}.uses.value`]:1,[`flags.${ID}.moonbeam`]:state});if(!updated||Number(actionFor(item)?.uses.value)!==1||moonbeamState(item)?.regionUuid!==region.uuid)throw Error('Could not spend the Moonbeam use.');}catch(error){if(light)await light.delete();if(region)await region.delete();throw error;}await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Moonbeam:</strong> ${esc(actor.name)} conjures a circle of moonlight within Close range.</p>`});return true;}
export function installMoonbeamRefresh(actions,clear=clearMoonbeam){const native=actions?.refreshActors;if(typeof native!=='function'||native[WRAPPED])return;const wrapped=async function(...args){const scene=game.user.isGM&&this.refreshSelections?.scene?.selected,result=await native.apply(this,args);if(scene)await clear();return result;};Object.defineProperty(wrapped,WRAPPED,{value:true});actions.refreshActors=wrapped;}
export function registerMoonbeam(){CONFIG.queries[ACTIVATE]=activateMoonbeam;const Action=game.system.api.data.actions.actionsTypes.base,native=Action.prototype.use;Action.prototype.use=async function(...args){if(this.id!==MOONBEAM_ACTION||moonbeamItem(this.actor)?.uuid!==this.item?.uuid)return native.apply(this,args);const gm=game.users.activeGM;if(!gm)throw Error('Moonbeam needs an active GM.');return gm.isSelf?activateMoonbeam({actorUuid:this.actor.uuid},{user:game.user}):gm.query(ACTIVATE,{actorUuid:this.actor.uuid},{timeout:15000});};const install=()=>{installMoonbeamRefresh(CONFIG.ui.daggerheartMenu?.DEFAULT_OPTIONS?.actions);installMoonbeamRefresh(ui.daggerheartMenu?.options?.actions);};install();Hooks.on('renderDaggerheartMenu',app=>installMoonbeamRefresh(app.options.actions));const cleanup=document=>{const itemUuid=document.flags?.[ID]?.moonbeam?.itemUuid;if(!game.user.isActiveGM||!itemUuid)return;void fromUuid(itemUuid).then(item=>moonbeamState(item)&&endMoonbeam(item)).catch(error=>ui.notifications.error(`Moonbeam: ${error.message}`));};Hooks.on('deleteRegion',cleanup);Hooks.on('deleteAmbientLight',cleanup);}
