import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {ownerFor,closeDistance} from './aura-rules.js';
import {sourceToken} from './hallowed-aura.js';
import {markReactiveStress} from './stress-payment.js';
import {NIGHTS_GLAMOUR_KEY,NIGHTS_GLAMOUR_EFFECT} from './nights-glamour-data.js';
const ATTACK=`${ID}.nightsGlamourAttack`,MAINTAIN=`${ID}.nightsGlamourMaintain`,PROMPT=`${ID}.nightsGlamourPrompt`,HP_BEFORE=`${ID}.nightsGlamourHPBefore`,receipts=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function nightsGlamourItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const f=item.flags?.[ID];return featureActive(item)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===NIGHTS_GLAMOUR_KEY;})??null:null;}
export function glamourEffect(actor){const item=nightsGlamourItem(actor),origin=item?.effects?.get?.(NIGHTS_GLAMOUR_EFFECT)?.uuid??item?.effects?.find?.(e=>(e.id??e._id)===NIGHTS_GLAMOUR_EFFECT)?.uuid;return origin?actor.effects?.find(effect=>effect.origin===origin&&!effect.disabled&&!effect.isSuppressed)??null:null;}
function sourceAction(actor,source){const item=actor?.items?.get?.(source?.item),attack=actor?.system?.attack;if(source?.action&&(attack?.id??attack?._id)===source.action)return attack;return item?.system.actions?.get?.(source?.action)??item?.system.actionsList?.find?.(action=>action.id===source?.action);}
function closeLimit(){const rules=game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement;return closeDistance(canvas.scene,rules,CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id);}
export function glamourAttackTargets(actor,source,targetUuids){if(actor?.type!=='adversary'||sourceAction(actor,source)?.type!=='attack')return[];const attacker=sourceToken(actor),limit=closeLimit();if(!attacker||!Number.isFinite(limit))return[];return [...new Set(targetUuids??[])].map(uuid=>foundry.utils.fromUuidSync(uuid)).filter(target=>{const token=sourceToken(target),distance=token&&attacker.distanceTo(token);return glamourEffect(target)&&Number.isFinite(distance)&&distance<=limit;});}
export async function resolveGlamourAttack(request,{user}){if(!game.user.isActiveGM||!user?.active)return false;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER')||!glamourAttackTargets(actor,request.source,request.targetUuids).length)return false;await actor.modifyResource([{key:'stress',value:1}]);await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Night’s Glamour:</strong> ${esc(actor.name)} marks 1 Stress to attack the Glamoured Witch.</p>`});return true;}
export async function promptMaintainGlamour(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!glamourEffect(actor))return false;const trigger=data.mode==='hp'?'marked a Hit Point':'dealt damage';return Boolean(await timedDialog(`Night’s Glamour — ${actor.name}`,`<p>${esc(actor.name)} ${trigger}.</p><p>Mark <strong>1 Stress</strong> to maintain your Glamour?</p>`,[{action:'maintain',label:'Mark Stress & Maintain',callback:()=>true},{action:'drop',label:'Drop Glamour',default:true,callback:()=>false}]));}
export async function resolveMaintainGlamour(request,{user},ask=promptMaintainGlamour,pay=markReactiveStress){if(!game.user.isActiveGM||!user?.active||!['hp','damage'].includes(request.mode)||typeof request.id!=='string'||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000))return false;for(const[id,entry]of receipts)if(entry.expires<decisionNow())receipts.delete(id);if(receipts.has(request.id))return receipts.get(request.id).promise;const promise=(async()=>{const actor=await fromUuid(request.actorUuid),effect=glamourEffect(actor);if(!effect||!actor.testUserPermission(user,'OWNER'))return false;const owner=ownerFor(actor,[...game.users],game.user),accepted=owner.isSelf?await ask({actorUuid:actor.uuid,mode:request.mode},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,mode:request.mode},{timeout:decisionBudget(65000)});if(accepted&&request.deadline>=decisionNow()&&await pay(actor.uuid,a=>Boolean(glamourEffect(a)))){await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Night’s Glamour:</strong> ${esc(actor.name)} marks 1 Stress and maintains the Glamour.</p>`});return true;}const current=glamourEffect(actor);if(current)await current.delete();await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Night’s Glamour:</strong> ${esc(actor.name)}’s Glamour drops.</p>`});return false;})();receipts.set(request.id,{promise,expires:decisionNow()+decisionBudget(300000)});return promise;}
export const dealtDamage=updates=>(updates??[]).some(update=>['hitPoints','stress'].includes(update.key)&&!update.clear&&!update.itemId&&Number(update.value)>0);
export function markedHP(change,before){const value=change?.['system.resources.hitPoints.value']??change?.system?.resources?.hitPoints?.value;return Number.isFinite(before)&&Number(value)>before;}
export function installGlamourAttack(D20,offer){const native=D20.buildEvaluate;D20.buildEvaluate=async function(roll,config,...args){const actor=config.data?.parent??(config.source?.actor?await fromUuid(config.source.actor):null),targets=(config.targets??[]).map(target=>target.actorId).filter(Boolean);if(actor&&!config[ID]?.nightsGlamourAttack&&glamourAttackTargets(actor,config.source,targets).length){config[ID]={...config[ID],nightsGlamourAttack:true};await offer({actorUuid:actor.uuid,source:config.source,targetUuids:targets});}return native.call(this,roll,config,...args);};}
export function installGlamourDamageRoll(Damage){const native=Damage.buildEvaluate;Damage.buildEvaluate=async function(roll,config,...args){const result=await native.call(this,roll,config,...args),actor=game.messages.get(config.source?.message)?.system?.action?.actor??config.data?.parent;if(glamourEffect(actor)&&!config.hasHealing&&config.damage?.main){config.damage.main.options[ID]={...config.damage.main.options[ID],nightsGlamour:{actorUuid:actor.uuid,id:foundry.utils.randomID()}};if(typeof config.damage.toObject==='function')config.damage=new config.damage.constructor({...config.damage.toObject(),main:config.damage.main.toJSON(),resources:Object.fromEntries(Object.entries(config.damage.resources??{}).map(([key,value])=>[key,value.toJSON()]))});}return result;};}
export function installGlamourDamage(Actor,offer){const native=Actor.prototype.takeDamage;Actor.prototype.takeDamage=async function(packet,...args){const result=await native.call(this,packet,...args),source=packet?.main?.options?.[ID]?.nightsGlamour;if(source&&dealtDamage(result))await offer({actorUuid:source.actorUuid,mode:'damage',id:source.id});return result;};}
async function dispatch(name,request){const gm=game.users.activeGM;if(!gm)throw Error("Night's Glamour needs an active GM.");return gm.isSelf?CONFIG.queries[name](request,{user:game.user}):gm.query(name,request,{timeout:decisionBudget(125000)});}
export function registerNightsGlamour(){CONFIG.queries[ATTACK]=resolveGlamourAttack;CONFIG.queries[MAINTAIN]=resolveMaintainGlamour;CONFIG.queries[PROMPT]=promptMaintainGlamour;installGlamourAttack(CONFIG.Dice.daggerheart.D20Roll,request=>dispatch(ATTACK,request));installGlamourDamageRoll(CONFIG.Dice.daggerheart.DamageRoll);installGlamourDamage(CONFIG.Actor.documentClass,request=>dispatch(MAINTAIN,{...request,deadline:decisionNow()+decisionBudget(120000)}));Hooks.on('preUpdateActor',(actor,change,options)=>{const value=change['system.resources.hitPoints.value']??change.system?.resources?.hitPoints?.value;if(glamourEffect(actor)&&value!==undefined)options[HP_BEFORE]=Number(actor.system.resources.hitPoints.value);});Hooks.on('updateActor',(actor,change,options)=>{if(!game.user.isActiveGM||!glamourEffect(actor)||!markedHP(change,options[HP_BEFORE]))return;void dispatch(MAINTAIN,{actorUuid:actor.uuid,mode:'hp',id:foundry.utils.randomID(),deadline:decisionNow()+decisionBudget(120000)}).catch(error=>ui.notifications.error(error.message));});}
