import {ID,featureActive} from '../core.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {timedDialog} from '../dialog.js';
import {ownerFor,unavailableActor} from './aura-rules.js';
import {overwhelmHits} from './overwhelm.js';
import {sourceToken} from './hallowed-aura.js';
import {meleeLimit} from './kick.js';
import {OCEAN_MASTER_KEY,OCEAN_MASTER_ACTION,OCEAN_MASTER_EFFECT} from './ocean-master-data.js';
const QUERY=`${ID}.oceanMaster`,PROMPT=`${QUERY}Prompt`,WRAPPED=Symbol.for(`${ID}.oceanMaster`),pending=new Set();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function oceanMasterItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===OCEAN_MASTER_KEY;})??null:null;}
export function oceanMasterHits(message){const actor=message?.system?.action?.actor,origin=actor&&sourceToken(actor);if(!origin||!oceanMasterItem(actor))return[];return overwhelmHits(message).filter(hit=>{const token=canvas.tokens.get(hit.id),distance=token&&origin.distanceTo(token);return token?.actor?.uuid===hit.actorId&&!unavailableActor(token.actor)&&Number.isFinite(distance)&&distance<=meleeLimit(canvas.scene);});}
export async function promptOceanMaster(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.active||!actor?.testUserPermission(user,'OWNER')||!oceanMasterItem(actor)||!data.targets?.length)return false;return timedDialog(`Ocean Master — ${actor.name}`,`<p>Choose one successful target within Melee to make temporarily <strong>Restrained</strong>.</p>${data.targets.map((target,index)=>`<label style="display:block;margin:.35rem 0"><input type="radio" name="oceanTarget" value="${esc(target.id)}" ${index?'':'checked'}> ${esc(target.name)}</label>`).join('')}`,[{action:'use',label:'Restrain Target',callback:(_event,_button,dialog)=>dialog.element.querySelector('[name="oceanTarget"]:checked')?.value??false},{action:'decline',label:'Decline',default:true,callback:()=>false}]);}
export async function resolveOceanMaster(request,{user},ask=promptOceanMaster){if(!game.user.isActiveGM||!user?.active||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000)||pending.has(request.messageUuid))return false;const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,item=oceanMasterItem(actor);if(!item||!actor.testUserPermission(user,'OWNER')||message.flags?.[ID]?.oceanMasterOffered)return false;let hits=oceanMasterHits(message);if(!hits.length)return false;const targets=(await Promise.all(hits.map(async hit=>({id:hit.id,actorId:hit.actorId,name:(await fromUuid(hit.actorId))?.name})))).filter(target=>target.name);if(!targets.length)return false;pending.add(request.messageUuid);try{await message.setFlag(ID,'oceanMasterOffered',true);const owner=ownerFor(actor,[...game.users],game.user),selected=owner.isSelf?await ask({actorUuid:actor.uuid,targets},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,targets},{timeout:decisionBudget(65000)});if(!selected||decisionNow()>request.deadline)return false;hits=oceanMasterHits(message);const hit=hits.find(entry=>entry.id===selected),chosen=targets.find(entry=>entry.id===selected&&entry.actorId===hit?.actorId),target=chosen&&await fromUuid(chosen.actorId),effect=item.effects?.get?.(OCEAN_MASTER_EFFECT);if(!target||unavailableActor(target)||!effect)return false;await game.system.api.fields.ActionFields.EffectsField.applyEffect(effect,target);await message.setFlag(ID,'oceanMaster',{targetUuid:target.uuid});await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Ocean Master:</strong> ${esc(target.name)} becomes temporarily Restrained.</p>`});return true;}finally{pending.delete(request.messageUuid);}}
export function installOceanMaster(Action,dispatch){if(!Action||Action[WRAPPED])return;const native=Action.prototype.use;Action.prototype.use=async function(...args){const config=await native.apply(this,args);if(config?.message&&oceanMasterItem(this.actor)&&oceanMasterHits(config.message).length&&!config.message.flags?.[ID]?.oceanMasterOffered)try{await dispatch({messageUuid:config.message.uuid,deadline:decisionNow()+decisionBudget(120000)});}catch(error){console.error(`${ID} | Ocean Master failed`,error);ui.notifications?.error?.('Ocean Master failed; the completed attack was preserved.');}return config;};Object.defineProperty(Action,WRAPPED,{value:true});}
export function registerOceanMaster(){CONFIG.queries[QUERY]=resolveOceanMaster;CONFIG.queries[PROMPT]=promptOceanMaster;const dispatch=request=>{const gm=game.users.activeGM;if(!gm)throw Error('Ocean Master needs an active GM.');return gm.isSelf?resolveOceanMaster(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});};installOceanMaster(game.system.api.data.actions.actionsTypes.base,dispatch);Hooks.on('daggerheart.preUseAction',action=>{const flags=action.item?.flags?.[ID];if(action.id!==OCEAN_MASTER_ACTION||(flags?.applied?.key??flags?.premade?.key)!==OCEAN_MASTER_KEY)return;ui.notifications.info('Ocean Master is offered automatically after a successful attack within Melee range.');return false;});}
