import { ID,featureActive } from '../core.js';
import {attackHitTargets} from '../attack-outcome.js';
import { companionPartner } from '../companion-context.js';
import { PACK_HUNTING_KEY } from './pack-hunting-data.js';
const ACTION_WRAPPED=Symbol.for(`${ID}.packHuntingAction`),DAMAGE_WRAPPED=Symbol.for(`${ID}.packHuntingDamage`),inFlight=new Map();
let previous=null;
export function packHuntingItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===PACK_HUNTING_KEY;})??null:null;}
export function packParticipant(actor,party=game.actors.party?.system.partyMembers??[]){const members=new Set(party.map(member=>member?.uuid).filter(Boolean));if(members.has(actor?.uuid))return actor;const partner=actor?.type==='companion'?companionPartner(actor):null;return partner&&members.has(partner.uuid)?actor:null;}
export function actionRecord(actor,config){if(!packParticipant(actor)||!config)return null;const targets=config.message?.system?.targets??config.targets??[];return{actorUuid:actor.uuid,targetActorUuids:[...new Set(targets.map(target=>target.actorId).filter(Boolean))]};}
export function packHuntingHit(message,record){const data=message?.system,actor=data?.action?.actor;if(!packHuntingItem(actor)||!record||record.actorUuid===actor.uuid||data.action.type!=='attack'||!Number.isFinite(data.roll?.total))return null;const hits=attackHitTargets(message);return hits.length===1&&record.targetActorUuids.includes(hits[0].actorId)?hits[0]:null;}
export function resetPackHunting(){previous=null;inFlight.clear();}
export function installPackHuntingAction(Action){if(!Action||Action[ACTION_WRAPPED])return;const native=Action.prototype.use;Action.prototype.use=async function(...args){const participant=packParticipant(this.actor),prior=previous;if(participant)inFlight.set(this.actor.uuid,prior);try{const config=await native.apply(this,args);if(participant&&config){const hit=packHuntingHit(config.message,prior);if(hit)await config.message.setFlag(ID,'packHunting',{allyUuid:prior.actorUuid,targetActorUuid:hit.actorId});previous=actionRecord(this.actor,config);}return config;}finally{if(participant)inFlight.delete(this.actor.uuid);}};Object.defineProperty(Action,ACTION_WRAPPED,{value:true});}
export function installPackHuntingDamage(Damage){if(!Damage||Damage[DAMAGE_WRAPPED])return;const configure=Damage.buildConfigure,create=Damage.createRollInstance,bonus=Damage.prototype.applyBaseBonus,enabled=new WeakSet();Damage.buildConfigure=async function(config,...args){const message=game.messages.get(config.source?.message),actor=message?.system?.action?.actor,flag=message?.flags?.[ID]?.packHunting,record=flag?{actorUuid:flag.allyUuid,targetActorUuids:[flag.targetActorUuid]}:inFlight.get(actor?.uuid);if(!config.hasHealing&&config.damageFormula&&packHuntingHit(message,record))enabled.add(config);try{return await configure.call(this,config,...args);}finally{enabled.delete(config);}};Damage.createRollInstance=function(config){const roll=create.call(this,config);if(enabled.has(config)){config.bonusEffects??={};config.bonusEffects[PACK_HUNTING_KEY]={name:'Pack Hunting (+1d8)',description:'A party ally acted against this target immediately before you.',selected:true,changes:[]};roll.options.bonusEffects=config.bonusEffects;}return roll;};Damage.prototype.applyBaseBonus=function(part){const modifiers=bonus.call(this,part),effect=this.options.bonusEffects?.[PACK_HUNTING_KEY];if(effect?.selected&&!this.options.hasHealing)modifiers.push({label:'Pack Hunting',value:'1d8'});return modifiers;};Object.defineProperty(Damage,DAMAGE_WRAPPED,{value:true});}
export function registerPackHunting(){installPackHuntingAction(game.system.api.data.actions.actionsTypes.base);installPackHuntingDamage(CONFIG.Dice.daggerheart.DamageRoll);Hooks.on('daggerheart.preRefreshScene',()=>resetPackHunting());Hooks.on('daggerheart.preRefreshSession',()=>resetPackHunting());}
