import {ID,featureActive} from '../core.js';
import {patronFaces} from './patrons-pact.js';
import {severeStormDamage} from './eye-of-the-storm.js';
import {FURY_KEY,FURY_EFFECT} from './patrons-fury-data.js';
const QUERY=`${ID}.patronsFury`,WRAPPED=Symbol.for(`${ID}.patronsFury`);
export function furyItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===FURY_KEY;})??null:null;}
export function furyEffect(actor){const item=furyItem(actor),origin=item?.effects?.get?.(FURY_EFFECT)?.uuid;return item?actor.effects?.find(effect=>!effect.disabled&&!effect.isSuppressed&&(effect.flags?.[ID]?.patronsFury||origin&&effect.origin===origin))??null:null;}
export function furyDice(actor){const tier=Math.max(1,Math.floor(Number(actor?.system?.tier??actor?.system?.levelData?.tier?.current??1)||1));return`${tier}d${patronFaces(actor)}`;}
export function furyDamageActor(config){return game.messages.get(config.source?.message)?.system?.action?.actor??config.data?.parent??null;}
export function addFuryBonus(roll,config){const actor=furyDamageActor(config),effect=!config.hasHealing&&config.damageFormula?furyEffect(actor):null;if(!effect)return null;const dice=furyDice(actor),bonus={name:`Patron's Fury (+${dice})`,description:`Tier ${actor.system.tier??actor.system.levelData?.tier?.current??1} Patron Dice.`,selected:true,changes:[],dice,effectId:effect.id,actorUuid:actor.uuid};config.bonusEffects??={};config.bonusEffects[FURY_KEY]=bonus;roll.options.bonusEffects=config.bonusEffects;return bonus;}
export function markFuryDamage(config){const actor=furyDamageActor(config),effect=furyEffect(actor);if(!actor||!effect||config.hasHealing||!config.damage?.main)return false;config.damage.main.options[ID]={...config.damage.main.options[ID],patronsFury:{actorUuid:actor.uuid,effectId:effect.id}};if(typeof config.damage.toObject==='function')config.damage=new config.damage.constructor({...config.damage.toObject(),main:config.damage.main.toJSON(),resources:Object.fromEntries(Object.entries(config.damage.resources??{}).map(([key,value])=>[key,value.toJSON()]))});return true;}
export async function expireFury(request,{user}){if(!game.user.isActiveGM||!user?.active||!severeStormDamage(request.updates))return false;const actor=await fromUuid(request.actorUuid),target=await fromUuid(request.targetUuid),effect=furyEffect(actor);if(!actor||effect?.id!==request.effectId||!(user.isGM||actor.testUserPermission(user,'OWNER')||target?.testUserPermission(user,'OWNER')))return false;await actor.deleteEmbeddedDocuments('ActiveEffect',[effect.id]);return true;}
export function installPatronsFury(Damage,Actor,send){if(Damage[WRAPPED])return;const create=Damage.createRollInstance,bonus=Damage.prototype.applyBaseBonus,evaluate=Damage.buildEvaluate,take=Actor.prototype.takeDamage;Damage.createRollInstance=function(config){const roll=create.call(this,config);addFuryBonus(roll,config);return roll;};Damage.prototype.applyBaseBonus=function(part){const result=bonus.call(this,part),effect=this.options.bonusEffects?.[FURY_KEY];if(part.applyTo==='hitPoints'&&!this.options.hasHealing&&effect?.selected)result.push({label:"Patron's Fury",value:effect.dice});return result;};Damage.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);markFuryDamage(config);return result;};Actor.prototype.takeDamage=async function(packet,...args){const fury=packet?.main?.options?.[ID]?.patronsFury,result=await take.call(this,packet,...args);if(fury&&severeStormDamage(result))await send({...fury,targetUuid:this.uuid,updates:result});return result;};Object.defineProperty(Damage,WRAPPED,{value:true});}
export function registerPatronsFury(){CONFIG.queries[QUERY]=expireFury;const send=request=>{const gm=game.users.activeGM;if(!gm)throw Error("Patron's Fury needs an active GM to expire.");return gm.isSelf?expireFury(request,{user:game.user}):gm.query(QUERY,request,{timeout:15000});};installPatronsFury(CONFIG.Dice.daggerheart.DamageRoll,CONFIG.Actor.documentClass,send);Hooks.on('renderChatMessageHTML',(message,html)=>{const fury=message.system?.damage?.main?.options?.[ID]?.patronsFury;if(!message.isContentVisible||!fury||html.querySelector('.dhp-patrons-fury'))return;const p=html.ownerDocument.createElement('p');p.className='dhp-patrons-fury';p.textContent="Patron's Fury: Patron Dice added to this damage roll.";html.querySelector('.message-content')?.append(p);});}
