import { decisionBudget } from '../settings.js';
import { ID,featureActive } from '../core.js';
import { QUICK_STANCE_KEY,QUICK_STANCE_EFFECT } from './quick-stance-data.js';
import { sourceToken } from './hallowed-aura.js';
import { ownerFor } from './aura-rules.js';
import { timedDialog } from '../dialog.js';
import { markReactiveStress } from './stress-payment.js';
import { withHopeLock } from './hope-lock.js';
import { syncFocus } from './stance-fighter.js';
const QUERY=`${ID}.quickStance`,PROMPT=`${ID}.quickStancePrompt`,pending=new Set();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function quickActive(actor){const item=actor?.items?.find(i=>{const f=i.flags?.[ID];return featureActive(i)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===QUICK_STANCE_KEY;});const origin=item?.effects.get(QUICK_STANCE_EFFECT)?.uuid;return Boolean(origin&&actor.effects.some(e=>e.origin===origin&&!e.disabled&&!e.isSuppressed));}
export function quickPayments(actor){const r=actor.system.resources;return [Number(r.focus?.value)>=1?'focus':null,Number(r.stress?.value)<Number(r.stress?.max)?'stress':null].filter(Boolean);}
export function quickCandidates(action,targets){const actor=action.actor,origin=sourceToken(actor);if(!origin||action.type!=='attack'||!targets?.length)return [];const ranges=game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement,local=canvas.scene.flags?.daggerheart?.rangeMeasurement;const limit=Number(ranges.enabled&&local?.setting===CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id?local[action.range]:ranges[action.range]);if(!Number.isFinite(limit))return [];const excluded=new Set(targets.map(t=>t.actorId));return canvas.tokens.placeables.filter(t=>t.actor&&t.actor.uuid!==actor.uuid&&!excluded.has(t.actor.uuid)&&!t.document.hidden&&Number.isFinite(origin.distanceTo(t))&&origin.distanceTo(t)<=limit);}
function actionFor(actor,source){if(actor.system.attack?.id===source.action||actor.system.attack?._id===source.action)return actor.system.attack;const item=actor.items.get(source.item);return item?.system.actions?.get?.(source.action)??item?.system.actionsList?.find(a=>a.id===source.action);}
export async function promptQuickStance(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!quickActive(actor))return null;return timedDialog(`Quick Stance — ${actor.name}`,`<p>Add one creature to this attack:</p><select name="quickTarget" style="width:100%">${data.targets.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select>`,[...quickPayments(actor).map(payment=>({action:payment,label:payment==='focus'?'Spend 1 Focus':'Mark 1 Stress',callback:(_e,_b,d)=>({payment,targetId:d.element.querySelector('[name="quickTarget"]').value})})),{action:'decline',label:'Decline',default:true,callback:()=>null}]);}
export async function resolveQuickStance(request,{user}){if(!game.user.isActiveGM||!user?.active)return null;const actor=await fromUuid(request.source?.actor);if(!actor?.testUserPermission(user,'OWNER')||!quickActive(actor)||pending.has(actor.uuid))return null;const action=actionFor(actor,request.source);if(!action||!quickPayments(actor).length)return null;const candidates=quickCandidates(action,request.targets);if(!candidates.length)return null;pending.add(actor.uuid);try{const owner=ownerFor(actor,[...game.users],game.user),data={actorUuid:actor.uuid,targets:candidates.map(t=>({id:t.id,name:t.name}))};const choice=owner.isSelf?await promptQuickStance(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});if(!choice||!quickActive(actor)||!quickPayments(actor).includes(choice.payment))return null;const target=quickCandidates(action,request.targets).find(t=>t.id===choice.targetId);if(!target)return null;
 let paid=false;if(choice.payment==='stress')paid=await markReactiveStress(actor.uuid,quickActive);else paid=await withHopeLock(actor.uuid,async()=>{if(!quickActive(actor)||!quickPayments(actor).includes('focus'))return false;const next=Number(actor.system.resources.focus.value)-1;const updated=await actor.update({'system.resources.focus.value':next});if(!updated||Number(actor.system.resources.focus.value)!==next)return false;await syncFocus(actor);return true;});
 return paid?game.system.api.fields.ActionFields.TargetField.formatTarget.call(action,target):null;
 }finally{pending.delete(actor.uuid);}}
export function installQuickStance(Roll,offer){const native=Roll.buildConfigure;Roll.buildConfigure=async function(config,...args){const roll=await native.call(this,config,...args);if(!roll||roll._evaluated||config.actionType==='reaction'||!config.targets?.length)return roll;const actor=config.data?.parent;if(!quickActive(actor))return roll;const target=await offer({source:config.source,targets:config.targets});if(target&&!config.targets.some(t=>t.actorId===target.actorId))config.targets.push(target);return roll;};}
export function registerQuickStance(){CONFIG.queries[QUERY]=resolveQuickStance;CONFIG.queries[PROMPT]=promptQuickStance;installQuickStance(CONFIG.Dice.daggerheart.DualityRoll,request=>{const gm=game.users.activeGM;if(!gm)throw new Error('Quick stance needs an active GM.');return gm.isSelf?resolveQuickStance(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(65000)});});}
