import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {ownerFor} from './aura-rules.js';
import {animateInitialDamage} from './combo-strike.js';
import {selectableDamageDice} from './damage-reroll.js';
import {overwhelmHits} from './overwhelm.js';
import {RAMPAGE_KEY,RAMPAGE_EFFECT} from './rampage-data.js';
const QUERY=`${ID}.rampage`,PROMPT=`${QUERY}Prompt`,DAMAGE_WRAP=Symbol.for(`${ID}.rampageDamage`),ACTION_WRAP=Symbol.for(`${ID}.rampageAction`),requests=new Map();
export function rampageItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===RAMPAGE_KEY;})??null:null;}
export function rampageEffects(actor,item=rampageItem(actor)){if(!item)return[];const origin=item.effects?.get?.(RAMPAGE_EFFECT)?.uuid;return[...(actor?.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&(effect.flags?.[ID]?.rampageProficiency||origin&&effect.origin===origin));}
export const rampageOnes=roll=>selectableDamageDice(roll).filter(die=>die.value===1);
export async function promptRampage(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.active||!actor?.testUserPermission(game.user,'OWNER')||!rampageItem(actor))return false;const formula=`${data.count}d10`;return Boolean(await timedDialog(`Rampage — ${actor.name}`,`<p>Your damage roll contains <strong>${data.count}</strong> damage ${data.count===1?'die':'dice'} showing 1.</p><p>Roll <strong>${formula}</strong> and add the result to the damage?</p>`,[{action:'roll',label:`Roll ${formula}`,callback:()=>true},{action:'decline',label:'Keep Damage',default:true,callback:()=>false}]));}
export async function resolveRampage(request,{user}){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||!Number.isInteger(request.count)||request.count<1||request.deadline<decisionNow())return false;for(const[id,expiry]of requests)if(expiry<decisionNow())requests.delete(id);if(requests.has(request.id))return false;const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,item=rampageItem(actor);if(!item||item.uuid!==request.itemUuid||!actor.testUserPermission(user,'OWNER'))return false;requests.set(request.id,decisionNow()+decisionBudget(300000));const owner=ownerFor(actor,[...game.users],game.user);return owner.isSelf?promptRampage({actorUuid:actor.uuid,count:request.count},{user:game.user}):owner.query(PROMPT,{actorUuid:actor.uuid,count:request.count},{timeout:decisionBudget(65000)});}
export async function addRampageDamage(roll,count=1,rollDie=async formula=>new Roll(formula).evaluate()){if(roll.options?.[ID]?.rampage)return false;if(!Number.isSafeInteger(count)||count<1)throw Error('Invalid Rampage die count.');const formula=`${count}d10`,bonus=await rollDie(formula);if(!Number.isInteger(bonus.total)||bonus.total<count||bonus.total>count*10)throw Error('Invalid Rampage d10 result.');roll.terms.push(new foundry.dice.terms.OperatorTerm({operator:'+'}),...bonus.terms);roll._total=roll._evaluateTotal();roll.resetFormula();roll.options[ID]={...roll.options[ID],rampage:{bonus:bonus.total,count}};if(game.dice3d){await game.dice3d.showForRoll(bonus,game.user,true);for(const die of bonus.dice)for(const result of die.results)result.hidden=true;}return bonus.total;}
export async function expireRampageDamage(message){const pending=message?.flags?.[ID]?.rampageProficiency;if(!pending)return false;const actor=await fromUuid(pending.actorUuid),ids=(pending.effectIds??[]).filter(id=>actor?.effects?.get?.(id));if(ids.length)await actor.deleteEmbeddedDocuments('ActiveEffect',ids);await message.unsetFlag?.(ID,'rampageProficiency');return true;}
export async function offerRampage(config,dependencies={}){const message=game.messages.get(config.source?.message),actor=message?.system?.action?.actor??config.data?.parent,item=rampageItem(actor),roll=config.damage?.main,ones=rampageOnes(roll);if(config.hasHealing||!message||!item||!roll||roll.options?.[ID]?.rampage||!ones.length)return false;await(dependencies.initial??animateInitialDamage)(config,message);const decide=dependencies.decide??(async request=>{const gm=game.users.activeGM;if(!gm)throw Error('Rampage needs an active GM.');return gm.isSelf?resolveRampage(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(65000)});}),accepted=await decide({id:foundry.utils.randomID(),messageUuid:message.uuid,itemUuid:item.uuid,count:ones.length,deadline:decisionNow()+decisionBudget(60000)}),current=rampageOnes(roll).length;if(!accepted||!rampageItem(actor)||!current)return false;return addRampageDamage(roll,current,dependencies.rollDie);}
export function installRampage(Damage,Action,offer=offerRampage){if(Damage&&!Damage[DAMAGE_WRAP]){const evaluate=Damage.buildEvaluate,post=Damage.buildPost;Damage.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);if(!config.hasHealing&&config.damage?.main)try{await offer(config);}catch(error){console.error(`${ID} | Rampage damage automation failed`,error);ui.notifications?.error?.('Rampage automation failed; the normal damage roll was preserved. Check the console for details.');}return result;};Damage.buildPost=async function(roll,config,...args){const result=await post.call(this,roll,config,...args);if(!config.hasHealing&&config.source?.message)await expireRampageDamage(game.messages.get(config.source.message));return result;};Object.defineProperty(Damage,DAMAGE_WRAP,{value:true});}if(Action&&!Action[ACTION_WRAP]){const use=Action.prototype.use;Action.prototype.use=async function(...args){const ids=this.type==='attack'?rampageEffects(this.actor).map(effect=>effect.id):[],config=await use.apply(this,args);if(!config||!ids.length)return config;const current=ids.filter(id=>this.actor.effects?.get?.(id));if(!current.length)return config;const message=config.message,defersDamage=Boolean(this.damage?.main&&overwhelmHits(message).length&&message?.setFlag);if(defersDamage)await message.setFlag(ID,'rampageProficiency',{actorUuid:this.actor.uuid,effectIds:current});else await this.actor.deleteEmbeddedDocuments('ActiveEffect',current);return config;};Object.defineProperty(Action,ACTION_WRAP,{value:true});}}
export function registerRampage(){CONFIG.queries[QUERY]=resolveRampage;CONFIG.queries[PROMPT]=promptRampage;installRampage(CONFIG.Dice.daggerheart.DamageRoll,game.system.api.data.actions.actionsTypes.base);}
