import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {ownerFor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {RUNE_WARD_KEY,RUNE_WARD_ACTION,RUNE_WARD_CHARGED,RUNE_WARD_DRAINED} from './rune-ward-data.js';

const QUERY=`${ID}.runeWard`,PROMPT=`${QUERY}Prompt`,ACTION_WRAP=Symbol.for(`${ID}.runeWardAction`),DAMAGE_WRAP=Symbol.for(`${ID}.runeWardDamage`),REST_WRAP=Symbol.for(`${ID}.runeWardRest`),receipts=new Map();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function runeWardItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return item.type==='domainCard'&&!item.system?.inVault&&featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===RUNE_WARD_KEY;})??null:null;}
export function runeWardEffects(actor,state=null){return[...(actor?.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&effect.flags?.[ID]?.runeWard?.itemUuid&&(!state||effect.flags[ID].runeWard.state===state));}
export function runeWardHolders(source){const party=game.actors.party?.system?.partyMembers??[];return[...new Map([source,...party].filter(actor=>actor?.type==='character'&&actor.uuid).map(actor=>[actor.uuid,actor])).values()];}
function sourceEffect(item,state){const id=state==='charged'?RUNE_WARD_CHARGED:RUNE_WARD_DRAINED;return item.effects?.get?.(id)??item.effects?.find?.(effect=>(effect.id??effect._id)===id);}
function wardEffectData(item,state){const template=sourceEffect(item,state),data=template?.toObject?template.toObject():structuredClone(template);if(!data)throw Error('Rune Ward effects are missing. Reapply Medkit.');delete data._id;delete data.id;data.disabled=false;data.transfer=false;data.origin=template.uuid??`${item.uuid}.ActiveEffect.${state==='charged'?RUNE_WARD_CHARGED:RUNE_WARD_DRAINED}`;data.flags={...data.flags,[ID]:{...data.flags?.[ID],runeWard:{itemUuid:item.uuid,sourceActorUuid:item.actor.uuid,state}}};return data;}
async function removeWardCopies(item,keep=[]){const retained=new Set(keep);for(const actor of game.actors){const ids=runeWardEffects(actor).filter(effect=>effect.flags[ID].runeWard.itemUuid===item.uuid&&!retained.has(effect.id)).map(effect=>effect.id);if(ids.length)await actor.deleteEmbeddedDocuments('ActiveEffect',ids);}}
export async function validRuneWard(effect){const data=effect?.flags?.[ID]?.runeWard,item=data?.itemUuid?await fromUuid(data.itemUuid):null;return data?.state==='charged'&&runeWardItem(item?.actor)?.uuid===item.uuid?{effect,item,source:item.actor}:null;}
export async function runeWardCandidates(target){const candidates=[];for(const effect of runeWardEffects(target,'charged')){const valid=await validRuneWard(effect);if(valid)candidates.push(valid);}return candidates.sort((a,b)=>a.item.uuid.localeCompare(b.item.uuid));}

export async function activateRuneWard(request,{user}){if(!game.user.isActiveGM||!user?.active)return false;const source=await fromUuid(request.sourceActorUuid),holder=await fromUuid(request.holderUuid),item=runeWardItem(source);if(!item||!source.testUserPermission(user,'OWNER')||!runeWardHolders(source).some(actor=>actor.uuid===holder?.uuid))return false;const created=await holder.createEmbeddedDocuments('ActiveEffect',[wardEffectData(item,'charged')]);if(!created.length)throw Error('Rune Ward could not be given to its holder.');try{await removeWardCopies(item,created.map(effect=>effect.id));}catch(error){await holder.deleteEmbeddedDocuments('ActiveEffect',created.map(effect=>effect.id));throw error;}await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:source}),content:`<p><strong>Rune Ward:</strong> ${esc(source.name)} gives the charged ward to ${esc(holder.name)}.</p>`});return true;}
export async function promptRuneWard(data,{user}){const holder=await fromUuid(data.holderUuid),effect=holder?.effects?.get?.(data.effectId)??holder?.effects?.find?.(entry=>entry.id===data.effectId),valid=await validRuneWard(effect);if(!user?.isGM||!holder?.testUserPermission(game.user,'OWNER')||!valid||Number(holder.system.resources?.hope?.value)<1)return false;return Boolean(await timedDialog(`Rune Ward — ${holder.name}`,`<p>${esc(holder.name)} is taking <strong>${esc(data.total)} damage</strong>.</p><p>Spend <strong>1 Hope</strong> and roll the <strong>d8 Ward Die</strong> before native damage reduction?</p>`,[{action:'spend',label:'Spend Hope & Roll d8',callback:()=>true},{action:'decline',label:'Decline',default:true,callback:()=>false}]));}
async function swapRuneWard(holder,effect,item,state){const created=await holder.createEmbeddedDocuments('ActiveEffect',[wardEffectData(item,state)]);if(!created.length)throw Error(`Rune Ward could not become ${state}.`);try{await holder.deleteEmbeddedDocuments('ActiveEffect',[effect.id]);}catch(error){await holder.deleteEmbeddedDocuments('ActiveEffect',created.map(entry=>entry.id));throw error;}return created[0];}
export async function resolveRuneWard(request,{user},ask=promptRuneWard,rollDie=async()=>new Roll('1d8').evaluate()){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||!Number.isFinite(request.total)||request.total<=0||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000))return false;for(const[id,record]of receipts)if(record.expires<decisionNow())receipts.delete(id);const key=`${user.id}:${request.id}`;if(receipts.has(key))return receipts.get(key).promise;const promise=(async()=>{let holder=await fromUuid(request.holderUuid),effect=holder?.effects?.get?.(request.effectId)??holder?.effects?.find?.(entry=>entry.id===request.effectId),valid=await validRuneWard(effect);if(!valid||Number(holder.system.resources?.hope?.value)<1)return false;const owner=ownerFor(holder,[...game.users],game.user),accepted=owner.isSelf?await ask(request,{user:game.user}):await owner.query(PROMPT,request,{timeout:decisionBudget(65000)});if(!accepted||request.deadline<decisionNow())return false;return withHopeLock(holder.uuid,async()=>{holder=await fromUuid(request.holderUuid);effect=holder?.effects?.get?.(request.effectId)??holder?.effects?.find?.(entry=>entry.id===request.effectId);valid=await validRuneWard(effect);const hope=Number(holder?.system.resources?.hope?.value);if(!valid||hope<1)return false;const paid=await holder.update({'system.resources.hope.value':hope-1});if(!paid||Number(holder.system.resources.hope.value)!==hope-1)throw Error('Rune Ward could not spend Hope.');let roll;try{roll=await rollDie();}catch(error){await holder.update({'system.resources.hope.value':hope});throw error;}const result=Number(roll.total),drained=result===8;if(drained)await swapRuneWard(holder,effect,valid.item,'drained');const message=await roll.toMessage({speaker:ChatMessage.getSpeaker({actor:holder}),flavor:`<strong>Rune Ward</strong><p>Reduces incoming damage by ${Math.min(request.total,result)}.${drained?' The ward is drained.':''}</p>`});if(message&&game.dice3d)await game.dice3d.waitFor3DAnimationByMessageID(message.id);return{reduction:result,drained};});})();receipts.set(key,{promise,expires:decisionNow()+decisionBudget(300000)});return promise;}
export function incomingRuneDamage(args={}){const damage='total'in args?args:(args.main??args.damage),total=typeof damage==='number'?damage:Number(damage?.total);return Number.isFinite(total)&&total>0?{damage,total}:null;}
export function reducedRuneDamage(args,amount){const incoming=incomingRuneDamage(args),total=Math.max(0,incoming.total-Math.max(0,Number(amount)||0));if('total'in args)return{...args,total};const damage=incoming.damage,options=damage?.options?{...damage.options}:damage?.damageTypes?{damageTypes:damage.damageTypes}:null;return{...args,main:{total,...(options?{options}: {})},resources:args.resources};}
async function offerRuneWard(holder,total){let remaining=total;for(const candidate of await runeWardCandidates(holder)){if(remaining<=0)break;const gm=game.users.activeGM;if(!gm)throw Error('Rune Ward needs an active GM.');const request={id:foundry.utils.randomID(),holderUuid:holder.uuid,effectId:candidate.effect.id,total:remaining,deadline:decisionNow()+decisionBudget(120000)},result=gm.isSelf?await resolveRuneWard(request,{user:game.user}):await gm.query(QUERY,request,{timeout:decisionBudget(125000)});if(result)remaining=Math.max(0,remaining-result.reduction);}return remaining;}
export function installRuneWardDamage(Actor,offer=offerRuneWard){if(Actor[DAMAGE_WRAP])return;const native=Actor.prototype.takeDamage;Actor.prototype.takeDamage=async function(args={},...rest){const incoming=incomingRuneDamage(args);if(!incoming||Number(this.system.resources?.hope?.value)<1||!(await runeWardCandidates(this)).length)return native.call(this,args,...rest);const remaining=await offer(this,incoming.total);return native.call(this,reducedRuneDamage(args,incoming.total-remaining),...rest);};Object.defineProperty(Actor,DAMAGE_WRAP,{value:true});}
export async function rechargeRuneWard(request,{user}){if(!game.user.isActiveGM||!user?.active)return false;const source=await fromUuid(request.sourceActorUuid),item=runeWardItem(source);if(!item||!source.testUserPermission(user,'OWNER'))return false;let count=0;for(const holder of game.actors){for(const effect of runeWardEffects(holder,'drained').filter(entry=>entry.flags[ID].runeWard.itemUuid===item.uuid)){await swapRuneWard(holder,effect,item,'charged');count++;}}if(count)await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:source}),content:`<p><strong>Rune Ward:</strong> ${esc(source.name)} recharges the ward.</p>`});return count;}
export function installRuneWardRest(Downtime,dispatch){if(!Downtime||Downtime[REST_WRAP])return;const native=Downtime.prototype.close;Downtime.prototype.close=async function(...args){const source=this.actor,completed=Boolean(this.nrChoices&&Object.values(this.nrChoices).every(category=>Number(category.taken)>=Number(category.max))),result=await native.apply(this,args);if(completed&&runeWardItem(source))await dispatch({op:'recharge',sourceActorUuid:source.uuid});return result;};Object.defineProperty(Downtime,REST_WRAP,{value:true});}
export function registerRuneWard(){CONFIG.queries[QUERY]=async(request,context)=>request.op==='activate'?activateRuneWard(request,context):request.op==='recharge'?rechargeRuneWard(request,context):resolveRuneWard(request,context);CONFIG.queries[PROMPT]=promptRuneWard;const dispatch=request=>{const gm=game.users.activeGM;if(!gm)throw Error('Rune Ward needs an active GM.');return gm.isSelf?CONFIG.queries[QUERY](request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});};installRuneWardDamage(CONFIG.Actor.documentClass);installRuneWardRest(game.system.api.applications.dialogs.Downtime,dispatch);const Action=game.system.api.data.actions.actionsTypes.base;if(!Action[ACTION_WRAP]){const native=Action.prototype.use;Action.prototype.use=async function(...args){if(this.id!==RUNE_WARD_ACTION||runeWardItem(this.actor)?.uuid!==this.item?.uuid)return native.apply(this,args);if(!this.actor.testUserPermission(game.user,'OWNER'))return false;const targets=[...(game.user.targets??[])].map(token=>token.actor).filter(Boolean);if(targets.length>1)throw Error('Rune Ward requires one targeted holder, or no target to choose yourself.');return dispatch({op:'activate',sourceActorUuid:this.actor.uuid,holderUuid:(targets[0]??this.actor).uuid});};Object.defineProperty(Action,ACTION_WRAP,{value:true});}}
