import {ID,featureActive} from '../core.js';
import {attackHitTargets} from '../attack-outcome.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {ownerFor,closeDistance} from './aura-rules.js';
import {sourceToken} from './hallowed-aura.js';
import {withHopeLock} from './hope-lock.js';
import {SECOND_WIND_KEY} from './second-wind-data.js';
const QUERY=`${ID}.secondWind`,PROMPT=`${QUERY}Prompt`,WRAP=Symbol.for(QUERY),pending=new Set();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function secondWindItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID],s=item.system;return item.type==='domainCard'&&featureActive(item)&&!flags?.disabled&&(!s?.inVault||s.vaultActive)&&!s?.isDomainTouchedSuppressed&&(flags?.applied?.key??flags?.premade?.key)===SECOND_WIND_KEY&&s.resource?.recovery==='shortRest'&&Number(s.resource.value)===1;})??null:null;}
export function secondWindRecovery(actor){return ['stress','hitPoints'].filter(key=>Number(actor?.system?.resources?.[key]?.value)>0);}
export function secondWindHope(message){const roll=message?.system?.roll;if(roll?.isCritical)return true;if(typeof roll?.withHope==='boolean')return roll.withHope;return roll?.result?.duality===1;}
export async function secondWindAttack(message){const d=message?.system;if(d?.action?.type!=='attack'||d.action.actionType==='reaction'||d.actionType==='reaction'||d.roll?.options?.actionType==='reaction'||d.roll?._evaluated===false||!Number.isFinite(d.roll?.total)||!secondWindItem(d.action.actor))return false;for(const hit of attackHitTargets(message))if((await fromUuid(hit.actorId))?.type==='adversary')return true;return false;}
export function secondWindAllies(actor){const origin=sourceToken(actor);if(!origin)return[];const rules=game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement,limit=closeDistance(canvas.scene,rules,CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id),seen=new Set();return canvas.tokens.placeables.filter(token=>{const ally=token.actor;if(!ally||ally.uuid===actor.uuid||seen.has(ally.uuid)||token.document?.disposition!==origin.document?.disposition||token.document?.disposition!==1||ally.statuses?.has('dead')||ally.statuses?.has('defeated')||!secondWindRecovery(ally).length)return false;const distance=origin.distanceTo(token);if(!Number.isFinite(distance)||distance>limit)return false;seen.add(ally.uuid);return true;}).map(t=>t.actor);}
export async function promptSecondWind(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.active||!actor?.testUserPermission(user,'OWNER')||!secondWindItem(actor))return false;const names={stress:'Clear 3 Stress',hitPoints:'Clear 1 HP'},options=keys=>keys.map(key=>`<option value="${key}">${names[key]}</option>`).join('');return timedDialog(`Second Wind — ${actor.name}`,`<p>Use Second Wind (once per rest)?</p><div class="form-group"><label>Your recovery</label><select name="secondWindSelf">${data.self.length?options(data.self):'<option value="">No recovery needed</option>'}</select></div>${data.hope?`<div class="form-group"><label>Ally within Close</label><select name="secondWindAlly"><option value="">No ally recovery</option>${data.allies.flatMap(a=>a.keys.map(key=>`<option value="${esc(a.uuid)}|${key}">${esc(a.name)} — ${names[key]}</option>`)).join('')}</select></div>`:''}`,[{action:'use',label:'Use Second Wind',callback:(_event,_button,dialog)=>({self:dialog.element.querySelector('[name="secondWindSelf"]')?.value??'',ally:dialog.element.querySelector('[name="secondWindAlly"]')?.value??''})},{action:'decline',label:'Decline',default:true,callback:()=>false}]);}
// Await the native healing API's asynchronous resource writes, including nested updates.
export async function clearSecondWind(actor,key){return withHopeLock(actor.uuid,async()=>{if(!secondWindRecovery(actor).includes(key))return 0;const before=Number(actor.system.resources[key].value),amount=key==='stress'?3:1,prior=Object.getOwnPropertyDescriptor(actor,'update'),native=actor.update,writes=[];const capture=function(...args){const result=native.apply(this,args);writes.push(Promise.resolve(result));return result;};Object.defineProperty(actor,'update',{value:capture,writable:true,configurable:true});try{await actor.takeHealing({resources:{[key]:{total:amount}}});let i=0;while(i<writes.length){const end=writes.length;await Promise.all(writes.slice(i,end));i=end;}const cleared=before-Number(actor.system.resources[key].value);if(cleared!==Math.min(amount,before))throw Error('Second Wind recovery could not be verified.');return cleared;}finally{if(actor.update===capture){if(prior)Object.defineProperty(actor,'update',prior);else delete actor.update;}}});}
export async function resolveSecondWind(request,{user},ask=promptSecondWind){
 if(!game.user.isActiveGM||!user?.active||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000)||pending.has(request.messageUuid))return false;
 const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,item=secondWindItem(actor);if(!item||!actor.testUserPermission(user,'OWNER')||message.flags?.[ID]?.secondWindOffered||!await secondWindAttack(message)||pending.has(request.messageUuid))return false;
 pending.add(request.messageUuid);try{
  const hope=secondWindHope(message),allies=hope?secondWindAllies(actor):[],self=secondWindRecovery(actor);if(!self.length&&!allies.length)return false;
  await message.setFlag(ID,'secondWindOffered',true);const owner=ownerFor(actor,[...game.users],game.user),data={actorUuid:actor.uuid,self,hope,allies:allies.map(a=>({uuid:a.uuid,name:a.name,keys:secondWindRecovery(a)}))};
  const choice=owner.isSelf?await ask(data,{user:game.user}):await owner.query(PROMPT,data,{timeout:decisionBudget(65000)});if(!choice||!owner.active||!user.active||!actor.testUserPermission(owner,'OWNER')||decisionNow()>request.deadline)return false;
  return await withHopeLock(item.uuid,async()=>{
   if(!game.user.isActiveGM||!user.active||!owner.active||!actor.testUserPermission(user,'OWNER')||!actor.testUserPermission(owner,'OWNER')||secondWindItem(actor)?.uuid!==item.uuid||!await secondWindAttack(message)||decisionNow()>request.deadline)return false;
   if(choice.self&&!self.includes(choice.self)||choice.self&&!secondWindRecovery(actor).includes(choice.self))return false;
   let ally,key;if(choice.ally){const parts=String(choice.ally).split('|');if(parts.length!==2||!hope||!secondWindHope(message))return false;[ally,key]=[allies.find(a=>a.uuid===parts[0]),parts[1]];if(!ally||!data.allies.find(a=>a.uuid===ally.uuid)?.keys.includes(key)||!secondWindAllies(actor).some(a=>a.uuid===ally.uuid)||!secondWindRecovery(ally).includes(key))return false;}
   if(!choice.self&&!ally)return false;
   const spent=await item.update({'system.resource.value':0});if(!spent||Number(item.system.resource.value)!==0)throw Error('Could not spend Second Wind’s rest use.');
   const healed=[];try{if(choice.self)healed.push(`${esc(actor.name)} clears ${await clearSecondWind(actor,choice.self)} ${choice.self==='stress'?'Stress':'HP'}`);if(ally){if(!secondWindHope(message)||!secondWindAllies(actor).some(a=>a.uuid===ally.uuid))throw Error('Ally is no longer within Close or eligible.');healed.push(`${esc(ally.name)} clears ${await clearSecondWind(ally,key)} ${key==='stress'?'Stress':'HP'}`);}}catch(error){throw Error(`Second Wind's rest use was spent; check recovery manually: ${error.message}`);}
   await message.setFlag(ID,'secondWindApplied',{itemUuid:item.uuid,self:choice.self??'',allyUuid:ally?.uuid??null,allyKey:key??null});
   await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Second Wind:</strong> ${healed.join('; ')}.</p>`});return true;
  });
 }finally{pending.delete(request.messageUuid);}
}
export function installSecondWind(Action,send){if(!Action||Action[WRAP])return;const native=Action.prototype.use;Action.prototype.use=async function(...args){const config=await native.apply(this,args);if(config?.message&&secondWindItem(this.actor)){try{if(await secondWindAttack(config.message)&&!config.message.flags?.[ID]?.secondWindOffered){if(game.dice3d&&config.message.id)await game.dice3d.waitFor3DAnimationByMessageID(config.message.id);await send({messageUuid:config.message.uuid,deadline:decisionNow()+decisionBudget(120000)});}}catch(error){console.error(`${ID} | Second Wind`,error);ui.notifications.error(`Second Wind: ${error.message}. The completed attack was preserved.`);}}return config;};Object.defineProperty(Action,WRAP,{value:true});}
export function registerSecondWind(){CONFIG.queries[QUERY]=resolveSecondWind;CONFIG.queries[PROMPT]=promptSecondWind;installSecondWind(game.system.api.data.actions.actionsTypes.base,request=>{const gm=game.users.activeGM;if(!gm)throw Error('Second Wind needs an active GM.');return gm.isSelf?resolveSecondWind(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});});Hooks.on('daggerheart.preUseAction',action=>{const f=action.item?.flags?.[ID];if(!f?.disabled&&(f?.applied?.key??f?.premade?.key)===SECOND_WIND_KEY&&['1w6rcNGdI6H9wVIz','OIrSjtVdt4b2yJ2t'].includes(action.id)){ui.notifications.info('Second Wind is offered automatically after a successful attack against an adversary.');return false;}});}
