import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {ownerFor,unavailableActor} from './aura-rules.js';
import {sourceToken} from './hallowed-aura.js';
import {meleeLimit} from './kick.js';
import {withHopeLock} from './hope-lock.js';
import {HP_REACTIONS_HANDLED} from './hp-reactions.js';
import {traumaFollowups} from './shared-trauma-followups.js';
import {TRAUMA_KEY,TRAUMA_ACTION} from './shared-trauma-data.js';
const QUERY=`${ID}.sharedTrauma`,PICK=`${QUERY}Pick`,CONSENT=`${QUERY}Consent`,WRAP=Symbol.for(QUERY),requests=new Map();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const actionFor=item=>item?.system.actions?.get?.(TRAUMA_ACTION)??item?.system.actions?.[TRAUMA_ACTION];
const hpValue=actor=>Number(actor?.system?.resources?.hitPoints?.value),hpMax=actor=>Number(actor?.system?.resources?.hitPoints?.max);
export function traumaItem(actor){return actor?.type==='character'&&!unavailableActor(actor)?actor.items?.find(i=>{const f=i.flags?.[ID];return i.type==='domainCard'&&featureActive(i)&&!i.system.inVault&&!i.system.isDomainTouchedSuppressed&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===TRAUMA_KEY;})??null:null;}
export function traumaMaximum(donor,recipient){const max=Math.min(hpMax(donor)-hpValue(donor),hpValue(recipient));return Number.isSafeInteger(max)&&max>0?max:0;}
export async function traumaState(request,{spent=false}={}){
 if(typeof request?.actorUuid!=='string'||typeof request.itemUuid!=='string'||typeof request.tokenUuid!=='string'||!Array.isArray(request.targets)||request.targets.length!==2||request.targets.some(row=>typeof row?.actorUuid!=='string'||typeof row.tokenUuid!=='string'))return null;
 const actor=await fromUuid(request?.actorUuid),item=traumaItem(actor),action=actionFor(item);if(!canvas.ready||!item||item.uuid!==request.itemUuid||action?.uses?.recovery!=='shortRest'||Number(action.uses.value??0)!==(spent?1:0)||!Array.isArray(request.targets)||request.targets.length!==2)return null;
 const origin=await fromUuid(request.tokenUuid),limit=meleeLimit(canvas.scene);if(origin?.actor?.uuid!==actor.uuid||origin.parent?.id!==canvas.scene.id||!origin.object||!Number.isFinite(limit)||limit<0)return null;
 const targets=[];for(const row of request.targets){const token=await fromUuid(row.tokenUuid),target=token?.actor;if(!target||target.uuid!==row.actorUuid||!['character','adversary'].includes(target.type)||unavailableActor(target)||token.parent?.id!==canvas.scene.id||!token.object||!Number.isSafeInteger(hpValue(target))||!Number.isSafeInteger(hpMax(target))||hpValue(target)<0||hpMax(target)<1||hpValue(target)>hpMax(target))return null;const distance=token.uuid===origin.uuid?0:origin.object.distanceTo(token.object);if(!Number.isFinite(distance)||distance<0||distance>limit)return null;targets.push(target);}
 if(targets[0].uuid===targets[1].uuid)return null;return {actor,item,action,targets};
}
export async function chooseTrauma(request,{user}){const state=await traumaState(request);if(!user?.isGM||!state?.actor.testUserPermission(game.user,'OWNER'))return null;
 const rows=state.targets.map((donor,i)=>({donor,recipient:state.targets[1-i],max:traumaMaximum(donor,state.targets[1-i])}));if(!rows.some(r=>r.max))return null;
 const first=rows.findIndex(r=>r.max>0),content=`<p>Both creatures must be willing. Choose who marks HP; the other clears the same amount.</p>${rows.map((r,i)=>`<label style="display:block;margin:0.5rem 0"><input type="radio" name="traumaDonor" value="${i}" ${i===first?'checked':''} ${r.max?'':'disabled'}> ${esc(r.donor.name)} marks HP → ${esc(r.recipient.name)} clears HP</label>`).join('')}<label style="display:block">HP to transfer <select name="traumaAmount"></select></label>`;
 return timedDialog('Shared Trauma — Transfer Suffering',content,[{action:'transfer',label:'Transfer HP',callback:(_e,_b,d)=>{const index=Number(d.element.querySelector('[name="traumaDonor"]:checked')?.value);return {donorUuid:rows[index]?.donor.uuid,amount:Number(d.element.querySelector('[name="traumaAmount"]').value)};}},{action:'cancel',label:'Cancel',default:true,callback:()=>null}],d=>{const select=d.element.querySelector('[name="traumaAmount"]'),refresh=()=>{const index=Number(d.element.querySelector('[name="traumaDonor"]:checked')?.value),max=rows[index]?.max??0;select.innerHTML=Array.from({length:max},(_,n)=>`<option value="${n+1}">${n+1}</option>`).join('');};for(const input of d.element.querySelectorAll('[name="traumaDonor"]'))input.addEventListener('change',refresh);refresh();});
}
export async function consentTrauma(data,{user}){if(!user?.isGM||!user.active||!Array.isArray(data.rows))return false;for(const row of data.rows){const actor=await fromUuid(row.actorUuid);if(!actor?.testUserPermission(game.user,'OWNER'))return false;}
 return Boolean(await timedDialog('Shared Trauma — Willing Creature',`<p>${esc(data.casterName)} offers Shared Trauma:</p>${data.rows.map(row=>`<p>${esc(row.name)} will <strong>${row.mark?'mark':'clear'} ${data.amount} HP</strong>.</p>`).join('')}<p>This HP cost cannot be reduced or prevented. Are you willing?</p>`,[{action:'accept',label:'Accept',callback:()=>true},{action:'decline',label:'Decline',default:true,callback:()=>false}]));
}
const lockActors=(actors,callback)=>{const ids=[...new Set(actors.map(a=>a.uuid))].sort();const next=i=>i===ids.length?callback():withHopeLock(`traumaHP:${ids[i]}`,()=>next(i+1));return next(0);};
export async function resolveTrauma(request,{user},pick=chooseTrauma,consent=consentTrauma,followups=traumaFollowups){
 if(!game.user.isActiveGM||!user?.active||typeof request?.id!=='string'||!/^[a-zA-Z0-9]{16}$/.test(request.id))return false;
 let state=await traumaState(request);if(!state?.actor.testUserPermission(user,'OWNER'))return false;const key=`${user.id}:${request.id}`,signature=JSON.stringify(request),previous=requests.get(key);if(previous)return previous.signature===signature?previous.promise:false;
 const operation=(async()=>{let committed;try{
  const result=await withHopeLock(`traumaUse:${state.item.uuid}`,async()=>{
   state=await traumaState(request);if(!state||!user.active||!game.user.isActiveGM||!state.actor.testUserPermission(user,'OWNER'))return false;
   const owner=ownerFor(state.actor,[...game.users],game.user),choice=owner.isSelf?await pick(request,{user:game.user}):await owner.query(PICK,request,{timeout:decisionBudget(65000)});
   const fresh=async()=>{const current=await traumaState(request);return current&&user.active&&owner.active&&game.user.isActiveGM&&current.actor.testUserPermission(user,'OWNER')&&current.actor.testUserPermission(owner,'OWNER')?current:null;};
   state=await fresh();if(!state||!choice||!Number.isSafeInteger(choice.amount)||choice.amount<1)return false;let donor=state.targets.find(a=>a.uuid===choice.donorUuid),recipient=state.targets.find(a=>a.uuid!==choice.donorUuid);if(!donor||!recipient||choice.amount>traumaMaximum(donor,recipient))return false;
   const consentOwners=new Map();for(const target of state.targets){const targetOwner=ownerFor(target,[...game.users],game.user);if(targetOwner.id===owner.id)continue;const group=consentOwners.get(targetOwner.id)??{owner:targetOwner,rows:[]};group.rows.push({actorUuid:target.uuid,name:target.name,mark:target.uuid===donor.uuid});consentOwners.set(targetOwner.id,group);}
   for(const group of consentOwners.values()){const data={casterName:state.actor.name,amount:choice.amount,rows:group.rows},accepted=group.owner.isSelf?await consent(data,{user:game.user}):await group.owner.query(CONSENT,data,{timeout:decisionBudget(65000)});if(!accepted||!group.owner.active||!await fresh())return false;for(const row of group.rows){const target=state.targets.find(a=>a.uuid===row.actorUuid);if(!target.testUserPermission(group.owner,'OWNER'))return false;}}
   return lockActors(state.targets,async()=>{state=await fresh();if(!state)return false;for(const group of consentOwners.values())if(!group.owner.active||group.rows.some(row=>!state.targets.find(a=>a.uuid===row.actorUuid)?.testUserPermission(group.owner,'OWNER')))return false;donor=state.targets.find(a=>a.uuid===choice.donorUuid);recipient=state.targets.find(a=>a.uuid!==choice.donorUuid);if(choice.amount>traumaMaximum(donor,recipient))return false;
    const path=`system.actions.${TRAUMA_ACTION}.uses.value`,beforeDonor=hpValue(donor),beforeRecipient=hpValue(recipient),nextDonor=beforeDonor+choice.amount,nextRecipient=beforeRecipient-choice.amount;let reserved=false,paid=false;
    try{const used=await state.item.update({[path]:1,[`flags.${ID}.sharedTrauma`]:{id:request.id,started:true}});reserved=Number(actionFor(state.item)?.uses.value)===1;if(!used||!reserved)throw Error('Could not reserve Shared Trauma use.');
     const current=await traumaState(request,{spent:true});if(!current||!user.active||!owner.active||!game.user.isActiveGM||!current.actor.testUserPermission(user,'OWNER')||!current.actor.testUserPermission(owner,'OWNER')||hpValue(donor)!==beforeDonor||hpValue(recipient)!==beforeRecipient||[...consentOwners.values()].some(g=>!g.owner.active||g.rows.some(row=>!state.targets.find(a=>a.uuid===row.actorUuid)?.testUserPermission(g.owner,'OWNER'))))throw Error('Shared Trauma changed before HP payment.');
     const marking=await donor.update({'system.resources.hitPoints.value':nextDonor},{[HP_REACTIONS_HANDLED]:true,[`${ID}.dominionEarthHandled`]:true});paid=hpValue(donor)===nextDonor;if(!marking||!paid)throw Error('Shared Trauma HP cost could not be confirmed.');
     committed={actor:donor,source:state.actor,count:choice.amount};
     // Pay first. A failed healing write must not grant free healing or roll
     // back already-triggered HP consequences; it requires manual completion.
     if(hpValue(recipient)!==beforeRecipient)throw Error('Shared Trauma recipient HP changed after payment.');
     const healing=await recipient.update({'system.resources.hitPoints.value':nextRecipient});if(!healing||hpValue(recipient)!==nextRecipient)throw Error('Shared Trauma healing could not be confirmed.');
     const receipt={amount:choice.amount,donorUuid:donor.uuid,recipientUuid:recipient.uuid};
     try{await state.item.update({[`flags.${ID}.sharedTrauma`]:{id:request.id,started:true,completed:true,...receipt}});}catch(error){console.error(`${ID} | Shared Trauma receipt`,error);}return receipt;
    }catch(error){paid ||= hpValue(donor)!==beforeDonor;if(!paid){reserved ||= Number(actionFor(state.item)?.uses.value)===1&&state.item.flags?.[ID]?.sharedTrauma?.id===request.id;if(reserved){const reverted=await state.item.update({[path]:0});if(!reverted||Number(actionFor(state.item)?.uses.value)!==0)throw Error('Shared Trauma use rollback failed. Check the use manually.');}}else {if(!committed&&hpValue(donor)===nextDonor)committed={actor:donor,source:state.actor,count:choice.amount};ui.notifications.error('Shared Trauma HP was marked. Check both HP and the use manually; do not repeat the transfer.');}throw error;}
   });
  });
  if(committed)try{await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:committed.source}),content:`<p><strong>Shared Trauma:</strong> ${esc(committed.actor.name)} marks ${result.amount} HP; ${esc((await fromUuid(result.recipientUuid))?.name)} clears ${result.amount} HP.</p>`});}catch(error){console.error(`${ID} | Shared Trauma chat`,error);}return result;
 }finally{if(committed)try{await followups(committed.actor,committed.source,committed.count);}catch(error){console.error(`${ID} | Shared Trauma follow-ups`,error);ui.notifications.error('Shared Trauma HP was marked, but follow-ups failed. Do not repeat the transfer.');}}
 })();requests.set(key,{signature,promise:operation});if(requests.size>512)requests.delete(requests.keys().next().value);return operation;
}
export function installSharedTrauma(Action,send){if(Object.hasOwn(Action,WRAP))return;const native=Action.prototype.use;Action.prototype.use=async function(...args){const item=traumaItem(this.actor);if(this.id!==TRAUMA_ACTION||item?.uuid!==this.item?.uuid)return native.apply(this,args);const token=sourceToken(this.actor),targets=[...game.user.targets];if(!token||targets.length!==2||new Set(targets.map(t=>t.actor?.uuid)).size!==2){ui.notifications.warn('Shared Trauma: target two distinct willing creatures within Melee, and place your caster token on the scene.');return false;}return send({id:foundry.utils.randomID(),actorUuid:this.actor.uuid,itemUuid:item.uuid,tokenUuid:token.document.uuid,targets:targets.map(t=>({actorUuid:t.actor?.uuid,tokenUuid:t.document.uuid}))});};Object.defineProperty(Action,WRAP,{value:true});}
export function registerSharedTrauma(){CONFIG.queries[QUERY]=resolveTrauma;CONFIG.queries[PICK]=chooseTrauma;CONFIG.queries[CONSENT]=consentTrauma;installSharedTrauma(game.system.api.data.actions.actionsTypes.base,request=>{const gm=game.users.activeGM;if(!gm)throw Error('Shared Trauma needs an active GM.');return gm.isSelf?resolveTrauma(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(600000)});});}
