import {ID,featureActive} from '../core.js';import {SLAYER_KEY} from './slayer-data.js';import {timedDialog} from '../dialog.js';import {rerollSlayerOnes,resolveWeaponReroll} from './weapon-specialist.js';
const SPEND=`${ID}.spendSlayer`,GAIN=Symbol.for(`${ID}.slayerGain`),ROLL=Symbol.for(`${ID}.slayerRoll`),REFRESH=Symbol.for(`${ID}.slayerRefresh`),locks=new Map();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function slayerItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const f=item.flags?.[ID];return featureActive(item)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===SLAYER_KEY;})??null:null;}
export function slayerCapacity(item){const actor=item?.actor,max=Number(actor?.system?.proficiency);return Number.isFinite(max)?Math.max(0,Math.floor(max)):Math.max(0,Math.floor(Number(item?.system?.resource?.max)||0));}
export function slayerAvailable(item){return Math.max(0,Math.floor(Number(item?.system?.resource?.value)||0));}
export function temporarySlayerEffects(actor){return [...(actor?.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&effect.flags?.[ID]?.temporarySlayerDie);}
export function slayerPool(actor){const item=slayerItem(actor);return{item,stored:slayerAvailable(item),temporary:temporarySlayerEffects(actor).length};}
export async function createTemporarySlayerDice(actor,count,origin){const data=Array.from({length:count},()=>({name:'Martial Preparation — Slayer Die',img:origin?.img??'icons/skills/melee/sword-winged-holy-orange.webp',type:'base',transfer:false,disabled:false,origin:origin?.uuid,showIcon:CONST.ACTIVE_EFFECT_SHOW_ICON.ALWAYS,description:'<p>A temporary d6 Slayer Die. Before an attack or damage roll, choose whether to include it. It expires at Session refresh if unspent.</p>',system:{changes:[],duration:{type:'session',description:'Until spent or the end of the session.'}},flags:{[ID]:{temporarySlayerDie:true}}}));const created=await actor.createEmbeddedDocuments('ActiveEffect',data);if(created.length!==count)throw Error('Could not grant the temporary Slayer Die.');return created;}
export function slayerCanGain(actor){const item=slayerItem(actor);return Boolean(item&&slayerAvailable(item)<slayerCapacity(item));}
export async function promptSlayerGain(actor){return timedDialog(`Slayer — ${actor.name}`,'<p>This action rolled with Hope. Choose the normal Hope gain or add one <strong>d6 Slayer Die</strong> to your pool.</p>',[{action:'die',label:'Gain Slayer Die',callback:()=>true},{action:'hope',label:'Gain Hope',default:true,callback:()=>false}]);}
export function installSlayerGain(Duality,choose=promptSlayerGain){if(Duality[GAIN])return;const native=Duality.addDualityResourceUpdates;Duality.addDualityResourceUpdates=async function(config){const withHope=config.actionType==='action'&&!config.skips?.resources&&(config.roll?.result?.duality===1||config.roll?.isCritical),actor=withHope?await fromUuid(config.source?.actor):null,item=slayerItem(actor);if(!item||!slayerCanGain(actor)||!await choose(actor,item,config))return native.call(this,config);const original=config.resourceUpdates,proxy=new Proxy(original,{get(target,key){if(key==='addResources')return updates=>target.addResources(updates.filter(update=>!(update.key==='hope'&&update.value===1)));const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;}});config.resourceUpdates=proxy;try{const result=await native.call(this,config),before=slayerAvailable(item),max=slayerCapacity(item);if(before>=max)throw Error('The Slayer Dice pool is full.');if(!await item.update({'system.resource.value':before+1}))throw Error('Could not gain a Slayer Die.');config[ID]={...config[ID],slayerGain:true};await config.message?.setFlag?.(ID,'slayerGain',{actorUuid:actor.uuid,count:before+1});return result;}finally{config.resourceUpdates=original;}};Object.defineProperty(Duality,GAIN,{value:true});}
export function slayerRollActor(config,mode){if(mode==='attack'){const actor=config.data?.parent;return config.actionType==='action'&&config.roll?.type==='attack'?actor:null;}if(config.hasHealing)return null;return config.data?.parent??game.messages.get(config.source?.message)?.system?.action?.actor??null;}
export async function promptSlayerSpend(actor,mode){const pool=slayerPool(actor),available=pool.stored+pool.temporary;if(!available)return 0;const options=Array.from({length:available},(_,i)=>`<option value="${i+1}">${i+1}d6</option>`).join(''),details=[pool.temporary&&`${pool.temporary} temporary`,pool.stored&&`${pool.stored} stored`].filter(Boolean).join(', ');return Number(await timedDialog(`Slayer Dice — ${actor.name}`,`<p>Choose Slayer Dice to include in this <strong>${mode}</strong> roll (${details}). Temporary dice are spent first.</p><select name="slayerCount" style="width:100%">${options}</select>`,[{action:'use',label:'Use Slayer Dice',callback:(_e,_b,d)=>d.element.querySelector('[name="slayerCount"]').value},{action:'cancel',label:'Do Not Use',default:true,callback:()=>0}])||0);}
export async function spendSlayer(request,{user}){if(!game.user.isActiveGM||!user?.active)return false;const actor=await fromUuid(request.actorUuid),count=Number(request.count);if(!actor?.testUserPermission(user,'OWNER')||!Number.isSafeInteger(count)||count<1)return false;const key=actor.uuid,operation=(locks.get(key)??Promise.resolve()).catch(()=>{}).then(async()=>{const pool=slayerPool(actor),temporary=temporarySlayerEffects(actor),useTemporary=Math.min(count,temporary.length),useStored=count-useTemporary;if(useStored>pool.stored)return false;const next=pool.stored-useStored;if(useStored&&!await pool.item.update({'system.resource.value':next}))return false;try{if(useTemporary){const ids=temporary.slice(0,useTemporary).map(effect=>effect.id),deleted=await actor.deleteEmbeddedDocuments('ActiveEffect',ids);if(deleted===false||ids.some(id=>temporarySlayerEffects(actor).some(effect=>effect.id===id)))throw Error('Could not spend the temporary Slayer Dice.');}return true;}catch(error){if(useStored)await pool.item.update({'system.resource.value':pool.stored});throw error;}});locks.set(key,operation);try{return await operation;}finally{if(locks.get(key)===operation)locks.delete(key);}}
function markSlayerDice(roll,count){const die=[...(roll?.dice??[])].reverse().find(entry=>Number(entry.faces)===6&&Number(entry.number??entry.results?.length)===count&&!entry.options?.[ID]?.slayerDice);if(!die)return null;die.options??={};die.options[ID]={...die.options[ID],slayerDice:true};return die;}
export function installSlayerRoll(RollClass,mode,choose=promptSlayerSpend,pay=spendSlayer){const marker=Symbol.for(`${ID}.slayerRoll.${mode}`);if(!RollClass||RollClass[marker])return;const configure=RollClass.buildConfigure,evaluate=RollClass.buildEvaluate,bonus=RollClass.prototype.applyBaseBonus;RollClass.buildConfigure=async function(config,...args){const actor=slayerRollActor(config,mode),pool=slayerPool(actor),available=pool.stored+pool.temporary;if(actor&&available){const count=await choose(actor,mode,config);if(Number.isSafeInteger(count)&&count>0&&count<=available)config[ID]={...config[ID],slayerSpend:{actorUuid:actor.uuid,count,mode,paid:false}};}return configure.call(this,config,...args);};RollClass.prototype.applyBaseBonus=function(...args){const modifiers=bonus.apply(this,args),choice=this.options?.[ID]?.slayerSpend;if(choice?.count)modifiers.push({label:'Slayer Dice',value:`${choice.count}d6`});return modifiers;};RollClass.buildEvaluate=async function(roll,config,...args){const choice=config[ID]?.slayerSpend;if(choice&&!choice.paid){const gm=game.users.activeGM;if(!gm)throw Error('Slayer Dice need an active GM.');const ok=gm.isSelf?await pay(choice,{user:game.user}):await gm.query(SPEND,choice,{timeout:20000});if(!ok)throw Error('Slayer Dice are no longer available.');choice.paid=true;roll.options[ID]={...roll.options[ID],slayerSpend:choice};}const result=await evaluate.call(this,roll,config,...args),target=mode==='attack'?roll:config.damage?.main;if(choice){markSlayerDice(target,choice.count);await rerollSlayerOnes(choice.actorUuid?await fromUuid(choice.actorUuid):null,target,async actor=>resolveWeaponReroll({actorUuid:actor.uuid},{user:game.user}));}return result;};Object.defineProperty(RollClass,marker,{value:true});}
export async function settleSlayerSession(){if(!game.user.isActiveGM)return;for(const actor of game.actors){const item=slayerItem(actor),count=slayerAvailable(item),temporary=temporarySlayerEffects(actor);if(item&&count){await item.update({'system.resource.value':0});await actor.modifyResource([{key:'hope',value:count}]);await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Slayer — ${esc(actor.name)}</strong></p><p>Cleared ${count} unspent Slayer ${count===1?'Die':'Dice'} and gained ${count} Hope.</p>`});}if(temporary.length)await actor.deleteEmbeddedDocuments('ActiveEffect',temporary.map(effect=>effect.id));}}
export function installSlayerRefresh(actions,settle=settleSlayerSession){const native=actions?.refreshActors;if(typeof native!=='function'||native[REFRESH])return;const wrapped=async function(...args){const session=game.user.isGM&&this.refreshSelections?.session?.selected,result=await native.apply(this,args);if(session)await settle();return result;};Object.defineProperty(wrapped,REFRESH,{value:true});actions.refreshActors=wrapped;}
export function registerSlayer(){CONFIG.queries[SPEND]=spendSlayer;installSlayerGain(CONFIG.Dice.daggerheart.DualityRoll);installSlayerRoll(CONFIG.Dice.daggerheart.DualityRoll,'attack');installSlayerRoll(CONFIG.Dice.daggerheart.DamageRoll,'damage');installSlayerRefresh(CONFIG.ui.daggerheartMenu?.DEFAULT_OPTIONS?.actions);installSlayerRefresh(ui.daggerheartMenu?.options?.actions);Hooks.on('renderDaggerheartMenu',app=>installSlayerRefresh(app.options.actions));}
