import {ID,featureActive} from '../core.js';
import {decisionBudget} from '../settings.js';
import {decisionNow} from '../decision-clock.js';
import {timedDialog} from '../dialog.js';
import {ownerFor} from './aura-rules.js';
import {overwhelmHits} from './overwhelm.js';
import {sourceToken} from './hallowed-aura.js';
import {meleeLimit} from './kick.js';
import {withHopeLock} from './hope-lock.js';
import {syncBeastformAttackAction} from '../beastform-roll-damage.js';
import {SNAPPING_STRIKE_KEY,SNAPPING_STRIKE_ACTION,SNAPPING_STRIKE_EFFECT} from './snapping-strike-data.js';

const QUERY=`${ID}.snappingStrike`,PROMPT=`${QUERY}Prompt`,WRAPPED=Symbol.for(`${ID}.snappingStrike`),pending=new Set();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function snappingStrikeItem(actor,requireHope=false){if(actor?.type!=='character'||requireHope&&Number(actor.system.resources?.hope?.value)<1)return null;return actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===SNAPPING_STRIKE_KEY;})??null;}
export function snappingStrikeHits(message){const actor=message?.system?.action?.actor,origin=actor&&sourceToken(actor);if(!origin||!snappingStrikeItem(actor))return[];return overwhelmHits(message).filter(hit=>{const token=canvas.tokens.get(hit.id),distance=token&&origin.distanceTo(token);return token?.actor?.uuid===hit.actorId&&Number.isFinite(distance)&&distance<=meleeLimit(canvas.scene);});}
export async function promptSnappingStrike(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.active||!actor?.testUserPermission(user,'OWNER')||!snappingStrikeItem(actor,true)||!data.targets?.length)return false;return timedDialog(`Snapping Strike — ${actor.name}`,`<p>Spend <strong>1 Hope</strong> to make one hit target within Melee temporarily <strong>Restrained</strong> and <strong>Vulnerable</strong>?</p>${data.targets.map((target,index)=>`<label style="display:block;margin:.35rem 0"><input type="radio" name="snappingTarget" value="${esc(target.id)}" ${index?'':'checked'}> ${esc(target.name)}</label>`).join('')}`,[{action:'use',label:'Spend 1 Hope',callback:(_event,_button,dialog)=>dialog.element.querySelector('[name="snappingTarget"]:checked')?.value??false},{action:'decline',label:'Decline',default:true,callback:()=>false}]);}
export async function applySnappingStrike(actor,target,message,item){const effect=item.effects?.get?.(SNAPPING_STRIKE_EFFECT),hope=Number(actor.system.resources?.hope?.value);if(!effect||hope<1)return false;const paid=await actor.update({'system.resources.hope.value':hope-1});if(!paid)throw Error('Snapping Strike could not spend Hope.');try{await game.system.api.fields.ActionFields.EffectsField.applyEffect(effect,target);await syncBeastformAttackAction(message,actor);await message.setFlag(ID,'snappingStrike',{targetUuid:target.uuid});await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Snapping Strike:</strong> ${esc(actor.name)} spends 1 Hope; ${esc(target.name)} becomes temporarily Restrained and Vulnerable.</p>`});return true;}catch(error){await actor.update({'system.resources.hope.value':hope});throw error;}}
export async function resolveSnappingStrike(request,{user},ask=promptSnappingStrike){if(!game.user.isActiveGM||!user?.active||!Number.isFinite(request.deadline)||request.deadline<decisionNow()||request.deadline>decisionNow()+decisionBudget(125000)||pending.has(request.messageUuid))return false;const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,item=snappingStrikeItem(actor,true);if(!item||!actor.testUserPermission(user,'OWNER')||message.flags?.[ID]?.snappingStrikeOffered)return false;let hits=snappingStrikeHits(message);if(!hits.length)return false;const targets=(await Promise.all(hits.map(async hit=>({id:hit.id,actorId:hit.actorId,name:(await fromUuid(hit.actorId))?.name})))).filter(target=>target.name);if(!targets.length)return false;pending.add(request.messageUuid);try{await message.setFlag(ID,'snappingStrikeOffered',true);const owner=ownerFor(actor,[...game.users],game.user),selected=owner.isSelf?await ask({actorUuid:actor.uuid,targets},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,targets},{timeout:decisionBudget(65000)});if(!selected||decisionNow()>request.deadline)return false;hits=snappingStrikeHits(message);const hit=hits.find(entry=>entry.id===selected),chosen=targets.find(entry=>entry.id===selected&&entry.actorId===hit?.actorId),target=chosen&&await fromUuid(chosen.actorId);if(!target)return false;return withHopeLock(actor.uuid,async()=>{const current=snappingStrikeItem(actor,true);if(!current||!snappingStrikeHits(message).some(entry=>entry.id===selected&&entry.actorId===target.uuid))return false;return applySnappingStrike(actor,target,message,current);});}finally{pending.delete(request.messageUuid);}}
export function installSnappingStrike(Action,dispatch){if(!Action||Action[WRAPPED])return;const native=Action.prototype.use;Action.prototype.use=async function(...args){const config=await native.apply(this,args);if(config?.message&&snappingStrikeItem(this.actor)){try{await syncBeastformAttackAction(config.message,this.actor);if(snappingStrikeItem(this.actor,true)&&snappingStrikeHits(config.message).length&&!config.message.flags?.[ID]?.snappingStrikeOffered)await dispatch({messageUuid:config.message.uuid,deadline:decisionNow()+decisionBudget(120000)});}catch(error){console.error(`${ID} | Snapping Strike failed`,error);ui.notifications?.error?.('Snapping Strike failed; the completed attack was preserved.');}}return config;};Object.defineProperty(Action,WRAPPED,{value:true});}
export function registerSnappingStrike(){CONFIG.queries[QUERY]=resolveSnappingStrike;CONFIG.queries[PROMPT]=promptSnappingStrike;const dispatch=request=>{const gm=game.users.activeGM;if(!gm)throw Error('Snapping Strike needs an active GM.');return gm.isSelf?resolveSnappingStrike(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(125000)});};installSnappingStrike(game.system.api.data.actions.actionsTypes.base,dispatch);Hooks.on('daggerheart.preUseAction',action=>{const flags=action.item?.flags?.[ID];if(action.id!==SNAPPING_STRIKE_ACTION||(flags?.applied?.key??flags?.premade?.key)!==SNAPPING_STRIKE_KEY)return;ui.notifications.info('Snapping Strike is offered automatically after a successful attack within Melee range.');return false;});}
