import {ID,clone,featureActive} from '../core.js';
import {untimedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {withHopeLock} from './hope-lock.js';
import {absorbingWrites} from './armor-absorbing.js';
import {SPEECH_KEY} from './soothing-speech-data.js';
const QUERY=ID+'.soothingSpeech',WRAP=Symbol.for(QUERY),running=new Map(),clicks=new Set(),applying=new WeakSet();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function speechItem(actor){return actor?.type==='character'?actor.items?.find(i=>{const f=i.flags?.[ID];return i.type==='domainCard'&&featureActive(i)&&!f?.disabled&&(!i.system.inVault||i.system.vaultActive)&&!i.system.isDomainTouchedSuppressed&&(f?.applied?.key??f?.premade?.key)===SPEECH_KEY;})??null:null;}
export function speechMove(message,index,actionIndex){if(!Number.isSafeInteger(index)||index<0||!Number.isSafeInteger(actionIndex)||actionIndex<0)return null;const move=message?.system?.moves?.[index],mark=move?.soothingSpeech,action=move?.actions?.[actionIndex];return move?.movePath==='shortRest.moves.tendToWounds'&&mark?.shortRest===true&&mark.actorUuid===message.system.actor&&typeof mark.itemUuid==='string'&&/^[a-zA-Z0-9]{16}$/.test(mark.restId)&&action?.type==='healing'&&action.damage?.resources?.hitPoints?{move,mark,action}:null;}
export function installSpeechRest(Downtime){if(Object.hasOwn(Downtime,WRAP))return;const take=Downtime.DEFAULT_OPTIONS.actions.takeDowntime;const wrapped=async function(...args){const item=this.shortrest===true?speechItem(this.actor):null,moves=this.moveData?.shortRest?.moves,original=moves?.tendToWounds;if(!item||!(Number(original?.selected)>0))return take.apply(this,args);const view={...original,soothingSpeech:{shortRest:true,restId:foundry.utils.randomID(),actorUuid:this.actor.uuid,itemUuid:item.uuid}};moves.tendToWounds=view;try{return await take.apply(this,args);}finally{if(moves.tendToWounds===view){original.selected=view.selected;moves.tendToWounds=original;}}};Downtime.DEFAULT_OPTIONS.actions.takeDowntime=wrapped;Downtime.takeDowntime=wrapped;Object.defineProperty(Downtime,WRAP,{value:true});}
export async function promptSpeech(caster,target){return Boolean(await untimedDialog('Soothing Speech',`<p>Take time to comfort <strong>${esc(target.name)}</strong> while tending their wounds?</p><p>They clear <strong>1 additional HP</strong>, and you clear <strong>2 HP</strong>.</p>`,[{action:'comfort',label:'Comfort Them',default:true,callback:()=>true},{action:'normal',label:'Tend Normally',callback:()=>false}]));}
async function speechContext(request,user){if(typeof request?.messageUuid!=='string'||typeof request?.targetUuid!=='string')return null;const message=await fromUuid(request.messageUuid),move=speechMove(message,request.moveIndex,request.actionIndex);if(!move)return null;const caster=await fromUuid(move.mark.actorUuid),item=speechItem(caster),target=await fromUuid(request.targetUuid);return item?.uuid===move.mark.itemUuid&&caster.testUserPermission(user,'OWNER')&&target?.type==='character'&&target.uuid!==caster.uuid&&target.testUserPermission(user,'LIMITED')?{message,move,caster,item,target}:null;}
const rowKey=r=>r.moveIndex+':'+r.actionIndex;
async function saveRow(message,key,row){const rows={...message.flags?.[ID]?.soothingSpeech,[key]:row};if(!await message.setFlag(ID,'soothingSpeech',rows))throw Error('Could not save Soothing Speech resolution.');}
export async function resolveSpeech(request,{user}){if(!game.user.isActiveGM||!user?.active||!['begin','cancel','apply'].includes(request?.op))return false;const context=await speechContext(request,user);if(!context)return false;const {message,move,caster,item,target}=context,key=rowKey(request);return withHopeLock('soothing-speech:recovery',async()=>{
 if(!user.active||!await speechContext(request,user))return false;const row=message.flags?.[ID]?.soothingSpeech?.[key];
 if(request.op==='begin'){if(row)return false;const ticket=foundry.utils.randomID(),record={ticket,state:'pending',casterUuid:caster.uuid,itemUuid:item.uuid,targetUuid:target.uuid,restId:move.mark.restId};await saveRow(message,key,record);return {...record,messageUuid:message.uuid,moveIndex:request.moveIndex,actionIndex:request.actionIndex};}
 if(!row||row.ticket!==request.ticket||row.targetUuid!==target.uuid||row.casterUuid!==caster.uuid||row.itemUuid!==item.uuid)return false;
 if(request.op==='cancel'){if(row.state==='pending')await saveRow(message,key,{...row,state:'canceled'});return false;}
 if(row.state==='completed')return {completed:true,allyCleared:row.allyCleared,casterCleared:row.casterCleared};if(row.state==='prevented')return {completed:false,prevented:true};if(row.state!=='pending'||typeof request.healingMessageUuid!=='string')return false;
 const healing=await fromUuid(request.healingMessageUuid),proof=healing?.flags?.[ID]?.soothingSpeechHealing,hp=healing?.system?.damage?.resources?.hitPoints,origin=healing?.system?.source?.originItem;if(!proof||proof.ticket!==row.ticket||proof.messageUuid!==message.uuid||proof.targetUuid!==target.uuid||proof.casterUuid!==caster.uuid||proof.moveIndex!==request.moveIndex||proof.actionIndex!==request.actionIndex||healing.system.source?.actor!==caster.uuid||origin?.type!==CONFIG.DH.ITEM.originItemType.restMove||origin.itemPath!=='shortRest.moves.tendToWounds'||Number(origin.actionIndex)!==request.actionIndex||!healing.system.hasHealing||!Number.isFinite(hp?.total)||hp.total<0)return false;
 if(game.dice3d)await game.dice3d.waitFor3DAnimationByMessageID(healing.id);
 if(!user.active||!await speechContext(request,user))return false;
 await saveRow(message,key,{...row,state:'applying',healingMessageUuid:healing.uuid});
 const beforeAlly=Number(target.system.resources.hitPoints.value),beforeCaster=Number(caster.system.resources.hitPoints.value);applying.add(target);
 try{const result=await absorbingWrites(target,()=>target.takeHealing(healing.system.damage));if(result===null){await saveRow(message,key,{...row,state:'prevented'});return {completed:false,prevented:true};}if(!Array.isArray(result))throw Error('Could not confirm Tend to Wounds recovery.');await absorbingWrites(caster,()=>caster.takeHealing({resources:{hitPoints:2}}));const allyCleared=beforeAlly-Number(target.system.resources.hitPoints.value),casterCleared=beforeCaster-Number(caster.system.resources.hitPoints.value);await saveRow(message,key,{...row,state:'completed',healingMessageUuid:healing.uuid,allyCleared,casterCleared});try{await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:caster}),content:`<p><strong>Soothing Speech:</strong> ${esc(target.name)} cleared ${allyCleared} HP (including the +1 bonus); ${esc(caster.name)} cleared ${casterCleared} HP.</p>`});}catch(error){console.warn(ID+' | Soothing Speech notification',error);}return {completed:true,allyCleared,casterCleared};}
 catch(error){ui.notifications.error('Soothing Speech stopped. Preserve any completed healing and review the remaining recovery manually: '+error.message);throw error;}finally{applying.delete(target);}
 });}
export function speechBonus(source,formula){const data=clone(source),hp=data.damage?.resources?.hitPoints;if(!hp||typeof formula!=='string'||!formula.trim())throw Error('Tend to Wounds has no supported HP recovery formula.');hp.value={...hp.value,custom:{enabled:true,formula:`(${formula}) + 1`}};return data;}
export async function launchSpeech(parent,source,event,record,send){const caster=await fromUuid(record.casterUuid);if(!caster||!speechItem(caster))throw Error('Soothing Speech caster is no longer available.');const cls=game.system.api.models.actions.actionsTypes[source.type],base=new cls({...clone(source),_id:foundry.utils.randomID(),name:game.i18n.localize(source.name),targetUuid:parent.uuid,originItem:{type:CONFIG.DH.ITEM.originItemType.restMove,itemPath:'shortRest.moves.tendToWounds',actionIndex:record.actionIndex}},{parent:caster.system}),formula=base.damage.resources.hitPoints.value.getFormula(),action=new cls({...speechBonus(source,formula),_id:base.id,name:base.name,targetUuid:parent.uuid,originItem:base.originItem},{parent:caster.system});const parts=action.workflow,apply=parts.get('applyDamage'),damage=parts.get('damage');if(!apply||!damage)throw Error('Native Tend to Wounds workflow is missing.');running.set(action.id,record);let applied=false;
 const marked={...damage,execute:async(...args)=>{const result=await damage.execute(...args),config=args[0],message=config.message;if(result===false)return false;if(!message||!config.damage?.resources?.hitPoints)throw Error('Tend to Wounds has no completed healing card.');const meta={...record,healingMessageUuid:message.uuid};config.damage.resources.hitPoints.options[ID]={...config.damage.resources.hitPoints.options[ID],soothingSpeech:meta};const serialized={...config.damage.toObject(),resources:Object.fromEntries(Object.entries(config.damage.resources).map(([k,v])=>[k,v.toJSON()]))};if(!await message.update({'system.damage':serialized,['flags.'+ID+'.soothingSpeechHealing']:record}))throw Error('Could not save Soothing Speech healing provenance.');}};
 const resolve={...apply,execute:async config=>{const message=config.message;if(!message)throw Error('Tend to Wounds has no healing message.');const result=await send({...record,op:'apply',healingMessageUuid:message.uuid});if(!result?.completed&&!result?.prevented)throw Error('Soothing Speech recovery was not confirmed.');applied=true;}};parts.set('damage',marked);parts.set('applyDamage',resolve);
 try{const result=await action.use(event??{shiftKey:false});if(!applied)await send({...record,op:'cancel'});return result;}finally{if(parts.get('damage')===marked)parts.set('damage',damage);if(parts.get('applyDamage')===resolve)parts.set('applyDamage',apply);running.delete(action.id);}
}
// Native chat listeners normally pass document.toObject(false), without a UUID.
// Keep the actual button available after awaiting context/consent: DOM dispatch
// clears Event.currentTarget as soon as the listener returns its promise.
export function installSpeechChat(Log,send,ask=promptSpeech,launch=launchSpeech){if(Object.hasOwn(Log,WRAP))return;const native=Log.prototype.actionUseButton;Log.prototype.actionUseButton=async function(event,snapshot){const button=event.currentTarget,data=button.dataset,moveIndex=Number(data.moveIndex),actionIndex=Number(data.actionIndex),message=game.messages.get(snapshot._id??snapshot.id)??snapshot,move=speechMove(message,moveIndex,actionIndex);if(!move)return native.call(this,event,snapshot);const capturedEvent=new Proxy(event,{get(target,key){if(key==='currentTarget')return button;const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;}}),targetUuid=button.closest('.action-use-button-parent').querySelector('select')?.value,request={messageUuid:message.uuid,moveIndex,actionIndex,targetUuid},key=message.uuid+':'+rowKey(request);if(clicks.has(key)||message.flags?.[ID]?.soothingSpeech?.[rowKey(request)])return;clicks.add(key);try{const context=await speechContext(request,game.user);if(!context||!await ask(context.caster,context.target))return native.call(this,capturedEvent,snapshot);const record=await send({...request,op:'begin'});if(!record)return;return await launch(context.target,move.action,capturedEvent,record,send);}catch(error){console.error(ID+' | Soothing Speech',error);ui.notifications.error('Soothing Speech needs manual review: '+error.message);}finally{clicks.delete(key);}};Object.defineProperty(Log,WRAP,{value:true});}
export function installSpeechHealing(Actor,send){if(Object.hasOwn(Actor,WRAP))return;const native=Actor.prototype.takeHealing;Actor.prototype.takeHealing=async function(packet,...args){const meta=packet?.resources?.hitPoints?.options?.[ID]?.soothingSpeech;if(!meta||applying.has(this))return native.call(this,packet,...args);const result=await send({...meta,op:'apply'});return result?.completed||result?.prevented?[]:null;};Object.defineProperty(Actor,WRAP,{value:true});}
export function tagSpeechHealing(message){const record=running.get(message.system?.source?.action);if(record&&message.system.source.actor===record.casterUuid&&message.system.hasHealing)message.updateSource({['flags.'+ID+'.soothingSpeechHealing']:record});}
export function registerSpeech(){CONFIG.queries[QUERY]=resolveSpeech;const send=request=>{const gm=game.users.activeGM;if(!gm)throw Error('Soothing Speech needs an active GM.');return gm.isSelf?resolveSpeech(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(600000)});};installSpeechRest(game.system.api.applications.dialogs.Downtime);installSpeechChat(CONFIG.ui.chat,send);installSpeechHealing(CONFIG.Actor.documentClass,send);Hooks.on('preCreateChatMessage',tagSpeechHealing);}
