import {ID,featureActive} from '../core.js';
import {SPIRIT_KEY,SPIRIT_ACTION} from './spirit-weapon-data.js';
import {sourceToken} from './hallowed-aura.js';
import {closeDistance,ownerFor} from './aura-rules.js';
import {markReactiveStress} from './stress-payment.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
const QUERY=`${ID}.spiritWeapon`,PROMPT=`${ID}.spiritWeaponPrompt`,WRAPPED=Symbol.for(`${ID}.spiritWeapon`),pending=new Set();
export function spiritItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===SPIRIT_KEY;})??null:null;}
export function spiritAttack(action){return Boolean(spiritItem(action?.actor)&&action.type==='attack'&&action.item?.type==='weapon'&&action.item.system?.equipped&&['melee','veryClose'].includes(action.range));}
const settings=()=>game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement;
export function spiritTargets(actor,targets){const origin=sourceToken(actor),limit=origin?closeDistance(canvas.scene,settings(),CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id):NaN;if(!origin||targets?.length!==2||!Number.isFinite(limit))return [];const seen=new Set(),eligible=targets.map(target=>canvas.tokens.get(target.id)).filter(token=>{const distance=token&&origin.distanceTo(token),valid=token?.actor?.type==='adversary'&&token.actor.uuid!==actor.uuid&&token.actor.uuid===targets.find(t=>t.id===token.id)?.actorId&&!token.document.hidden&&!seen.has(token.actor.uuid)&&Number.isFinite(distance)&&distance<=limit;if(valid)seen.add(token.actor.uuid);return valid;});return eligible.length===2?eligible:[];}
export async function promptSpirit(data,{user}){const actor=await fromUuid(data.actorUuid);if(!user?.isGM||!actor?.testUserPermission(game.user,'OWNER')||!spiritItem(actor))return false;return Boolean(await timedDialog(`Spirit Weapon — ${actor.name}`,'<p>Mark <strong>1 Stress</strong> to target both selected adversaries with this attack roll?</p>',[{action:'use',label:'Mark 1 Stress',callback:()=>true},{action:'decline',label:'Cancel Attack',default:true,callback:()=>false}]));}
export async function resolveSpirit(request,{user},ask=promptSpirit){if(!game.user.isActiveGM||!user?.active||pending.has(request.actorUuid))return false;const actor=await fromUuid(request.actorUuid),weapon=await fromUuid(request.weaponUuid);if(!actor?.testUserPermission(user,'OWNER')||weapon?.actor?.uuid!==actor.uuid||weapon.type!=='weapon'||!weapon.system.equipped||!['melee','veryClose'].includes(weapon.system.attack?.range)||!spiritItem(actor)||spiritTargets(actor,request.targets).length!==2)return false;pending.add(actor.uuid);try{const owner=ownerFor(actor,[...game.users],game.user),accepted=owner.isSelf?await ask({actorUuid:actor.uuid},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid},{timeout:decisionBudget(65000)});if(!accepted||spiritTargets(actor,request.targets).length!==2)return false;return markReactiveStress(actor.uuid,current=>Boolean(spiritItem(current)&&weapon.system.equipped&&['melee','veryClose'].includes(weapon.system.attack?.range)&&spiritTargets(current,request.targets).length===2));}finally{pending.delete(actor.uuid);}}
export function installSpiritWeapon(Duality,offer){if(Duality[WRAPPED])return;const configure=Duality.buildConfigure;Duality.buildConfigure=async function(config,...args){const roll=await configure.call(this,config,...args),request=config[ID]?.spiritWeapon;if(!roll||!request||config[ID].spiritWeaponPaid)return roll;if(!await offer(request))return null;config[ID].spiritWeaponPaid=true;return roll;};Object.defineProperty(Duality,WRAPPED,{value:true});}
export function registerSpiritWeapon(){CONFIG.queries[QUERY]=resolveSpirit;CONFIG.queries[PROMPT]=promptSpirit;installSpiritWeapon(CONFIG.Dice.daggerheart.DualityRoll,request=>{const gm=game.users.activeGM;if(!gm)throw new Error('Spirit Weapon needs an active GM.');return gm.isSelf?resolveSpirit(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(75000)});});Hooks.on('daggerheart.preUseAction',(action,config)=>{const flags=action.item?.flags?.[ID];if(action.id===SPIRIT_ACTION&&(flags?.applied?.key??flags?.premade?.key)===SPIRIT_KEY){ui.notifications.info('Select two adversaries, then make an attack with an equipped Melee or Very Close weapon.');return false;}if(!spiritAttack(action)||config.targets?.length!==2)return;const targets=config.targets.map(t=>({id:t.id,actorId:t.actorId}));if(spiritTargets(action.actor,targets).length!==2){ui.notifications.warn('Spirit Weapon requires two different adversaries within Close range.');return false;}config[ID]={...config[ID],spiritWeapon:{actorUuid:action.actor.uuid,weaponUuid:action.item.uuid,targets}};});}
