import {ID,featureActive} from '../core.js';
import {attackHitTargets} from '../attack-outcome.js';
import {timedDialog} from '../dialog.js';
import {decisionBudget} from '../settings.js';
import {ownerFor} from './aura-rules.js';
import {withHopeLock} from './hope-lock.js';
import {absorbingWrites} from './armor-absorbing.js';
import {bulkyDamagePacket} from './armor-bulky.js';
import {HORROR_KEY,HORROR_ACTION} from './summon-horror-data.js';
const QUERY=ID+'.summonHorrorDamage',REACTION=ID+'.summonHorrorReaction',DAMAGE=Symbol.for(QUERY),TAG=Symbol.for(QUERY+'Tag'),requests=new Map(),followups=new Map();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=v=>typeof v==='string'&&/^[a-zA-Z0-9]{16}$/.test(v),rows=m=>m.flags?.[ID]?.summonHorror??[];
export function horrorItem(actor){return actor?.type==='character'?actor.items?.find(i=>{const f=i.flags?.[ID],s=i.system;return i.type==='domainCard'&&featureActive(i)&&!f?.disabled&&(!s.inVault||s.vaultActive)&&!s.isDomainTouchedSuppressed&&(f?.applied?.key??f?.premade?.key)===HORROR_KEY;})??null:null;}
export function horrorAttack(message){const action=message?.system?.action,item=horrorItem(action?.actor);return item&&item.uuid===action.item?.uuid&&action.id===HORROR_ACTION&&action.type==='attack'&&action.actionType!=='reaction'&&message.system.roll?.options?.actionType!=='reaction'&&message.system.roll?._evaluated!==false&&Number.isFinite(message.system.roll?.total)?{message,actor:action.actor,item}:null;}
export function tagHorrorDamage(config){const context=horrorAttack(game.messages.get(config.source?.message)),main=config.damage?.main;if(config.hasHealing||!main||!context)return false;main.options??={};main.options[ID]={...main.options[ID],summonHorror:{messageUuid:context.message.uuid,actorUuid:context.actor.uuid,itemUuid:context.item.uuid}};const damage=config.damage;if(typeof damage.toObject==='function')config.damage=new damage.constructor({...damage.toObject(),main:main.toJSON(),resources:Object.fromEntries(Object.entries(damage.resources??{}).map(([k,r])=>[k,r.toJSON()]))});return true;}
export const horrorSource=packet=>(packet?.main??packet?.damage??packet)?.options?.[ID]?.summonHorror;
export async function horrorContext(packet,target){const source=horrorSource(packet);if(!source||typeof source.messageUuid!=='string')return null;const context=horrorAttack(await fromUuid(source.messageUuid));if(!context||context.actor.uuid!==source.actorUuid||context.item.uuid!==source.itemUuid||!['character','adversary'].includes(target?.type))return null;const main=packet?.main??packet?.damage??packet;if(!attackHitTargets(context.message).some(t=>t.actorId===target.uuid)&&!main?.options?.[ID]?.loyalRedirect)return null;return context;}
export function horrorHP(actor,updates,before,excluded=0,overflow=new WeakMap()){const marked=Number(actor.system.resources?.hitPoints?.value)-before,receipt=Array.isArray(updates)?updates.filter(r=>r.key==='hitPoints'&&!r.itemId&&!r.clear&&r.damageTypes&&Number.isSafeInteger(r.value)&&r.value>0).reduce((n,r)=>n+r.value-(overflow.get(r)??0),0)-excluded:0,count=Math.min(marked,receipt);return Number.isSafeInteger(count)&&count>0?count:0;}
async function writeReceipt(message,row){await withHopeLock('horror-receipt:'+message.uuid,async()=>{const current=rows(message),next=[...current.filter(r=>r.targetUuid!==row.targetUuid),row];await message.setFlag(ID,'summonHorror',next);if(!rows(message).some(r=>r.targetUuid===row.targetUuid&&r.id===row.id&&r.state===row.state))throw Error('Summon Horror could not save its reaction receipt.');});}
export async function chooseHorrorTrait(actor){return timedDialog('Summon Horror — Reaction Trait',`<p>${esc(actor.name)}: choose a trait for your Reaction Roll (12).</p><label>Trait<select name="trait">${['agility','strength','finesse','instinct','presence','knowledge'].map(t=>`<option value="${t}">${esc(game.i18n.localize(CONFIG.DH.ACTOR.abilities[t]?.label??t))}</option>`).join('')}</select></label>`,[{action:'roll',label:'Roll Reaction',callback:(_e,_b,d)=>d.element.querySelector('[name="trait"]').value},{action:'cancel',label:'Cancel',default:true,callback:()=>null}]);}
export async function rollHorrorReaction(data,{user},choose=chooseHorrorTrait){if(!user?.isGM||!user.active||!id(data?.id)||!Number.isSafeInteger(data.hp)||data.hp<1)return null;const actor=await fromUuid(data.targetUuid),context=horrorAttack(await fromUuid(data.attackUuid)),pending=context&&rows(context.message).find(r=>r.id===data.id&&r.targetUuid===data.targetUuid&&r.hp===data.hp&&r.state==='pending');if(!actor||!context||!pending||!actor.testUserPermission(game.user,'OWNER'))return null;const trait=actor.type==='character'?await choose(actor):null;if(actor.type==='character'&&!['agility','strength','finesse','instinct','presence','knowledge'].includes(trait))return null;if(!actor.testUserPermission(game.user,'OWNER')||!game.user.active)return null;
 const result=await actor.diceRoll({event:{shiftKey:false},title:'Summon Horror — Reaction Roll (12)',roll:{type:'trait',trait,difficulty:12},actionType:'reaction',hasRoll:true,dialog:{configure:true},data:actor.getRollData()});if(!result?.message||!Number.isFinite(result.roll?.total))return null;await result.message.setFlag(ID,'summonHorrorReaction',{id:data.id,attackUuid:data.attackUuid,targetUuid:actor.uuid,hp:data.hp});if(game.dice3d)await game.dice3d.waitFor3DAnimationByMessageID(result.message.id);return {messageUuid:result.message.uuid};}
export async function finishHorror(context,target,hp,ask=rollHorrorReaction){const key=context.message.uuid+':'+target.uuid,old=followups.get(key);if(old)return old;if(rows(context.message).some(r=>r.targetUuid===target.uuid))return false;
 const operation=(async()=>{const row={id:foundry.utils.randomID(),targetUuid:target.uuid,hp,state:'pending'};await writeReceipt(context.message,row);if(game.dice3d)await game.dice3d.waitFor3DAnimationByMessageID(context.message.id);const owner=ownerFor(target,[...game.users],game.user),data={id:row.id,targetUuid:target.uuid,attackUuid:context.message.uuid,hp};const response=owner.isSelf?await ask(data,{user:game.user}):await owner.query(REACTION,data,{timeout:decisionBudget(300000)});if(!response){await writeReceipt(context.message,{...row,state:'canceled'});ui.notifications.warn('Summon Horror: finish the canceled reaction and any Stress manually. Do not apply the attack’s damage again.');return false;}
 const message=await fromUuid(response.messageUuid),roll=message?.system?.roll??message?.rolls?.[0],proof=message?.flags?.[ID]?.summonHorrorReaction;if(!game.user.isActiveGM||!owner.active||!target.testUserPermission(owner,'OWNER')||message?.system?.source?.actor!==target.uuid||proof?.id!==row.id||proof.attackUuid!==context.message.uuid||proof.targetUuid!==target.uuid||proof.hp!==hp||!Number.isFinite(roll?.total)||(roll.options?.actionType??message.system.actionType)!=='reaction')throw Error('Summon Horror reaction result could not be verified.');
 const success=Boolean(roll.isCritical||roll.total>=12);if(!success){await writeReceipt(context.message,{...row,state:'applying',reactionUuid:message.uuid});await withHopeLock('horror-stress:'+target.uuid,()=>absorbingWrites(target,()=>target.takeDamage({resources:{stress:hp}},true)));}
 await writeReceipt(context.message,{...row,state:success?'success':'failed',reactionUuid:message.uuid});try{await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:context.actor}),content:`<p><strong>Summon Horror:</strong> ${esc(target.name)} ${success?'succeeds on the Reaction Roll; no extra Stress.':`fails the Reaction Roll and takes ${hp} Stress from ${hp} HP marked.`}</p>`});}catch(error){console.warn(ID+' | Summon Horror notification',error);}return {hp,success};
 })();followups.set(key,operation);if(followups.size>512)followups.delete(followups.keys().next().value);return operation;}
export async function resolveHorrorDamage(request,{user}){if(!game.user.isActiveGM||!user?.active||!id(request?.id)||typeof request.targetUuid!=='string'||typeof request.isDirect!=='boolean')return null;const key=user.id+':'+request.id,sig=JSON.stringify(request),old=requests.get(key);if(old)return old.sig===sig?old.promise:null;const promise=(async()=>{const target=await fromUuid(request.targetUuid),packet=bulkyDamagePacket(request.packet),context=target&&packet&&await horrorContext(packet,target);if(!context||!user.isGM&&!target.testUserPermission(user,'OWNER')&&!context.actor.testUserPermission(user,'OWNER'))return null;return {result:await target.takeDamage(packet,request.isDirect)};})();requests.set(key,{sig,promise});if(requests.size>512)requests.delete(requests.keys().next().value);return promise;}
export function installHorror(Damage,Actor,send,ask=rollHorrorReaction){if(Damage&&!Object.hasOwn(Damage,TAG)){const evaluate=Damage.buildEvaluate,post=Damage.buildPost;Damage.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);tagHorrorDamage(config);return result;};Damage.buildPost=async function(roll,config,...args){tagHorrorDamage(config);return post.call(this,roll,config,...args);};Object.defineProperty(Damage,TAG,{value:true});}
 if(!Actor||Object.hasOwn(Actor,DAMAGE))return;const take=Actor.prototype.takeDamage,convert=Actor.prototype.convertStressDamageToHP,captures=new WeakMap();Actor.prototype.convertStressDamageToHP=function(resources,...args){const capture=captures.get(this),before=new Map(resources.filter(r=>r.key==='hitPoints').map(r=>[r,Number(r.value)||0])),result=convert.call(this,resources,...args);if(capture)for(const r of resources.filter(r=>r.key==='hitPoints')){const added=(Number(r.value)||0)-(before.get(r)??0);if(added>0)capture.set(r,(capture.get(r)??0)+added);}return result;};
 Actor.prototype.takeDamage=async function(packet,...args){if(!horrorSource(packet)||!bulkyDamagePacket(packet))return take.call(this,packet,...args);const context=await horrorContext(packet,this);if(!context)return take.call(this,packet,...args);if(!game.user.isActiveGM){const response=await send({id:foundry.utils.randomID(),targetUuid:this.uuid,packet:bulkyDamagePacket(packet),isDirect:Boolean(args[0])});if(!response||!Object.hasOwn(response,'result'))throw Error('Summon Horror damage coordination failed. Review damage before continuing.');return response.result;}
 const completed=await withHopeLock('horror-damage:'+this.uuid,async()=>{const before=Number(this.system.resources?.hitPoints?.value),overflow=new WeakMap(),prior=captures.get(this),resource=packet.resources?.hitPoints,excluded=resource?.options?.itemId||resource?.options?.fullRestore?0:Math.max(0,Number(typeof resource==='number'?resource:resource?.total)||0);captures.set(this,overflow);try{const result=await absorbingWrites(this,()=>take.call(this,packet,...args));return {result,hp:horrorHP(this,result,before,excluded,overflow)};}finally{if(prior)captures.set(this,prior);else captures.delete(this);}});
 if(completed.hp)try{await finishHorror(context,this,completed.hp,ask);}catch(error){console.error(ID+' | Summon Horror follow-up',error);ui.notifications.error('Summon Horror damage completed, but the reaction/Stress needs manual review. Do not repeat damage: '+error.message);}return completed.result;};Object.defineProperty(Actor,DAMAGE,{value:true});}
export function registerHorror(){CONFIG.queries[QUERY]=resolveHorrorDamage;CONFIG.queries[REACTION]=rollHorrorReaction;installHorror(CONFIG.Dice.daggerheart.DamageRoll,CONFIG.Actor.documentClass,r=>{const gm=game.users.activeGM;if(!gm)throw Error('Summon Horror needs an active GM.');return gm.isSelf?resolveHorrorDamage(r,{user:game.user}):gm.query(QUERY,r,{timeout:decisionBudget(600000)});});}
