import {ID,featureActive} from '../core.js';
import {decisionNow} from '../decision-clock.js';import {decisionBudget} from '../settings.js';
import {criticalRerollResult} from '../roll-rerolls.js';import {markRerolledDice} from '../reroll-indicators.js';
import {timedDialog} from '../dialog.js';import {sourceToken} from './hallowed-aura.js';
import {ownerFor,unavailableActor} from './aura-rules.js';import {adaptabilityOutcome} from './adaptability.js';
import {withHopeLock} from './hope-lock.js';import {hopeCapacity,spendHope,isHopePaymentCancellation} from './hope-payment.js';
import {consumeResolutionTicket,resolutionTicketStatus} from '../resolution-manager.js';
import {SUPPORT_KEY,SUPPORT_ACTION} from './support-tank-data.js';
const QUERY=ID+'.supportTank',PROMPT=QUERY+'Consent',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const identity=a=>a?.token?.baseActor?.uuid??a?.uuid;
export function supportAvailable(item){const f=item?.flags?.[ID],s=item?.system;return Boolean(item?.type==='domainCard'&&item.actor?.type==='character'&&!unavailableActor(item.actor)&&featureActive(item)&&!f?.disabled&&(!s.inVault||s.vaultActive)&&!s.isDomainTouchedSuppressed&&(f?.applied?.key??f?.premade?.key)===SUPPORT_KEY&&hopeCapacity(item.actor)>=2);}
export function supportRange(bearer,source){if(source?.type!=='character'||unavailableActor(source)||identity(bearer)===identity(source)||!globalThis.canvas?.ready)return false;const a=sourceToken(bearer),b=sourceToken(source);if(!a||!b||a.document.hidden||b.document.hidden||a.document.disposition!==1||b.document.disposition!==1)return false;const rules=game.system.settings.variantRules?.rangeMeasurement??game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement,local=canvas.scene.flags?.daggerheart?.rangeMeasurement,limit=Number(canvas.scene.rangeSettings?.close??(rules?.enabled&&local?.setting==='custom'?local.close:rules?.close)),distance=a.distanceTo(b);return Number.isFinite(limit)&&limit>=0&&Number.isFinite(distance)&&distance<=limit;}
export function supportCandidates(source){const actors=new Map([...(game.actors?.[Symbol.iterator]?game.actors:game.actors?.contents??[])].map(a=>[a.uuid,a]));for(const t of globalThis.canvas?.tokens?.placeables??[])if(t.actor)actors.set(t.actor.uuid,t.actor);return [...actors.values()].flatMap(a=>{const items=[...(a.items??[])].filter(supportAvailable);return items.length&&supportRange(a,source)?items.map(i=>({itemUuid:i.uuid})):[];});}
export async function validateSupport(r,user){if(!user?.active||!['action','reaction'].includes(r?.actionType)||criticalRerollResult(r)||r.convertedSuccess||!Number.isFinite(r.deadline)||r.deadline<=decisionNow()||![r.total,r.hope,r.fear].every(Number.isFinite))return null;const source=await fromUuid(r.sourceUuid),item=await fromUuid(r.candidate?.itemUuid),bearer=item?.actor;if(!source?.testUserPermission(user,'OWNER')||!supportAvailable(item)||!supportRange(bearer,source))return null;const outcome=adaptabilityOutcome(r.total,r.critical,r.difficulty,r.targets);return outcome==='success'?null:{source,item,bearer,outcome};}
export async function promptSupport(data,{user}){const source=await fromUuid(data.sourceUuid),item=await fromUuid(data.itemUuid);if(!user?.active||!user.isGM||!source?.testUserPermission(game.user,'OWNER')||!supportAvailable(item)||!supportRange(item.actor,source))return null;return timedDialog('Support Tank — '+source.name,`<p>${esc(item.actor.name)} offers to spend 2 Hope so you can reroll one Duality Die. The new result replaces that die before consequences.</p>`,[{action:'hope',label:'Reroll Hope Die',callback:()=> 'hope'},{action:'fear',label:'Reroll Fear Die',callback:()=> 'fear'},{action:'decline',label:'Keep this roll',default:true,callback:()=>null}]);}
export async function resolveSupport(r,{user},authorize=consumeResolutionTicket,ask=promptSupport){
 if(!game.user.isActiveGM||!Number.isFinite(r?.deadline)||r.deadline>decisionNow()+decisionBudget(125000))return false;let valid=await validateSupport(r,user);if(!valid||!authorize(r.resolutionToken,'support',valid.item.uuid,user))return false;
 const recipient=ownerFor(valid.source,[...game.users],game.user),holder=ownerFor(valid.bearer,[...game.users],game.user);if(!recipient?.active||!holder?.active)return false;
 await resolutionTicketStatus(r.resolutionToken,'Choosing a die');const data={sourceUuid:valid.source.uuid,itemUuid:valid.item.uuid},die=recipient.isSelf?await ask(data,{user:game.user}):await recipient.query(PROMPT,data,{timeout:decisionBudget(65000)});await resolutionTicketStatus(r.resolutionToken,'Resolving');if(!['hope','fear'].includes(die)||!recipient.active)return false;
 return withHopeLock(valid.bearer.uuid,async()=>{try{valid=await validateSupport(r,user);if(!valid||!game.user.isActiveGM||!recipient.active||!holder.active||!valid.source.testUserPermission(recipient,'OWNER')||!valid.bearer.testUserPermission(holder,'OWNER'))return false;if(!await spendHope(valid.bearer,2,{label:'Support Tank'}))throw Error('Could not pay Support Tank.');return {itemUuid:valid.item.uuid,bearerName:valid.bearer.name,die};}catch(error){if(isHopePaymentCancellation(error))return false;throw error;}});
}
export async function rerollSupportDie(roll,which){if(!['hope','fear'].includes(which))throw Error('Invalid Support Tank die.');const original=which==='hope'?roll.dHope:roll.dFear,position=roll.terms.indexOf(original);if(position<0)throw Error('Could not find the selected Duality Die.');const options={...original.options};delete options.sfx;const die=new original.constructor({number:original.number,faces:original.faces,modifiers:[...original.modifiers],options}),pair=foundry.dice.Roll.fromTerms([die]);await pair.evaluate();markRerolledDice([die]);roll.terms[position]=die;roll._total=roll._evaluateTotal();return pair;}
export function registerSupportTank(){CONFIG.queries[QUERY]=resolveSupport;CONFIG.queries[PROMPT]=promptSupport;Hooks.on('daggerheart.preUseAction',action=>{if(action.id===SUPPORT_ACTION&&supportAvailable(action.item)){ui.notifications.info('Offer Support Tank in Roll Resolution after a nearby ally fails a roll.');return false;}});Hooks.on('renderChatMessageHTML',(message,html)=>{const uses=message.system?.roll?.options?.[ID]?.supportTank;if(!uses?.length||!message.isContentVisible||html.querySelector('.dhp-support-note'))return;const p=html.ownerDocument.createElement('p');p.className='dhp-support-note';p.textContent=uses.map(u=>`Support Tank: ${u.bearerName} spent 2 Hope to reroll the ${u.die==='hope'?'Hope':'Fear'} Die.`).join(' ');html.querySelector('.message-content')?.append(p);});}
