import {ID,featureActive} from '../core.js';
import {decisionBudget} from '../settings.js';
import {overwhelmHits} from './overwhelm.js';
import {TAKEDOWN_KEY} from './takedown-data.js';
const QUERY=`${ID}.takedown`,WRAPPED=Symbol.for(`${ID}.takedown`),seen=new Set();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function takedownItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===TAKEDOWN_KEY;})??null:null;}
export function takedownEffects(actor,item=takedownItem(actor)){if(!item)return[];const origin=item.effects?.find?.(effect=>effect.flags?.[ID]?.takedown)?.uuid??item.effects?.get?.('BuKQ4yMAFebxj83k')?.uuid;return[...(actor?.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&(effect.flags?.[ID]?.takedown||origin&&effect.origin===origin));}
export function takedownHits(message){return message?.system?.action?.type==='attack'?overwhelmHits(message):[];}
export async function resolveTakedown(request,{user}){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||seen.has(request.id))return false;seen.add(request.id);const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,item=takedownItem(actor);if(!item||!actor.testUserPermission(user,'OWNER')||!request.effectIds?.some(id=>takedownEffects(actor,item).some(effect=>effect.id===id)))return false;const hits=takedownHits(message).filter(hit=>request.targetIds?.includes(hit.id)),marked=[];for(const hit of hits){const target=await fromUuid(hit.actorId);if(!target)continue;await target.modifyResource([{key:'stress',value:1}]);marked.push(target.name);}if(marked.length){await message.update({[`flags.${ID}.takedown`]:{targets:hits.map(hit=>hit.id)}});await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Takedown:</strong> ${marked.map(esc).join(', ')} ${marked.length===1?'marks':'mark'} 1 Stress.</p>`});}return marked.length;}
async function dispatch(request){const gm=game.users.activeGM;if(!gm)throw Error('Takedown needs an active GM.');return gm.isSelf?resolveTakedown(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(65000)});}
export function installTakedown(Action,send=dispatch){if(!Action||Action[WRAPPED])return;const native=Action.prototype.use;Action.prototype.use=async function(...args){const effectIds=takedownEffects(this.actor).map(effect=>effect.id),config=await native.apply(this,args);if(!config||!effectIds.length)return config;try{if(!config.message?.flags?.[ID]?.takedown){const hits=takedownHits(config.message);if(hits.length)await send({id:foundry.utils.randomID(),messageUuid:config.message.uuid,effectIds,targetIds:hits.map(hit=>hit.id)});}}finally{const current=effectIds.filter(id=>this.actor.effects?.get?.(id));if(current.length)await this.actor.deleteEmbeddedDocuments('ActiveEffect',current);}return config;};Object.defineProperty(Action,WRAPPED,{value:true});}
export function registerTakedown(){CONFIG.queries[QUERY]=resolveTakedown;installTakedown(game.system.api.data.actions.actionsTypes.base);}
