import {ID,featureActive} from '../core.js';
import {timedDialog} from '../dialog.js';
import {TRANSCENDENCE_KEY,TRANSCENDENCE_ACTION,TRANSCENDENCE_EFFECTS} from './transcendence-data.js';
const TRAITS=['agility','strength','finesse','instinct','presence','knowledge'],pending=new Set();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function transcendenceAction(action){const item=action?.item??action?.parent,flags=item?.flags?.[ID];return action?.id===TRANSCENDENCE_ACTION&&featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===TRANSCENDENCE_KEY;}
export function validTranscendenceChoice(choice){return Boolean(choice&&Array.isArray(choice.benefits)&&choice.benefits.length===2&&new Set(choice.benefits).size===2&&choice.benefits.every(key=>Object.hasOwn(TRANSCENDENCE_EFFECTS,key))&&(!choice.benefits.includes('trait')||TRAITS.includes(choice.trait)));}
export async function promptTranscendence(actor){const options=[['threshold','+4 Severe threshold'],['trait','+1 to a character trait'],['proficiency','+1 Proficiency'],['evasion','+2 Evasion']];return timedDialog(`Transcendence — ${actor.name}`,`<p>Choose exactly <strong>two</strong> benefits. If you choose Trait, select which trait receives +1.</p><div>${options.map(([key,label])=>`<label style="display:block;margin:0.4rem 0"><input type="checkbox" name="transcendenceBenefit" value="${key}"> ${label}</label>`).join('')}</div><label>Trait <select name="transcendenceTrait" style="width:100%">${TRAITS.map(trait=>`<option value="${trait}">${esc(trait[0].toUpperCase()+trait.slice(1))}</option>`).join('')}</select></label>`,[{action:'transform',label:'Transform',callback:(_event,_button,dialog)=>({benefits:[...dialog.element.querySelectorAll('[name="transcendenceBenefit"]:checked')].map(input=>input.value),trait:dialog.element.querySelector('[name="transcendenceTrait"]').value})},{action:'cancel',label:'Cancel',default:true,callback:()=>null}]);}
export function transcendenceEffectData(item,choice){return choice.benefits.map(key=>{const id=TRANSCENDENCE_EFFECTS[key],source=item.effects?.get?.(id)??item.effects?.find?.(effect=>(effect.id??effect._id)===id),data=source?.toObject?source.toObject():structuredClone(source);if(!data)throw new Error(`Transcendence effect ${key} is missing.`);delete data._id;delete data.id;data.disabled=false;data.transfer=false;data.origin=source.uuid??`${item.uuid}.ActiveEffect.${id}`;data.system={...data.system,duration:{...data.system?.duration,type:'shortRest',description:'Until your next rest.'}};if(key==='trait'){data.name=`Transcendence: ${choice.trait[0].toUpperCase()+choice.trait.slice(1)}`;data.description=`<p>+1 bonus to ${choice.trait[0].toUpperCase()+choice.trait.slice(1)}.</p>`;data.system.changes=[{key:`system.traits.${choice.trait}.value`,type:'add',value:'1',priority:null,phase:'initial'}];}data.flags={...data.flags,[ID]:{...data.flags?.[ID],transcendenceBenefit:key,trait:key==='trait'?choice.trait:null}};return data;});}
export function installTranscendence(Action,ask=promptTranscendence){const native=Action.prototype.use;Action.prototype.use=async function(...args){if(!transcendenceAction(this))return native.apply(this,args);const actor=this.actor,item=this.item??this.parent;if(pending.has(actor.uuid))return;pending.add(actor.uuid);try{const choice=await ask(actor);if(!choice)return;if(!validTranscendenceChoice(choice)){ui.notifications.warn('Choose exactly two Transcendence benefits and a valid trait when applicable.');return;}if(!transcendenceAction(this))return;const effects=transcendenceEffectData(item,choice),data=this.toObject();data.effects=[];const action=new this.constructor(data,{parent:this.parent}),result=await native.apply(action,args);if(!result)return result;await actor.createEmbeddedDocuments('ActiveEffect',effects);return result;}finally{pending.delete(actor.uuid);}};}
export function registerTranscendence(){installTranscendence(game.system.api.data.actions.actionsTypes.base);}
