import {ID,featureActive} from '../core.js';
import {VANISHING_KEY,VANISHING_ACTION,VANISHING_EFFECT} from './vanishing-act-data.js';
const QUERY=`${ID}.expireVanishing`,WRAPPED=Symbol.for(`${ID}.vanishingAct`);
export function vanishingItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===VANISHING_KEY;})??null:null;}
export function vanishingEffects(actor){const item=vanishingItem(actor),origin=item?.effects?.get?.(VANISHING_EFFECT)?.uuid??item?.effects?.find?.(effect=>(effect.id??effect._id)===VANISHING_EFFECT)?.uuid;return item?[...(actor.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&(effect.origin===origin||effect.origin?.endsWith(`.ActiveEffect.${VANISHING_EFFECT}`)||effect.name?.trim().toLowerCase()==='vanishing act: cloaked')):[];}
export async function expireVanishing(request,{user}){if(!game.user.isActiveGM||!user?.active||request.actionType!=='action')return false;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER'))return false;const allowed=new Set(request.effectIds??[]),effects=vanishingEffects(actor).filter(effect=>!allowed.size||allowed.has(effect.id));if(!effects.length)return false;await actor.deleteEmbeddedDocuments('ActiveEffect',effects.map(effect=>effect.id));return true;}
export async function clearVanishingRestrained(actor){if(!actor.statuses?.has('restrained'))return false;const effects=[...(actor.effects??[])].filter(effect=>effect.statuses?.has?.('restrained'));if(effects.length)await actor.deleteEmbeddedDocuments('ActiveEffect',effects.map(effect=>effect.id));else await actor.toggleStatusEffect('restrained',{active:false});return true;}
export function installVanishingRoll(Duality,expire){if(Duality[WRAPPED])return;const evaluate=Duality.buildEvaluate;Duality.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args),actor=config.data?.parent??roll.data?.parent,effects=config.actionType==='action'&&roll.withFear?vanishingEffects(actor):[];if(effects.length)await expire({actionType:'action',actorUuid:actor.uuid,effectIds:effects.map(effect=>effect.id)});return result;};Object.defineProperty(Duality,WRAPPED,{value:true});}
export function registerVanishingAct(){CONFIG.queries[QUERY]=expireVanishing;const dispatch=request=>{const gm=game.users.activeGM;if(!gm)throw new Error('Vanishing Act expiry needs an active GM.');return gm.isSelf?expireVanishing(request,{user:game.user}):gm.query(QUERY,request,{timeout:15000});};installVanishingRoll(CONFIG.Dice.daggerheart.DualityRoll,dispatch);Hooks.on('daggerheart.postUseAction',(action)=>{const flags=action.item?.flags?.[ID];if(action.id!==VANISHING_ACTION||!featureActive(action.item)||flags?.disabled||(flags?.applied?.key??flags?.premade?.key)!==VANISHING_KEY)return;void clearVanishingRestrained(action.actor).catch(error=>{console.error(`${ID} | Vanishing Act`,error);ui.notifications.error('Vanishing Act could not clear Restrained.');});});}
