import { decisionBudget } from '../settings.js';
import { ID,featureActive } from '../core.js';
import { overwhelmHits } from './overwhelm.js';
import { sourceToken } from './hallowed-aura.js';
import { meleeLimit } from './kick.js';
import { VENOMOUS_BITE_KEY,VENOMOUS_BITE_ACTION,VENOMOUS_BITE_EFFECT } from './venomous-bite-data.js';
import { VENOMOUS_STRIKE_KEY,VENOMOUS_STRIKE_ACTION,VENOMOUS_STRIKE_EFFECT } from './venomous-strike-data.js';
const QUERY=`${ID}.venomousBite`,WRAPPED=Symbol.for(`${ID}.venomousBite`),seen=new Set();
export function venomousBiteItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===VENOMOUS_BITE_KEY;})??null:null;}
export function venomousStrikeItem(actor){return actor?.type==='character'?actor.items?.find(item=>{const flags=item.flags?.[ID];return featureActive(item)&&!flags?.disabled&&(flags?.applied?.key??flags?.premade?.key)===VENOMOUS_STRIKE_KEY;})??null:null;}
const venomousOrigin=effect=>[VENOMOUS_BITE_EFFECT,VENOMOUS_STRIKE_EFFECT].some(id=>String(effect?.origin??'').endsWith(`.ActiveEffect.${id}`));
export const venomousBiteEffects=actor=>[...(actor?.effects??[])].filter(effect=>!effect.disabled&&!effect.isSuppressed&&(effect.flags?.[ID]?.venomousBite||effect.flags?.[ID]?.venomousPoison||venomousOrigin(effect)));
export function venomousBiteHits(message){const actor=message?.system?.action?.actor,origin=actor&&sourceToken(actor);if(!origin||!venomousBiteItem(actor))return[];return overwhelmHits(message).filter(hit=>{const token=canvas.tokens.get(hit.id),distance=token&&origin.distanceTo(token);return token?.actor?.uuid===hit.actorId&&Number.isFinite(distance)&&distance<=meleeLimit(canvas.scene);});}
const veryCloseLimit=()=>{const rules=game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement,local=canvas.scene.flags?.daggerheart?.rangeMeasurement;return Number(rules.enabled&&local?.setting===CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id?local.veryClose:rules.veryClose);};
export function venomousStrikeHits(message){const actor=message?.system?.action?.actor,origin=actor&&sourceToken(actor),limit=veryCloseLimit();if(!origin||!venomousStrikeItem(actor)||!Number.isFinite(limit))return[];return overwhelmHits(message).filter(hit=>{const token=canvas.tokens.get(hit.id),distance=token&&origin.distanceTo(token);return token?.actor?.uuid===hit.actorId&&Number.isFinite(distance)&&distance<=limit;});}
export async function resolveVenomousBite(request,{user},rollDie=async()=>new Roll('1d10',{}, {damageTypes:['physical']}).evaluate()){if(!game.user.isActiveGM||!user?.active||typeof request.id!=='string'||seen.has(request.id))return false;seen.add(request.id);if(request.op==='poison'){const message=await fromUuid(request.messageUuid),actor=message?.system?.action?.actor,strike=request.source==='strike',hit=(strike?venomousStrikeHits(message):venomousBiteHits(message)).find(entry=>entry.id===request.targetId);if(!actor?.testUserPermission(user,'OWNER')||!hit)return false;const target=await fromUuid(hit.actorId),item=strike?venomousStrikeItem(actor):venomousBiteItem(actor),effect=item?.effects?.get?.(strike?VENOMOUS_STRIKE_EFFECT:VENOMOUS_BITE_EFFECT);if(!target||!effect||strike&&(request.itemUuid!==item.uuid||request.actionId!==VENOMOUS_STRIKE_ACTION))return false;let poisons=venomousBiteEffects(target);if(!poisons.length){await game.system.api.fields.ActionFields.EffectsField.applyEffect(effect,target);poisons=venomousBiteEffects(target);}if(poisons.length>1)await target.deleteEmbeddedDocuments('ActiveEffect',poisons.slice(1).map(entry=>entry.id));await message.update({[`flags.${ID}.venomousBite.${request.targetId}`]:'poisoned'});return true;}if(request.op!=='tick')return false;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER')||!venomousBiteEffects(actor).some(effect=>request.effectIds?.includes(effect.id)))return false;const roll=await rollDie();if(!Number.isInteger(roll.total)||roll.total<1||roll.total>10)throw Error('Invalid Poisoned damage roll.');await roll.toMessage({speaker:ChatMessage.getSpeaker({actor}),flavor:'Poisoned — action damage'});const multiplier=Number(actor.system.rules?.attack?.damage?.hpDamageTakenMultiplier??1),main=roll.toJSON();main.total=Math.ceil(roll.total*multiplier);await actor.takeDamage({main,resources:{}},true);return{total:main.total};}
async function dispatch(request){const gm=game.users.activeGM;if(!gm)throw Error('Venomous Bite needs an active GM.');return gm.isSelf?resolveVenomousBite(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(65000)});}
export function installVenomousBite(Action,send=dispatch){if(!Action||Action[WRAPPED])return;const native=Action.prototype.use;Action.prototype.use=async function(...args){const poisonIds=venomousBiteEffects(this.actor).map(effect=>effect.id),strike=this.id===VENOMOUS_STRIKE_ACTION&&venomousStrikeItem(this.actor)?.uuid===this.item?.uuid,config=await native.apply(this,args);if(!config)return config;const hits=strike?venomousStrikeHits(config.message):venomousBiteHits(config.message);for(const hit of hits)await send({op:'poison',id:foundry.utils.randomID(),messageUuid:config.message.uuid,targetId:hit.id,...(strike?{source:'strike',itemUuid:this.item.uuid,actionId:this.id}:{})});if(poisonIds.length)await send({op:'tick',id:foundry.utils.randomID(),actorUuid:this.actor.uuid,effectIds:poisonIds});return config;};Object.defineProperty(Action,WRAPPED,{value:true});}
export function registerVenomousBite(){CONFIG.queries[QUERY]=resolveVenomousBite;installVenomousBite(game.system.api.data.actions.actionsTypes.base);Hooks.on('daggerheart.preUseAction',action=>{const flags=action.item?.flags?.[ID];if(action.id!==VENOMOUS_BITE_ACTION||(flags?.applied?.key??flags?.premade?.key)!==VENOMOUS_BITE_KEY)return;ui.notifications.info('Venomous Bite applies automatically after a successful attack within Melee range.');return false;});}
