import {ID,featureActive} from '../core.js';
import {withHopeLock} from './hope-lock.js';
import {WEAPON_DEADLY_KEY} from './weapon-deadly-data.js';
const WRAPPED=Symbol.for(`${ID}.weaponDeadly`);
export function deadlyWeapon(item){return Boolean(item?.type==='weapon'&&item.system?.equipped&&featureActive(item)&&!item.flags?.[ID]?.disabled&&item.flags?.[ID]?.applied?.key===WEAPON_DEADLY_KEY&&item.system.weaponFeatures?.some(f=>f.value==='deadly'));}
export function deadlySource(config){if(config.hasHealing||!config.damage?.main)return null;const source=config.source;if(!source||typeof source.action!=='string'||!source.action)return null;const actor=config.data?.parent??foundry.utils.fromUuidSync?.(source.actor),item=actor?.items?.get?.(source.item);if(actor?.uuid!==source.actor||!deadlyWeapon(item))return null;const action=item.system.attack?.id===source.action?item.system.attack:item.system.actions?.get?.(source.action)??item.system.actions?.[source.action];return action?.type==='attack'?{weaponUuid:item.uuid,source:{actor:source.actor,item:source.item,action:source.action}}:null;}
export function tagDeadly(config){const record=deadlySource(config),main=config.damage?.main;if(!record||!main)return false;main.options??={};main.options[ID]={...main.options[ID],weaponDeadly:record};const damage=config.damage;if(typeof damage.toObject==='function')config.damage=new damage.constructor({...damage.toObject(),main:main.toJSON(),resources:Object.fromEntries(Object.entries(damage.resources??{}).map(([key,value])=>[key,value.toJSON()]))});return true;}
export function deadlyPacket(packet){const main=packet?.main??packet?.damage??packet,record=main?.options?.[ID]?.weaponDeadly;return Number.isFinite(main?.total)&&main.total>0&&typeof record?.weaponUuid==='string'&&['actor','item','action'].every(key=>typeof record.source?.[key]==='string'&&record.source[key])?record:null;}
export function addDeadlyHP(updates,excludedHP=0){const hp=updates?.find(row=>row.key==='hitPoints'&&!row.itemId&&!row.clear&&row.damageTypes&&Number.isSafeInteger(row.value)&&row.value>0);if(!hp||hp.value-excludedHP<3)return false;hp.value++;return true;}
export function installWeaponDeadly(Damage,Actor,triggers){
 if(Damage&&!Object.hasOwn(Damage,WRAPPED)){const evaluate=Damage.buildEvaluate,post=Damage.buildPost;Damage.buildEvaluate=async function(roll,config,...args){const result=await evaluate.call(this,roll,config,...args);tagDeadly(config);return result;};Damage.buildPost=async function(roll,config,...args){tagDeadly(config);return post.call(this,roll,config,...args);};Object.defineProperty(Damage,WRAPPED,{value:true});}
 if(!Actor||Object.hasOwn(Actor,WRAPPED))return;const take=Actor.prototype.takeDamage,update=Actor.prototype.update,run=triggers.runTrigger,contexts=new WeakMap();
 Actor.prototype.update=function(...args){const result=update.apply(this,args);contexts.get(this)?.writes.push(Promise.resolve(result));return result;};
 // Native postDamageReduction runs after Armor/resistance/severity reduction,
 // before modifyResource HP prevention and Stress overflow. Add to the same
 // receipt, not a second resource write. Serialize the async recipient context.
 Actor.prototype.takeDamage=function(packet,...args){if(!deadlyPacket(packet)||this.type==='companion')return take.call(this,packet,...args);return withHopeLock(`weaponDeadlyDamage:${this.uuid}`,async()=>{const resource=packet.resources?.hitPoints,excludedHP=resource?.options?.itemId||resource?.options?.fullRestore?0:Math.max(0,Number(typeof resource==='number'?resource:resource?.total)||0),context={excludedHP,handled:false,writes:[]};contexts.set(this,context);try{const result=await take.call(this,packet,...args);let position=0;while(position<context.writes.length){const end=context.writes.length;await Promise.all(context.writes.slice(position,end));position=end;}return result;}finally{contexts.delete(this);}});};
triggers.runTrigger=async function(trigger,actor,updates,...args){const result=await run.call(this,trigger,actor,updates,...args),context=contexts.get(actor);if(trigger===CONFIG.DH.TRIGGER.triggers.postDamageReduction.id&&context&&!context.handled){context.handled=true;addDeadlyHP(updates,context.excludedHP);}return result;};Object.defineProperty(Actor,WRAPPED,{value:true});
}
export function registerWeaponDeadly(){installWeaponDeadly(CONFIG.Dice.daggerheart.DamageRoll,CONFIG.Actor.documentClass,game.system.registeredTriggers);Hooks.on('daggerheart.preUseAction',action=>{if(deadlyWeapon(action.item)&&action.item.system.weaponFeatures.some(f=>f.value==='deadly'&&f.actionIds?.includes(action.id))){ui.notifications.info('Deadly automatically adds 1 HP when this weapon deals Severe damage.');return false;}});}
