import {ID,featureActive} from '../core.js';
import {decisionBudget} from '../settings.js';
import {attackHitTargets} from '../attack-outcome.js';
import {markReactiveStress} from './stress-payment.js';
import {WEAPON_SCARY_KEY} from './weapon-scary-data.js';
const QUERY=`${ID}.weaponScary`,WRAPPED=Symbol.for(QUERY),receipts=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function scaryWeapon(item){return Boolean(item?.type==='weapon'&&item.system?.equipped&&featureActive(item)&&!item.flags?.[ID]?.disabled&&item.flags?.[ID]?.applied?.key===WEAPON_SCARY_KEY&&item.system.weaponFeatures?.some(f=>f.value==='scary'));}
export function weaponScaryContext(message){const data=message?.system,action=data?.action,actor=action?.actor,item=action?.item,source=data?.source;if(actor?.type!=='character'||action.type!=='attack'||data.hasHealing||!Number.isFinite(data.roll?.total)||!scaryWeapon(item)||source?.actor!==actor.uuid||source.item!==item.id||typeof source.action!=='string'||!source.action||source.action!==action.id||actor.items?.get?.(item.id)?.uuid!==item.uuid)return null;const hits=attackHitTargets(message);return hits.length?{actor,item,hits}:null;}
export async function resolveWeaponScary(request,{user},mark=markReactiveStress){if(!game.user.isActiveGM||!user?.active||typeof request?.messageUuid!=='string')return false;const message=await fromUuid(request.messageUuid),context=weaponScaryContext(message);if(!context||!context.actor.testUserPermission(user,'OWNER'))return false;if(receipts.has(message.uuid))return receipts.get(message.uuid);if(message.flags?.[ID]?.weaponScary)return false;
 const operation=(async()=>{const initial=[...new Set(context.hits.map(hit=>hit.actorId))],record={weaponUuid:context.item.uuid,targets:[],complete:false};await message.setFlag(ID,'weaponScary',record);const lines=[];
  for(const uuid of initial){const target=await fromUuid(uuid);if(!target||!['character','adversary','companion'].includes(target.type)||!target.system.resources?.stress)continue;const eligible=current=>{const fresh=weaponScaryContext(message);return Boolean(game.user.isActiveGM&&user.active&&fresh?.item.uuid===context.item.uuid&&fresh.actor.testUserPermission(user,'OWNER')&&fresh.hits.some(hit=>hit.actorId===current.uuid));};if(!eligible(target))continue;
   record.targets.push({actorUuid:uuid,status:'started'});await message.setFlag(ID,'weaponScary',structuredClone(record));const paid=await mark(uuid,eligible);record.targets.at(-1).status=paid?'marked':'notMarked';await message.setFlag(ID,'weaponScary',structuredClone(record));lines.push(`${esc(target.name)}: ${paid?'marks 1 Stress':'no Stress marked'}`);
  }
  record.complete=true;await message.setFlag(ID,'weaponScary',record);if(lines.length)try{await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:context.actor}),whisper:[...(message.whisper??[])],blind:Boolean(message.blind),content:`<p><strong>Scary</strong> — ${lines.join('; ')}.</p>`});}catch(error){console.warn(`${ID} | Scary notification`,error);}return true;
 })();receipts.set(message.uuid,operation);if(receipts.size>1000)receipts.delete(receipts.keys().next().value);return operation;
}
export function installWeaponScary(Action,apply){if(!Action||Object.hasOwn(Action,WRAPPED))return;const use=Action.prototype.use;Action.prototype.use=async function(...args){const result=await use.apply(this,args),message=result?.message;if(message&&weaponScaryContext(message)&&this.actor?.uuid===message.system.source.actor&&this.item?.uuid===message.system.action.item.uuid&&this.id===message.system.source.action)try{await apply({messageUuid:message.uuid});}catch(error){console.error(`${ID} | Scary weapon Stress`,error);ui.notifications.error('Scary: the attack completed, but target Stress could not be confirmed. Check target Stress before retrying.');}return result;};Object.defineProperty(Action,WRAPPED,{value:true});}
export function registerWeaponScary(){CONFIG.queries[QUERY]=resolveWeaponScary;installWeaponScary(game.system.api.data.actions.actionsTypes.base,request=>{const gm=game.users.activeGM;if(!gm)throw Error('Scary needs an active GM.');return gm.isSelf?resolveWeaponScary(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(65000)});});Hooks.on('daggerheart.preUseAction',action=>{if(scaryWeapon(action.item)&&action.item.system.weaponFeatures.some(f=>f.value==='scary'&&f.actionIds?.includes(action.id))){ui.notifications.info('Scary automatically marks 1 Stress on targets hit by this weapon.');return false;}});}
