import {premadeDocuments,configurePremadePack} from '../premade-setup-context.js';
import {ID} from '../core.js';
export const WOLF_FORM_KEY='transformation-werewolf-wolf-form',HOWLING_RAMPAGE_KEY='transformation-werewolf-howling-rampage',WOLF_FORM_EFFECT='DhpWolfForm00001';
const wolfImg='icons/creatures/mammals/wolf-shadow-black.webp',rampageImg='icons/magic/control/fear-fright-monster-grin-red-orange.webp';
export function wolfFormData(folder){return{name:'Wolf Form',type:'feature',img:wolfImg,folder,system:{attribution:{source:'Daggerheart SRD',page:null,artist:''},description:'<p>When you mark 1 or more Hit Points, you can <strong>mark a Stress</strong> to enter your Wolf Form. While in this form, you gain a <strong>1d10</strong> bonus to attack and damage rolls. When you roll with Hope while in Wolf Form, you must mark a Stress. Your Wolf Form lasts until you go into your "Howling Rampage" or take a rest.</p>',gmNotes:'After HP is marked, optionally mark 1 Stress to enter Wolf Form. The visible effect supplies +1d10 to attack and damage rolls and expires at either rest. Final rolls with Hope, including critical successes, automatically mark Stress. Filling the last Stress triggers Howling Rampage.',resource:null,actions:{},granter:null,featureForm:'passive',actorResources:[]},effects:[{name:'Wolf Form',disabled:true,img:wolfImg,description:'<p>Gain +1d10 to attack and damage rolls. Rolls with Hope mark 1 Stress.</p>',transfer:false,statuses:[],system:{changes:[{key:'system.bonuses.damage.dice',type:'add',value:'1d10',priority:null,phase:'initial'},{key:'system.bonuses.roll.dice',type:'add',value:'1d10',priority:null,phase:'initial'}],duration:{description:'Until Howling Rampage or your next rest.',type:'shortRest'},rangeDependence:null,stacking:null,targetDispositions:[],conditionals:[{type:'actionType',actionTypes:['attack'],traits:[]}]},_id:WOLF_FORM_EFFECT,type:'base',duration:{value:null,units:'seconds',expiry:null,expired:false},tint:'#ffffff',showIcon:1,folder:null,sort:0,flags:{[ID]:{wolfForm:true}}}],flags:{[ID]:{premade:{key:WOLF_FORM_KEY,version:'1.0.0',category:'transformation-features',aliases:[],sourceUuids:['Compendium.daggerheart.transformations.Item.m0lRcWjXdqGW4StE']}}}};}
export function howlingRampageData(folder){return{name:'Howling Rampage',type:'feature',img:rampageImg,folder,system:{attribution:{source:'Daggerheart SRD',page:null,artist:''},description:'<p>When you mark your last Stress while in Wolf Form, you go into a rampage. Roll a number of <strong>d20s</strong> equal to your tier and deal that much physical damage to all creatures within Very Close range, then drop out of Wolf Form.</p>',gmNotes:'Automatically triggers when Stress becomes full during Wolf Form. Rolls tier d20s in chat, applies that physical damage through native damage reduction to every creature within Very Close, then ends Wolf Form.',resource:null,actions:{},granter:null,featureForm:'passive',actorResources:[]},effects:[],flags:{[ID]:{premade:{key:HOWLING_RAMPAGE_KEY,version:'1.0.0',category:'transformation-features',aliases:[],sourceUuids:['Compendium.daggerheart.transformations.Item.po9tIudU8LBRb3um']}}}};}
async function ensure(key,make){const pack=game.packs.get(`${ID}.transformation-features`);if(!pack)throw Error('The Transformation Features compendium is missing. Restart Foundry after installing this module version.');const existing=(await premadeDocuments(pack)).find(item=>item.getFlag(ID,'premade')?.key===key);if(existing?.getFlag(ID,'premade')?.version==='1.0.0')return existing;const folder=pack.folders.find(entry=>!entry.folder&&entry.name==='Transformation Features');if(!folder)throw Error('The Transformation Features compendium folder is missing.');const locked=pack.locked;try{if(locked)await configurePremadePack(pack,{locked:false});const data=make(folder.id),item=existing?await existing.update(data,{diff:false,recursive:false}):await Item.create(data,{pack:pack.collection});if(!item)throw Error(`${data.name} creation was cancelled.`);return item;}finally{if(locked)await configurePremadePack(pack,{locked:true});}}
export const ensureWolfForm=()=>ensure(WOLF_FORM_KEY,wolfFormData);
export const ensureHowlingRampage=()=>ensure(HOWLING_RAMPAGE_KEY,howlingRampageData);
