import {ID,featureActive} from '../core.js';
import {decisionBudget} from '../settings.js';
import {timedDialog} from '../dialog.js';
import {ownerFor} from './aura-rules.js';
import {sourceToken} from './hallowed-aura.js';
import {markReactiveStress} from './stress-payment.js';
import {WOLF_FORM_KEY,HOWLING_RAMPAGE_KEY,WOLF_FORM_EFFECT} from './werewolf-data.js';
const QUERY=`${ID}.werewolf`,PROMPT=`${QUERY}Prompt`,WRAP=Symbol.for(`${ID}.werewolfActor`),ROLL_WRAP=Symbol.for(`${ID}.werewolfRoll`),rampaging=new Set();
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const feature=(actor,key)=>actor?.type==='character'?actor.items?.find(item=>{const f=item.flags?.[ID];return featureActive(item)&&!f?.disabled&&(f?.applied?.key??f?.premade?.key)===key;})??null:null;
export const wolfFormItem=actor=>feature(actor,WOLF_FORM_KEY);
export const howlingRampageItem=actor=>feature(actor,HOWLING_RAMPAGE_KEY);
export function wolfFormEffect(actor){return actor?.effects?.find(effect=>!effect.disabled&&!effect.isSuppressed&&effect.flags?.[ID]?.wolfForm)??null;}
export const fullStress=actor=>Number(actor?.system?.resources?.stress?.value)>=Number(actor?.system?.resources?.stress?.max);
const veryCloseLimit=()=>{const rules=game.settings.get(CONFIG.DH.id,CONFIG.DH.SETTINGS.gameSettings.variantRules).rangeMeasurement,local=canvas.scene.flags?.daggerheart?.rangeMeasurement;return Number(rules.enabled&&local?.setting===CONFIG.DH.GENERAL.sceneRangeMeasurementSetting.custom.id?local.veryClose:rules.veryClose);};
export function rampageTargets(actor){const origin=sourceToken(actor),limit=veryCloseLimit(),targets=new Map;if(!origin||!Number.isFinite(limit))return[];for(const token of canvas.tokens?.placeables??[]){const target=token.actor,distance=origin.distanceTo(token);if(!target||target.uuid===actor.uuid||!['character','adversary'].includes(target.type)||!Number.isFinite(distance)||distance>limit)continue;if(!targets.has(target.uuid))targets.set(target.uuid,target);}return[...targets.values()];}
export async function promptWolfForm(data,{user}){const actor=await fromUuid(data.actorUuid),stress=actor?.system?.resources?.stress;if(!user?.active||!actor?.testUserPermission(user,'OWNER')||!wolfFormItem(actor)||wolfFormEffect(actor)||!(Number(stress?.value)<Number(stress?.max)))return false;return Boolean(await timedDialog(`Wolf Form — ${actor.name}`,`<p>${esc(actor.name)} marked ${data.hp} HP.</p><p>Mark <strong>1 Stress</strong> to enter Wolf Form?</p>`,[{action:'transform',label:'Mark Stress & Transform',callback:()=>true},{action:'decline',label:'Decline',default:true,callback:()=>false}]));}
function wolfEffectData(item){const source=item.effects?.get?.(WOLF_FORM_EFFECT)??item.effects?.find?.(effect=>(effect.id??effect._id)===WOLF_FORM_EFFECT),data=source?.toObject?source.toObject():structuredClone(source);if(!data)throw Error('Wolf Form effect is missing. Reapply Medkit.');delete data._id;delete data.id;data.disabled=false;data.transfer=false;data.origin=source.uuid??`${item.uuid}.ActiveEffect.${WOLF_FORM_EFFECT}`;data.flags={...data.flags,[ID]:{...data.flags?.[ID],wolfForm:true}};return data;}
export async function resolveWerewolf(request,{user},ask=promptWolfForm,rollDice=async formula=>new Roll(formula,{}, {damageTypes:['physical']}).evaluate()){if(!game.user.isActiveGM||!user?.active)return false;const actor=await fromUuid(request.actorUuid);if(!actor?.testUserPermission(user,'OWNER'))return false;if(request.op==='activate'){const item=wolfFormItem(actor),stress=actor.system.resources?.stress;if(!item||wolfFormEffect(actor)||!(Number(stress?.value)<Number(stress?.max)))return false;const owner=ownerFor(actor,[...game.users],game.user),accepted=owner.isSelf?await ask({actorUuid:actor.uuid,hp:request.hp},{user:game.user}):await owner.query(PROMPT,{actorUuid:actor.uuid,hp:request.hp},{timeout:decisionBudget(65000)});if(!accepted||wolfFormEffect(actor)||!await markReactiveStress(actor.uuid,current=>Boolean(wolfFormItem(current)&&!wolfFormEffect(current))))return false;const created=await actor.createEmbeddedDocuments('ActiveEffect',[wolfEffectData(item)]);if(!created.length)throw Error('Wolf Form could not be applied.');return true;}if(request.op==='hope'){if(request.actionType!=='action'||!wolfFormEffect(actor))return false;const paid=await markReactiveStress(actor.uuid,current=>Boolean(wolfFormEffect(current)));if(paid)await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>Wolf Form:</strong> ${esc(actor.name)} rolled with Hope and marks 1 Stress.</p>`});return paid;}if(request.op!=='rampage'||!wolfFormEffect(actor)||!howlingRampageItem(actor)||!fullStress(actor)||rampaging.has(actor.uuid))return false;rampaging.add(actor.uuid);try{const tier=Math.max(1,Number(actor.system?.tier)||1),roll=await rollDice(`${tier}d20`),targets=rampageTargets(actor),message=await roll.toMessage({speaker:ChatMessage.getSpeaker({actor}),flavor:`<strong>Howling Rampage</strong><p>${targets.map(target=>esc(target.name)).join(', ')||'No creatures'} within Very Close take ${roll.total} physical damage.</p>`});if(message&&game.dice3d)await game.dice3d.waitFor3DAnimationByMessageID(message.id);for(const target of targets){const main=roll.toJSON();main.options={...main.options,damageTypes:['physical'],[ID]:{howlingRampage:true}};await target.takeDamage({main,resources:{}},false);}const effect=wolfFormEffect(actor);if(effect)await effect.delete();return{total:roll.total,targets:targets.map(target=>target.uuid)};}finally{rampaging.delete(actor.uuid);}}
export function installWerewolfActor(Actor,dispatch){if(Actor[WRAP])return;const native=Actor.prototype.update;Actor.prototype.update=async function(changes,...args){const hp=Number(this.system?.resources?.hitPoints?.value),stress=Number(this.system?.resources?.stress?.value),hadWolf=Boolean(wolfFormEffect(this)),result=await native.call(this,changes,...args),hpNow=Number(this.system?.resources?.hitPoints?.value),stressNow=Number(this.system?.resources?.stress?.value);if(hpNow>hp&&wolfFormItem(this)&&!wolfFormEffect(this))await dispatch({op:'activate',actorUuid:this.uuid,hp:hpNow-hp});if(hadWolf&&stressNow>stress&&fullStress(this)&&howlingRampageItem(this))await dispatch({op:'rampage',actorUuid:this.uuid});return result;};Object.defineProperty(Actor,WRAP,{value:true});}
export function installWerewolfRoll(Duality,dispatch){if(Duality[ROLL_WRAP])return;const post=Duality.buildPost;Duality.buildPost=async function(roll,config,...args){const result=await post.call(this,roll,config,...args),actor=config.data?.parent;if(config.actionType==='action'&&wolfFormEffect(actor)&&(roll.withHope||roll.isCritical)&&!roll.options?.[ID]?.wolfHope){roll.options[ID]={...roll.options[ID],wolfHope:true};await dispatch({op:'hope',actionType:'action',actorUuid:actor.uuid});}return result;};Object.defineProperty(Duality,ROLL_WRAP,{value:true});}
export function registerWerewolf(){CONFIG.queries[QUERY]=resolveWerewolf;CONFIG.queries[PROMPT]=promptWolfForm;const dispatch=request=>{const gm=game.users.activeGM;if(!gm)throw Error('Werewolf automation needs an active GM.');return gm.isSelf?resolveWerewolf(request,{user:game.user}):gm.query(QUERY,request,{timeout:decisionBudget(300000)});};installWerewolfActor(CONFIG.Actor.documentClass,dispatch);installWerewolfRoll(CONFIG.Dice.daggerheart.DualityRoll,dispatch);}
