// Folder names from the installed Daggerheart 2.9.2 compendiums.
export const FOLDER_CATALOG = {
  "class-features": [
    "Assassin",
    "Bard",
    "Brawler",
    "Druid",
    "Guardian",
    "Ranger",
    "Rogue",
    "Seraph",
    "Sorcerer",
    "Warlock",
    "Warrior",
    "Witch",
    "Wizard"
  ],
  "subclass-features": [
    "Beastbound",
    "Call Of The Brave",
    "Call Of The Slayer",
    "Divine Wielder",
    "Elemental Origin",
    "Executioners Guild",
    "Hedge",
    "Juggernaut",
    "Martial Artist",
    "Moon",
    "Nightwalker",
    "Pact of the Endless",
    "Pact of the Wrathful",
    "Poisoners Guild",
    "Primal Origin",
    "School Of Knowledge",
    "School Of War",
    "Stalwart",
    "Syndicate",
    "Troubadour",
    "Vengeance",
    "Warden of Renewal",
    "Warden of the Elements",
    "Wayfinder",
    "Winged Sentinel",
    "Wordsmith"
  ],
  "domain-cards": [
    "Arcana",
    "Blade",
    "Bone",
    "Codex",
    "Dread",
    "Grace",
    "Midnight",
    "Sage",
    "Splendor",
    "Valor"
  ],
  "ancestry-features": [
    "Aetheris",
    "Clank",
    "Drakona",
    "Dwarf",
    "Earthkin",
    "Elf",
    "Emberkin",
    "Faerie",
    "Faun",
    "Firbolg",
    "Fungril",
    "Galapa",
    "Giant",
    "Gnome",
    "Goblin",
    "Halfling",
    "Human",
    "Infernis",
    "Katari",
    "Orc",
    "Ribbet",
    "Simiah",
    "Skykin",
    "Tidekin"
  ],
  "community-features": [
    "Duneborne",
    "Freeborne",
    "Frostborne",
    "Hearthborne",
    "Highborne",
    "Loreborne",
    "Orderborne",
    "Reborne",
    "Ridgeborne",
    "Seaborne",
    "Slyborne",
    "Underborne",
    "Wanderborne",
    "Warborne",
    "Wildborne"
  ],
  "beastform-features": [
    "Beastform Features"
  ],
  "transformation-features": [
    "Transformation Features"
  ]
};
