import {registerRuthlessPredator} from './premades/ruthless-predator.js';
import {ensureRuthlessPredator} from './premades/ruthless-predator-data.js';
import {registerElusivePredator} from './premades/elusive-predator.js';
import {ensureElusivePredator} from './premades/elusive-predator-data.js';
import {registerApexPredator} from './premades/apex-predator.js';
import {ensureApexPredator} from './premades/apex-predator-data.js';
import {registerContactsEverywhere} from './premades/contacts-everywhere.js';
import {ensureContactsEverywhere} from './premades/contacts-everywhere-data.js';
import {registerReliableBackup} from './premades/reliable-backup.js';
import {ensureReliableBackup} from './premades/reliable-backup-data.js';
import {registerAdrenaline} from './premades/adrenaline.js';
import {ensureAdrenaline} from './premades/adrenaline-data.js';
import {registerVanishingAct} from './premades/vanishing-act.js';
import {ensureVanishingAct} from './premades/vanishing-act-data.js';
import {registerSpiritWeapon} from './premades/spirit-weapon.js';
import {ensureSpiritWeapon} from './premades/spirit-weapon-data.js';
import {registerDevout} from './premades/devout.js';
import {ensureDevout} from './premades/devout-data.js';
import {registerSacredResonance} from './premades/sacred-resonance.js';
import {ensureSacredResonance} from './premades/sacred-resonance-data.js';
import {registerWingsOfLight} from './premades/wings-of-light.js';
import {ensureWingsOfLight} from './premades/wings-of-light-data.js';
import {registerEtherealVisage} from './premades/ethereal-visage.js';
import {ensureEtherealVisage} from './premades/ethereal-visage-data.js';
import {ensurePowerOfTheGods} from './premades/power-of-the-gods-data.js';
import {registerRuneWard} from './premades/rune-ward.js';
import {ensureRuneWard} from './premades/rune-ward-data.js';
import {registerNotGoodEnough} from './premades/not-good-enough.js';
import {ensureNotGoodEnough} from './premades/not-good-enough-data.js';
import {registerWhirlwind} from './premades/whirlwind.js';
import {ensureWhirlwind} from './premades/whirlwind-data.js';
import {registerDeftManeuvers} from './premades/deft-maneuvers.js';
import {ensureDeftManeuvers} from './premades/deft-maneuvers-data.js';
import {registerISeeItComing} from './premades/i-see-it-coming.js';
import {ensureISeeItComing} from './premades/i-see-it-coming-data.js';
import {registerBookOfAva} from './premades/book-of-ava.js';
import {ensureBookOfAva} from './premades/book-of-ava-data.js';
import {registerBookOfIlliat} from './premades/book-of-illiat.js';
import {ensureBookOfIlliat} from './premades/book-of-illiat-data.js';
import {registerBlightingStrike} from './premades/blighting-strike.js';
import {ensureBlightingStrike} from './premades/blighting-strike-data.js';
import {registerUmbralVeil} from './premades/umbral-veil.js';
import {ensureUmbralVeil} from './premades/umbral-veil-data.js';
import {registerRainOfBlades} from './premades/rain-of-blades.js';
import {ensureRainOfBlades} from './premades/rain-of-blades-data.js';
import {registerUncannyDisguise} from './premades/uncanny-disguise.js';
import {ensureUncannyDisguise} from './premades/uncanny-disguise-data.js';
import {registerNaturesTongue} from './premades/natures-tongue.js';
import {ensureNaturesTongue} from './premades/natures-tongue-data.js';
import {registerViciousEntangle} from './premades/vicious-entangle.js';
import {ensureViciousEntangle} from './premades/vicious-entangle-data.js';
import {registerReassurance} from './premades/reassurance.js';
import {ensureReassurance} from './premades/reassurance-data.js';
import {registerForcefulPush} from './premades/forceful-push.js';
import {ensureForcefulPush} from './premades/forceful-push-data.js';
import {registerIAmYourShield} from './premades/i-am-your-shield.js';
import {ensureIAmYourShield} from './premades/i-am-your-shield-data.js';
import {registerEnchantedAid} from './premades/enchanted-aid.js';
import {ensureEnchantedAid} from './premades/enchanted-aid-data.js';
import {registerArcaneCharge} from './premades/arcane-charge.js';
import {ensureArcaneCharge} from './premades/arcane-charge-data.js';
import {registerElementalist} from './premades/elementalist.js';
import {ensureElementalist} from './premades/elementalist-data.js';
import {ensureNaturalEvasion} from './premades/natural-evasion-data.js';
import {registerTranscendence} from './premades/transcendence.js';
import {ensureTranscendence} from './premades/transcendence-data.js';
import {registerManipulateMagic} from './premades/manipulate-magic.js';
import {ensureManipulateMagic} from './premades/manipulate-magic-data.js';
import {registerCompanionAdvancements} from './premades/companion-advancements.js';
import {ensureCompanionAdvancements} from './premades/companion-advancements-data.js';
import {registerLoyalFriend} from './premades/loyal-friend.js';
import {ensureLoyalFriend} from './premades/loyal-friend-data.js';
import {registerEvasionIndicators} from './evasion-indicators.js';
import {registerBattleBonded} from './premades/battle-bonded.js';
import {ensureBattleBonded} from './premades/battle-bonded-data.js';
import { registerCompanions } from './companions.js';
import { registerHelpAlly } from './help-ally.js';
import { registerModuleSettings, initializeModuleSettings } from './settings.js';
import { registerAutoMedkit } from './auto-medkit.js';
import { registerDecisionClockSetting, initializeDecisionClock } from './decision-clock.js';
import { registerLoyalProtector } from './premades/loyal-protector.js';
import { ensureLoyalProtector } from './premades/loyal-protector-data.js';
import { registerPartnerInArms } from './premades/partner-in-arms.js';
import { ensurePartnerInArms } from './premades/partner-in-arms-data.js';
import { registerNemesis } from './premades/nemesis.js';
import { ensureNemesis } from './premades/nemesis-data.js';
import { registerReprisal } from './premades/reprisal.js';
import { ensureReprisal } from './premades/reprisal-data.js';
import { registerRevenge } from './premades/revenge.js';
import { ensureRevenge } from './premades/revenge-data.js';
import { registerDefender } from './premades/defender.js';
import { ensureDefender } from './premades/defender-data.js';
import { registerWardensProtection } from './premades/wardens-protection.js';
import { ensureWardensProtection } from './premades/wardens-protection-data.js';
import { registerClarityNature } from './premades/clarity-nature.js';
import { ensureClarityNature } from './premades/clarity-nature-data.js';
import { registerElementalDominion } from './premades/elemental-dominion.js';
import { ensureElementalDominion } from './premades/elemental-dominion-data.js';
import { registerElementalAura } from './premades/elemental-aura.js';
import { ensureElementalAura } from './premades/elemental-aura-data.js';
import { registerElementalIncarnation } from './premades/elemental-incarnation.js';
import { ensureElementalIncarnation } from './premades/elemental-incarnation-data.js';
import { registerFlowState } from './premades/flow-state.js';
import { ensureFlowState } from './premades/flow-state-data.js';
import { registerKeenDefenses } from './premades/keen-defenses.js';
import { ensureKeenDefenses } from './premades/keen-defenses-data.js';
import { registerVigilant } from './premades/vigilant.js';
import { ensureIsolating } from './premades/isolating-data.js';
import { registerHoned } from './premades/honed.js';
import { ensureHoned } from './premades/honed-data.js';
import { registerExacting } from './premades/exacting.js';
import { ensureExacting } from './premades/exacting-data.js';
import { registerCrushing } from './premades/crushing.js';
import { ensureCrushing } from './premades/crushing-data.js';
import { ensureVigilant } from './premades/vigilant-data.js';
import { ensureStable } from './premades/stable-data.js';
import { registerScary } from './premades/scary.js';
import { ensureScary } from './premades/scary-data.js';
import { registerGrappling } from './premades/grappling.js';
import { ensureGrappling } from './premades/grappling-data.js';
import { registerOtherwordly } from './premades/otherwordly.js';
import { ensureOtherwordly } from './premades/otherwordly-data.js';
import { registerDefensive } from './premades/defensive.js';
import { ensureDefensive } from './premades/defensive-data.js';
import { registerAggressive } from './premades/aggressive.js';
import { ensureAggressive } from './premades/aggressive-data.js';
import { registerQuickStance } from './premades/quick-stance.js';
import { ensureQuickStance } from './premades/quick-stance-data.js';
import { registerInvigorating } from './premades/invigorating.js';
import { ensureInvigorating } from './premades/invigorating-data.js';
import { registerFavored } from './premades/favored.js';
import { ensureFavored } from './premades/favored-data.js';
import { registerStanceLifecycle } from './premades/stance-lifecycle.js';
import { registerStanceFighter } from './premades/stance-fighter.js';
import { ensureStanceFighter } from './premades/stance-fighter-data.js';
import { registerNotDone } from './premades/not-done-yet.js';
import { ensureNotDone } from './premades/not-done-yet-data.js';
import { registerPummeljoy } from './premades/pummeljoy.js';
import { ensurePummeljoy } from './premades/pummeljoy-data.js';
import { registerAttackHope } from './premades/attack-hope.js';
import { registerEyeForEye } from './premades/eye-for-eye.js';
import { ensureEyeForEye } from './premades/eye-for-eye-data.js';
import { registerOverwhelm } from './premades/overwhelm.js';
import { ensureOverwhelm } from './premades/overwhelm-data.js';
import { registerEloquent } from './premades/eloquent.js';
import { ensureEloquent } from './premades/eloquent-data.js';
import { registerVirtuoso } from './premades/virtuoso.js';
import { ensureVirtuoso } from './premades/virtuoso-data.js';
import { registerRallyTargets } from './premades/rally-targets.js';
import { registerMaestro } from './premades/maestro.js';
import { ensureMaestro } from './premades/maestro-data.js';
import { registerGiftedPerformer } from './premades/gifted-performer.js';
import { ensureGiftedPerformer } from './premades/gifted-performer-data.js';
import { registerVenomancer } from './premades/venomancer.js';
import { ensureVenomancer } from './premades/venomancer-data.js';
import { ensureTwinFang } from './premades/twin-fang-data.js';
import { registerPoisonCompendium } from './premades/poison-compendium.js';
import { ensurePoisonCompendium } from './premades/poison-compendium-data.js';
import { registerToxic } from './premades/toxic-concoctions.js';
import { ensureToxic } from './premades/toxic-concoctions-data.js';
import { registerTrueStrike } from './premades/true-strike.js';
import { ensureTrueStrike } from './premades/true-strike-data.js';
import { ensureBackstab } from './premades/backstab-data.js';
import { featureActive } from './core.js';
import { registerScorpionsPoise } from './premades/scorpions-poise.js';
import { ensureScorpionsPoise } from './premades/scorpions-poise-data.js';
import { registerDeathStrike } from './premades/death-strike.js';
import { ensureDeathStrike } from './premades/death-strike-data.js';
import { registerAmbush } from './premades/ambush.js';
import { ensureAmbush } from './premades/ambush-data.js';
import { registerFirstStrike } from './premades/first-strike.js';
import { ensureFirstStrike } from './premades/first-strike-data.js';
import { registerNotThisTime } from './premades/not-this-time.js';
import { ensureNotThisTime } from './premades/not-this-time-data.js';
import { registerWitchsCharm } from './premades/witchs-charm.js';
import { ensureWitchsCharm } from './premades/witchs-charm-data.js';
import { registerPatronsPact } from './premades/patrons-pact.js';
import { ensurePatronsPact } from './premades/patrons-pact-data.js';
import { registerPatronsMantle } from './premades/patrons-mantle.js';
import { ensurePatronsMantle } from './premades/patrons-mantle-data.js';
import { registerPatronsFury } from './premades/patrons-fury.js';
import { ensurePatronsFury } from './premades/patrons-fury-data.js';
import { registerDeadlyVengeance } from './premades/deadly-vengeance.js';
import { ensureDeadlyVengeance } from './premades/deadly-vengeance-data.js';
import { registerMenacingReach, registerMenacingWeaponRestore } from './premades/menacing-reach.js';
import { ensureMenacingReach } from './premades/menacing-reach-data.js';
import { registerDiminishMyFoes } from './premades/diminish-my-foes.js';
import { ensureDiminishMyFoes } from './premades/diminish-my-foes-data.js';
import { registerFearsomeAttack } from './premades/fearsome-attack.js';
import { ensureFearsomeAttack } from './premades/fearsome-attack-data.js';
import {registerCourage} from './premades/courage.js';
import {ensureCourage} from './premades/courage-data.js';
import {registerRiseToTheChallenge} from './premades/rise-to-the-challenge.js';
import {ensureRiseToTheChallenge} from './premades/rise-to-the-challenge-data.js';
import {registerSlayer} from './premades/slayer.js';
import {ensureSlayer} from './premades/slayer-data.js';
import {registerWeaponSpecialist} from './premades/weapon-specialist.js';
import {ensureWeaponSpecialist} from './premades/weapon-specialist-data.js';
import {registerMartialPreparation} from './premades/martial-preparation.js';
import {ensureMartialPreparation} from './premades/martial-preparation-data.js';
import {registerHerbalRemedies} from './premades/herbal-remedies.js';
import {ensureHerbalRemedies} from './premades/herbal-remedies-data.js';
import {registerEnchantedTalisman} from './premades/enchanted-talisman.js';
import {ensureEnchantedTalisman} from './premades/enchanted-talisman-data.js';
import {registerWalkBetweenWorlds} from './premades/walk-between-worlds.js';
import {ensureWalkBetweenWorlds} from './premades/walk-between-worlds-data.js';
import {ensureVexingMalison} from './premades/vexing-malison-data.js';
import {registerCircleOfPower} from './premades/circle-of-power.js';
import {ensureCircleOfPower} from './premades/circle-of-power-data.js';
import {registerNightsGlamour} from './premades/nights-glamour.js';
import {ensureNightsGlamour} from './premades/nights-glamour-data.js';
import {registerMoonbeam} from './premades/moonbeam.js';
import {ensureMoonbeam} from './premades/moonbeam-data.js';
import {registerIreOfPaleLight} from './premades/ire-of-pale-light.js';
import {ensureIreOfPaleLight} from './premades/ire-of-pale-light-data.js';
import {registerLunarPhases} from './premades/lunar-phases.js';
import {ensureLunarPhases} from './premades/lunar-phases-data.js';
import {registerAdept} from './premades/adept.js';
import {registerPerfectRecall} from './premades/perfect-recall.js';
import {ensurePerfectRecall} from './premades/perfect-recall-data.js';
import {registerHonedExpertise} from './premades/honed-expertise.js';
import {ensureHonedExpertise} from './premades/honed-expertise-data.js';
import {registerFaceYourFear} from './premades/face-your-fear.js';
import {ensureFaceYourFear} from './premades/face-your-fear-data.js';
import {ensureFueledByFear} from './premades/fueled-by-fear-data.js';
import {ensureHaveNoFear} from './premades/have-no-fear-data.js';
import {ensureConjureShield} from './premades/conjure-shield-data.js';
import {registerThriveInChaos} from './premades/thrive-in-chaos.js';
import {ensureThriveInChaos} from './premades/thrive-in-chaos-data.js';
import {registerFragile} from './premades/fragile.js';
import {ensureFragile} from './premades/fragile-data.js';
import {ensureElusivePrey} from './premades/elusive-prey-data.js';
import {registerHobblingStrike} from './premades/hobbling-strike.js';
import {ensureHobblingStrike} from './premades/hobbling-strike-data.js';
import {registerPackHunting} from './premades/pack-hunting.js';
import {ensurePackHunting} from './premades/pack-hunting-data.js';
import {registerVenomousBite} from './premades/venomous-bite.js';
import {ensureVenomousBite} from './premades/venomous-bite-data.js';
import {ensureBeastformCompanion} from './premades/companion-data.js';
import {registerCannonball} from './premades/cannonball.js';
import {ensureCannonball} from './premades/cannonball-data.js';
import {registerTakedown} from './premades/takedown.js';
import {ensureTakedown} from './premades/takedown-data.js';
import {ensureVenomousStrike} from './premades/venomous-strike-data.js';
import {registerRampage} from './premades/rampage.js';
import {ensureRampage} from './premades/rampage-data.js';
import {registerRollResolverCompat} from './roll-resolver-compat.js';
import {registerViciousMaul} from './premades/vicious-maul.js';
import {ensureViciousMaul} from './premades/vicious-maul-data.js';
import {registerSnappingStrike} from './premades/snapping-strike.js';
import {ensureSnappingStrike} from './premades/snapping-strike-data.js';
import {registerDevastatingStrikes} from './premades/devastating-strikes.js';
import {ensureDevastatingStrikes} from './premades/devastating-strikes-data.js';
import {registerBeastformRollDamage} from './beastform-roll-damage.js';
import {registerOceanMaster} from './premades/ocean-master.js';
import {ensureOceanMaster} from './premades/ocean-master-data.js';
import {registerUnyielding} from './premades/unyielding.js';
import {ensureUnyielding} from './premades/unyielding-data.js';
import {registerDeadlyRaptor} from './premades/deadly-raptor.js';
import {ensureDeadlyRaptor} from './premades/deadly-raptor-data.js';
import {registerWeightOfDivinity} from './premades/weight-of-divinity.js';
import {ensureWeightOfDivinity} from './premades/weight-of-divinity-data.js';
import {registerChangeShape} from './premades/change-shape.js';
import {ensureChangeShape} from './premades/change-shape-data.js';
import {registerFeed} from './premades/feed.js';
import {ensureFeed} from './premades/feed-data.js';
import {registerWerewolf} from './premades/werewolf.js';
import {ensureWolfForm,ensureHowlingRampage} from './premades/werewolf-data.js';
import {registerRestLoadout} from './rest-loadout.js';
import {registerEfficientRest} from './efficient-rest.js';
import {registerVaultRecall} from './vault-recall.js';
import {ensureAdept} from './premades/adept-data.js';
import { registerOtherworldlyIre } from './premades/otherworldly-ire.js';
import { ensureOtherworldlyIre } from './premades/otherworldly-ire-data.js';
import { registerDeathlessEmbrace } from './premades/deathless-embrace.js';
import { ensureDeathlessEmbrace } from './premades/deathless-embrace-data.js';
import { registerHarrowingInvocation } from './premades/harrowing-invocation.js';
import { ensureHarrowingInvocation } from './premades/harrowing-invocation-data.js';
import { registerDamageSink } from './premades/damage-sink.js';
import { ensureDamageSink } from './premades/damage-sink-data.js';
import { registerDarkAegis } from './premades/dark-aegis.js';
import { ensureDarkAegis } from './premades/dark-aegis-data.js';
import { registerDrainingBane } from './premades/draining-bane.js';
import { ensureDrainingBane } from './premades/draining-bane-data.js';
import { registerFavor } from './premades/favor.js';
import { ensureFavor } from './premades/favor-data.js';
import { registerPatronsBoon } from './premades/patrons-boon.js';
import { ensurePatronsBoon } from './premades/patrons-boon-data.js';
import { registerChannelRawPower } from './premades/channel-raw-power.js';
import { ensureChannelRawPower } from './premades/channel-raw-power-data.js';
import { registerVolatileMagic } from './premades/volatile-magic.js';
import { ensureVolatileMagic } from './premades/volatile-magic-data.js';
import { registerPrayerDice } from './premades/prayer-dice.js';
import { ensurePrayerDice } from './premades/prayer-dice-data.js';
import { registerSneakAttack } from './premades/sneak-attack.js';
import { ensureSneakAttack } from './premades/sneak-attack-data.js';
import { registerHiddenAttacks } from './hidden.js';
import { registerRoguesDodge } from './premades/rogues-dodge.js';
import { ensureRoguesDodge } from './premades/rogues-dodge-data.js';
import { registerRangersFocus } from './premades/rangers-focus.js';
import { ensureRangersFocus } from './premades/rangers-focus-data.js';
import { registerComboStrike } from './premades/combo-strike.js';
import { ensureComboStrike } from './premades/combo-strike-data.js';
import { registerIAmTheWeapon } from './premades/i-am-the-weapon.js';
import { ensureIAmTheWeapon } from './premades/i-am-the-weapon-data.js';
import { registerMarkedForDeath } from './premades/marked-for-death.js';
import { ensureMarkedForDeath } from './premades/marked-for-death-data.js';
import { registerKnowTheTide } from './premades/know-the-tide.js';
import { ensureKnowTheTide } from './premades/know-the-tide-data.js';
import { registerBraveFace } from './premades/brave-face.js';
import { ensureBraveFace } from './premades/brave-face-data.js';
import { registerHardy } from './premades/hardy.js';
import { ensureHardy } from './premades/hardy-data.js';
import { registerUnbound } from './premades/unbound.js';
import { ensureUnbound } from './premades/unbound-data.js';
import { registerEyeOfTheStorm } from './premades/eye-of-the-storm.js';
import { ensureEyeOfTheStorm } from './premades/eye-of-the-storm-data.js';
import { registerTusks } from './premades/tusks.js';
import { ensureTusks } from './premades/tusks-data.js';
import { registerSturdyEffects } from './premades/sturdy.js';
import { ensureSturdy } from './premades/sturdy-data.js';
import { registerFelineInstincts } from './premades/feline-instincts.js';
import { ensureFelineInstincts } from './premades/feline-instincts-data.js';
import { registerFearless } from './premades/fearless.js';
import { ensureFearless } from './premades/fearless-data.js';
import { registerAdaptability } from './premades/adaptability.js';
import { ensureAdaptability } from './premades/adaptability-data.js';
import { registerInternalCompass } from './premades/internal-compass.js';
import { ensureInternalCompass } from './premades/internal-compass-data.js';
import { registerLuckbringer } from './premades/luckbringer.js';
import { ensureLuckbringer } from './premades/luckbringer-data.js';
import { registerAttackResolution } from './attack-resolution.js';
import { ensureDangerSense } from './premades/danger-sense-data.js';
import { ensureNimbleFingers } from './premades/nimble-fingers-data.js';
import { registerNimbleFingers } from './premades/nimble-fingers.js';
import { registerResolutionManager, installDamageReductionMonitoring, addPendingDecisionsControl } from './resolution-manager.js';
import { registerRollProviders, resolveManagedRoll, resolveManagedAura } from './roll-resolution.js';
import { ensureRetract } from './premades/retract-data.js';
import { registerVulnerableSetting, registerVulnerableAdvantage } from './vulnerable.js';
import { ID, CATEGORIES, supported, metadata, categoryFor, matches, itemStatus } from './core.js';
import { library, apply, savePremade, setPremadeEnabled, registerPremadeDisableHooks } from './service.js';
import { medkitControl, registerStatusHooks } from './status.js';
import { ensureFolders, removeEmptyAncestryFolders, removeEmptyCommunityFolders, removeObsoleteWitchSubclassFolder, removeObsoleteWarriorSubclassFolder } from './folders.js';
import { ensureHallowedAura } from './premades/hallowed-aura-data.js';
import { ensureCelestialWings } from './premades/celestial-wings-data.js';
import { registerCelestialWings } from './premades/celestial-wings.js';
import { ensureIncreasedFortitude } from './premades/increased-fortitude-data.js';
import { registerIncreasedFortitude } from './premades/increased-fortitude.js';
import { removeStoneskinPremade } from './premades/stoneskin-data.js';
import { ensureQuickReactions } from './premades/quick-reactions-data.js';
import { registerQuickReactions } from './premades/quick-reactions.js';
import { ensureFaerieWings } from './premades/faerie-wings-data.js';
import { registerFaerieWings } from './premades/faerie-wings.js';
import { ensureLuckbender } from './premades/luckbender-data.js';
import { registerLuckbender } from './premades/luckbender.js';
import { ensureKick } from './premades/kick-data.js';
import { registerKick } from './premades/kick.js';
import { ensureUnshakeable } from './premades/unshakeable-data.js';
import { registerUnshakeable } from './premades/unshakeable.js';
import { registerHallowedAura } from './premades/hallowed-aura.js';

const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const guarded = fn => async (...args) => {
  try { return await fn(...args); }
  catch (error) { console.error(`${ID} |`, error); ui.notifications.error(error.message); }
};
import { managementDialog as dialog } from './dialog.js';
export async function openMedkit(document) {
  if (!game.user.isGM) throw new Error('Medkit is GM-only.');
  const items = document.documentName === 'Actor' ? document.items.filter(item=>supported(item)&&featureActive(item)) : supported(document)&&featureActive(document) ? [document] : [];
  const { entries, errors } = await library();
  const priority = { outdated: 0, available: 1, current: 2, disabled: 2, none: 3 };
  const rows = items.map(item => {
    const data = item.toObject();
    const status = itemStatus(item, entries);
    const installed = data.flags?.[ID]?.applied ?? data.flags?.[ID]?.premade;
    return { item, candidates: matches(item, entries), priority: status === 'none' && installed ? 2 : priority[status] };
  }).sort((a, b) => a.priority - b.priority || a.item.name.localeCompare(b.item.name, game.i18n.lang, { sensitivity: 'base', numeric: true }));
  const warnings = errors.length ? `<p class="dhp-warning">${errors.map(esc).join('<br>')}</p>` : '';
  const content = `${warnings}<p>Select matching premades and click Apply. Only selected items are updated.</p>
    ${!entries.length ? '<p><strong>No premades yet.</strong> Unlock a module compendium, open a configured feature or domain card, and choose “Save as Premade” from its header menu.</p>' : ''}
    ${!items.length ? '<p>This actor has no supported features or domain cards.</p>' : ''}
    <div class="dhp-list">${rows.map(({item,candidates}, index) => {
      const installed = item.getFlag(ID, 'applied') ?? item.getFlag(ID, 'premade');
      const disabled = Boolean(item.getFlag(ID, 'disabled'));
      const currentName = installed?.name ?? candidates.find(e => metadata(e.data).key === installed?.key)?.data.name ?? item.name;
      return `<div class="dhp-row"><label for="dhp-${index}"><strong>${esc(item.name)}</strong><small>${installed ? `${esc(currentName)} v${esc(installed.version)} — ${disabled ? 'disabled' : 'applied'}` : 'No premade applied'}</small></label>
      <select id="dhp-${index}" name="item-${index}" ${candidates.length ? '' : 'disabled'}><option value="">${installed ? `Keep ${esc(currentName)} v${esc(installed.version)} (already applied)` : candidates.length ? 'Do not apply a premade' : 'No matching premade'}</option>
      ${candidates.map(e => `<option value="${esc(e.uuid)}" ${candidates.length === 1 && (installed?.key !== metadata(e.data).key || installed?.version !== metadata(e.data).version) ? 'selected' : ''}>${esc(e.data.name)} · ${esc(CATEGORIES[metadata(e.data).category])} · v${esc(metadata(e.data).version)}</option>`).join('')}</select>
      ${installed || candidates.length ? `<label class="dhp-enabled"><input type="checkbox" name="enabled-${index}" ${disabled ? '' : 'checked'}> Enabled</label>` : ''}
      ${candidates.length > 1 ? '<small>Multiple matches: choose explicitly.</small>' : ''}</div>`;
    }).join('')}</div>`;
  const selected = await dialog(`Medkit — ${document.name}`, content, [
    { action: 'apply', label: 'Apply', icon: 'fa-solid fa-kit-medical', callback: (_event, button) => rows.flatMap((row,index) => {
      const uuid = button.form.elements[`item-${index}`]?.value;
      const enabled = button.form.elements[`enabled-${index}`]?.checked ?? !row.item.getFlag(ID, 'disabled');
      const toggle = (row.item.getFlag(ID, 'applied') || row.item.getFlag(ID, 'premade')) && Boolean(row.item.getFlag(ID, 'disabled')) !== !enabled;
      return uuid || toggle ? [{ item: row.item, entry: entries.find(e => e.uuid === uuid), enabled }] : [];
    }) },
    { action: 'cancel', label: 'Cancel', callback: () => null }
  ]);
  if (!selected?.length) return;
  const summary = [];
  for (const { item, entry, enabled } of selected) {
    const previous = item.getFlag(ID, 'applied') ?? item.getFlag(ID, 'premade');
    const wasDisabled = Boolean(item.getFlag(ID, 'disabled'));
    try {
      if (entry) {
        await apply(item, entry);
        summary.push(`${item.name}: ${previous ? previous.version === metadata(entry.data).version ? 'Reapplied' : 'Updated' : 'Added'} ${entry.data.name} ${previous && previous.version !== metadata(entry.data).version ? `v${previous.version} → ` : ''}v${metadata(entry.data).version}.`);
      }
      if (entry || wasDisabled !== !enabled) {
        await setPremadeEnabled(item, enabled);
        if (wasDisabled !== !enabled) summary.push(`${item.name}: ${enabled ? 'Enabled' : 'Disabled'}.`);
      }
    } catch (error) { summary.push(`${item.name}: Failed — ${error.message}`); }
  }
  await ChatMessage.create({
    content: `<h3>Medkit — ${esc(document.name)}</h3><ul>${summary.map(line => `<li>${esc(line)}</li>`).join('')}</ul>`,
    whisper: [game.user.id], speaker: { alias: 'Daggerheart Premades' }
  });
  ui.notifications.info('Medkit finished. See your private chat summary.');
}
async function author(item) {
  if (item.pack?.startsWith(`${ID}.`)) {
    const meta = item.getFlag(ID, 'premade');
    if (!meta) throw new Error('This entry has no premade metadata. Author it from a world item using Save as Premade.');
    const version = await dialog('Premade version', `<p>Stable key: <strong>${esc(meta.key)}</strong>. Increment the version after editing this premade’s actions or effects.</p><input name="version" value="${esc(meta.version)}" aria-label="Version">`, [
      { action:'save', label:'Save version', callback: (_event,button) => button.form.elements.version.value.trim() },
      { action:'cancel', label:'Cancel', callback: () => null }
    ]);
    if (!version) return;
    if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error('Use an x.y.z version.');
    if (game.packs.get(item.pack).locked) throw new Error('Unlock this compendium first.');
    await item.setFlag(ID, 'premade', { ...meta, version });
    return;
  }
  const category = categoryFor(item);
  const options = Object.entries(CATEGORIES).filter(([k]) => (item.type === 'domainCard') === (k === 'domain-cards'));
  const result = await dialog('Save as Premade', `<p>Save this configured item into the premade library. Unlock the destination compendium first.</p>
    <label>Category<select name="category">${options.map(([k,v]) => `<option value="${k}" ${k===category?'selected':''}>${esc(v)}</option>`).join('')}</select></label>
    <label>Stable key<input name="key" value="${esc(item.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}" required></label>
    <label>Version<input name="version" value="1.0.0" required></label>
    <label>Alternate names (one per line)<textarea name="aliases"></textarea></label>`, [
      { action:'save', label:'Save premade', callback: (_event,button) => Object.fromEntries(new FormData(button.form)) },
      { action:'cancel', label:'Cancel', callback: () => null }
    ]);
  if (!result) return;
  const saved = await savePremade(item, result);
  ui.notifications.info(`Saved ${saved.name} to ${CATEGORIES[result.category]}.`);
}
Hooks.once('init', () => {
  registerModuleSettings();
  registerVulnerableSetting();
  registerDecisionClockSetting();
  Hooks.on('getSceneControlButtons', controls => addPendingDecisionsControl(controls));
  game.modules.get(ID).api = { openMedkit: guarded(openMedkit), library, apply, savePremade, setPremadeEnabled, ensureFolders };
  registerStatusHooks(guarded(openMedkit));
});
Hooks.on('getHeaderControlsApplicationV2', (app, controls) => {
  if (game.system.id !== 'daggerheart' || !game.user.isGM) return;
  const doc = app.document;
  if (!doc?.isOwner) return;
  const isItem = doc.documentName === 'Item' && supported(doc);
  if (!isItem && doc.documentName !== 'Actor') return;
  if (!doc.pack?.startsWith(`${ID}.`)) controls.push(medkitControl(doc, guarded(() => openMedkit(doc))));
  if (isItem) {
    controls.push({ action:'dhp-author', icon:'fa-solid fa-book-medical', label:doc.pack?.startsWith(`${ID}.`) ? 'Premade Version' : 'Save as Premade', onClick:guarded(() => author(doc)) });
  }
});
Hooks.once('ready', async () => {
  if (game.system.id !== 'daggerheart') return;
  registerRollResolverCompat();
  initializeModuleSettings();
  initializeDecisionClock();
  registerAutoMedkit();
  registerPremadeDisableHooks();
  registerContactsEverywhere();
  registerElementalist();
  registerTranscendence();
  registerResolutionManager();
  registerRollProviders();
  registerVulnerableAdvantage();
  registerSturdyEffects();
  registerHelpAlly();
  registerEnchantedAid();
  registerHallowedAura(resolveManagedAura);
  registerWitchsCharm();
  registerLuckbender(resolveManagedRoll);
  registerNimbleFingers();
  registerInternalCompass();
  registerAdaptability();
  registerFearless();
  registerUnbound();
  registerHardy();
  registerKnowTheTide();
  registerBraveFace();
  registerFelineInstincts();
  registerCelestialWings();
  installDamageReductionMonitoring(CONFIG.queries);
  registerIncreasedFortitude();
  registerQuickReactions();
  registerFaerieWings(true);
  registerAttackResolution();
  registerLuckbringer();
  registerKick();
  registerTusks();
  registerComboStrike();
  registerMarkedForDeath();
  registerRangersFocus();
  registerRoguesDodge();
  registerHiddenAttacks();
  registerSneakAttack();
  registerPrayerDice();
  registerSlayer();
  registerWeaponSpecialist();
  registerMartialPreparation();
  registerNotGoodEnough();
  registerVolatileMagic();
  registerFearsomeAttack();
  registerCourage();
  registerRiseToTheChallenge();
  registerManipulateMagic();
  registerArcaneCharge();
  registerChannelRawPower();
  registerPatronsBoon();
  registerFavor();
  registerPatronsPact();
  registerPatronsMantle();
  registerPatronsFury();
  registerDeadlyVengeance();
  registerMenacingReach();
  registerMenacingWeaponRestore();
  registerDiminishMyFoes();
  registerOtherworldlyIre();
  registerDeathlessEmbrace();
  registerHarrowingInvocation();
  registerDrainingBane();
  registerDamageSink();
  registerNotThisTime();
  registerFirstStrike();
  registerAmbush();
  registerDeathStrike();
  registerScorpionsPoise();
  registerTrueStrike();
  registerToxic();
  registerPoisonCompendium();
  registerVenomancer();
  registerGiftedPerformer();
  registerMaestro();
  registerVirtuoso();
  registerEloquent();
  registerOverwhelm();
  registerNotDone();
  registerEyeForEye();
  registerRallyTargets();
  registerIAmTheWeapon();
  registerEyeOfTheStorm();
  registerUnshakeable();
  registerAttackHope();
  registerPummeljoy();
  registerStanceFighter();
  registerStanceLifecycle();
  registerFavored();
  registerInvigorating();
  registerQuickStance();
  registerAggressive();
  registerDefensive();
  registerOtherwordly();
  registerGrappling();
  registerScary();
  registerCrushing();
  registerExacting();
  registerHoned();
  registerVigilant();
  registerKeenDefenses();
  registerFlowState();
  registerElementalIncarnation();
  registerElementalAura();
  registerElementalDominion();
  registerClarityNature();
  registerWardensProtection();
  registerEnchantedTalisman();
  registerWalkBetweenWorlds();
  registerCircleOfPower();
  registerNightsGlamour();
  registerMoonbeam();
  registerIreOfPaleLight();
  registerLunarPhases();
  registerAdept();
  registerPerfectRecall();
  registerHonedExpertise();
  registerFaceYourFear();
  registerDefender();
  registerReliableBackup();
  registerDarkAegis();
  registerAdrenaline();
  registerVanishingAct();
  registerSpiritWeapon();
  registerDevout();
  registerSacredResonance();
  registerWingsOfLight();
  registerEtherealVisage();
  registerRevenge();
  registerReprisal();
  registerNemesis();
  registerPartnerInArms();
  registerLoyalProtector();
  registerCompanions();
  registerHerbalRemedies();
  registerLoyalFriend();
  registerCompanionAdvancements();
  registerRuthlessPredator();
  registerElusivePredator();
  registerApexPredator();
  registerBattleBonded();
  registerEvasionIndicators();
  registerRestLoadout();
  registerEfficientRest();
  registerVaultRecall();
  registerFragile();
  registerHobblingStrike();
  registerPackHunting();
  registerVenomousBite();
  registerCannonball();
  registerTakedown();
  registerRampage();
  registerViciousMaul();
  registerSnappingStrike();
  registerDevastatingStrikes();
  registerOceanMaster();
  registerUnyielding();
  registerDeadlyRaptor();
  registerWeightOfDivinity();
  registerChangeShape();
  registerFeed();
  registerWerewolf();
  registerThriveInChaos();
  registerBeastformRollDamage();
  registerRuneWard();
  // Outer to recipient defenses, inner to Whirlwind/Rain's per-target packet adjustments.
  registerIAmYourShield();
  registerWhirlwind();
  registerDeftManeuvers();
  registerISeeItComing();
  registerBookOfAva();
  registerBookOfIlliat();
  registerBlightingStrike();
  registerUmbralVeil();
  registerRainOfBlades();
  registerUncannyDisguise();
  registerNaturesTongue();
  registerViciousEntangle();
  registerReassurance();
  registerForcefulPush();
  if (game.user.isActiveGM) {
    try {
      const count = await ensureFolders();
      if (count) ui.notifications.info(`Daggerheart Premades: created ${count} compendium folders.`);
      await ensureHallowedAura();
      await ensureCelestialWings();
      await ensureIncreasedFortitude();
      await ensureQuickReactions();
      await ensureFaerieWings();
      await ensureLuckbender();
      await ensureKick();
      await ensureUnshakeable();
      await ensureRetract();
      await ensureNimbleFingers();
      await ensureDangerSense();
      await ensureLuckbringer();
      await ensureInternalCompass();
      await ensureAdaptability();
      await ensureFearless();
      await ensureFelineInstincts();
      await ensureSturdy();
      await ensureTusks();
      await ensureEyeOfTheStorm();
      await ensureUnbound();
      await ensureHardy();
      await ensureKnowTheTide();
      await ensureMarkedForDeath();
      await ensureIAmTheWeapon();
      await ensureComboStrike();
      await ensureRangersFocus();
      await ensureRoguesDodge();
      await ensureSneakAttack();
      await ensurePrayerDice();
      await ensureVolatileMagic();
      await ensureEnchantedAid();
      await ensureArcaneCharge();
      await ensureChannelRawPower();
      await ensurePatronsBoon();
      await ensureFavor();
      await ensurePatronsPact();
      await ensurePatronsMantle();
      await ensurePatronsFury();
      await ensureDeadlyVengeance();
      await ensureMenacingReach();
      await ensureDiminishMyFoes();
      await ensureFearsomeAttack();
      await ensureCourage();
      await ensureRiseToTheChallenge();
      await ensureSlayer();
      await ensureWeaponSpecialist();
      await ensureMartialPreparation();
      await ensureHerbalRemedies();
      await ensureEnchantedTalisman();
      await ensureWalkBetweenWorlds();
      await ensureVexingMalison();
      await ensureCircleOfPower();
      await ensureNightsGlamour();
      await ensureMoonbeam();
      await ensureIreOfPaleLight();
      await ensureLunarPhases();
      await ensureAdept();
      await ensurePerfectRecall();
      await ensureHonedExpertise();
      await ensureFaceYourFear();
      await ensureFueledByFear();
      await ensureHaveNoFear();
      await ensureConjureShield();
      await ensureThriveInChaos();
      await ensureFragile();
      await ensureElusivePrey();
      await ensureHobblingStrike();
      await ensurePackHunting();
      await ensureVenomousBite();
      await ensureBeastformCompanion();
      await ensureCannonball();
      await ensureTakedown();
      await ensureVenomousStrike();
      await ensureRampage();
      await ensureViciousMaul();
      await ensureSnappingStrike();
      await ensureDevastatingStrikes();
      await ensureOceanMaster();
      await ensureUnyielding();
      await ensureDeadlyRaptor();
      await ensureWeightOfDivinity();
      await ensureChangeShape();
      await ensureFeed();
      await ensureWolfForm();
      await ensureHowlingRampage();
      await ensureOtherworldlyIre();
      await ensureDeathlessEmbrace();
      await ensureHarrowingInvocation();
      await ensureDamageSink();
      await ensureDarkAegis();
      await ensureDrainingBane();
      await ensureWitchsCharm();
      await ensureNotThisTime();
      await ensureFirstStrike();
      await ensureAmbush();
      await ensureDeathStrike();
      await ensureScorpionsPoise();
      await ensureTrueStrike();
      await ensureBackstab();
      await ensureToxic();
      await ensurePoisonCompendium();
      await ensureTwinFang();
      await ensureVenomancer();
      await ensureGiftedPerformer();
      await ensureMaestro();
      await ensureVirtuoso();
      await ensureEloquent();
      await ensureOverwhelm();
      await ensureEyeForEye();
      await ensurePummeljoy();
      await ensureNotDone();
      await ensureStanceFighter();
      await ensureFavored();
      await ensureInvigorating();
      await ensureQuickStance();
      await ensureAggressive();
      await ensureDefensive();
      await ensureOtherwordly();
      await ensureGrappling();
      await ensureScary();
      await ensureStable();
      await ensureVigilant();
      await ensureCrushing();
      await ensureExacting();
      await ensureHoned();
      await ensureIsolating();
      await ensureKeenDefenses();
      await ensureFlowState();
      await ensureElementalIncarnation();
      await ensureElementalist();
      await ensureNaturalEvasion();
      await ensureTranscendence();
      await ensureManipulateMagic();
      await ensureElementalAura();
      await ensureElementalDominion();
      await ensureClarityNature();
      await ensureWardensProtection();
      await ensureDefender();
      await ensureRevenge();
      await ensureReprisal();
      await ensureNemesis();
      await ensurePartnerInArms();
      await ensureLoyalProtector();
      await ensureBattleBonded();
      await ensureLoyalFriend();
      await ensureCompanionAdvancements();
      await ensureRuthlessPredator();
      await ensureElusivePredator();
      await ensureApexPredator();
      await ensureContactsEverywhere();
      await ensureReliableBackup();
      await ensureAdrenaline();
      await ensureVanishingAct();
      await ensureSpiritWeapon();
      await ensureDevout();
      await ensureSacredResonance();
      await ensureWingsOfLight();
      await ensureEtherealVisage();
      await ensurePowerOfTheGods();
      await ensureBraveFace();
      await ensureRuneWard();
      await ensureNotGoodEnough();
      await ensureWhirlwind();
      await ensureDeftManeuvers();
      await ensureISeeItComing();
      await ensureBookOfAva();
      await ensureBookOfIlliat();
      await ensureBlightingStrike();
      await ensureUmbralVeil();
      await ensureRainOfBlades();
      await ensureUncannyDisguise();
      await ensureNaturesTongue();
      await ensureViciousEntangle();
      await ensureReassurance();
      await ensureForcefulPush();
      await ensureIAmYourShield();
      await removeStoneskinPremade();
      await removeEmptyAncestryFolders();
      await removeEmptyCommunityFolders();
      await removeObsoleteWitchSubclassFolder();
      await removeObsoleteWarriorSubclassFolder();
    } catch (error) {
      console.error(`${ID} | Folder setup failed`, error);
      ui.notifications.error(`Premade folder setup: ${error.message}`);
    }
  }
  console.info('Daggerheart Premades | Framework ready. Use actor and item header menus to open Medkit.');
});
